### ISSUE TITLE
[Boss] Malygos - Eye of Eternity

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2174] opened 2018-01-31 14:36 UTC
Just ran EoE on 25 man difficulty and noticed a few issues on first phase.
Here's a link to a video of how the fight should go: https://www.youtube.com/watch?v=bjNM7Gy-RyI

First issue I noticed was with sparks (we only had one spawn during the first phase because we had a lot of dps so this issue will need confirming). When we killed a spark, it didn't drop the buff area it is supposed to.

Second issue was with vortex. Only a few members were actually spinning in the air, instead of the whole raid. For instance, I stayed on the ground during vortex, but was still taking damage and unable to cast long spells, so it might only be a visual problem (though it removes the coordination needed when vortex ends to reposition the raid).

Last issue was the transition from p1 to p2. When the boss reaches 50%, he should start an rp transition during which ranged dps should be able to attack him. However during our raid, Malygos simply flew away as soon as he reached 50%, making p3 last longer than needed.

Link to Malygos and her abilities:
http://www.wowhead.com/npc=28859/malygos#abilities

**Comment by Keader** [comment] 2018-01-31 14:42
Waiting confirmation of testers to work on this :)

**Comment by Dranah** [comment] 2018-01-31 23:34
1. ) Sparks : http://www.wow-mania.com/armory/?search=power+spark
How it should work: 
- Sparks slowly move from rifts outside the platform towards Malygos on the platform. 
- They should be near-ground level as they move on the platform.
- Sparks do not move during the Vortex
- Dead sparks spawn a Power Spark area http://www.wow-mania.com/armory/?spell=55849 on the ground location where they die, granting a buff to players.
- If a spark is not killed or rooted, it will sacrifice itself upon reaching the boss, giving Malygos a damage buff instead. For this the spark needs to reach the red circle indicating Malygos' hitbox.

How it really works at the moment:
- Sparks appear to move slowly at first, but switch to insane speed as they reach the platform, sprinting into Malygos within 1-2seconds after they are in range to shoot for players. 
- Sparks merge into the boss from a way too large distance , without being anywhere near his hitbox (the sprinting spark stops well behind the melee group and disappears , granting Malygos the damage buff). On the retail videos you can even see sparks sitting rooted under Malygos' tail without a problem as long as they're outside his hitbox.
- Sparks fly high up in the air instead of being close to the ground, making it hard to see/target or catch them
- Sparks that are killed do not grant a Power Spark buff on the ground (this could be also because they never land , and their buff disappears into the air)
- Sparks keep moving during Vortex, resulting in the first spark running into Malygos while you're still spinning in the air
- Some of the Sparks just disappear overall. You see the message they spawn, but they are nowhere to be seen, Malygos doesn't receive a buff afterwards either, there is no damage done to them from the raid, so they couldn't have died. It's a mystery I've yet to solve.

2) Vortex: http://www.wowhead.com/spell=56105
- Damages and interrupts spellcasts as if you were being moved as described by OP.
- Movement part is broken: it moves the player properly when testing alone on dev, but does not move 9 out of 10 people at all when testing with full 10men on Redemption. This leaves me to assume the Vortex only works for 1 player no matter how many are present. It is not a visual issue as the vortex is meant to relocate the raid members, messing up your positioning is the essence of the mechanism.

3) Nexus Lords: http://www.wow-mania.com/armory/?npc=30245
These are the melee mobs during phase2 that are intended to be tanked.
How it works at the moment: these npcs just stare at you and don't do anything. They don't move to their aggro target so you can't pull them under the bubbles.

4) Transition from P1 to P2
Confirmed, no roleplay talk takes place. 
How it should work: It should essentially allow you 20 seconds of free dps while Malygos talks.

5) The enrage.
Now I suppose this should wipe the raid, but it doesn't. Everything continues as before, the only ability which seems to scale with the enraged damage is Surge of Power, which affects only 1 (10man) or 3 (25man) targets at a time, and would be lethal anyway if the target forgets to shield. Everything else continues to deal damage as before, allowing you to finish the fight well beyond the berserk without problems.

**Comment by fvicaria** [comment] 2018-02-20 07:40
There is another issue with The Eye of Eternity raid on phase 1 everyone after a little bit of time is supposed to fly up into the air and start taking dmg from the aoe. Some people are supposed to be able to damage him from what I remember and healing needs to go off during this part of the phase.Currently in phase 1 no one gets sent up into the air so this part of the fight isn't working as intended. Instead everyone just stays on the platform and after about 10 seconds we start taking damage then. Rest of the fight seems to be working as intended.
--

**Comment by Zunrin** [comment] 2018-04-17 16:17
To add to point 3 from Dranah's comment, death gripping the nexus lords seems to make them bug out completely, making them undamageable (which means you can never reach p3)

**Comment by Keader** [comment] 2018-04-25 23:41
About vortex, funny part is: both players is casting the spell, but looks like if they cast "together" somethig dont work :/
But if both cast in little diff time, work fine...
trying find the reason y.y

**Comment by Keader** [comment] 2018-04-26 00:41
After lost time as fuck, i did a hackfix to vortex shit
so it's fixed.

**Comment by Keader** [comment] 2018-04-26 20:15
Nexus lord fixed with a fucking big hack.

**Comment by Keader** [comment] 2018-04-29 23:28
Revify fixed.
Exit portal i think it's fixed, need check tomorrow.

@Dranah  can you give me a list of spells that he should use in last phase? ty.

**Comment by Keader** [comment] 2018-04-30 14:40
@Dranah i need feedback if issues marked as fixed worked in dev.

**Comment by Keader** [comment] 2018-05-02 00:14
Still waiting @Dranah  💃

**Comment by fvicaria** [comment] 2018-05-02 12:25
I will be closing this shortly. It has been deployed to Redemption.

**Comment by Dranah** [comment] 2018-05-06 15:58
UPDATE:

1) Sparks 
- Fixes: It is now is possible to catch them. They no longer move during the vortex and if you do manage to kill them, they properly spawn their damage zones on ground now.
- Problems: They still merge into Malygos from a way too large distance (we can leave this tweaking, not a big deal)
2) Vortex
- Fixes: Now grabbed 4 out of a 10man raid, improvement certainly compared to just one.
- Problems: The other 6 targets didnt take any damage nor suffered interrupt on casts. Also when the vortex ends, it is supposed to drop all people off near the center of the platform, right now it drops off everyone where they currently are when the spinning ends (Keader said this can't be fixed because of vehicle issues, so i guess it stays tweaking too)
3) Nexus Lords now work as intended (fixed)
4) Transition between p1 and p2
- Fixes: Now malygos' /yell speech shows up on the text
- Problems: Malygos still flies off instantly, instead of staying in the air until he finishes the speech that should take approximately 20 seconds, allowing the raid to dps him in the air.
5) Phase3
- Malygos still fails to cast most of his "Surge of Power" spell=60936 he is supposed to spam. 
It appears that if the target of the spell is alone, it can cast properly, but if there are other drakes stacked on top of him, the spellcast breaks instantly and shows up as "failed".
Possibly it is Surge of power's splash damage portion http://www.wow-mania.com/armory/?spell=56505 which bugs it, it would be triggered to damage nearby raid members when multiple drakes stack around the main target of the spell, but I never saw splash damage happen and the Surge itself only seems to be able to cast when the target is alone.
6) Revivify 
- Fixes: No longer consumes combo points
- Problem: But does not award them either; the way the spell should work is that the caster must target a drake for each cast, and for each revivify cast, he will receive 1 combo point on the targeted drake. It is possible to have combo points on more than 1 drake at once, Currently you cannot get any at all.
7) Exit portal
- Problem: portal still does not work. Says "Cant do that right now" and then disappears.

**Comment by Keader** [comment] 2018-05-06 17:10
1 - Hitbox area.
2 - Vehicle issue :/
4 - Dragon shit
5 - Waitind Janitor send me the file
6 - Nothing more can be done.
7 - Waiting Janitor send me the file.

**Comment by Keader** [comment] 2018-05-06 22:30
- Fixed exit portal
- Fixed disks usable before lord die
- Fixed Surge of Light cast

**Comment by Dranah** [comment] 2018-05-07 22:36
UPDATE:

- Disk / Nexus Lords
It got broken. Please revert.
Details: When a Nexus Lord lands, he despawns and its disk disappears, and a new, full health nexus Lord spawns instead.
The first problem is that the damage you put into the Nexus Lord while it was descending is basically lost, because a brand new, full health version spawns.
The second problem is that if you kill this Nexus Lord, the disk reappears, but its unable to fly (you can mount it but it's stuck on ground).
The disk only works properly if you manage to kill the Nexus lord before he lands (while he's descending, which requires insane DPS burst and literally never happens), and make him drop the disk before he despawns.

- Surge of Power spell=60936 is now properly cast every time, does not get interrupted no matter whom it targets (fixed)
- Surge of Power's splash damage, spell=56505, however still does not damage drakes near the primary target of Surge. (need fix)
- Exit portal now works properly (fixed)

**Comment by Keader** [comment] 2018-05-08 19:12
56505 is not a spash damage.
It's casted in phase 2 and damage all creatures lul
And nothing in Surge of Power dbc say that it should spreat to near targets. Checking how this type of spell work in dbc, just need select multiple targets to damage they.

Life Burst is not Heal over time spell:

`Effect 1: Id 10 (SPELL_EFFECT_HEAL)
BasePoints = 5000
Targets (22, 30) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ALLY)
Radius (Id 48) 60,00`

To be a HOT, need be:

`Aura Id 8 (SPELL_AURA_PERIODIC_HEAL), value = 8, misc = 0 (0), miscB = 0, periodic = xxxx
`

About Nexus Lords i did a fix, i'm waiting janitor build to test if work.

**Comment by Dranah** [comment] 2018-05-08 19:39
Hmm, there is a bit of confusion with tooltips and descriptions, but i suppose you're right.
Life Burst is described as X healing over Y seconds, which usually indicates a HOT, but in this case the duration probably just stands for the 50% healing increase buff. This is very unclear based on tooltip in game.
As for 56505, both wowhead and wowwiki claim it is a phase3 ability that damages multiple players, but it seems their articles are completely inaccurate and fucked up for Malygos (which is a little odd for the two biggest official retail sites). I cannot find video-evidence of surge damaging nearby players (though it's difficult also because drakes usually spread), so screw it.

Let me know when Nexus Lords are up for test.

**Comment by Zunrin** [comment] 2018-05-08 23:56
From what I can see on world of logs (on a fight where Bursts of Life are hitting a bunch of target, so i guess the raid is packed):
On p2, Malygos casts 56505 (Surge of Power) on an entity called Surge of Power, causing everyone to take damage from the 56548 spell (Surge of Power).
On p3, Malygos casts 60936 (Surge of Power) on three targets, and only those drakes take damage from it (not any nearby drakes)
Finally, Life Burst is indeed NOT a hot

**Closed** 2018-05-11 08:34 UTC
Labels: Confirmed, Fix Confirmed in Dev, Tweaking
