### ISSUE TITLE
[Dungeon] Murmur restores too much HP on wipe; wrong and missing mechanics

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5738] opened 2022-03-05 10:08 UTC
**Links:**
Boss: https://www.wow-mania.com/armory/?npc=18708
Murmur's Touch: https://tbc.wowhead.com/spell=33711/murmurs-touch
https://www.youtube.com/watch?v=l1M3NnUgSR4
Sonic Boom: https://tbc.wowhead.com/spell=33666/sonic-boom
Magnetic Pull: https://tbc.wowhead.com/spell=33689/magnetic-pull
The spells are not in our armory at all.

ROOM: https://www.youtube.com/watch?v=ym9K83HWbhs (45:30 onward)

**What is Happening:**
1: Wipe on Murmur resulted in him getting to about 82 or 92 % HP instead of his 40 % (The encounter starts at 40 %)
2: Murmur's touch does not launch the person into the air upon detonation
3: Sonic Boom has a lot bigger area on our server. In the video you can see it is enough to run out past the 1st hightened circle/ledge. On our server you have to run up on the higher, outermost ledge and stand on top of it.
4: I am not sure if he is using Magnetic Pull or if he uses it right. So far I just seen some person (me) getting pulled in the middle of the boss, that is all, but it mgiht be cause we keep spreaded more due to the wrong range of Sonic Boom.
5: He does nothing when you enter the room. (as opposed to "ROOM" video)

**What Should happen:**
1: Murmur should stay at 40%
2: Person should go flying after the touch detonates
3: Sonic boom should be smaller
4: Magnetic Pull in the video looks like it is focused on a player, often the one who gets Murmur's Touch and it makes other players pulled to the the focused person
5: When you enter the Scream Room (iirc) or just boss room, Murmur should be fighting with the orcs as seen in video "ROOM"

**Comment by Echinaceax** [comment] 2022-03-07 12:15
note - will be checked with the other Shadow lab issues already reported 
thanks @Greywolf59

**Comment by Echinaceax** [comment] 2022-03-18 01:06
Cant go from 2020 video @Greywolf59 for Orcs fighting 
from a 2007 video there is no Orcs https://www.youtube.com/watch?v=Juveu_Zxck8

@mfranca0009 
linked for abilities and attacks 
https://wowpedia.fandom.com/wiki/Murmur

definately needs working on

thanks @Greywolf59 

Added issue 
still getting spammed combat log with Banish https://i.gyazo.com/dd69f21959ac56c2bc4b850737adb7c7.mp4

**Comment by Greywolf59** [comment] 2022-03-18 07:53
Well no Orcs fighting cause they are already dead in your video. I menat they should be sending casts on him when you enter the room and he should be slowly killing some of them. Will try find something but dunno.

**Comment by Echinaceax** [comment] 2022-03-18 09:53
Thanks yes I see them 12:56 😄 thanks @Greywolf59

**Comment by mfranca0009** [comment] 2022-05-07 02:25
WoWWiki: https://wowwiki-archive.fandom.com/wiki/Murmur

**Murmur's touch** is not supposed to throw you in the air, it states it should only detonate when the debuff expires, which will damage players and silence them when in a surrounding radius. Therefore, based on this I don't see an issue with this spell.

**Sonic Boom** is fine, it does not have a larger radius. When he casts Sonic Boom you see the blue circle visual, and on our server, it reaches the large outer circle; the same as the video you linked. The yellow ground effect doesn't cause damage, it's visual once sonic boom cast was successful, the actual damaging part comes from if you're still standing within that blue visual circle that appeared while he was casting. No issue with this as far as I can see.

**Magnetic Pull** is also fine, the tooltip for the spell states "pulls an enemy towards you". This is working as expected, and it will grab a player and pull towards Murmur. There is only a slight difference where WoWWiki claims it should be pulling **all** players, but since the spell description, even on WoWhead TBC, does not shed any light on this and, only specifies an "enemy" (singular), it will remain as-is since it is currently is only pulling one enemy at a time.

### Current issues being worked on
- [x] Murmur should always start at 40% health (initial spawn and after group wipe).
- [ ] Murmur should be casting resonance at the Cabal NPCs within the boss room.

**Comment by Greywolf59** [comment] 2022-05-07 09:50
I have tested it again and indeed Sonic Boom is fine (at least on normal). But if you check the video I provided in the OP at 1:02 he casts the touch on the priest → ppl get pulled to the priest → they run out → priests explodes and goes flying.

**Comment by Echinaceax** [comment] 2022-05-18 20:01
confirmed ALL issues listed fixed in PTR 

all visual effects https://i.gyazo.com/0b4ee08c6f5dfdd2f61c56226792467e.mp4
all voice lines https://i.gyazo.com/53d79c590dd3f1f1b026535a47a2dc62.mp4

![image](https://user-images.githubusercontent.com/39439201/169145585-7979e2d8-5488-4ebf-982d-88cf34873105.png)

**Closed** 2022-05-21 10:32 UTC
Labels: Fixed on PTR - Tester Confirmed
