### ISSUE TITLE
[Mount] x-53 Touring Rocket

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5432] opened 2021-04-13 16:37 UTC
**Links:**
Link to Item in armory: https://www.wow-mania.com/armory/?item=54860

**What is Happening:**
Unable to mount second rider in Outlands and only some players are able to mount while on Azeroth

**What Should happen:**
According to the description it should be mounted a second seat by anyone while anywhere.

**Comment by Rushor** [comment] 2021-04-13 17:14
I think this is intended restriction?

**Comment by Rushor** [comment] 2021-04-13 17:14
I think this is intended restriction?

**Comment by jeyrella** [comment] 2021-04-13 17:54
@womptista define "some"?  What players can't?

**Comment by womptista** [comment] 2021-04-13 20:02
when I was flying around in azeroth we found that all classes except paladin were able to ride passenger. I relogged and they would relogg and still didn't work.

**Comment by jeyrella** [comment] 2021-04-13 20:47
what class were you?  what levels were you all?

**Comment by jeyrella** [comment] 2021-04-13 20:56
Can't seem to immediately reproduce.
![image](https://user-images.githubusercontent.com/46089380/114619860-e117cb00-9ca2-11eb-9b01-39138c5b0721.png)
Need to know:
Levels, classes and races of both pilots and passengers
Exact locations.
Riding skills of all players involved

**Comment by jeyrella** [comment] 2021-04-13 21:00
![image](https://user-images.githubusercontent.com/46089380/114620605-a7938f80-9ca3-11eb-8445-c77c0e3eb963.png)

**Comment by jeyrella** [comment] 2021-04-14 21:33
Unfortunately, despite extensive testing, cannot reproduce it.  
Closing for now - we will reopen for further testing if you come across it again, please note the exact specific circumstances of race/class/level/skill combinations (or player names)

**Closed by jeyrella** 2021-04-14 21:33 UTC
Labels: A tester is on it
