### ISSUE TITLE
[NPC] Bash'ir Arcanist / Bash'ir Spell-Thief - Targeted mob issue 

### ISSUE THREAD

**Issue by mark4th** [WoWManiaUK/Redemption#6097] opened 2023-10-31 20:48 UTC
**Links:**

**What is Happening:**

I am currently leveling at bash'ir landing.  I have been noticing my death grip occasionally pulling a mob that is in line with the one i have targeted.  I can now replicate this bug reliably every time.    To do so I target a bash'ir arcanist while a spell stealer is slightly behond him in an almost straight line.  I CLICK on the arcanist and see the red circle under it and then execute my death grip.   The bash'ir spell stealer is then death gripped to me instead of the arcanist.   Again, this is occurring 100% of the time.

I have tested this with all addons disabled and i can still observe the bug occurring 100% of the time in the above scenario.

**What Should happen:**

Death grip should pull the mob that is targeted.

**Comment by mark4th** [comment] 2023-10-31 20:52
update:   this is not limited to death grip.  it just happend with icy touch too.   Mob A targeted,  Mob B hit.

**Comment by Echinaceax** [comment] 2023-11-01 00:18
Bash'ir Arcanist https://www.wow-mania.com/armory/?npc=22243
Bash'ir Spell-Thief https://www.wow-mania.com/armory/?npc=22242

- [x] confirmed bugged death grips the wrong target 
https://i.gyazo.com/e56871d306dfae7d5924ff860d2f4284.mp4

- [x] Also noticed that the Bash'ir Arcanist stays incomabat but doesnt do anything 
https://i.gyazo.com/ca00f2605a02145eaa8a854c6d95c46f.mp4

- [x] Icy touch 
https://i.gyazo.com/da35cde34e611c02f750d2cfa13718f8.mp4

@Rushor 
Its not only a DK issue, its same for my priest so im ashuming its a NPC issue
https://i.gyazo.com/32aa1538212447dca62f0c67a80b8650.mp4

Reproduce here  
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/dfc33875-0121-4ef1-9407-397f0cd0100e)

**Comment by Lumber-Jack-2** [comment] 2023-11-01 10:50
>  Also noticed that the Bash'ir Arcanist stays incomabat but doesnt do anything

This should be fixed on ptr within next restart already

**Comment by Rushor** [comment] 2023-11-01 13:58
okay found the reason, fixed with next restart of ptr

**Comment by Echinaceax** [comment] 2023-11-01 19:38
Fix confirmed on PTR

**Closed as completed** 2023-11-03 08:27 UTC
Labels: Fixed on PTR - Tester Confirmed, DB Change
