### ISSUE TITLE
Stealth Issue with Rogues

### ISSUE THREAD

**Issue by Desasw** [WoWManiaUK/Redemption#3285] opened 2019-05-23 15:00 UTC
Launched with WoW Launcher.
Updated 3.3.5a
Class: Rogue
Race: Undead (Not specified if any other class retains same bug)

Issue: Upon stealth every so often if stealth is caught by an aggressive mob, auto-attack function seizes to continue. Skills can still be used, however auto-attack cannot does not register.

Steps to Reproduce: Stealth with Rogue, run into an aggressive mob and try to active a skill (Skill will sometimes fail) auto-attack will not register.

**Comment by WhitephoenixTheBunny** [comment] 2019-05-24 08:51
We need some other informations like your level and mobs levels.

If mobs level are higher than yours, they will detect you, even if your stealth.

**Comment by Kitzunu** [comment] 2019-05-24 08:55
Keep in mind that Mobs can see you if they are facing you and that auto attacks and some spells break stealth.

**Comment by volkangul** [comment] 2019-05-24 15:17
If you dont have Master of Deception ( SUB talent) equal level of mobs will always detect you from in front by 10 yards. The thing Desasw is trying to say, if you fail to open to a mob with a skill ( ambush,garrote etc) the Rogue cannot auto attacks even if you right click or start attack button, but you are in combat and can use your special abilities (sinisterstrike,hemo,gouge etc ). This also happens sometimes to me which requires to target another one then return to previous target can fix it. For me this usually happens when my Killing Spree changes targets.

**Comment by IvanLlanas** [comment] 2019-05-25 16:38
This often happened to my hunter while leveling. Now it happens less often. An UI reload didn't fix it, so it forced close the client.

**Comment by Keader** [comment] 2019-05-27 14:25
I cant reproduce, or maybe i dont understood the issue :/

**Comment by volkangul** [comment] 2019-05-27 19:51
Let me explain Keader, in somehow when you auto attack a target, auto attacks are not going but you can cast your special abilities. this happens rarely, and the only way to fix it, lose your target and re-attack.

**Comment by Kitzunu** [comment] 2019-05-28 09:51
If I understand correctly, if you are going to auto attack (right click) a target while IN stealth it sometimes miss/blocks/dont go through?

Is there a way to reproduce this issue?
I think this will be hard to find the issue otherwise...

**Comment by Kitzunu** [comment] 2019-05-28 11:47
I will close this until more information is given.

At this moment with the current information, none of us can reproduce it.

I will re-open if more information that can help us identify the bug is added :)

Thanks for the contribution

**Closed by Kitzunu** 2019-05-28 11:47 UTC
