### ISSUE TITLE
[Quest] Frost Infusion

### ISSUE THREAD

**Issue by Magabro** [WoWManiaUK/Redemption#1981] opened 2017-12-21 20:57 UTC
Another issue discovered while completing the Frost Infusion quest for Shadowmourne quest line.

When receiving the 4th frost breath from Sindragosa, the stacks of Frost Infusion buff reset to 1 stack.  During the most recent attempt, I received 5 frost breathe attacks and ended the fight with 2 stacks of Frost Infusion.  Below are screen shots showing the progression of my Frost Infusion debuff stacks.  You can clearly see the number of stacks I at each phase and on the 4th breath my stacks reset to 1.

![wowscrnshot_122117_122503](https://user-images.githubusercontent.com/34353250/34274262-a1f80184-e64c-11e7-87a0-5960f48029b7.jpg)
![wowscrnshot_122117_122909](https://user-images.githubusercontent.com/34353250/34274266-a7fa3b74-e64c-11e7-854f-32c214c62d2e.jpg)
![wowscrnshot_122117_123027](https://user-images.githubusercontent.com/34353250/34274276-b14dd1e0-e64c-11e7-938d-40a86c5a1ea4.jpg)
![wowscrnshot_122117_123111](https://user-images.githubusercontent.com/34353250/34274284-b7abc376-e64c-11e7-934e-da81c73a3715.jpg)
![wowscrnshot_122117_123211](https://user-images.githubusercontent.com/34353250/34274293-bf66fb58-e64c-11e7-9d55-9410be69c844.jpg)
![wowscrnshot_122117_123216](https://user-images.githubusercontent.com/34353250/34274295-c4647932-e64c-11e7-977d-af172df22d2a.jpg)
![wowscrnshot_122117_123240](https://user-images.githubusercontent.com/34353250/34274644-59eefc10-e64e-11e7-870e-f09588754f53.jpg)
![wowscrnshot_122117_123514](https://user-images.githubusercontent.com/34353250/34274657-60a5fbc6-e64e-11e7-8ab1-087db1f44807.jpg)

As seen from the screen shots i took a total of 5 breathes and ended with 2 stacks of Frost Infusion.  The 4th breath rolled my stacks over to 1 stack then the 5th breath put me at 2 stacks.

**Comment by fvicaria** [comment] 2017-12-21 20:59
I am sorry the quest works. I am not going to look into it anymore. People fail and try to find a problem with it. A lot of people have done it successfully.

**Comment by Magabro** [comment] 2017-12-21 21:06
Hey janitor.  Again I have documented well with the screen shots the issue.  If you recall the last issue I submitted was indeed a bug.  It is possible the fix for the previous bug of 28k tick damage may have caused this.  Please review the screen shots.  Thank you.

**Comment by LooneyBin** [comment] 2017-12-21 21:27
Yeah, Frost Infusion isent working as intended atm.
Just came from there, where a guildy got 4 breaths on 2 attempts (4 each time ofc), he had his Shadow's Edge equipped and survived the fight and all, but he still couldnt complete the quest.
Another problem atm, the debuff stick to the player after Sindragosa is dead, and atm, only way to remove it it to die (that we found atleast, bubble doesnt remove it).

**Comment by GMWeeble** [comment] 2017-12-21 22:04
Tested, the stack did get reset then the 4th breath hit.

**Comment by VA-L** [comment] 2017-12-21 23:00
- This is now fixed.

**Comment by Magabro** [comment] 2017-12-21 23:02
Thank you VA-L!

**Comment by LooneyBin** [comment] 2017-12-22 07:59
VA-L... did you have had the chance to look at the debuff aswell? 
it stayed on a guildy after Sindragosa was dead, and only way we found to remove it was to have him kill himself.... nothing major, just an annoying factor.

**Comment by VA-L** [comment] 2017-12-22 08:36
It is meant to annoying.

![image](https://user-images.githubusercontent.com/11377592/34291173-4afb7942-e6fb-11e7-8c5f-05e1b1e5676f.png)

The duration is the same here except that it's coded not to show below the debuff.

**Closed** 2017-12-26 09:00 UTC
Labels: Confirmed, Fixed Confirmed in Dev, Fixed in Dev
