### ISSUE TITLE
[NPC] Crock and Company inside ICC

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#5898] opened 2022-08-15 06:08 UTC
This video is the only one I could find on youtube of the encounter in question. It doesn't appear to be from retail 3.3.5, but it looks like it is from the Mists of Pandaria Expansion on retail. Regardless, this is clearly the way blizzard intends for the encounter to go. 
https://youtu.be/DqCcsZlSzNU?t=1456

If you engage the frost wing before the Roleplay of Crock and Company finishes, you bug the entire hallway and Valithria Deathwhisper's door won't open. This is because Crock won't make it to the banshee and so her encounter won't engage. You then can't kill her and so can't progress through the raid.

What should happen is that if you decide to engage the mobs before the roleplay is finished, it should skip to the last line of the roleplay where Crock says to help our champions and then the ally NPC's help fight through the hallway. I think that this trigger is missing because if you don't let them start the fight then they just stand there and do nothing. Even if you try to engage them by dragging the trash to them, they will start fighting then run back to their starting positions once out of combat. 

Why this bug is important to be fixed is because as the video shows, it's not working as intended. But further more, this issue results in pug runs potentially being ruined by some random derp who decides not to wait until the mobs engage the fight. So basically you can do everything right as a raid leader and someone screws over your entire weeks worth of raid lockout. 

We had a GM come into our raid this week not to go in before the encounter starts. Well that's great. So apparently they know about the issue but it hasn't been reported. The GM fixed the issue in 30 seconds by killing the boss banshee at the end of the tunnel. So if they know what to do to fix it, then it should be fixed or at least be reported by now.

**Comment by jeyrella** [comment] 2022-08-15 16:09
This is a regression, since a while ago we put in a fix to stop this scenario being a possibility.  It seems a lot of these fixes got reverted so we will have to find this one and put it back in.
Will mark this one as "will not fix", simply because it's a duplicate of the original, but will leave open until we find the correct one.
Thanks.

**Comment by jeyrella** [comment] 2022-08-15 16:11
#5677 to be reopened

**Closed** 2022-08-15 16:12 UTC
Labels: Invalid - Intended/Blizzlike/as-is - Won't fix
