### ISSUE TITLE
[NPC] Coilskar Defender not scripted

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5755] opened 2022-03-12 12:06 UTC
**Links:**
Coilskar Defender:
https://www.wow-mania.com/armory/?npc=19762
https://tbc.wowhead.com/npc=19762/coilskar-defender#screenshots
At least I think it is this one.

**What is Happening:** NAXXRAMAS
All the Defenders are visible, move around but they can't be targetted/clicked on. They do not aggro.

**What Should happen:**
They should have HP, be targettable and hostile.

**Comment by jeyrella** [comment] 2022-03-12 12:11
Important for SMV quest chains, and consequently SMV and OL quest achievements

**Comment by Rushor** [comment] 2022-03-12 12:25
yeah not in that list, because ai for them was never ever been added

**Comment by Echinaceax** [comment] 2022-03-12 14:33
Confirmed bugged in PTR

https://i.gyazo.com/0f7452989332f0082c979cb1b2ca9204.mp4

**Comment by mfranca0009** [comment] 2022-03-21 21:36
All set 👍 

### Issues Corrected
- [x] Removed unnecessary data preventing NPC from aggroing and not selectable
- [x] Added abilities to cast on victims: Shield Block and Shield Bash

**Comment by Echinaceax** [comment] 2022-03-21 21:37
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/159367942-c7a9f253-9646-46ea-af45-0b94e4998063.png)

**Comment by Rushor** [comment] 2022-03-26 16:21
not fair that it was unassigned, but well not repeat this in future please

**Closed** 2022-03-28 11:25 UTC
Labels: Fixed on PTR - Tester Confirmed
