### ISSUE TITLE
Dungeon(TOC5nm+HC) loot chest phasing

### ISSUE THREAD

**Issue by GM-Osyris** [WoWManiaUK/Redemption#4543] opened 2020-05-05 17:49 UTC
**Links:**
https://cdn.discordapp.com/attachments/697519727525888025/707287797664579696/WoWScrnShot_050520_193820.jpg

**What is Happening:**
The chest is phasing out when parties are killing the boss. aswell as the npc who starts the next fight.

**What Should happen:**
once boss is killed Chest should be dropped + npc should appear.

**Comment by Rushor** [comment] 2020-05-05 19:48
is this always happening or only sometimes?

**Comment by GM-Osyris** [comment] 2020-05-05 20:10
Its on occasion. however iv seen it increasing more recently

**Comment by svijetlo** [comment] 2020-05-05 21:08
i notice on photo they did wipe as there are skeletons around could that have some effects on it 
way to tired atm will test it tomorrow

**Comment by GM-Osyris** [comment] 2020-05-06 15:38
That is possible. ill drop another notice on this if i see it again on tickets etc.

**Comment by svijetlo** [comment] 2020-05-06 17:56
pls do as i did place few times today on different toons and it was fine i even wiped 
would like to know what fight was it

**Comment by Rushor** [comment] 2020-05-06 18:43
oh actually: at which boss fight is that happening? every bossfight? or only specific ones?

**Comment by Tankjnr** [comment] 2020-05-07 15:41
Happened to me today. i think we where phased. GM-Osyris summoned us and then we could see chest (happened on first boss)(no wipe)

**Comment by svijetlo** [comment] 2020-05-10 21:22
what boss you were on , what did you do before , was it 2nd boss ? for trinket did you run out and back in to reset fight to get other boss ?

**Comment by Aristo14** [comment] 2020-05-11 09:18
Maybe related to https://github.com/WoWManiaUK/Redemption/issues/4059

When the dungeon is run normally, without trying to reset, the issue cannot be reproduced without more info. Without this info I will have to close this and any subsequent report about it, that fails to provide steps to reproduce or are caused by repetetive resetting of the bosses for trinket farming.

**Closed by Aristo14** 2020-05-11 09:18 UTC
