### ISSUE TITLE
[Raid] Ruby Sanctum

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#1914] opened 2017-12-07 18:29 UTC
During our fight against Halion in 10hc (http://www.wowhead.com/npc=39863/halion) we had a bug. The AoE left behind by both Fiery Combustion (http://www.wowhead.com/spell=74562/fiery-combustion) and Soul Consumption (http://www.wowhead.com/spell=74792/soul-consumption) were visible in both realms and pushed or pulled our members.

**Comment by CrustyMuffin** [comment] 2017-12-07 18:31
For some reason that bug only appears  on heroic difficulty. We farmed Halion on normal for weeks and had no such bug.

**Comment by fvicaria** [comment] 2017-12-07 19:26
The more info you add, the better for us to find a fix.

**Comment by CrustyMuffin** [comment] 2017-12-08 18:35
well, there is not really much to add. People got pulled, pushed and damaged from the AoE, of the debuff, 
 that was dispelled from the other phase. Fiery Combustion pushing people away in Shadow real etc.

**Comment by fvicaria** [comment] 2017-12-08 18:36
We have done a lot of work it today. It should be fixed now. We will try to push it tomorrow morning.

**Closed** 2017-12-09 12:23 UTC
Labels: Fixed in Dev

**Comment by Plege** [comment] 2017-12-09 14:36
the reason this -bug- appeared only in heroic is because it's not a bug but intentional it's a retail hc mechanic
RS is actually working near blizzlike atm in both nm and hc
