### ISSUE TITLE
[Dungeon] Halls of refection

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Redemption#3191] opened 2019-04-14 12:45 UTC
**Links:**
https://www.wowhead.com/halls-of-reflection

**What is Happening:**
Just tried to do this dungeon in HC mode the party consisted of two dks, 2 pally's and a resto shammy, first four waves were cleared but then the boss didn't appear and the waves reset but no mobs appeared. This left us trapped has the doors do not then open. iv taken several screen shots of the  party's builds I will added them in the comments

**What Should happen:**
After the first 4 waves the first min boss should appear then after killing him, then second 4 waves should appear.

**Comment by sarahkay88** [comment] 2019-04-14 12:46
![World of Warcraft 14_04_2019 13_38_37](https://user-images.githubusercontent.com/42302580/56093032-b334fb80-5ebb-11e9-8b4c-7d5978c5827f.png)
![World of Warcraft 14_04_2019 13_38_49](https://user-images.githubusercontent.com/42302580/56093035-b4febf00-5ebb-11e9-87eb-00d3aab8f0c9.png)
![World of Warcraft 14_04_2019 13_39_02](https://user-images.githubusercontent.com/42302580/56093036-b62fec00-5ebb-11e9-8fae-e0335fe51db7.png)

**Comment by sarahkay88** [comment] 2019-04-14 12:47
![World of Warcraft 14_04_2019 13_39_13](https://user-images.githubusercontent.com/42302580/56093042-c8118f00-5ebb-11e9-8161-4c313413cfea.png)
![World of Warcraft 14_04_2019 13_39_22](https://user-images.githubusercontent.com/42302580/56093044-c942bc00-5ebb-11e9-9b25-20e493d37c99.png)
![Uploading World of Warcraft 14_04_2019 13_39_36.png…]()

**Comment by Keader** [comment] 2019-04-14 13:38
We need a repro steps to fix it...
Everything that i know that can bug it is fixed already.
So right now, i have no idea.

**Comment by sarahkay88** [comment] 2019-04-14 13:55
I don't know how to give you a repo on how to produce it because it was running smoothly, no one died and the mobs were easily killed.
we entered through rdf
used the fast process of starting dungeon
pally tanked, dps did damage and I healed.
just after the last mob in phase 4 died it auto reset.
only thing I can suggest is finding 2 dks, 2 pally's and a resto shammy queue and do fast dungeon starter
kill the waves has intended and see if it can be reproduced.
if not then it may have been a random bug. but if you read the chat they were saying it has gotten worse since the last update.
I don't often run this dungeon so I cant really give you more info than I already have sorry.

**Comment by Dranah** [comment] 2019-04-14 15:56
Information that can help: what cooldowns have you used on the last active wave, what order did the mobs die in the last wave, did you use any crowd control, how long it took to finish off a wave, where was the party positioned?
This can all help reproduce.
I've done HoR several times with each of those specs in my 5man party and never managed to bug it, which means it probably isnt random. We need to figure what some groups do differently.

**Comment by sarahkay88** [comment] 2019-04-14 16:10
For the other I cannot speak but for myself, I had tremor and cleanse totem down.
The waves died fairly fast wasn't expecting it to bug so didn't check time. I was positioned beside the wall to the right. The rest in the centre.
I'm sorry I can't quite remember order of deaths I was just focusing on keeping them alive.

**Comment by Drostthehunter** [comment] 2019-04-18 09:43
I have found that if you CC some of the mobs with aka Freezing Arrow, it knows to reset if the rest of the wave is killed befote the CCed target if free. Also killing a mage while he is invisible because of casting that mirror image spell ( can happen if the damage is to high or if the DotS take down mage before he reapears from invisibility) 
Those are the ones that caused reset of the instance for me.

**Comment by volkangul** [comment] 2019-04-18 12:44
I believe there are 2 options before headstart. 1- long one 2- short one. I have done a few times this dungeon. Whenever we choose 2-short one ( starts with whatever lady just ... ) waves are bugged.

**Comment by wow-mania** [comment] 2019-04-18 14:13
I will close this until someone can come up with steps that actually show the issue.
Dev cannot reproduce it.

**Closed by wow-mania** 2019-04-18 14:13 UTC
Labels: Need Informations
