### ISSUE TITLE
[Transmog] Transmogs disappear

### ISSUE THREAD

**Issue by kartof41** [WoWManiaUK/Redemption#5343] opened 2021-03-05 19:50 UTC
**Links:**

**What is Happening:**
   Today, 5th of March, I was playing with my Death Knight and was killing some mobs. When my Deathbringer's Will activated I changed my form (to one of the 3 forms) and when I got back to my normal form I was without a transmog. I had full set transmog (Malevolent) from mail tmog vendor Donno. Only my weapons were tmoged to a sword which I have in the bank. 
After this happened, I restarted my game, but nothing changed. Then I went to Mail because I had this set saved but when I got to the vendor I saw that my saved set wasn't there too. I don't know if it was a bug from Deathbringer's Will or not. Because DW may bug my form but why would it clear it from Mail? I don't get it. 
   I've talked to game master who told me to report the bug here because he can't see my previous transmogs. So here I am.

**What Should happen:**
The first thing I would like to happen is to get back my transmog set. The second think I would like you to do is to check that bug because I can transmog my set again but I don't want this to happen, to me or to other people, again in the future (I think u don't want that to happen eather).

**Comment by jeyrella** [comment] 2021-03-07 14:04
We've been chasing this spurious sporadic issue for months, and have never been able to reproduce it.

A question though, the items that you lost a mog on, do you physically have any of those source mog items, or were they applied from the vendor?   I note this simply because you _didn't_ lose your weapons, and you physically have those.

**Comment by Keader** [comment] 2021-03-07 14:28
Without a reproduce steps i cant do a thing.
I tested my self in ptr now, and i cant reproduce.

**Comment by wow-mania** [comment] 2021-03-07 16:17
This is most likely due to closing the client straight from the "X" on Windows or some other abrupt way and not by logging out from the character.
This can also happen if you leave your char online and the server happens to restart or crash.
Best way to avoid this is by:

1. Typing ".save" every time you do some important change to your character 
2. Logging out from the character first when closing the game.

Contact me on discord and we can see what I can do about your case.

**Closed by wow-mania** 2021-03-07 16:17 UTC
