### ISSUE TITLE
[Quest] Gnomeregan Quest 'A Fine Mess'

### ISSUE THREAD

**Issue by Brazier1** [WoWManiaUK/Redemption#4398] opened 2020-04-09 12:13 UTC
**Links:** https://www.youtube.com/watch?v=1o9a0s8O4PE

**What is Happening:** The NPC Kernobee should be escorted to the Clockwork exit in order to complete the quest. He will follow you as also the alarm robot (slow but he follow) When approaching the exit, Kernobee doesn't say anything like "I can almost see the exit" or "Thank you for protecting me" and at the exit the quest doesn't get completed. He just stand there and  dies when the alarm robot explode as the time runs out. I've tried to get him outside the dungeon also but he doesn't follow nor the robot. They stay inside and start following you again when i reentered. 

**What Should happen:** When you are at exit (dungeon entrance) The quest should get completed and Kernobee should thanking you etc, inside or outside. The link is a video how it should happen.

**Comment by wow-mania** [comment] 2020-04-09 12:46
Pretty sure it works and you just missed the correct area. 
Let's wait for confirmation.

**Comment by Rushor** [comment] 2020-04-09 13:16
The mechanic is that the creature complete it if reached near Position xy in dungeon. Can give Testers more Info soon

**Comment by Brazier1** [comment] 2020-04-09 13:31
I've tested it again to make sure i'm not at the wrong exit. Walked exact the way shown in the video. Still not completed.

**Comment by jeyrella** [comment] 2020-04-09 18:19
https://www.youtube.com/watch?v=Bv0WKTNodJI  era-appropriate video, saving here as notepad for referencing testing later today

**Comment by Rushor** [comment] 2020-04-09 20:39
once confirmed i will fix it :)

**Comment by jeyrella** [comment] 2020-04-09 20:52
Well.  I did this 5 times in PTR, and each time he did exactly as expected in quest.  Ran to the exit, quest completed.  I can't immediately see specific failure conditions.
Have also checked, I have previously completed it on 2 toons on Redemption, so it definitely has worked in the past too.

@Brazier1 what class are you?  Did you use any vanish/stealth skills?  Kill every mob that you got aggro from?   I will need more info if this to be investigated, otherwise I will have to mark as "cannot reproduce" and close.

https://youtu.be/9y5fruhBNjY

![image](https://user-images.githubusercontent.com/46089380/78938028-6291b780-7aa9-11ea-809e-30a1fe82a259.png)

I do however agree that [Alarm-a-bomb 2600](https://www.wow-mania.com/armory/?npc=7897) moves far too slowly while on the quest, should be perhaps 5x maybe as much as 10x faster.

**Comment by Rushor** [comment] 2020-04-09 21:19
maybe player was in "raid" group then quest will not be completed

/script LeaveParty()

**Comment by Brazier1** [comment] 2020-04-09 21:57
Hello, ty for taking the time to investigate this. I've watched both video's. In this video ( https://www.youtube.com/watch?v=Bv0WKTNodJI ) I've also walked that path. Only difference i saw is that Kernobee isn't saying anything on my run. I waited for Alarm a bomb to follow us. I had cleared the path before hand or killed everything that got agroed. I'm playing a lvl 80 MM hunter and have not used anything like Shadowmeld etc.. My pet was also on passive. And i use the right launcher version and cleared cache, if you wonder. I was not in a raid nor a group.

**Comment by jeyrella** [comment] 2020-04-10 12:36
Well, done this twice on Hunter too.  Can't find any failure cause, will have to close this as unreproducible.
Thanks for your time to report.
If you have video of it, feel free to post - if you do we will review to see if there was an edge case we missed.

**Closed by jeyrella** 2020-04-10 12:36 UTC
Labels: Invalid - Cannot Reproduce

**Comment by Brazier1** [comment] 2020-04-10 22:26
Ty. I was about to provide a video, but dunno why but the quest got completed while i was recording. Didn't do anything different from previous test beside clearing cache or restart before the recorded run.
