### ISSUE TITLE
[Quest] Battle at Valhalas: Fallen Heroes

### ISSUE THREAD

**Issue by phiedw** [WoWManiaUK/Redemption#546] opened 2016-11-27 10:05 UTC
The quest seems quite bugged. There are  elites to kill and I completed the quest after killing only two: Rith and i'm not sure which was the second one I killed.

**Comment by wow-mania** [comment] 2016-11-27 10:49
These quests work 100%. Your report tells me nothing. Do the quests in order and let me know exactly which one is bugged and how.

**Comment by philoudu16** [comment] 2016-11-28 14:37
I agree on the fact they work, just not 100% as intended. I did do them in order, and the bugged one is called "Battle at Valhalas: Fallen Heroes" where you have to defeat a group of 6 elites in one fight. The way it is bugged is I didn't need to kill all of them. Basically, I had time to burst two of them down and somehow the quest became complete. I then talked to a gm because I had issues with Prince Valanar (if you die when he has his fire shield up, he seems to not reset and evades everything) and he told me to post an issue for the first part of the quest (as he was already posting for the Valanar part).

----- Mail original -----
De: "Janitor" <notifications@github.com>
À: "wow-mania/Redemption" <Redemption@noreply.github.com>
Cc: "philoudu16" <philippe.edwards@telecom-paristech.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 27 Novembre 2016 11:49:43
Objet: Re: [wow-mania/Redemption] [Quest] Battle at Valhalas: Fallen Heroes (#546)

These quests work 100%. Your report tells me nothing. Do the quests in order and let me know exactly which one is bugged and how.

**Comment by Woofles** [comment] 2021-09-10 14:27
Just took the quest solo to test the mobs: 
1) died and upon reincarnation (shaman) it got completed
2) took the quest second time but flew out of range. The moment i got out of agro radius it completed again
3) another player tried taking it and doing it the same way but it seems me being there with the quest taken interfered and both option didnt work for him. We weren't in a party.

**Comment by Maine1** [comment] 2023-10-16 15:54
@Rushor confirmed as bugged from player report. You can fly mount away or normal mount or just run out of range of threat. They will despawn and the quest just completes itself. Even if you die it completes.
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/59f2650e-4952-4fb2-8732-f64e856e51f7)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/5dfcf782-e488-402f-be75-72e490042a8e)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1d05560d-97ed-4bd3-9e3e-2094d4a6c99c)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/b439c884-a18d-49c6-9070-ef6a0358609c)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/dd708ce2-5227-4549-afbe-d3535538e032)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/e64b2962-b3a6-4d55-8429-08a018dffead)

**Comment by Lumber-Jack-2** [comment] 2023-10-16 16:22
okay this must be fixed

**Comment by Woofles** [comment] 2023-10-16 17:29
Just want to clarify that every quest in that group has that problem, not just the first one.
[13214](https://www.wow-mania.com/armory/?quest=13214) , [13215](https://www.wow-mania.com/armory/?quest=13215), [13216](https://www.wow-mania.com/armory/?quest=13216), [13217](https://www.wow-mania.com/armory/?quest=13217), [13218](https://www.wow-mania.com/armory/?quest=13218), [13219](https://www.wow-mania.com/armory/?quest=13219) 
Also dying and waiting without releasing works just as fine. (messed the file extension when recording so can't upload that right now :D )

P.S.: When I found this I tested it on the other 2 arenas but seems this questline is the only one with the bug.

**Comment by Maine1** [comment] 2023-10-16 17:37
All the Battle of Valhalas Quests in the pit break this same way. so all questline needs fixing, Also the death should fail this quest

**Comment by Lumber-Jack-2** [comment] 2023-10-17 11:03
> death should fail this quest

this i gonna not add, it could fail for close players on different quest stage

but it will only credit the quest in future if the creature was actually killed

**Comment by Echinaceax** [comment] 2023-10-17 14:51
Not quite fixed @Rushor 

has problems if one the quest and server crashed, the original quest guardians you follow are still spawned when you relog but are inactive. 

When you abandon the quest and retake there are 2 sets of them, they then start spawning chat 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/84874a09-523b-454d-a77d-7d5c87a37c43)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a4f7cceb-1217-4af7-a79c-e9d86d378bd2)

**Comment by Rushor** [comment] 2023-10-17 15:00
is for the other issue, that one is icecrown

**Comment by Echinaceax** [comment] 2023-10-18 08:47
Fixed in PTR for [13214](https://www.wow-mania.com/armory/?quest=13214) , [13215](https://www.wow-mania.com/armory/?quest=13215), [13216](https://www.wow-mania.com/armory/?quest=13216), [13217](https://www.wow-mania.com/armory/?quest=13217), [13218](https://www.wow-mania.com/armory/?quest=13218), [13219](https://www.wow-mania.com/armory/?quest=13219)

Druid flight = no auto complete
https://i.gyazo.com/f4cdbd30b3e9f36e83114c3199ea91b6.mp4

Druid travel form  = no auto complete
https://i.gyazo.com/c151b1b6429d40d60acff80740551d68.mp4

Death without a kill  = no auto complete
https://i.gyazo.com/a30cb0aca9f4e2da767dcaacfe9d2eeb.mp4

Death with a kill  = no auto complete
https://i.gyazo.com/607c103dd58d7129b517e60ce25cfb7a.mp4

Death on Khit'rix = no auto complete
https://i.gyazo.com/154fa461e2e522451e355149617d32d4.mp4

Killed = completed
Out of range = Despawn
Quest fails = abandon and retake quest

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/54bc10cd-854d-4a29-aaab-bd90f911b0ed)

Final challange https://i.gyazo.com/36cca8b11579b3af50677fb6f53d967f.mp4

**Closed** 2023-10-24 11:18 UTC
Labels: Fixed on PTR - Tester Confirmed, Code Change, AIScript Change
