### ISSUE TITLE
[Spell] Spiritual Attunement

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1513] opened 2017-08-20 16:50 UTC
Hello, as you could not reproduce this issue based on my previous report, I looked deeper into this and found the problem.

Spiritual attunement (https://wotlk.evowow.com/?spell=31785) talent 
The way it's intended to work is that it gives you mana equal to 10% of healing received by other friendly players, which does not include overhealing. This means if a spell heals you for 1000 of which 800 is actual healing done and 200 overhealing, you should receive 80 mana, after the portion that was NOT overhealing.

Issue: currently it only gives mana if the WHOLE spell that lands on you is pure healing, if any small portion of it is overheal (i.eg. 999 healing done, 1 overhealing) bam, no mana.

I have screens to prove this:
http://imgur.com/YQU7bwB
This shows as the paladin receives 1181 healing from Lesser Healing Wave, of which 17 is overhealing, and zero mana is generated by Spiritual Attunement.
http://imgur.com/pdYLdjf
This one shows as the mana is properly generated by a Healing Stream Totem tick that does pure healing, and is not generated when it does partial overhealing.

(On my previous report, I checked the screens made by the testers and the healing done included no overhealing at all that's why they couldnt reproduce issue)

**Comment by captainloozer** [comment] 2017-08-20 18:07
Thank you Dranah for your report and that additional information.  This will help greatly with being able to reproduce the problem.

I will test this and post here with my findings.

**Comment by tvshadowz** [comment] 2017-08-20 18:25
Hi There Dranah!

From the screenshot below I gained 5% of the amount I was healed for. 


![testt](https://user-images.githubusercontent.com/30256554/29497217-18e3facc-85dc-11e7-9564-1e84d39df354.png)


Unfortunately the spell does describe "5% of the amount healed" and not "5% of the amount of healing received" which would mean this issue would be correct.  

This is how the spell is suppose to work. 

Thank you for your report! If you have any questions please feel free to contact a GM in game and ask them to direct you to myself.

**Comment by captainloozer** [comment] 2017-08-20 18:45
I was able to reproduce the issue.

The paladin with the spiritual atonement talent as shown in the picture had roughly 2000 health missing.  The druid healed him with a healing touch for 4197.  (1472 actual healing with 2725 overhealed).  This should result in the paladin receiving 10% of the amount of actual healing done. (147 mana)  As you can see in the combat log, because there was an amount of overhealing done, the actual healing was ignored and the paladin no mana back,

**Comment by tvshadowz** [comment] 2017-08-20 18:51
Whenever any overhealing is present, no mana is given from spiritual attunement.

**Comment by captainloozer** [comment] 2017-08-24 18:33
Behavior is still acting as before except now it seems that the full 10% isn't being given as before as can be seen in the screenshot.  The expected behavior would have granted 688 for the first heal, 416 for the second, and 274 for the third.  In this test I got 681, 254, and 0 respectively. 

![image](https://user-images.githubusercontent.com/9828794/29682485-cafcc0e4-88d0-11e7-9db8-358f9a1a15fe.png)

**Comment by fvicaria** [comment] 2017-08-25 15:56
I think it is working.
The other of the message is just messed up.
We can't guarantee they will appear in order.

**Comment by captainloozer** [comment] 2017-08-25 19:33
I have tested again, and this time I video recorded the behavior.

In this test, I did the following heals on the paladin and the following mana was received:

heal 1:  4253 healing / mana received 425
heal 2:  4720 healing / mana received 472
heal 3:  4539 healing / mana received 453
heal 4:  4015 healing / mana received 95  (Should have been 401)
heal 5:  840 actual healing with 3459 overhealed / mana received 0 (should have been 84)

Screenshot of combat log below

![image](https://user-images.githubusercontent.com/9828794/29729531-20c02a76-89a2-11e7-8b8d-1d8a13a17dda.png)


Video showing these logs are in order in which they happened:

https://youtu.be/HDPfhb5MsN4

Removing fixed in dev label accordingly.

**Comment by captainloozer** [comment] 2017-09-12 18:33
Tested again after recent changes made in dev, healing spells that include any amount of over healing are still not giving mana back with spiritual attunement.

![image](https://user-images.githubusercontent.com/9828794/30342280-f2beca30-97be-11e7-81ca-687157964244.png)

**Comment by captainloozer** [comment] 2017-09-14 03:44
Will test this again tomorrow when dev comes back up.

**Closed** 2017-09-14 07:50 UTC
Labels: Confirmed, Fixed in Dev

**Comment by captainloozer** [comment] 2017-09-18 13:49
Confirmed fixed in dev

![image](https://user-images.githubusercontent.com/9828794/30545092-41ab8a50-9c4e-11e7-9d0e-d663a6fae9d0.png)
