### ISSUE TITLE
[Boss] Gyth and Rend Blackhand - Black Rock Spire

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2292] opened 2018-02-25 17:47 UTC
We wanted to do BWL yesterday and the entrance is at the end of the upper part of Black Rock Spire so we had to do the Gyth and Rend Blackhand encounter (in the arena part, below where Lord Nefarius stands).

A couple things are not working properly with this encounter:
- First, the waves of mobs spawn, but do not enter the arena, so you can ignore them completely. This is not game breaking.
- Secondly, when Gyth (the dragon Rend uses as mount) spawns, he comes to the center of the arena as expected. While he was moving to the center of the arena, he was evading my spells (which was not surprising). But as soon as he stopped moving, Nefarius used some kind of lightning spell that one shot the dragon. This is a real issue, because Rend only spawns once Gyth gets low, and the gates only open when Rend dies, so the gates stayed closed (and we needed GM assistance to continue).

I'm not sure if this could make any difference, but I entered BRS from BWL (since I was already attuned to BWL) to start from the end of the dungeon to help my group get to BWL faster.

Links:
http://www.wowhead.com/npc=10339/gyth
http://www.wowhead.com/npc=10429/warchief-rend-blackhand

**Comment by squalllh1989** [comment] 2018-02-26 04:51
- **First issue**: confirmed that the waves of mob spawn doesn't move if you don't move close to them to agro them, so you can completely ignore them.
- **Second issue**: I test it out 3 time, first when Rend ride on Gyth into the arena, i didn't do any damage on him and just wait in the center of the arena, the second time, it start damage him right away when he is moving, the third time, i go clear where the add stand, pull all the welp from the egg there and kill them all. wait for rend in there and start dps him as he spawn. What happen: 
+ _The first time_: it's true that nefarius cast a lighting on them, but the lighting didn't one shot the dragon, i see no damage from it at all, so the fight work properly, when Gyth get low on hp, Rend jump down from his back. 
+_The second time_: he doesn't evade on any of my melee hit and start agro me right away, stop moving toward the center of the arena and start fight me at the gate, there is no lighting this time and everything work properly again.
+ _The third time_: Rend spawn and run toward Gyth, want to mount on him and ride him out, but stop do that and agro and attack me, when i killed Gyth first, another Rend spawn. After killing both Rend, the gate of the arena open, but i killed them inside the arena they spawn, so the gate there close and i can't get out from there, so my suggest is you don't kill Rend inside that arena or you will be trapped.
So basicly after the test, i can't reproduce the problem that Rend is not spawn, all 3 time when Gyth is low hp or death, Rend spawn properly and when him die, the arena open.

**Comment by squalllh1989** [comment] 2018-02-26 04:53
Need another tester to try this out to see if they can reproduce the 2nd issue that Zunrin mentioned, before we can reproduce it, i will mark this as Tweaking for the 1st issue of the stand still add waves.

**Comment by Keader** [comment] 2018-03-01 13:41
Someone can test it?

**Comment by flumby** [comment] 2018-03-01 18:50
Ill test it now

**Comment by flumby** [comment] 2018-03-01 19:40
Currently Testing...
----- Start of the encounter ----
First npcs don't need to be killed.
The gate just opens and closes with no adds actually spawning.
![image](https://user-images.githubusercontent.com/36037370/36864704-53de7a3a-1d85-11e8-8703-f406afd83f58.png)
![image](https://user-images.githubusercontent.com/36037370/36864710-59844500-1d85-11e8-8fab-57529eb42535.png)
-- Still nothing this far in, loads of text speech ---
![image](https://user-images.githubusercontent.com/36037370/36864782-91cf2452-1d85-11e8-9a65-f9c5fbb4c775.png)
Then the boss enters riding Gyth.

Boss comes down the middle and I gain aggro.

at 656 hp on Gyth the other boss Rend is spawned.

**Comment by flumby** [comment] 2018-03-01 20:23
Confirm that the Boss is summoned when Gyth is very nearly dead.  Adds just need implementing.

**Comment by Keader** [comment] 2018-03-01 20:24
Confirmed by flumby.
Adds is not implemented...
I need some sniffs to implement it, and i  dont have sniffs right now
so, it need be fixed in future, cant be done now.

**Closed** 2018-03-05 08:24 UTC
Labels: Fix Confirmed in Dev, Tweaking
