### ISSUE TITLE
[Spell][ Chimera Shot - Serpent Sting] not doing the correct damage

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2754] opened 2018-09-24 16:53 UTC
[http://www.wow-mania.com/armory?spell=53209](url)

So this is about the second part of Chimera shot, the chimera - serpent sting damage. 
**How it works:** The way it is working at the moment is that despite the damage your active Serpent Sting is doing, the Chimera - Serpent Sting damage is always the same (677 non crit - 1394 crit).  It went from like 7 - 8% overall dmg to 1% in everyfight on ICC. Ill show 2 separate screenshots. 

![wowscrnshot_092418_112928](https://user-images.githubusercontent.com/40045543/45966071-c9e33600-bfef-11e8-96b9-5d6111006feb.jpg)

![wowscrnshot_092418_112855](https://user-images.githubusercontent.com/40045543/45966176-031ba600-bff0-11e8-8aac-93b42b5b8e6b.jpg)

**How it should work:** Chimera - Serpent Sting should do the 40% of the dmg that your ACTIVE serpent sting is doing to your target, that means if you cast another Serpent Sting while having set bonus proc or atk power buffs the Chimera - Serpent Sting should do more damage. I was working as intended before the patch.

**Comment by Ashamedlol** [comment] 2018-09-24 17:51
Confirmed, notice how my Chimera Shot jumps in damage but the sting doesn't:

![stingchim](https://user-images.githubusercontent.com/16576459/45969148-87474b00-c03b-11e8-9764-bdea2251b206.png)

**Comment by crulinjr** [comment] 2018-09-25 13:53
Thanks for the quick response. Hopefully this will get fixed before my raid
on thursday. You are one of the main reasons im sticking to the server,
because it can have bugs but you guys always try to fix and improve.

**Comment by wow-mania** [comment] 2018-09-25 15:57
Is this not related to #2725? If so please close it.

**Comment by crulinjr** [comment] 2018-09-25 16:15
No i dont think its related. It has nothing to do with the icc buff

**Comment by Dranah** [comment] 2018-09-25 21:29
@wow-mania nope, completely unrelated
Also #2725 existed since forever, as it is a core issue.
This issue however broke with the 2.4 update.

**Comment by crulinjr** [comment] 2018-09-25 21:41
yup. btw Dranah got another one for you hope, hope you can give it a look.

**Comment by crulinjr** [comment] 2018-09-28 18:20
Any progress on the bug? Is there a way i can help?

**Comment by Dranah** [comment] 2018-09-28 20:01
Chimera-serpent now calculates damage properly from the total damage of Serpent sting (scales with gear and talents)
However, it double dips debuff effects,

**Comment by crulinjr** [comment] 2018-09-28 20:05
What do you mean with the last stateme t

**Comment by Dranah** [comment] 2018-09-28 20:11
It's a different bug that existed for a while now. 
Spells which deal an instant damage based on % of another effect are considering debuffs on target, which is unintended. They should deal always a fix % of the original effect.
This means when your warlock applies curse of elements, it increases serpent sting damage by 13% (which leads to chimera-serpent also doing 13% more) but then chimera-serpent considers that 13% again when landing, so it ends up doing 1,13x1,13 = 27,69% more damage than originally. That is a double-dip.

**Comment by Keader** [comment] 2018-09-28 21:28
Yes, it is in PTR only.
Will be on red in next update

**Comment by crulinjr** [comment] 2018-09-28 21:30
Sorry dont know when the next update Will be

**Comment by Dranah** [comment] 2018-09-30 01:42
Double dip issue fixed as well^^

**Comment by crulinjr** [comment] 2018-09-30 02:02
Oh WoW nice. Are the changes coming next week or when?

**Comment by Keader** [comment] 2018-09-30 03:48
Yes

**Closed** 2018-10-02 09:52 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev
