### ISSUE TITLE
[Object] Storm Beacons

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#3145] opened 2019-03-22 17:06 UTC
object ID 194398-194415 + 194506
Placed in ulduar among trash before Flame leviathan

How it should work: Storm beacons should periodically (every 3-4sec) spawn https://www.wowhead.com/npc=33572/steelforged-defender until they are destroyed
How it works atm: beacons don't do anything, there are no adds spawning. The beacons are properly killable but there's no use to it since theyre harmless.

**Comment by Keader** [comment] 2019-03-24 14:17
Test now.

**Comment by Dranah** [comment] 2019-03-25 00:18
The beacons now spawn mobs, however too fast and in limited amount. Like 10 mobs spawn under 10seconds and then it stops and nothing at all.
It should be a bit slower rate (every 3-4s) , but lasting until the beacon is destroyed.

**Comment by Keader** [comment] 2019-03-25 00:56
Is 2 sec interval (checked in sniffs).
We put a maximum value, we should remove?

**Comment by Keader** [comment] 2019-03-25 23:02
Added 4 sec interval.
Removed "stop spawn" event

**Comment by Dranah** [comment] 2019-04-01 21:54
The interval is good now. NPC spawns are continuous.
However killing the tower does not stop the NPCs spawning either.
There should be no limit on count, but if the tower is dead, it shouldn't spawn more...

**Comment by Keader** [comment] 2019-04-02 01:00
???
Gime repro steps... because i cant reproduce it.

https://youtu.be/y5cicaHp_Lk

**Comment by Dranah** [comment] 2019-04-02 22:26
Working on it. I believe it has something to do with multiple vehicles attacking the building at once.

**Comment by Dranah** [comment] 2019-07-27 12:40
I managed to reproduce this. Seems to happen with some delay, after destroying the buildings, after some time the towers seem to "respawn", beginning to produce add spawns again, despite being dead already. The object itself doesn't respawn and cannot be killed again, therefore you have a dead tower spawning adds on you.

**Closed** 2019-07-29 09:45 UTC
Labels: Fixed in Dev
