### ISSUE TITLE
[NPC] The Lurker Below resets on his target's death

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5718] opened 2022-02-26 21:34 UTC
**Links:**
Lurker Below 
https://www.wow-mania.com/armory/?npc=21217
**What is Happening:**
Looks like Lirker works all fine but if his main target dies he disappears and resets and has to be fished up again. Maybe any death in raid can reset it. Didn't test it but probably it is about death of his target. There were about 12 engaged in the battle

**What Should happen:**
He shouldn't reset after the death of his target (probably).

**Comment by Rushor** [comment] 2022-02-27 07:57
That one will be hard since his normal aggro Reaktion had to be adjusted. Under normal conditions he always rsets of the Player is in the water

**Comment by Rushor** [comment] 2022-02-27 10:33
oaky have an idea, we need to add a function that checks for alive player in instance, if everyone is dead > reset.

**Comment by svijetlo** [comment] 2022-03-02 13:22
boss need to reset only if there is no target in his agro range

**Comment by Echinaceax** [comment] 2022-03-02 20:15
As the OP said (probably) 
we can close this then @svijetlo

**Comment by Greywolf59** [comment] 2022-03-03 01:33
Well I said he despawns when he kills his primary target, even if he kills him by melee on th circle, not by flushing him away. And even if there are other people in the melee range/on the circle still alive. That's what I am saying.

**Comment by Rushor** [comment] 2022-03-03 07:25
The issue is valid, atm he resets when Main target is dead, but he should only reset when nö target is left.
That case was overseen while testing the last time

**Comment by Rushor** [comment] 2022-03-03 07:25
The issue is valid, atm he resets when Main target is dead, but he should only reset when nö target is left.
That case was overseen while testing the last time

**Comment by Rushor** [comment] 2022-03-03 07:25
The issue is valid, atm he resets when Main target is dead, but he should only reset when nö target is left.
That case was overseen while testing the last time

**Comment by Echinaceax** [comment] 2022-03-03 10:03
> The issue is valid, atm he resets when Main target is dead, but he should only reset when nö target is left. That case was overseen while testing the last time

My bad 😄

**Comment by svijetlo** [comment] 2022-03-03 11:52
yes issue is valid sry i did not see before was busy with irl things

**Comment by Rushor** [comment] 2022-03-06 15:03
only if all players are dead, the boss will reset now. only option we have to fix this (due to the water level evade behaviour)

**Comment by svijetlo** [comment] 2022-03-07 09:31
![WoWScrnShot_030722_103000](https://user-images.githubusercontent.com/61908373/157004578-821e3b19-a400-4cd5-a7c3-1a3494049b9c.jpg)
reset come
![WoWScrnShot_030722_103018](https://user-images.githubusercontent.com/61908373/157004590-fd079aec-4777-4776-b635-86c0c6a69df7.jpg)
s only after all players that are in his range die

**Comment by Rushor** [comment] 2022-03-08 13:33
Perfect

**Closed** 2022-03-09 15:26 UTC
Labels: Fixed on PTR - Tester Confirmed
