### ISSUE TITLE
[NPC] Doom'rel Summoner's Tomb Trial - Blackrock Depths

### ISSUE THREAD

**Issue by SebastianPop** [WoWManiaUK/Redemption#6005] opened 2023-05-15 19:52 UTC
**Links:**
https://www.wowhead.com/npc=9039/doomrel

**What is Happening:**
In the Summoner's Tomb in Blackrock Depths, when commencing The Seven trial, Doom'rel and all the other six ghosts attack you all at once.

**What Should happen:**

Doom'rel's trial in the Summoner's Tomb of Blackrock Depths is supposed to be a gauntlet, where every ghost attacks you alone one after another, with only one of them being hostile at a time, beginning with Anger'rel and Doom'rel only becoming hostile at the very end.

**Comment by GMZinius** [comment] 2023-05-30 14:39
Thank you for reporting this issue @SebastianPop 
However you see by the wowhead comments state if you do not kill each one fast enough another one will became attackable.
The are called on a timer so you must kill each one fast

I tested this myself and saw they are on a timer 


![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/7f8674a0-6666-433f-874b-f69eab7cc34f)

**Comment by GMZinius** [comment] 2023-05-30 14:53
Yes I actually saw that Doom'rel was also attacking at the same time 
https://i.gyazo.com/f8a713001046bb6409218bd122e8b193.mp4

However If you can search a 2009 video showing the actual timers betwwen each one that would be helpful, because atm you havent provided any evidence on what the timers should actually be

I will reopen this once we have to timer information
Thank you again @SebastianPop

**Comment by SebastianPop** [comment] 2023-05-30 15:25
Okay, well, there doesn't seem to be any concrete info on what the timer is anywhere, everyone just says you need to kill them 'fast enough'. Youtube videos from 2009 on the topic seem non-existent, but current Classic Wow official server gameplay footage seem to suggest at least 30 seconds time for each, likely more.

https://www.youtube.com/watch?v=6vn6rjoew5c&ab_channel=Wrecking

Doom'Rel's 'now you will die' speech is at 1:40, which is when Anger'El becomes hostile The group manages to kill him at 2:16, so the time seems to be of over 30 seconds. The others seem to take the group 25-30 seconds on average, with no double teaming at any point (which seems to be the intended upper limit of simultaneous enemies here). I don't know if this means the timer is 35, 40 seconds, a minute, or what, but 30 seconds seems to be the minimum.

I found a 2014 video too, but the group is much faster and deals with each in around 20 seconds on average. Still the same order though.

https://www.youtube.com/watch?v=t2laoZZCHAE&pp=ygUod2FyY3JhZnQgdGhlIHNldmVuIGJsYWNrcm9jayBkZXB0aHMgMjAwOQ%3D%3D

**Comment by SebastianPop** [comment] 2023-05-30 15:35
Finally, I found something from 2009, but it's a solo run by a level 80 overleveled paladin played at double speed at various points, including parts of individual Seven fights, so it's even less help. 

https://www.youtube.com/watch?v=3mIkmIdpEW4

For what it's worth, the fight with Anger'El starts at 4:32 and is atn ormal speed until 4:41 when he actually engages him, then double speed until he's dead at 4:46, so it's even less helpful to finding out the timer. Alas.

**Comment by GMZinius** [comment] 2023-05-30 15:52
Thank you @SebastianPop 
This is enough to show that the timers are definately to short here on Mania 

also See that the voidwakkers should spawn with Doom'rel on the last fight when he should become active

**Comment by SebastianPop** [comment] 2023-05-30 17:27
Thanks for looking into it!

**Comment by Echinaceax** [comment] 2023-07-20 11:50
timers are spaced out and i saw the voidwalker spawn with him 
confirmed fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/eff68b35-d2d6-4e39-bc61-233c4aa7830c)

**Comment by SebastianPop** [comment] 2023-07-20 12:31
Thanks!

**Comment by Echinaceax** [comment] 2023-07-20 15:24
> Thanks! Wasn't sure you could fix these things without needing to issue a whole new patch.

only thing Rushor couldnt do was the order of them, which is not that much of a huge deal as he said

its nice to get some of the old stuff fixed even if not 100%

**Closed** 2023-07-21 10:45 UTC
Labels: Fixed on PTR - Tester Confirmed, Code Change, AIScript Change
