### ISSUE TITLE
Quest The Reckoning Thorim not spawning.

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#1743] opened 2017-10-15 22:02 UTC
http://www.wowhead.com/quest=13047/the-reckoning
You can see how it should be from the videos on wowhead.
You fly down to the bridge and thorim should be standing there next to his mount (which currently is in there)
You talk to him and then they do their thing and once it's done.

**Comment by stealer0517** [comment] 2017-10-15 22:04
And of course right as I post this Thorim spawns.
Either way the spawn time should not be ~30 minutes, he should spawn as soon as someone who's on the quest shows up.

**Comment by squalllh1989** [comment] 2017-10-16 05:54
Hello, stealer0517, thank you for report your problem so we can make the server better.
About your problem, I have done this quest at least for 4 of my character to get The son of Hodir rep, everytime when i come, thorim is there, i haven't ever suffer the situation like you before. And just to make sure, i just did this again and have no problem in this quest, maybe it's caused by a lag or something when you do it, but the quest is working fine. I will close this for now, feel free to comment below if you still have trouble with this quest.

**Comment by GMZinius** [comment] 2022-12-30 16:59
@Rushor 
This issue is being report again, so I have reopened this one for you

**Comment by Rushor** [comment] 2022-12-31 15:50
fix applied

**Comment by Echinaceax** [comment] 2022-12-31 16:40
fixed on PTR

**Closed** 2023-01-02 09:43 UTC
Labels: Fixed on PTR - Tester Confirmed, AIScript Change
