### ISSUE TITLE
[Spell] Penance sometimes does not trigger 3rd tick

### ISSUE THREAD

**Issue by JohnBrinkle** [WoWManiaUK/Redemption#3157] opened 2019-03-31 00:52 UTC
**What is Happening:**
The Priests discipline talent spell Penance sometimes only heals/hits two times.

**What Should happen:**
Penance should always heal in three steps.
Sometimes the last one produces a sound but no animation or actual healing.
It does not seem to depend on any effect that can pop up from the priest
and can be reproduced outside any fight.
This happens round about 10% of the time.

**Comment by Tamagucci** [comment] 2019-04-02 14:28
I just want to mention. I had this same complaint back in August 2018, and it's still occurring for me as well.

https://github.com/WoWManiaUK/Redemption/issues/2667

**Comment by wow-mania** [comment] 2019-04-03 11:41
@Dranah Is this valid?

**Comment by Keader** [comment] 2019-04-03 12:14
I need a repro case.
Without it is impossible to fix.
Right now, i cant even reproduce it, always work to me.
Maybe caused by some item proc?

**Comment by Dranah** [comment] 2019-04-03 19:37
@Tamagucci It wasn't closed without a notice, I have asked you to try macroing [nochanneling] to your penance cast to make sure it is not clipped due to lag.
I could not reproduce the problem after intense testing and 2 other testers have also failed to do so.
Which means either your character is bugged, or you're doing something wrong. None of them can be fixed by a developer on github.

**Comment by JohnBrinkle** [comment] 2019-04-04 14:07
Thank you for trying.
I got that problem without using another spell after. So nochanneling is not the problem
(I even tested it with a macro and it still happens).
I made a 1min video for you to show some penance without gear and then with it.
It may be a problem with the haste. Maybe the division is not stable with it.
I didn't see any combination with proccs that make this occur.
https://streamable.com/ee1ef
As you can see from 0:50 onward it doesn't cast penance three times - even the log says so.

**Comment by JohnBrinkle** [comment] 2019-04-04 14:10
Okay.. now I got it without any gear on.. may it be a problem with trolls? :/ 
I have no clue now

**Comment by JohnBrinkle** [comment] 2019-04-04 14:18
Here is a video about it using this macro for you
"/cast [nochanneling: penance] penance"
https://streamable.com/xr6jm

**Comment by Dranah** [comment] 2019-04-05 19:29
Thanks for the effort, this may help find a clue to begin with.
What I can tell based on the videos so far is that clipping is definitely not the problem, with or without macro. 

Here's my current theory: 
The 2-tick penances appear to tick at different intervals than the regular ones. Which means it is indeed somehow related to haste or lag (or both).
Even if you have no gear on, you have 6% haste from your native talents, and the ticks don't happen at 1 and 2sec, but something like 0,94 and 1,92, which I can see displayed on your video.
When your penance bugs, it seems to tick at regular 1s/2s instead of the values after haste, but since haste also reduces the duration of the penance channel, the spell is no longer active when the 3rd tick is supposed to go off, which is why it probably doesn't happen.
The problem is, I don't see what causes the penance channel to forget its haste values. I still cannot reproduce, because it probably requires lag that I dont have. Tamagucci mentioned to see this bug happen more when the "red area in cast bar is bigger" which indicates higher amount of ms lag.
Now, i have no idea what can be done about this.
@Keader if you can work out anything of this news, let us know.

**Comment by Tamagucci** [comment] 2019-04-13 18:52
Sorry @Dranah didn't mean to sound derogatory in that comment, which I think it came across as.

**Comment by Dranah** [comment] 2019-05-28 17:25
no issues, simply there's no way to find the problem behind the issue atm

**Comment by Keader** [comment] 2021-01-05 14:45
Bleya send me it on discord somedays ago.

https://user-images.githubusercontent.com/7120913/103659593-5ad54580-4f4b-11eb-9a14-3a5b4575255f.mp4
I got a way to reproduce and fixed it.
Let me know if someone experience this bug again after this fix.

**Closed** 2021-01-06 10:19 UTC
Labels: Confirmed, Fixed on PTR - Ready to Test
