### ISSUE TITLE
[Anub'Arak ToC 10/25] Nerubian Burrowers

### ISSUE THREAD

**Issue by forrestxyz** [WoWManiaUK/Redemption#1490] opened 2017-08-15 13:57 UTC
Reopening as asked
#1415 
@fvicaria

**Comment by soundmeow** [comment] 2017-08-16 00:13
Checked in the past 2 weeks on **10 man normal** - they borrow no matter the context. 
Not a big issue on Normal mode but does have a rather unpleasant psychological effect on **heroic mode (if it's the case)** which can potentially ruin A Tribute to Insanity denying people their well deserved cloaks.

**Comment by BatuMania** [comment] 2017-08-16 06:36
@soundmeow Indeed thats whats happening :)

**Comment by captainloozer** [comment] 2017-08-17 15:35
I was able to reproduce the issue.  With and ice patches on the ground, the burrower went under as if it wasn't there.  The ice patch did, however, break properly after Anub used his spikes under it.

**Comment by forrestxyz** [comment] 2017-08-18 06:36
Yes, it needs to e tested whether or not the adds get the debuff standing on ice patch which stops them from burrowing

**Comment by captainloozer** [comment] 2017-08-19 21:09
I personally tested on 25 man normal mode and the burrowers did not receive the "permafrost" debuff which keeps them from burrowing.  It seems that according to wowhead, there are different ID's for the debuff depending on which difficulty you are using.  I will post them all here along with an image showing the burrower on top of the ice patch with no debuff.

http://www.wowhead.com/spell=66193 10 N - Permafrost
http://www.wowhead.com/spell=67856 10 H - Permafrost
http://www.wowhead.com/spell=67855 25 N - Permafrost
http://www.wowhead.com/spell=67857 25 H - Permafrost

![burrower1](https://user-images.githubusercontent.com/9828794/29490126-b99c52d2-84f8-11e7-8851-bb754580106a.PNG)

**Comment by fvicaria** [comment] 2017-08-20 13:33
Have taken another stab at it. Please test again.

**Comment by captainloozer** [comment] 2017-08-20 13:57
It seems that I am getting the permafrost debuff now, but the burrowers are not.

![burrower2](https://user-images.githubusercontent.com/9828794/29495468-894ae408-8585-11e7-96e3-6ca7b7910e2a.PNG)

**Comment by captainloozer** [comment] 2017-08-20 16:47
After testing several times I can confirm that if the PLAYER that has aggro on the burrower has the permafrost debuff, the burrower will not burrow.  The burrower still does not visually have the permafrost debuff.  If the player steps off of the ice patch far enough to drop the debuff, even if the burrower is still visually on top of the ice patch, the burrower will burrow.

**Comment by captainloozer** [comment] 2017-08-20 17:25
Janitor is confirming this will be the intended mechanic.  In order to prevent the Burrowers from going under, the player they are currently targeting must have the permafrost debuff, or in other words, standing on the ice patch while tanking.

Confirmed fixed on dev.

**Closed** 2017-08-22 09:57 UTC
Labels: Confirmed, Fixed Confirmed in Dev
