### ISSUE TITLE
[NPC] Crusader Olakin Sainrith - 30708 - Icecrown

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3960] opened 2020-01-06 13:11 UTC
**Links:**
https://www.wow-mania.com/armory/?npc=30708

**What is Happening:**
Crusader Olakin Sainrith is showing ! symbol even when no quest available to take, before any quests have been completed in the Blackwatch subzone.
![image](https://user-images.githubusercontent.com/46089380/71820048-cb6e2b80-3085-11ea-8663-94c5ba684300.png)

**What Should happen:**
Should not appear to offer quests before quests are actually available

**Comment by wow-mania** [comment] 2020-01-06 13:46
This is a generic issue.

**Comment by Kitzunu** [comment] 2020-01-06 13:58
No it is not @wow-mania

**Comment by Kitzunu** [comment] 2020-01-06 14:03
The issue is that quests has condition SourceTypeorReferenceId = 19 but dont have SourceTypeorReferenceId = 20 assigned to it.

**Comment by jarvik76** [comment] 2020-01-07 22:56
Looks fixed.  Sainrith correctly not offering quests.
With zero prequests done:
![image](https://user-images.githubusercontent.com/46089380/71935982-1a0fe880-31a0-11ea-8c27-5dfc64dd5b3d.png)
With prequest 13106 leading to Blackwatch done:
![image](https://user-images.githubusercontent.com/46089380/71936217-b803b300-31a0-11ea-8e2c-25f88ddf5e83.png)
With next in chain from Arly taken:
![image](https://user-images.githubusercontent.com/46089380/71936275-dbc6f900-31a0-11ea-90ca-55ea4ac012b8.png)

**Closed** 2020-01-10 10:38 UTC
Labels: Fix Confirmed in Dev, Fixed in Dev
