### ISSUE TITLE
[Quest] Wrath of the blue flight

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#1529] opened 2017-08-27 07:51 UTC
This is the quest : http://www.wowhead.com/quest=5162/wrath-of-the-blue-flight

When accepting the quest, the NPC [Haleh](http://www.wowhead.com/npc=10929/haleh) should kick you off the mountain to the plaguelands.
This does not happen, so you have to travel there to continue the quest.

**Comment by fvicaria** [comment] 2017-08-27 08:03
Should be fixed in the next update. Thanks for the report.

**Comment by captainloozer** [comment] 2017-08-27 08:08
Confirmed as shown in the video

https://youtu.be/eeFE4mSAcps

**Comment by captainloozer** [comment] 2017-08-27 08:14
Tested the quest again after the fix.  As shown in the video, working as intended.  Confirmed fixed in dev.

https://youtu.be/DxbZTHMQEeA

**Closed** 2017-08-29 10:34 UTC
Labels: Confirmed, Fixed Confirmed in Dev, Fixed in Dev
