### ISSUE TITLE
[Dungeon/NPC] Azjol-Nerub (Double watchers)

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4695] opened 2020-06-24 19:55 UTC
**Links:** https://www.wowhead.com/npc=28729/watcher-narjil
https://www.wowhead.com/npc=28731/watcher-silthik
https://www.wowhead.com/npc=28730/watcher-gashra
https://www.wowhead.com/npc=28684/krikthir-the-gatewatcher

**What is Happening:** There are currently doubles of every watchers present before the first boss of Azjol-Nerub. It used to be ok before today, but now there's duplicates.

On this first screenshot we can see the outlines of both duplicates of Watcher Silthik, as well as the double level marker (81) on the health bar.
![WoWScrnShot_062420_154003](https://user-images.githubusercontent.com/34783736/85621054-ade04e80-b632-11ea-9b7c-e4db4133132a.jpg)

In combat with both Watchers Narjil
![WoWScrnShot_062420_154050](https://user-images.githubusercontent.com/34783736/85621159-d0726780-b632-11ea-9396-a2821fb325bc.jpg)

In combat with both Watchers Gashra
![WoWScrnShot_062420_154132](https://user-images.githubusercontent.com/34783736/85621197-e122dd80-b632-11ea-96e4-58e86eeafdf6.jpg)

**What Should happen:** The packs in front of [Krik'thir the Gatewatcher](https://www.wowhead.com/npc=28684/krikthir-the-gatewatcher) should consist of 1 watcher and 2 minor spiders, for a total of 9 mobs (3 packs of 1 watcher with 2 spiders).

**Comment by jeyrella** [comment] 2020-06-24 22:30
Curious.  Confirmed.  Am marking this as regression as this was definitely correct before now.

![image](https://user-images.githubusercontent.com/46089380/85634177-b8223d00-b672-11ea-810a-2e0af4ed8577.png)

**Comment by jeyrella** [comment] 2020-06-26 09:49
Upgrading this to "not working" as it is causing many groups to wipe due to the sheer overpowering scale of power currently in the room.

**Comment by Rushor** [comment] 2020-06-26 11:02
fixed

**Comment by jeyrella** [comment] 2020-06-26 15:18
Looks good here.
![image](https://user-images.githubusercontent.com/46089380/85873097-9509a180-b7c8-11ea-9e25-d902b1f2b6b5.png)
![image](https://user-images.githubusercontent.com/46089380/85873118-9a66ec00-b7c8-11ea-9057-7cdc8bf32ca4.png)

**Comment by jeyrella** [comment] 2020-06-26 15:19
Leaving regression label on ticket for visibility on weekly update notes

**Closed** 2020-06-30 10:41 UTC
Labels: Fix - Tester Confirmed, Regression
