### ISSUE TITLE
[Quest] The sacred and the Corrupt

### ISSUE THREAD

**Issue by StefannelA** [WoWManiaUK/Redemption#882] opened 2017-02-23 20:41 UTC
Hi!
There is a problem with Light's Vengeance with attempting to pick it up.
The elite vyrkul is unattackable and cause of this, nothjing happens with attempting to pick up Light's Vengeance. In fact,n nothing happens when I click on the light's vengeance from the ground.

**Comment by fvicaria** [comment] 2017-02-23 21:26
Please read this next time you log an issue: https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by hotdoggidy** [comment] 2017-02-24 07:22
After Picking up the quest in Icecrown Citadel (http://wotlk.openwow.com/quest=24545), the player is sent to "Frostmourne Caverns" to retrieve "Light's Vengeance"(http://wotlk.openwow.com/item=49869) . 
As you approach the cave in Dragonblight ( 74.00 24.00) the area seems stuck between phases. 
"Deathbringer Revenants" (http://wotlk.openwow.com/npc=27382) are roaming the cave. The cave should be empty during this phase of the quest. 
"Wretched Ghouls" (http://wotlk.openwow.com/npc=37881) are also wandering the back of the cave. They should only be spawned when a player initiates the quest script by entering the cave and approaching "Light's Vengeance" near the center of the cave (75.00 20.31). 
Instead, the hammer is lying at the corner of the cave (76.00 20.78) where the player is meant to activate it to clear the room of the "Wretched Ghouls" spawned by Lich King when the script begins. 
"Vegard the Unforgiven" (http://wotlk.openwow.com/npc=37893), also spawned by Lich King at start of script, is not in the cave. To progress the quest from where it currently stands "Light's Vengeance" must be activated to destroy Vegard and all remaining Ghouls, landing back in the middle of the cave @ (75.00 20.31).

3min video of quest: https://www.youtube.com/watch?v=4CufhOOZVTc

Looking at the situation it feels as if someone was attempting the quest and got caught by a server reset and merged the phases.

Screenshot taken from "Light's Vengeance", facing the middle of cave where Vegard should be.
![wowscrnshot_022417_001859](https://cloud.githubusercontent.com/assets/23442126/23294124/151e7f84-fa27-11e6-95c2-563559e0634a.jpg)

**Comment by hotdoggidy** [comment] 2017-02-24 08:04
Same issue on Frostmourne server. 
-Cave does not phase properly. Revenants are "chillin" inside.
-Quest script began properly when character approached hammer. LK roleplay worked as intended.
-Hammer can be clicked but does not clear room of ghouls or destroy Vegard.
-quest cannot be completed.

**Comment by fvicaria** [comment] 2017-02-24 09:43
Please restest after restart. Start from scratch.

**Closed** 2017-02-24 17:09 UTC
Labels: Confirmed, Fixed Confirmed in Dev, Fixed in Dev, Tweaking
