### ISSUE TITLE
[NPC] Blackheart the Inciter - players do not use abilities while MC, room mobs not linked

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5723] opened 2022-02-26 22:54 UTC
**Links:**
https://wowwiki-archive.fandom.com/wiki/Blackheart_the_Inciter
Boss:
https://www.wow-mania.com/armory/?npc=18667
https://tbc.wowhead.com/npc=18667/blackheart-the-inciter#abilities;mode:normal
**What is Happening:**
I am not sure atm but I doubt he pulls the whole room with him. He has a lot more health than he should have (real damage is higher than 140k stated in his healthbar), his Incite Chaoes causes players to only autoatrack each other without using any abilities plus they keep turning around all the time which reduces the autoattack count too.
This goes both for normal and HC. Also not sure about his melee damage in HC.

**What Should happen:**
The boss should have only 140k HP, maybe should hit harder on heroic and wowwiki suggest that dueing the CC the players should use at least some of their abilities. I would also check the aggro wipe mechanic after the CC.

**Comment by Rushor** [comment] 2022-02-27 07:54
Aggro wide mechanic is correct, the Rest i gonna check

**Comment by svijetlo** [comment] 2022-03-02 13:17
if you pull him wo killing mobs in room he will pull all of them also
mind controlled players need to use their own class abilities
his health is 140 000 hp

**Comment by jeyrella** [comment] 2022-03-03 09:15
To be clear, he is *supposed* to pull all the mobs in the room if you do not clear.  It's *why* you need to clear.  That is not an issue.

**Comment by Greywolf59** [comment] 2022-03-03 09:48
I have tested it just now on normal difficulty. He does not pull the room.

**Comment by Greywolf59** [comment] 2022-03-03 09:53
If I am alone there on my feral, he makes me use survival abilities like barkskin and survival instincts. And to throw innervate on him. But that is all. No heals. And when I am with someone else, I just auto attack them. Maybe he can only use those abilities that do not trigger gcd, cause neither barkskin, survival instincts, nor Innervate do.

**Comment by jeyrella** [comment] 2022-03-03 09:57
> I have tested it just now on normal difficulty. He does not pull the room.

Ah, please make tickets clearer in future of the exact problem, as this was misunderstood.

**Comment by jeyrella** [comment] 2022-03-05 00:07
Melee damage modifiers are correct on HC

**Comment by mfranca0009** [comment] 2022-03-22 21:24
### Issues Corrected
- [x] All trash mobs within `Blackheart the Inciter`'s boss room will now aggro if engaging the boss before they are cleared.
- [x] `Incite Chaos` has been reworked and is functioning as intended using same blizzlike technique.
- [x] `Cabal Familiar` and `Cabal Warlock` corrected to allow combat move; they were being held in place due to poor SmartAI action being called outside of combat.

All other general issues marked here will be corrected as a different issue: #5737

**Comment by Echinaceax** [comment] 2022-03-22 21:29
confirmed fixed in PTR 

https://i.gyazo.com/38ff479f5c937efcac5c0502b138ce37.mp4

**Closed** 2022-03-28 11:25 UTC
Labels: Fixed on PTR - Tester Confirmed
