### ISSUE TITLE
[Boss] Freya-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2136] opened 2018-01-21 10:51 UTC
Attempted Freya today with my guild and found two issues that I can confirm with screenshots. For the majority, the fight seems to work well. The adds spawned at appropriate times. There may be an issue with the chain lightning from the Stormlasher casting chain lightning instantly without us being able to interupt but I can't confirm this so I will wait to confirm before reporting this.

1) The main issue with the fight right now is that on hard mode Freya is supposed to gain a new ability called Solar Flare, which is similar to the spell sunlight. Sunlight is cast on normal mode and looks like a giant sunbeam that comes from the sky and explodes onto a raid member. Its essentially an aoe on the ground, spell linked here:
http://www.wowhead.com/spell=62872/sunbeam#used-by-npc
The spell looks like this which are screenshots i took from ensidia's kill on retail 
https://cdn.discordapp.com/attachments/319713049768493057/404578893870268447/unknown.png
Video Reference:
https://www.youtube.com/watch?v=w2w2973jfBo

This spell works fine on Redemption server, but it's important to distinguish it from Solar Flare which is why I linked it.

Solar Flare is similar to Sunlight but it looks slightly different, only happens on hard mode [note: the spell can also be seen if you decide to attack and kill Elder Brightleaf before starting the fight on Freya. It might be useful to test this NPC as well as the boss for this ability, to see if it's working correctly for him.]  , and instead of being an single shot aoe, its stays on an area and ticks for damage if any raid member stands inside of it. It's essentially an aoe dot that ticks for roughly 4k nature damage.  I believe the range is 8 yards, which is the same as sunlight. 
Link to the Spell, as far as I can tell, the description is kind of weird:
http://www.wowhead.com/spell=64087/solar-flare
Link to Elder Brightleaf:
http://www.wowhead.com/npc=32915/elder-brightleaf#abilities

The following images are taken from both Ensidia's video and Tankspot's guide to Freya 3 Elders which show what Solar Flare is supposed to look like:
https://media.discordapp.net/attachments/319713049768493057/404578575921184789/unknown.png?width=1602&height=676
https://media.discordapp.net/attachments/319713049768493057/404579036300574750/unknown.png?width=1602&height=676
https://media.discordapp.net/attachments/319713049768493057/404579538375278602/unknown.png?width=1602&height=676
Video Reference:
https://www.youtube.com/watch?v=HJ1gxZZSRtI&t=133s

As you can see the first two images look different than the third. This is because Blizzard patched Ulduar at some point and changed the animation. In my opinion if you had to choose one animation to use I'd pick the first one because there was alot of hate towards Blizzard for using the second animation as it made the fight alot harder, but thats just my two cents. 

So issue 1 stems from the fact that currently on the Redemption server no animation shows letting you know that you are standing in Solar Flare. You can't see it cast, Deadly Boss Mods does tell you that the beam is on you and tells you to move, but not being able to see them makes the fight incredibly difficult, as people will run into them without knowing while we are trying to deal with the adds. If we are fighting the Guardian Spirit, and have to stack under mushrooms in order to be able to cast, without warning suddenly everyone just starts taking massive damage and we wipe. When you try to pull all of the  detonating lashers together by stacking, suddenly Solar Flare on top of the raid and no one sees it and we wipe. So the fight currently is kind of undoable as we can't see Solar Flare cast. Keep in mind that it's not just running out of the area that's the problem, the raid needs to know where it is so that we don't move into it, and there is alot of movement in this fight. 
Screenshots of me today trying to do the fight:
[Note: we did the fight and I didn't know what was going on so later I pulled 4 guildies into the group to confirm that it was indeed a visual bug so that I could report it. That's why there is only four of us]
https://media.discordapp.net/attachments/319713049768493057/404572689739808779/unknown.png?width=1602&height=676
https://media.discordapp.net/attachments/319713049768493057/404573033270083585/unknown.png?width=1602&height=676
https://media.discordapp.net/attachments/319713049768493057/404573692748627968/unknown.png?width=1602&height=676

As you can see there is no visual indication that lets me know I am standing in the Solar Flare.

2) Honestly this one is not a big deal, during the fight on Hard Mode Freya will root a random target within the raid group in place.
Link to spell:
http://www.wowhead.com/spell=62438/iron-roots

If you don't kill the roots on the fight and you wipe when you resurrect you will see that the roots are still there, not a big issue as you can just wait for Freya to walk away and kill them before you are ready to pull. But it shouldn't happen so that's why I'm reporting it. 
Screenshot of the Iron Roots on the ground after a wipe:
https://media.discordapp.net/attachments/319713049768493057/404573430407757824/unknown.png?width=1602&height=676

I tried to be as thorough as possible on this one so that hopefully it can speed up the process in fixing these issues. I'm currently 3/5 Hardmode bosses killed so that I can unlock Algalon. Hopefully soon the issues with Freya and Mimiron will be corrected so that we can work on killing him. The raid resets tomorrow so I am going to go through the raid as far as possible with my guild to see if anything else needs to be fixed, I also plan to try XT-002 on Hardmode to see if there is anything to report.

**Comment by Dranah** [comment] 2018-01-29 17:14
Leaving an abstract version of Bartok's newest report here:

1) Solar Flare is cast on way too many raid members. 
- How it should work: 
10 man should have Solar Flare being cast on 1,
25 man there should be a maximum of 3 beams being cast.
Link's to some videos for review:
https://youtu.be/HJ1gxZZSRtI
https://youtu.be/w2w2973jfBo

- How it works right now: 
10 man : minimum of 4 casts and a max i think tonight i saw of 7.
proof: https://media.discordapp.net/attachments/319713049768493057/407377855572344842/unknown.png?width=960&height=405
The 10m fight was still doable on hard mode, but much much more difficult.

2) 
How it works right now: Adds will continue to spawn even after phase 2 begins. Seed pods are seldom cast.
How it should work: After killing 6 waves of adds, she stops spawning more and will be focused on throwing out get seed pods.

**Comment by Keader** [comment] 2018-01-29 17:59
I dont get it.
You complain about Solar Flare, but the Screenshot show SunBeam spell
What's wrong, Sunbeam or Solar Flare?

**Comment by Keader** [comment] 2018-01-29 19:34
Test again :)

**Comment by Bartok14** [comment] 2018-01-30 00:05
Hey Janitor, I wasn't trying to report issues with the fight that were already known. Last week when I reported the original post it was that I couldn't have known about these two issues, the reason being that we didn't see the spell Solar Flare being cast, so we couldn't have known that there were too many casts going off at once. The second issue we couldn't have known because we could not make it to phase 2 last week as we were wiping on the fight due to solar flare not having a visual indication. Sorry for any confusion as to when I posted this topic. I'm going to make a forum post about suggesting perhaps that you update the suggestions for making a topic. The reason for this is that I had received an email today that said I was supposed to re open the original post on Github today, and I don't have the authority to do that. Also I'm not sure if you and the other Developers read closed topics if I post further information on them. If you could clarify for me in the future what you want me to do.

My current plan is to continue posting any NEW issues that I find in Ulduar, after the previous fixes have been implemented. Do you want me to make a new topic about this? Or will you see any new issues that I submit to closed topics?

**Comment by Bartok14** [comment] 2018-01-30 05:54
In the matter of whether the ability is sunbeam or solar flare to the best of my knowledge it's called Solar Flare. Sunbeam is the ability that Freya Casts during the regular 10 and 25 man attempts. Elder Brightleaf will cast Solar Flare which is the aoe dot that stays in place for about 8 seconds or so. Since you don't kill him on the hard mode attempt it allows Freya to cast both Sunbeam and Solar Flare. I've marked the image here so that you can distinguish the difference in the animations. 
 
![ulduar freya solar flare marked](https://user-images.githubusercontent.com/32959403/35550337-eb463b38-0557-11e8-899a-dd9583f20608.png)

A link to both abilities can be found here as well as a link to Elder Brightleaf:
http://www.wowhead.com/spell=64087/solar-flare
http://www.wowhead.com/npc=32915/elder-brightleaf#abilities
http://www.wowhead.com/spell=62872/sunbeam#used-by-npc

**Comment by Dranah** [comment] 2018-01-30 19:30
UPDATE:

-  Solar flare now targets only 1 player on 10man mode and 3 players on 25man (Fixed)
-  Add waves no longer spawn during phase2 (Fixed)
-  Nature bombs are now cast more frequently during phase2. (Fixed)

Additional problems to report:

1. Timers for spells Freya inherits from elders are wrong. I extracted data from retail videos and compared them to how often they are cast on Redemption.
http://www.wow-mania.com/armory/?spell=64087 Solar Flare 
http://www.wow-mania.com/armory/?spell=62440 Roots
Ground Tremor appears fixed since last night.

How it should work: 
- All three abilities run on a separate, roughly half minute cooldown, otherwise Freya uses them in random order. 
- Freya does not start using these special abilities until about ~20-25sec into the fight

How it works right now:
- Freya starts casting these spells together with the first wave of adds.
- Ground Tremor runs on a proper ~28sec cooldown after the latest tests
- Strengthened Iron Roots:
Cooldown appears to be ~12sec (too frequent!)
- Solar Flare:
Cooldown appears to be ~16sec (too frequent!)

2. Ancient Conservator's Nature's Fury http://www.wow-mania.com/armory/?spell=62589 
This spell should be cast every ~15seconds on 10man version and every ~5seconds on 25man version, making it affect overall 3 times more players on 25m as a result.
How it works right now: the spell is cast every 5sec on both difficulties.

**Comment by Keader** [comment] 2018-02-01 23:28
Fixed timers issue.
Will be in dev tomorrow morning.

**Comment by Dranah** [comment] 2018-02-02 14:09
UPDATE:
- Freya no longer casts her special abilities in the first 20seconds of the fight (Fixed)
- Internal cooldown for Strenghtened Iron Roots and Solar Flare is fixed.
- Nature's fury's no longer recast before the previous expires on 10man mode (Fixed)

Additional problems:

1) Adds health: Not every add receives the intended hard mode health values when doing hard mode.
It appears that the hardmode health values are only working for adds that spawn in the direct proximity of Freya. Adds that spawn further retain their original non-hardmode health values, making the fight considerably easier.
- Example: 
Roots that spawn on melee/tank have their increased 30k health, roots that spawn on ranged targets have the original 19k.
Ancient Conservator that spawns on top of melees has the intended 836k health, the ones that spawn a bit further at the ranged group have only 522k.
90% of the lashers that spawn have their original 71k health, only a few that spawns closest to Freya gain 114k (hardmode health)
Same goes for Eonar's gift.

2. Nature's bombs
The first cast of the pods in phase2 is delayed, on blizz videos it happens roughly 24-25 seconds after removing the last stack and beginning p2, here it happens ~50 seconds after. The frequency of pod casts afterwards works as intended (that was fixed earlier)

**Comment by Keader** [comment] 2018-02-02 23:37
Fixed in my server, i will pass to janitor tomorrow morning.
I will not accept any "update" with new bugs.
It's enough for me

**Comment by Keader** [comment] 2018-02-03 11:49
Sended to Janitor, will be up in next restart.
Well, to me freya is done.

**Comment by Dranah** [comment] 2018-02-03 14:24
Above problems are fixed. Good to go on red.

**Closed** 2018-02-07 10:14 UTC
Labels: Fix Confirmed in Dev, Fixed in Dev
