### ISSUE TITLE
[Calendar] Calendar event game crash

### ISSUE THREAD

**Issue by svijetlo** [WoWManiaUK/Redemption#4364] opened 2020-04-05 12:40 UTC
**Links:**
non

**What is Happening:**
 if person who is no officer in guild and has no privilege of making public calendar events for guild make private event on calendar and sends invites out to players , the player who click Accept or anything other on event invite will have his/her game crash/taken out to login screen then and for all other interactions and sign ups for calendar events unless they are moderator of event.

**What Should happen:**
Events on calendar should not log out/crash your game

**Comment by wow-mania** [comment] 2020-04-05 13:44
cannot reproduce this

**Comment by wow-mania** [comment] 2020-04-05 13:45
and everyone should have our client otherwise, frankly, we don't care.

**Comment by jeyrella** [comment] 2020-04-05 13:53
See https://github.com/WoWManiaUK/Redemption/issues/4342
This is players with the client.  Not all players, and not even all toons on an account.  It is reproducible by those players.  Suggest anyone that suffers from this to capture their log in the "Errors" folder inside the wow-mania install folder
![image](https://user-images.githubusercontent.com/46089380/78500207-22e76a80-774d-11ea-8067-18d2c3f71d24.png)

**Comment by svijetlo** [comment] 2020-04-05 14:09
i em on most recent our client, i use most recent launcher and it happens to me today ,

**Comment by yani** [comment] 2020-04-05 19:03
I've seen this happen to many people already. Definitely has some weird conditions to trigger, but it often happens.

**Comment by Keader** [comment] 2020-04-05 21:13
I tested like this topic said, and i cant reproduce.

**Comment by Aristo14** [comment] 2020-04-06 00:13
Have to close it until more info becomes available, both keader and janitor couldn't reproduce.

**Closed by Aristo14** 2020-04-06 00:13 UTC
Labels: Invalid - Cannot Reproduce, Priority - Low
