### ISSUE TITLE
Procrate lock and load on black arrow

### ISSUE THREAD

**Issue by Aristo14** [WoWManiaUK/Redemption#2922] opened 2018-12-17 15:14 UTC
http://www.wow-mania.com/armory/?spell=56344
http://www.wow-mania.com/armory/?spell=63672

The procrate of the lock and load ability seems to be a bit to low. 
 
### Testresults on dummy 

20 BA shots = 100 BA dots 
_6% procrate_
**expected** procs: **6** 
**actually** procs: **3**

40 BA shots = 200 BA dots 
_6% procrate_
**expected** procs: **12** 
**actually** procs: **6**

60 BA shots = 300 BA dots 
_6% procrate_
**expected** procs: **18** 
**actually** procs: **9**

80 BA shots = 400 BA dots 
_6% procrate_
**expected** procs: **24** 
**actually** procs: **12**

100 BA shots = 500 BA dots 
_6% procrate_
**expected** procs **30** 
**actually** procs **15**

As you can see the results are falling behind, but in a noticable consistent manner. 
NB:  I did not use BA during the icd of the lock and load proc, I waited out the 22seconds.

**Comment by Dranah** [comment] 2018-12-17 18:59
Something is off about your test numbers.
You claim you did not use BA during the ICD lock, but you are saying 20 BA shots = 100 ticks, implying each BA you cast ran a full course of 5 ticks.
Unless you always, and I mean always, had the proc happen on the last tick and then waited the 22second, this is just not possible.
Because if you get a proc on i.eg. first tick, the remaining 4 ticks are going to be ICD locked and statistically not representative.
On average, this means half the ticks from each BA are going to be ICD locked (averaging out the number of procs happening from 1st, 2nd, 3rd, 4th or 5th tick), which, for me, could explain why you are finding exactly half the amount of procs that you expect.

In my tests, only counting the ticks until the proc happen, their proc rate looks ok.

**Comment by Aristo14** [comment] 2018-12-17 21:33
Ok so per 100 ticks about 3 to 5 are during the proc

**Comment by Aristo14** [comment] 2018-12-17 21:47
i re-opened and removed cannot reproduce to prevent it from being closed without checking again ;)

**Comment by wow-mania** [comment] 2018-12-17 22:06
You cannot confirm your own issue.

**Comment by Dranah** [comment] 2018-12-17 23:54
Other testers are always free to add their input, but for as long as my testing goes, I found the 6% proc rate to be working as intended. 

Perhaps my theory is wrong about why you are finding lower proc rate, however you need to admit that your numbers are very artificial.
If you are making a bug report based on inaccurate numbers (and you did confess that you did not bother to discount the ticks that were affected by ICD), that makes me question its validity.

With that being said, if anyone has the time and energy, feel free to do more tests - as I always say, one test sample is never a real test. You had 3 procs over 20 casts, I had 3 over 6 casts, that tells enough about how RNG works.

**Comment by Aristo14** [comment] 2018-12-18 11:12
Well theorethically you will need about 1000 ticks (200 BA shots) to come to some empirical data that can be considdered viable to make any conclusions. 

My numbers are in now way "very artificial" 

Making complete and utter wrong calculations and then calling my numbers questionable, because I didnt mention the 1 or 2 ticks per proc being locked, is really ridiculous. If you dont want to look into it or fix it then please let others take a proper look at it. 

My 100 BA shots had a very consistent result of 3 procs per 20 BA shots (approx. 95 ticks) expected procs is 5.7 due to this. Still making procrates seem consistently lower. 

The whole reason I spend about an hour mindlesly shooting BA shots is to make sure rng had little effect on it.. doing only 6 shots getting 3 procs is in no way near testing. 

Thanks for your time, I hope someone can look into this.

**Comment by Dranah** [comment] 2018-12-18 19:52
Your arrogance is beyond me.
Just because I came to different results than you, it does not mean that I didn't look into it.
Having 3 procs over my first 6 shots was simply an example for how RNG works, I did not stop testing at that point... but I think we both know that. I think you're very well aware that i'm not testing anything with just 6 shots, so right now i'm certain that you're just taunting me on purpose.

I have never prevented any other tester from taking a look or forming a second opinion.
The ugly truth is that nobody else seems to give a damn to test your reports.

**Comment by Aristo14** [comment] 2018-12-19 15:14
I'm not trying to taunt you, i'm just stating where you where wrong in your conclussions. 

I took another hour to shoot another 100 black arrows to get the same result. 

This time I noted how many of the ticks where locked due to the proc, in total there where 37 ticks locked in total. 

500-37=463
6% of 463 =27.78

Expected procs: 27.78 
Actual procs:  15 

Again in a very consistent lower then expected manner. 

Combining earlier results the 200 BA shots total a 1000 ticks (before substracting locked ticks)
all in all so far the results show that of a procrate around 3.25%

**Comment by Dranah** [comment] 2018-12-19 21:22
Repeatedly saying that your report hasn't been properly looked into just because I came to different results is completely belittling and degrading towards me, for me that covers the meaning of "taunting".

Now, according to Keader, the proc is set to 6% as intended in the script.
On my tests, the numbers are within RNG limits of a 6% proc. (4,2% and 4,8% rate on my two tests with 90 BA casts. Roughly 13% of my total ticks were ICD locked - yes perhaps I went overbound saying its half the ticks - but this is still a large error that cannot be ignored)
If there is a specific condition that alters the proc rate, it's a needle in a haystack we won't find unless you point out what exactly it could be. 
My job here is done and if I cannot confirm the issue, i am ought to label it that way. It's not my problem if Jani closes the thread because nobody else looks at it.
But if that makes you happy, I won't put any label so for me the thread can stay open forever.

**Comment by Aristo14** [comment] 2018-12-20 11:17
Im sorry if you think I called you lazy, again this is not what I stated. What I did state was that due to the completely wrong calculation of the missing ticks in my testresults, it may have been to easily closed. 

I did later on thank you for your time (and again I do thank you for your time)  the things I said about doing few shots was with a ;) Sorry if it gave the wrong impression. 

We both have spend mindlessly numb hours testing, i'm curious about with what gear and spec you did test it? Im seeing very consistent lower numbers when i'm testing and i'm starting to think this maybe due to another ICD locking the proc? Could that be a posibility?

Ill be happy to spend more hours on it, all im asking is some feedback on this matter. 

Ill tag this myself, if the rate is correct then it must be something else interfering and ill have to figure it out.

**Comment by Aristo14** [comment] 2018-12-20 11:18
I see I can't anymore, feel free to tag and close

**Comment by Dranah** [comment] 2018-12-20 18:42
I'm glad you realized that we're on the same side here. I come here to try and confirm reports, not to close them prematurely.
To answer your question, anything is a possibility. Any talent, any proc, any aura could interact with it.
I feel more this is an RNG issue, because unlike you, I found no consistence during my tests. Often I have chain procs on every 2-3 BA, and then nothing for 15 casts at all. 
I've been testing with a naked hunter with no other spells used. I had only talented enough points into surv to pick up BA.

**Comment by Keader** [comment] 2018-12-21 10:40
i can take a look on this tomorrow.
Last week on uni before vacation, so... is a hell

**Comment by Dranah** [comment] 2018-12-22 14:45
After speaking with Keader, we found an extra RNG factor in spell mechanism which could explain why sometimes the spell appears to proc less than intended.

The 22sec ICD is apparently not a real ICD. It does not prevent the spell from procing while it lasts, it only prevents the player from gaining the aura from proc. Which means the spell CAN proc while it is on ICD, it will just have no effect. So a number of procs will happen during the ICD locked ticks that are "lost" due to the player not being ready to benefit from the effect.
This is obviously heavily RNG based, but this means statistically you will never reach the intended 6% of procs/ticks because a part of the procs (even if a small part) will always happen from ticks that are iCD locked. This is just how blizzard scripted the effect.

Currently this is all we have, couldn't find any other error or interference that could reduce tick count.

**Comment by Keader** [comment] 2018-12-23 15:48
No problem founded here.
Closing.

**Closed by Keader** 2018-12-23 15:48 UTC
Labels: Cannot Reproduce
