### ISSUE TITLE
[Object] Blight Crystal - Not respawning

### ISSUE THREAD

**Issue by lecoo123** [WoWManiaUK/Redemption#5845] opened 2022-06-01 21:55 UTC
**Links:**
![WoWScrnShot_060222_004858](https://user-images.githubusercontent.com/106707879/171507942-4496c649-0bb7-4a59-858c-f5278ebeaeab.jpg)

**What is Happening:**
I dont see any crystal which quest area shows. i change my video setup to ultra but it didn't change. I delete the cache file by launcher but it didn't change too.
there is a problem but i dont have any idea :/

**What Should happen:**
I see the crystals and use pet skill to get them.

**Comment by Echinaceax** [comment] 2022-06-01 22:17
Thank you again @lecoo123 for report a 2nd one 
i commented here that we found the issue https://github.com/WoWManiaUK/Redemption/issues/5844#issuecomment-1144192823 and i was making a seperate report 



@mfranca0009 respawn issue tested and confirmed in PTR
https://www.wowhead.com/object=191182/blight-crystal

**Comment by mfranca0009** [comment] 2022-06-04 03:04
Due to deep-rooted problems with gameobject respawning on forced despawn, `crystalized blight` gameobjects won't despawn anymore when the `Blight Geist` hits the crystal.

Quest should work as it did, just without the despawning of the crystal.

**Comment by Echinaceax** [comment] 2022-06-04 07:12
Confirmed fixed in PTR 

https://i.gyazo.com/2451a6934595e07cf80904a3771eae90.mp4

**Comment by Echinaceax** [comment] 2022-06-08 08:53
gone to live

**Closed by Echinaceax** 2022-06-08 08:53 UTC
Labels: Fixed on PTR - Tester Confirmed
