### ISSUE TITLE
[NPC] Bloodscalp Mystic

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2671] opened 2018-08-18 15:34 UTC
NPC ID - 701
Healing Ward - 11986
Quick Flame Ward - 4979

What is happening - The NPC will begin to cast Healing Wave and will switch mid-cast to Quick Flame Ward. Or, the NPC will begin to cast Quick Flame ward and switch mid cast to Healing Wave.

SS of said NPC going from Healing Wave to Quick Flame Ward (Notice combat log)

![wowscrnshot_081718_195242](https://user-images.githubusercontent.com/25806987/44300761-e776fe80-a2d1-11e8-8a16-43762fbd86ac.jpg)

How it should work - 

  NPC begins casting a spell and it should finish unless it is interrupted or the NPC is killed.

**Comment by Keader** [comment] 2018-08-18 21:46
Cant reproduce.
Tested in game, and he just cast healing weave when has a friendly target with less of 500 hp. And it happens only 1 time.

**Comment by Dranah** [comment] 2018-08-20 17:26
This happens because the Quick Flame Ward spell runs on a timer (NPC wants to cast it with fixed intervals) while the Healing Wave spell runs on a percentage health.
If the timer and the health percentage coincide, the NPC will attempt to cast both spells one after another, and the second one interrupts the first, as if it had ! command in a macro.

Steps to reproduce:

Scenario1: Pull NPC, wait for him to begin casting Quick Flame Ward, damage him below 500 health with an instant ability, he will begin casting Healing Wave interrupting the previous cast.
Scenario2: Pull NPC, take him to 500 health in 2seconds, he begins casting Healing Wave. The first Quick Flame Ward is due about 3sec after pull which results he will begin casting it at that point, interrupting the healing wave.

**Comment by Keader** [comment] 2018-08-21 11:58
Fixed.
If you will test in PTR, use: .reload smart_scripts before

**Closed** 2018-08-27 10:43 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev, Tweaking
