### ISSUE TITLE
[Quest] Vorsha the Lasher - Ashenvale

### ISSUE THREAD

**Issue by Aemeron** [WoWManiaUK/Redemption#3781] opened 2019-12-07 16:44 UTC
Issue: Questgiver (Muglash) for 'Vorsha the Lasher' does not move after accepting this quest. Seems to be bugged out in place after he is supposed to start moving to his normal escort location. Also not possible to interact with this NPC at this time.

Since it is an escort quest this quest is now not doable.

**Comment by gamer100** [comment] 2019-12-07 17:16
https://www.wow-mania.com/armory/?quest=6641
https://www.wow-mania.com/armory/?npc=12940

**Comment by jarvik76** [comment] 2019-12-07 22:10
Just tested on PTR and works fine.  
I suspect it may just need a reset of the NPC in the current Redemption.  Please raise a GM ticket and ask for an NPC reset.

**Comment by Kitzunu** [comment] 2019-12-07 22:13
@jarvik76 Pls try to get it to bug, because if it is a reset issue, Rushor can fix it

**Comment by gamer100** [comment] 2019-12-07 22:16
Was made gm ticket reset did not work. Have abandend and delete several time. Gm asked us to make ticket

**Comment by jarvik76** [comment] 2019-12-07 22:18
Can you give details on your race & class please, for more in-depth testing.

**Comment by jarvik76** [comment] 2019-12-07 22:22
Found a possible cause.  If the quest is failed or abandoned half-way through the escort, then the next time Muglash respawns he does not offer the quest.

**Comment by Aemeron** [comment] 2019-12-07 23:15
He did start moving towards the brazier at first, but after having summoned the actual quest target he started bugging out (stood next to the brazier for about 10 minutes before he despawned back to his originial position). The quest was not completed at this point. 

Abandoned the quest at this point to see if he still offered it after he respawned, which he did.

Accepting the quest afterwards made him stand in place for 10 minutes after his text dialogue, after which he despawned again.

GM killed him and it did not fix the issue.

**Comment by Rushor** [comment] 2019-12-08 22:19
okay i added a save addthreat call that 100% always adds threat to the questcreature and the summoned adds. should alwas aggro now. check it out :)

**Comment by Echinaceax** [comment] 2022-01-28 19:55
Bugged again @Rushor 

Player contacted GM, GM tested after resetting the npc but its still bugged he said 
confirmed still bugged by GM on live 

**Repro**
take quest 
npc says one dialog and then stands there

**Comment by Rushor** [comment] 2022-01-29 05:30
I cannot reproduce that either. I would suggest to keep it closed until we find a reproduce way on PTR :)

Because else i cannot help here. I hope we unterstand

**Comment by Echinaceax** [comment] 2022-02-02 19:35
update:

Just completed this now on Live with same char 🤣 
working fine for some strange reason
so all good 
 
![image](https://user-images.githubusercontent.com/39439201/152224028-40e4ade6-9261-48cf-bd5d-565546587e8c.png)

**Comment by jeyrella** [comment] 2022-02-02 19:43
I imagine there is another edge case scenario like I found in the original report with the player-abandoning issue, that also leaves the NPC in limbo - which is then reset after a server restart.
In other words, there is probably still an issue with it, but it will be very very difficult to test all the thousands of variations that could cause this - so we will probably need to rely on player feedback to find the root cause here :(

**Comment by Echinaceax** [comment] 2022-12-15 21:00
@Rushor ive closed the new report and reopened this one
me and Franca worked on simular issues, and i saw Skywing issue was fixed with you and Zinius 
as Jey says its to do with the fail/abandoning quest part (all the other fixes like this was that reason to)

**Comment by Echinaceax** [comment] 2022-12-15 22:41
> I cannot reproduce that either. I would suggest to keep it closed until we find a reproduce way on PTR :)
> Because else i cannot help here. I hope we unterstand

Reproduced @Rushor 

test 1 / char 1 (Echi)
- [x] accept quest and let him walk out of range https://i.gyazo.com/b95a5136ace71a10465ca0ca1604c8d3.mp4
abandon quest and retake quest 
- [x] let him get to the brazier, but dont click it, then run out of range for him to reset 
https://i.gyazo.com/275dabd387a07e55f707019a682ddd5c.mp4
- [x] accept the quest and DC

### notes
`what i did notice is that the quest hasnt said "failed" yet `

test 4 / char 2 (Echimage)
- [x] Log a different char and accept the quest and kill him to fail the quest
https://i.gyazo.com/e232cbe25ec2ff307c314cf45083b227.mp4
- [x] relog 1st char (that didnt fail the quest) to check 
https://i.gyazo.com/8f6be968ba37039cf02acfbc4256e462.mp4
- [x] relog 2nd char that failed the quest 
- [x] abandon failed quest and retake it and go to brazier and click it 
https://i.gyazo.com/dfba32946dff4bc35cd284e986d4653a.mp4
- [x] Start killing https://i.gyazo.com/85491932b61501f875c43e8d69e272cc.mp4 (no Vorsha the Lasher spawns)
- [ ] npc bugged https://i.gyazo.com/d54d81c81b21c7c1e24dc52bd9344677.mp4
- [ ] go afk, npc still stood over 6 mins https://i.gyazo.com/01b2dd21b9cd23ed42c10384e1d49435.mp4
- [x] log out and let the npc reset 

test 7
- [ ] Log 1st toon - BINGO BANGO npc bugged for other players after Vorsha the Lasher fails to spawn after char 2 failed the quest https://i.gyazo.com/cf96641b0dcf2d8dea47e903e6717fd1.mp4


### Fix needed 

- [x] If Muglash dies for what ever reason / quest fails `Need a full reset, not just a respawn`
- [x] Possibly adding a quest failed if player allows Muglash to get out of range of the escort distance

Extra notes
Quest fails on his death only (NPC needs a full reset of quest fail)
![image](https://user-images.githubusercontent.com/39439201/207975630-fdf5758f-f55a-41c2-b87c-9f7ff080f284.png)

**Comment by Rushor** [comment] 2022-12-16 04:07
finally good reproduction thank you!

**Comment by Rushor** [comment] 2022-12-16 04:23
Added that he will despawn if player is far away, added a full reset when he reaches his final path

**Comment by Echinaceax** [comment] 2022-12-16 11:06
> Added that he will despawn if player is far away, added a full reset when he reaches his final path

Confirmed fixed on PTR on 3 chars 
- [ ] Confirmed no bug after failing quest if Muglash dies
- [ ] Muglash already had a despawn if player allowed him to go out of range `it should fail not just despawn`
- [ ] Quest should fail if player allows Muglash to get to far 

can only find reference tho from 4.3 and 5.3 tho
![image](https://user-images.githubusercontent.com/39439201/208085134-d0e2067f-9514-43b9-b2ac-2cf444ac204a.png)
https://i.gyazo.com/04d120b1508bf175e0dd0706562d27ff.mp4

**Comment by Rushor** [comment] 2022-12-16 12:37
- quest will fail after 10 yards range has been extended by player

**Comment by Echinaceax** [comment] 2022-12-16 13:51
> * quest will fail after 20 yards range has been extended by player

![image](https://user-images.githubusercontent.com/39439201/208110000-dfeb6d70-ae80-4103-bd17-3547a07733da.png)


- [ ] confirmed fixed in PTR - 20yards aways from player is good 
- [ ] rechecked orginal "failed" bug is still fixed 

quest fail at 20 yards https://i.gyazo.com/bbe607da2eecf7fa5059c8de3f614c62.mp4
20 yards fine range classes https://i.gyazo.com/c4af08d271f652faf26d5c9cbfda02db.mp4

![image](https://user-images.githubusercontent.com/39439201/208112679-e29881f0-2fd9-4f90-a5d7-c0e3ad302cf2.png)

**Closed** 2022-12-21 10:05 UTC
Labels: Fixed on PTR - Tester Confirmed, Code Change
