### ISSUE TITLE
[Object] Waterlogged Footlocker, Ashenvale / Redridge Mountains (low spawn point count + new issue found)

### ISSUE THREAD

**Issue by Kjalris** [WoWManiaUK/Redemption#5934] opened 2022-10-22 19:48 UTC
**Links:**
https://www.wow-mania.com/armory/?object=179489

**What is Happening:**
You pick lock, chest disappears and never returns.

**What Should happen:**
It should respawn in 5-10 seconds

**Comment by GMZinius** [comment] 2022-10-24 00:00
Thank you for reporting @Kjalris 

From my checks I see 
ID 179489 (1) Ashenvale (in the water)
ID 179491 (7) Desolace
ID 179487 (15) Ashenvale and Redridge Mountains 

ID 179487 (on the shore in Ashenvale)
ID 179487 (in the water in Redridge Mountains)

I do believe they have long spawn times.
I do not believe they can be spawn camped from the video evidence.

Please feel free to find more evidence stating they have a 5-10 seconds respawn timer 

![image](https://user-images.githubusercontent.com/108176634/197423905-b6349eb5-738f-4e24-b872-a98a7ce35049.png)

**Comment by Kjalris** [comment] 2022-10-24 07:48
The only "proof" I have is, that I talked with a GM who said they should respawn faster. But if it's intended to be long respawn timers then it's not a bug.

**Comment by GMZinius** [comment] 2022-10-24 14:21
> The only "proof" I have is, that I talked with a GM who said they should respawn faster and I should open a ticket to look further into it. But if it's intended to be long respawn timers then it's not a bug and nothing needs to be done.
> 
> I do see in the video there are a lot more of the boxes compared to the 5 you can find on your server, maybe this is why it feels long? Because the boxes don't reappear in new places?

Yes the spawn timer part to Ashenvale seems right, I agree, spawn points are lower than they should be there should be more spawn points add to refelect research done

I will talk with the Dev's about this @Kjalris  Thank you again for reporting

**Comment by svijetlo** [comment] 2022-10-25 09:33
this exactly same things was reported in past and was fixed , but cant remember when/how long ago it was

**Comment by GMZinius** [comment] 2022-10-25 12:11
> this exactly same things was reported in past and was fixed , but cant remember when/how long ago it was

Thanks @svijetlo 👍

**Comment by Rushor** [comment] 2022-11-01 18:11
respawntimer for it is around 10 secs now

**Comment by Kjalris** [comment] 2022-11-01 18:20
@Rushor By looking around, people say its around 8 minutes respawn timer compared to 10 seconds.
https://www.wowhead.com/object=179487/waterlogged-footlocker#comments:id=247390 
http://forum.warmane.com/showthread.php?t=325317
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3290

I think it should be change to around 8 minutes. Would also not affect gameplay too much.

**Comment by GMZinius** [comment] 2022-11-01 18:26
> @Rushor By looking around, people say its around 8 minutes respawn timer compared to 10 seconds. https://www.wowhead.com/object=179487/waterlogged-footlocker#comments:id=247390 http://forum.warmane.com/showthread.php?t=325317 [FeenixServerProject/Archangel_2.4.3_Bugtracker#3290](https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3290)
> 
> I think it should be change to around 8 minutes. Would also not affect gameplay too much.

Ive noticed Rushor to change to 8 mins @Kjalris

**Comment by Rushor** [comment] 2022-11-01 18:30
okay done

**Comment by GMZinius** [comment] 2022-11-01 19:38
Confirmed fixed in PTR 

ID 179491 = 3mins (due to having only 7 spawns)
ID 179487 = 8mins (15 spawns)

![image](https://user-images.githubusercontent.com/108176634/199323218-969ded1b-c71d-42a7-81ad-30a3d176f170.png)
![image](https://user-images.githubusercontent.com/108176634/199323299-33589ac7-ea97-4796-b56b-15119fb6feda.png)

**Closed** 2022-11-03 08:33 UTC
Labels: Fixed on PTR - Tester Confirmed
