### ISSUE TITLE
[NPC] Ebon Blade Commander - duplicated

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5735] opened 2022-03-04 10:27 UTC
[Ebon Blade Commander](https://www.wow-mania.com/armory/?npc=37967) are, most of them, duplicated at the Frozen Halls tunnel/entrance, having alliance and horde spawned at same time.

I was on a allaince char

Some examples 
![image](https://user-images.githubusercontent.com/31921098/156746175-1ccd0def-5ec9-428f-b800-5d327c1d2172.png)
![image](https://user-images.githubusercontent.com/31921098/156746213-4b018ab7-1396-4423-9d8c-cc53ae709fdb.png)
![image](https://user-images.githubusercontent.com/31921098/156746297-a4291e63-142c-4971-9055-6ec2d76ece41.png)
![image](https://user-images.githubusercontent.com/31921098/156746370-883f69d2-1cc8-453b-8d2e-be5283811c40.png)

**Comment by Rushor** [comment] 2022-03-04 11:13
yeah that is due to wrong sniffed data back in the days

**Comment by mfranca0009** [comment] 2022-03-05 23:37
This is also occurring with the Argent Commanders as well, there are even Argent Hippogryphs carrying two Argent Commanders as well.

### For Reference
**Argent Commander:**https://www.wowhead.com/npc=37965/argent-commander
**Argent Hippogryphs:**https://www.wowhead.com/npc=37968/argent-hippogryph

**Comment by Echinaceax** [comment] 2022-03-05 23:39
Confirmed 

![image](https://user-images.githubusercontent.com/39439201/156903263-f5720a23-e86f-4811-9d69-a45d5759430d.png)

**Comment by mfranca0009** [comment] 2022-03-07 23:29
Duplicates have been dealt with and fixed 👍 

I've also corrected the position for all `Argent Hippogryphs` that are spawned on the side of the path to `The Frozen Halls` because their feet were clipping through the building floor.

**Comment by Echinaceax** [comment] 2022-03-07 23:31
Fixed in PTR
![image](https://user-images.githubusercontent.com/39439201/157135799-e4561f0a-eff8-424b-b4e5-20efd248f1b0.png)

https://i.gyazo.com/841f440d2b99a45acdc06f92e45ba922.mp4

**Closed** 2022-03-09 15:26 UTC
Labels: Fixed on PTR - Tester Confirmed
