### ISSUE TITLE
[NPC] Thrall - The Escape from Durnholde dungeon

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1549] opened 2017-09-01 14:00 UTC
Thrall inside the dungeon Escape from Durnholde (http://www.wowhead.com/npc=17876 )

Issue: When attempting to exit the building, he walks into the wall and sometimes gets stuck there.
It doesn't always happen, often he just keeps circling inside the wall and then exits it, but here's a screen showing where he just sits inside of it and he simply won't move: http://imgur.com/VGyXI1M
You cant interact with him and can't continue the event this way.

**Comment by fvicaria** [comment] 2017-09-01 14:40
Just keep following the path. He will continue. This is due to problems with the map and he falls through the floor but if you keep killing the npcs he will continue.

**Comment by Dranah** [comment] 2017-09-01 14:50
there were no npcs left , nor spawning, and I walked all the way to tarren mill and back and he never moved lol

**Comment by fvicaria** [comment] 2017-09-01 15:01
Test Team: Can somebody give it a go, please?

**Comment by captainloozer** [comment] 2017-09-01 17:31
I will test it.

**Comment by captainloozer** [comment] 2017-09-01 17:45
I tested the encounter, while thrall did seem a bit confused and had a hard time getting through the door, he did figure it out and I was able to escort him all the way through the gate.

While I can confirm that his pathing is a bit buggy, I can also confirm it is doable.  I'm not sure how many times I'd have to do this to get him completely stuck, but I can imagine that if it did happen, you could run out of the instance, run back in and reset him.  

I recorded my encounter here so everyone can see it.  But since it is currently doable, I will close this at the end of the day once Janitor has had a chance to review the video and decide what he wants to do with it.

ttps://www.youtube.com/watch?v=laG8V_r_2qM

**Comment by fvicaria** [comment] 2017-09-02 10:57
This is a map issue and not the quest itself. 
I will try to slightly change his path for next release.

**Closed by fvicaria** 2017-09-02 10:57 UTC
