### ISSUE TITLE
Arena Grandmaster / NPC Short John Mithril (bug)

### ISSUE THREAD

**Issue by Gainarrow** [WoWManiaUK/Redemption#2955] opened 2019-01-05 08:26 UTC
NPC Short John Mithril quest [Arena Grandmaster] is not doable, because there is no chest whatsoever in arena (spawn times checked 3, 6, 9, AM/PM +/-1h also random ones)...

**Comment by wow-mania** [comment] 2019-01-05 15:21
Found the issue.
It was working on every 2 hours and not 3.
Will be fixed for the next restart.

**Comment by Gainarrow** [comment] 2019-01-05 18:14
THANKS

**Comment by GMZinius** [comment] 2024-05-30 11:36
Little note due to player feedback and today's observation from player ticket is that something bugs him 
- He sometimes faces the wrong way on returning to home position after dropping his chest, which causing him to bug for the next timer 

No reproduce steps of how this happens yet unfortunately

In the meantime, a quick npc reset does the trick for now

**Comment by Lumber-Jack-2** [comment] 2024-05-30 17:56
is set to active now

**Comment by GMZinius** [comment] 2024-05-30 18:18
> is set to active now

Thank you Rushor, will update you if this didn't fix it 👍

**Closed** 2024-06-14 10:57 UTC
Labels: Confirmed, Fixed on PTR - Ready to Test, Core Change
