### ISSUE TITLE
[Quest] Fate of the Titans - missing dead bodies and other minor things

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5827] opened 2022-05-20 11:06 UTC
**Links:**
Video of the quest from 2015, only one I have found https://www.youtube.com/watch?v=uxFLWbMnM6s
→ but what databanks says on Mania is in alignement with this video.
Quest: https://wow-mania.com/armory/?quest=12986
Creteus' Mobile Databank (typo in the armory btw) https://wow-mania.com/armory/?item=42679
Mobile Databank: https://wow-mania.com/armory/?npc=30313

**What is Happening:**
1: There are no dead bodies in Temple of Invention.
→ Dead bodies: Mechagnome Attendant https://wow-mania.com/armory/?npc=30170
2: There are no dead bodies in temple of winter.
→ Dead bodies: Servant of Hodir https://wow-mania.com/armory/?npc=30881
3: I think Mobile Databank is missing that little light beam/tentacle analysis when analysing objects.
4: In Temple of Invention if you get into combat, the Databank stops working and it needs to be resummoned.
5: Timestamp 5:04 → Player uses Creteus' Mobile Databank when the npc is already summoned and it dismisses the databank and then he clicks it once more to summon the new one . On Mania it summons the new one right away after one click.

**What Should happen:**
1: There should be the bodies.
2: Being attacked should not interfere with the progress in Temple of Invention.
3: Databank should have the light tentacle when doing analysis
4: Using summon item should dismiss the databank if it is spawned already, not summon a new one right away.

**Comment by Echinaceax** [comment] 2022-05-20 17:26
bugs confirmed 

- [ ] Dead bodies: Mechagnome Attendant https://wow-mania.com/armory/?npc=30170
- [ ] Dead bodies: Servant of Hodir https://wow-mania.com/armory/?npc=30881
- [ ] Databank is missing that little light beam/tentacle analysis when analysing objects.
- [ ] Using summon item should dismiss the databank if it is spawned already, not summon a new one right away.

**Comment by Rushor** [comment] 2022-07-27 16:20
Dead bodies: Mechagnome Attendant https://wow-mania.com/armory/?npc=30170 
added 
Dead bodies: Servant of Hodir https://wow-mania.com/armory/?npc=30881  
added 
Databank is missing that little light beam/tentacle analysis when analysing objects. 
- cannot be done yet, i cannot find the correct spell
Using summon item should dismiss the databank if it is spawned already, not summon a new one right away. 
- done new npc will despawn if there already summoned one of it
In Temple of Invention if you get into combat, the Databank stops working and it needs to be resummoned.
- chnged so the npc starts the script when out of combat and will continue it even when in combat

**Comment by Echinaceax** [comment] 2022-07-27 18:05
fixed in PTR so far

- [ ] Servant of Hodir

![image](https://user-images.githubusercontent.com/39439201/181304938-fdce9a6c-af7c-4461-8a1d-476fd921c175.png)

- [ ] Mechagnome Attendant

![image](https://user-images.githubusercontent.com/39439201/181309695-11b2d6b8-fdc5-4618-b995-6f05c7acb64c.png)

- [ ] npc starts the script when out of combat and will continue it even when in combat

![image](https://user-images.githubusercontent.com/39439201/181310783-2786af84-225f-4b03-8e1a-cbf232a9389e.png)


- [ ] new npc will despawn if there already summoned one of it

https://i.gyazo.com/bb5195f66353cdf1f686e9dbfa31ea25.mp4


- [ ] 2 pathing issues for the data bank still to fix

**Comment by Rushor** [comment] 2022-08-02 09:56
pathing should be fixed now

**Comment by Echinaceax** [comment] 2022-08-02 10:38
Fixed in PTR 

https://i.gyazo.com/17497f36eeca061537a17495e11582db.mp4
https://i.gyazo.com/d512cb596364279d1efe3b33299d43cd.mp4

**Comment by GMZinius** [comment] 2023-04-26 20:11
@Rushor 
The quest Fate of the Titans seems to be bugged. The databank doesn't finish it's investigation of the Temple of Order.

I myself confirmed this issue with another player last week and the data bank disapears so doesnt give quest credit

**Comment by Echinaceax** [comment] 2023-04-27 10:06
Just tested this on PTR and all still woeking fine 

i did this one 1 

![image](https://user-images.githubusercontent.com/39439201/234830134-19212864-f01d-4f15-b580-1d9f611aa69a.png)

then 
![image](https://user-images.githubusercontent.com/39439201/234830356-a22f4cff-7c1e-4404-a7a3-601f85769058.png)

then 
![image](https://user-images.githubusercontent.com/39439201/234830498-0eea06bf-f7db-4d54-acf8-3f4f3af229c8.png)

and the last one (and this one bugged only on LIVE) 

https://i.gyazo.com/244ba5f1754ec3b79bebc5109712bfa1.mp4

**Comment by Echinaceax** [comment] 2023-04-27 15:22
> maybe it was not applied fully?

Can we re-apply it ?

**Comment by Rushor** [comment] 2023-05-03 20:51
reapplied on ptr, can you check if it still woks there, then the whole sql weill go to live again

**Comment by Echinaceax** [comment] 2023-05-03 21:15
> reapplied on ptr, can you check if it still woks there, then the whole sql weill go to live again

good to go 😄

**Closed** 2023-05-05 07:34 UTC
Labels: Fixed on PTR - Tester Confirmed, AIScript Change
