### ISSUE TITLE
[Quest] Now This is Ram Racing... Almost. 

### ISSUE THREAD

**Issue by redhawk816** [WoWManiaUK/Redemption#1646] opened 2017-09-19 23:23 UTC
http://www.wowhead.com/quest=11318/now-this-is-ram-racing-almost
Objectives are not completing.   I maintained each of the speeds for over the 8 seconds that are needed.  None of the objectives completed so neither did the quest.

**Comment by GmSaintz** [comment] 2017-09-19 23:33
I can confirm the issue with this quest.

**Comment by goldstinger** [comment] 2017-09-19 23:54
Also confirming. After 8 seconds with the same speed buff, the quest objective for any of the objectives do not complete.

**Comment by redhawk816** [comment] 2017-09-20 00:29
This affects two other quests that I cant think of, both daily quests: http://www.wowhead.com/quest=11412/there-and-back-again and The Bark quests such as http://www.wowhead.com/quest=11408/bark-for-tchalis-voodoo-brewery

**Comment by Karlusdark** [comment] 2017-09-20 01:27
Also confirming this issue, it's been like this since last year

**Comment by fvicaria** [comment] 2017-09-20 07:00
Are you getting the credit for the various stages?

**Comment by squalllh1989** [comment] 2017-09-20 09:44
none of the 3 stages work, after maintain 1 min for each state, quest didn't complete for any state.

**Comment by goldstinger** [comment] 2017-09-20 11:58
To address @fvicaria in particular, no. The credit for the various stages are not given after 8 seconds, or after any amount of time in those stages.

**Comment by Hulkster-WowMania** [comment] 2017-09-20 13:45
Confirmed fixed in dev.  All three speeds give credit.  

https://youtu.be/2W98dO1sz1k

**Comment by Ukhozii** [comment] 2017-09-20 21:01
The problem remains, at least on Horde's side. I've done all 3 different stages well over 8 sec and I never get any of the speeds completed. A friend of mine has also tried it and it just doesn't work for us.

**Comment by Karlusdark** [comment] 2017-09-20 22:33
Issue remains on Alliance's side, done all 3 stages over 8 sec and nothing happened.

**Comment by squalllh1989** [comment] 2017-09-21 04:39
Guy, it's "Fixed on Dev", the fix isn't pushed to redemtion yet, wait for the next update

**Closed** 2017-09-21 10:08 UTC
Labels: Fixed Confirmed in Dev, Fixed in Dev
