### ISSUE TITLE
Quest: If Valgarde falls... [Not necessarily a bug but observation that could be better]

### ISSUE THREAD

**Issue by Hodasboy** [WoWManiaUK/Redemption#6157] opened 2024-01-04 16:15 UTC
**Links:**
https://www.wow-mania.com/armory/?quest=11243

**What is Happening:**
Dragonflayer Invaders and Worgs are not continuously spawning in after dying to keep "invade" as on-going event.

**What Should happen:**
Dragonflayer invaders and Worgs are not spawning and attacking NPCs at the gate. (If not scripted properly work as an invading event like it is in retail, perhaps add faster spawn rate for mobs that exists (About 8-9 of them). This will become issue if server gets more populated and more people are doing this same quest at the same time.

2 pics from area https://imgur.com/a/o9ooYAx

--------------- 
This was reported 2017 with falsely closed. In Wow mania armory link it gives you NPC names that count towards this quest how ever only Dragonflayer Invader and Worgs are spawning in this area. Rest are all over northrend so obviously as coming to howling fjord as level 68 with no ability to fly around and absolutely no intent to fly to storm peaks to kill level 78 mob for this quest is absurd.

**Comment by Maine1** [comment] 2024-01-04 16:26
@Hodasboy This is actually working completely as intended and we have even got more spawns than wowhead.
https://www.wowhead.com/wotlk/npc=24051/dragonflayer-invader

They only have 6 on retail and we have 8 Spawned. We have 5 worgs.

**Comment by Hodasboy** [comment] 2024-01-04 16:42
Respawn rates are not there. I had to wait 4 minutes for them to respawn because I missed the big wave that gets killed by the guards. Blizzard had probably 6 spawning it but like I mentioned, it was continuously spawning them in. check this one https://www.youtube.com/watch?v=IovRV9sV6yU

It's not a bug but imagine 5 people coming in here and doing the quest if they are not in group they will have to wait for them to respawn and this quest is quite important because it's the starter quest for this zone.

**Comment by Echinaceax** [comment] 2024-01-04 22:40
> @Hodasboy This is actually working completely as intended and we have even got more spawns than wowhead. https://www.wowhead.com/wotlk/npc=24051/dragonflayer-invader

You posted a 10 year old video link not a 2009 one, so we cant go from that info.
A lot of changes were done at Cata and upwards, our fixes are based on wotlk 2009 

We cannot fix or add things to make the game "easier" this is'nt a bug therefor it will stay as-is

**Comment by Maine1** [comment] 2024-01-04 22:47
As mentioned above this is full working as intended with correct respawn timers for wotLK 2009

**Comment by Hodasboy** [comment] 2024-01-05 06:16
Now looking at comment section for RETAIL (Not Classic which also has the quest exactly same as old retail version did) version of wowhead and comment from 2009: https://www.wowhead.com/quest=11243/if-valgarde-falls

"These guys will spawn without limit so it can be a very efficient way to gain xp without the hassle of running around as you do to complete quests. I dual logged with my protection warrior and had my paladin healing me. I spammed thunderclap and demoralizing shout and each kill was getting me about 1100-1300 xp per kill rested as a level 72. I got 5 bars filled in twenty minutes. The guards will help you kill but you will noticeably get reduced xp if you can tag it before the guard finishes it off."

Your NPCs doesn't spawn with out limit because they are not continuously attacking guards. How much proof do you need that those standing NPCs at the area which you have in wow mania is not blizzard like back to 2009. They should be attacking continuously spawning instantly when they die. like in the video that I posted.

**Comment by Maine1** [comment] 2024-01-05 16:05
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/d2669827-29dc-45f0-bf94-655024c97c96)
this comment is in grey which means it hasnt been auhorized as legit. They turn them green after testing and make sure the comments are legit. This is in grey so not authorized by devs on blizzard

**Comment by Hodasboy** [comment] 2024-01-05 16:09
You guys surely high. No worries not gona bother. Suprisingly blizzard changes their scripts on old quests for sure. BS server anyway. 8 years in and Azjol Nerub isn't script path to Hardonox when mobs are path running down to it. No wonder you cant figure simple path finding issues fixed.

**Comment by Echinaceax** [comment] 2024-01-05 16:13
> You guys surely high. No worries not gona bother. Suprisingly blizzard changes their scripts on old quests for sure. BS server anyway. 

Listen @Hodasboy We have to fully verify reports that come in, that doesnt mean we are high, it means we are doing our best to get the 100% info for @Rushor so it is not wrong info for this patch.

So please respect that we know what we are doing 
You don't see the Dev chat, we do so please be patient, if its bugged we will reopen the report and fix it, if Rushor says it is not valid then we dont fix it 

> 8 years in and Azjol Nerub isn't script path to Hardonox when mobs are path running down to it. No wonder you cant figure simple path finding issues fixed.


Please can you link us a Azjol Nerub / Hardonox old report that has not be fixed. thx

**Comment by Lumber-Jack-2** [comment] 2024-01-10 21:12
Will add following:
- few more spawns
- better respawntime
- making sure friendly npcs can kill the invaders still

**Comment by Echinaceax** [comment] 2024-01-23 14:15
> * few more spawns
> * better respawntime
> * making sure friendly npcs can kill the invaders still

All 3 fixed on PTR 
https://i.gyazo.com/62af04987abfffd35cbeb2e27124778e.mp4

**Closed as completed** 2024-01-25 08:38 UTC
Labels: Fixed on PTR - Tester Confirmed, DB Change
