### ISSUE TITLE
[Icecrown Citadel - The Lich King (HC)] The Frostmourne room

### ISSUE THREAD

**Issue by keidian** [WoWManiaUK/Redemption#1304] opened 2017-06-19 12:20 UTC
When a druid shapeshifts, a mage uses invisiblity they fall through the floor and die because the ground is despawning for them. This also happens when you turn GM on and Off. 

It might be worth mentioning that the Frostmourne room is a gameojbect. There is a similar issue on the TC issues tracker.

**Comment by Forrestxz** [comment] 2017-06-19 14:17
Confirmed, SHOULD also be bugging out with blink/charge/Intervene due to pathing errors.

**Comment by fvicaria** [comment] 2017-06-20 08:51
This is the same issue as the phasing of some areas. All will be fixed in one goal.

**Closed by fvicaria** 2017-06-20 08:51 UTC
Labels: Confirmed
