### ISSUE TITLE
[NPC] Blacksmith at Warsong Hold does not stop when his shop is opened

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4253] opened 2020-03-18 00:14 UTC
**What is Happening:**
The blacksmith at Warsong Hold does not stop walking when you open his shop.

**What Should happen:**
I think he should stay in his current position when you open the shop.

![image](https://user-images.githubusercontent.com/6956790/76912917-c4e60680-68b5-11ea-8038-306c976180c1.png)

**Comment by Sharuzan** [comment] 2020-03-18 21:30
Confirmed: He does indeed walk, even if you speak to him. 
There seems to be no mention of Orkuruk walking while you shop in the retail version.

**Comment by jeyrella** [comment] 2020-03-19 14:29
Well.... yes.....  it technically is an improvement, but it does not break or even really interfere with the game in much way at all.  Marking it as low priority

**Comment by yani** [comment] 2020-03-20 12:16
It's almost impossible to browse his shop this way. It opens only for a few seconds.

**Comment by Rushor** [comment] 2020-03-22 12:55
creature will stop path for several seconds on gossip hello

**Comment by bLeyaa** [comment] 2020-03-22 20:50
Still moves around when interacted with. @Rushor

**Comment by Rushor** [comment] 2020-03-22 21:11
okay we must rescript that npc

**Closed** 2020-03-24 10:35 UTC
Labels: Confirmed - Improvement, Fix - In Dev/PTR, Priority - Low
