### ISSUE TITLE
[Spell] Warrior Fury Bloodsurge effect not working (Slam Proc)

### ISSUE THREAD

**Issue by UnTizioSfaticato** [WoWManiaUK/Redemption#3763] opened 2019-12-02 23:03 UTC
Bloodsurge: https://www.wow-mania.com/armory/?spell=46915
Slam: https://www.wow-mania.com/armory/?spell=47475

Hello! On my fury warrior, while I was facing a Boss of the Icc 25Hc raid, I noticed that the talent Bloodsurge, when it was activated, the spell Slam was not cast instant, as the talent says, but the cast remained unchanged (normal cast).
In the zip file you can find a video where I show you the bug.

[World of Warcraft 2019-12-02 23-58-37_Trim.zip](https://github.com/WoWManiaUK/Redemption/files/3913675/World.of.Warcraft.2019-12-02.23-58-37_Trim.zip)

**Comment by Kitzunu** [comment] 2019-12-02 23:06
duplicate of https://github.com/WoWManiaUK/Redemption/issues/3752

**Comment by Kitzunu** [comment] 2019-12-02 23:06
Will be fixed with next update :)

**Closed by Kitzunu** 2019-12-02 23:06 UTC
