### ISSUE TITLE
[NPC] Neill Ramstein/Ram Master Ray (Brewfest)

### ISSUE THREAD

**Issue by corrinr** [WoWManiaUK/Redemption#3595] opened 2019-09-20 09:09 UTC
**Links:**
http://www.wow-mania.com/armory/?npc=23558 || https://www.wowhead.com/npc=23558/neill-ramstein
http://www.wow-mania.com/armory/?npc=24497 || https://www.wowhead.com/npc=24497/ram-master-ray

**What is Happening:**
![WoWScrnShot_092019_011529](https://user-images.githubusercontent.com/48542141/65314172-5ff66180-db5b-11e9-80fe-da5e2647cdbe.jpg)
![WoWScrnShot_092019_011724](https://user-images.githubusercontent.com/48542141/65314173-608ef800-db5b-11e9-9135-355a61601b04.jpg)
This bug happened to 2 other guildies right after I experienced it. On taking Neill's gossip option ("Is there anything else I can do to help" type thing) I was given an invisible ram, which caused me to slow walk at the speed of the ram. I was unable to stop walking even after relogging and somehow got it to stop by a fluke. Other people who experienced the bug confirmed it happened after talking to this NPC, with no quest from him in their logs, and lasted longer than the 4 minutes the ram buff is supposed to last. 

**What Should happen:**
The NPC may be trying to give https://www.wowhead.com/quest=11122/there-and-back-again? I had done that quest prior to talking to him, so it's possible the timer is off. Regardless, the ram should be visible and controllable by using the provided reins, and should despawn after 4 minutes or right clicking the buff.

**Edit:**
Since making this issue several more people have asked about the bug in world chat, several of them Horde. It seems to trigger not just from the gossip option, but from any quest or dialogue given by the Ram Racing Master NPC on either side.

**Comment by corrinr** [comment] 2019-09-20 09:11
https://github.com/WoWManiaUK/Redemption/issues/1673 possibly related, the "more work" option OP is talking about is the one that gave me an invisible ram.

**Comment by Nyde** [comment] 2019-09-20 11:00
Happening on Horde side too. Relogging, duelling, porting to the mall or talents won't remove the effect. It somehow stopped, don't know why (maybe the invisible buff has a timer, or a GM intervened).

**Comment by WhitephoenixTheBunny** [comment] 2019-09-20 17:07
This only happen if you start the quest mounted. Starting it unmounted don't "bug you out"

**Comment by Rushor** [comment] 2019-09-20 17:33
Okay then we should maybe first unmount Player and then add the Mount spell

**Comment by WhitephoenixTheBunny** [comment] 2019-09-20 19:27
Maybe :P....

**Comment by WhitephoenixTheBunny** [comment] 2019-09-21 12:09
@Rushor 
Both faction, on the two quests and the "aditional work" also

**Comment by Rushor** [comment] 2019-09-22 23:47
now you get unmounted a soon as you talk to the creature

![I](https://i.imgur.com/lZGq18I.jpg)

**Comment by Rushor** [comment] 2019-09-22 23:49
so whenever you talk to the creature it will dismount you. hope this will not make any problems.

but the display issue is fixed with that

**Comment by WhitephoenixTheBunny** [comment] 2019-09-23 19:09
Alliance

On the first quest - [Now This is Ram Racing... Almost.](http://www.wow-mania.com/armory/?quest=11318) -  it works, 

On the second quest - [There and Back Again](http://www.wow-mania.com/armory/?quest=11122) - it does not

On the "Do you have additional work?" - it works.


Will edit - going test horde

**Comment by Rushor** [comment] 2019-09-24 09:00
okay that is strange

**Comment by Rushor** [comment] 2019-09-24 09:06
cannot reproduce, once i open the gossip of the creatures i get dismounted

![I](https://i.imgur.com/UIDe9zP.jpg)
![I](https://i.imgur.com/k6ID8C3.jpg)

can you tell me the steps you did for the issue?

**Comment by WhitephoenixTheBunny** [comment] 2019-09-24 11:37
@Rushor I mounted before take any quest / more work

**Comment by Rushor** [comment] 2019-09-24 19:45
yes i did that aswell, and i got unmounted as soon as i interact with creature

**Closed** 2019-09-26 09:37 UTC
Labels: Confirmed, Fixed in Dev
