### ISSUE TITLE
[Item]  Clamlette Magnifique

### ISSUE THREAD

**Issue by Velarix** [WoWManiaUK/Redemption#1526] opened 2017-08-25 18:55 UTC
So the food item Clamlette Magnifique has said in its description to give the user 2934 mana over 30 seconds but the problem is when i start eating it that it doesnt give me any mana at all. The drinking buff appears on the top right corner of my screen but i cant regen any mana when eating this food. When eating this it also gives a 1 minute cooldown on my Moonberry Juice?

**Comment by captainloozer** [comment] 2017-08-25 20:13
Hi Velarix, and thank you for your report!

Please  include a link to any items, quests, npcs, or spells that you are referring to using approved resources, such as http://wow-mania.com/armory.  This helps the developers and testers as it gives us quick access to vital information that we need to fix your problem.

**Comment by captainloozer** [comment] 2017-08-25 20:18
I was able to reproduce this issue in dev.  Below is a video showing the behavior of Clamlette Magnifique not restoring mana as it should, as well as putting a cooldown on Moonberry Juice

http://www.wow-mania.com/armory/?item=33004 - Clamlette Magnifique
http://www.wow-mania.com/armory/?item=1645  - Moonberry Juice

https://youtu.be/fFZ0MVx76I4

**Comment by captainloozer** [comment] 2017-08-26 16:25
Confirmed fixed in dev.   Clamlette is giving mana as intended now.

**Closed** 2017-08-29 10:34 UTC
Labels: Confirmed, Fixed Confirmed in Dev, Fixed in Dev
