### ISSUE TITLE
[Quest] Gordunni Cobalt Quest - 2987 - Feralas

### ISSUE THREAD

**Issue by allanjchiang** [WoWManiaUK/Redemption#4456] opened 2020-04-19 08:15 UTC
**What Is Happening:** Can't find any blue spots on the ground for the quest 'Gordunni Cobalt'

**What Should Happen:** There should be blue spots on the ground where I can dig 'Gordunni Cobalt'

**Comment by Rushor** [comment] 2020-04-19 09:12
Maybe respawn issue?

**Comment by jeyrella** [comment] 2020-04-19 10:26
![image](https://user-images.githubusercontent.com/46089380/79685408-964ea900-8230-11ea-9928-0ef43613fa53.png)

**Comment by jeyrella** [comment] 2020-04-19 10:26
https://www.wow-mania.com/armory/?quest=2987

**Comment by jeyrella** [comment] 2020-04-19 10:30
Well they definitely appear.  Testing respawn now
![image](https://user-images.githubusercontent.com/46089380/79685491-268cee00-8231-11ea-8ffc-3ad8deddb759.png)

**Comment by jeyrella** [comment] 2020-04-19 10:48
They do respawn, and timer is 15 minutes.
Due to the age, I cannot find any historic reference to how long this should be, but I don't think this is unreasonable given the location and context in which this quest occurs.

However, there is a side-issue that both the mining and collecting object is instant - both should have a 1 second cast.
Current:  https://youtu.be/DCoCHWsgmMU
Retail:  
Mining (yes this is modern Classic, but it is relevant):  https://youtu.be/csOsPiGanCs?t=367
Collecting (this one is era-correct):  https://youtu.be/ljMb__6xPnw?t=69
Possibly this spell  https://www.wow-mania.com/armory/?spell=11756 ?

**Comment by wow-mania** [comment] 2020-04-19 11:00
Can you check again please.

**Comment by Rushor** [comment] 2020-04-19 12:30
nah casttime is good already )you must .cheat casstime off) https://i.imgur.com/wHgoYiy.jpg https://i.imgur.com/bW6Et0L.jpg but that rspawntime seems really high for me. i gonna check some source

**Comment by Rushor** [comment] 2020-04-19 12:33
checked the mangos db, yes that 15 min is correct

**Comment by jeyrella** [comment] 2020-04-19 12:50
Arrrrrgh.  Sorry yeah i forgot I had my login script on.  Will learn for next time....

**Comment by GMZinius** [comment] 2023-06-29 14:46
> Well they definitely appear. Testing respawn now ![image](https://user-images.githubusercontent.com/46089380/79685491-268cee00-8231-11ea-8ffc-3ad8deddb759.png)

From this screenshot, I dont see the actual dirt piles as seen on the video 
Did you add the quest to yourself and try to loot the quest item?

Naxx ticket,  states that the blue dots are there yes, but no loot 

checked this myself on RED  and the issue is there is 0 Gordunni Dirt Mound object=144064
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/13038c31-b399-4ca4-8c41-356199edca75)
![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/d0cba612-be6d-4205-96ff-450e5ff216de)

**Comment by GMZinius** [comment] 2023-06-29 14:49
> Can you check again please.

I have checked this just a few mins ago due to Naxx ticket and there are 0 spawmns of the actual dirt needed for the quest https://www.wowhead.com/classic/object=144064/gordunni-dirt-mound

**Comment by Rushor** [comment] 2023-07-16 13:50
https://gyazo.com/ab29ef7bff3d442b482846cc53ce2ae6

**Comment by GMZinius** [comment] 2023-07-16 14:24
Thank @Rushor 
Confirmed fixed on PTR
https://i.gyazo.com/6b7fe987d25d36a654e291fdbb38f3fb.mp4

**Closed** 2023-07-21 10:45 UTC
Labels: Fixed on PTR - Tester Confirmed, AIScript Change
