### ISSUE TITLE
[NPC] illidan-stormrage ID: 31395: Too Many Spawns Present - quest ID:13400

### ISSUE THREAD

**Issue by Franciss983** [WoWManiaUK/Redemption#5839] opened 2022-05-26 17:31 UTC
**Links:**
Quest: https://www.wowhead.com/quest=13400/the-hunter-and-the-prince#comments
NPC: https://www.wowhead.com/npc=31395/illidan-stormrage

**What is Happening:**
After abandon the quest, this NPC is remaining (phased) and when the player pick quest again, there is Illidan Stormrage in multiple copies.
Each abandon adds new copy of npc=31395.
video.: https://gyazo.com/5fd9cb826e1de91c48f23a818aedd8c4
https://gyazo.com/4c001ee3f471411354985006c7764eaa

**What Should happen:**
After abandon of the quest, npc should despawn.

**Comment by Echinaceax** [comment] 2022-06-19 23:13
I believe this issue is solve now with this fix https://github.com/WoWManiaUK/Redemption/issues/5837

all seems fine now 


https://i.gyazo.com/7af525e46b4a101ff2b99037cdd90e88.mp4

**Comment by mfranca0009** [comment] 2022-06-20 01:29
It's not fixed, no one fixed it yet. Still a problem.
https://i.gyazo.com/16f2f4d3f023d817eb5967f755145831.mp4

Re-opened.

**Comment by Echinaceax** [comment] 2022-06-20 09:10
only when you dont manually exit the vehicle https://i.gyazo.com/7af525e46b4a101ff2b99037cdd90e88.mp4

**Comment by mfranca0009** [comment] 2022-06-23 04:28
Fix in progress, it's getting a rework. Not functioning as it should be based on a WoTLK video.

Video: https://www.youtube.com/watch?v=FjrLouOl_aI

**Comment by mfranca0009** [comment] 2022-06-24 04:57
Fixed and replicates the WotLK video above, the only issue left would be `Prince Arthas Menethil` not auto-attacking and looking like he's in combat; this may be a deeper core issue with player-controlled vehicles and will not touch at this time.

Test Video: https://youtu.be/zTT0QMBIoCI

### Hunter and The Prince Changes
- [x] Eliminated the problem with multiple `Illidan Stormrage` spawns occurring when a player abandons/accepts the quest.
- [x] Eliminated the problem of multiple `bloodstained stones` being spawned in by the same player when the quest is abandoned/accepted.  
- [x] Added a missing animation for `Illidan Stormrage`.
- [x] Implemented the intro events for `Illidan Stormrage` before the combat encounter with `Prince Arthas Menethil`.
- [x] Implemented quest fail conditions such as player manually leaving vehicle and player running away in the vehicle (65 yards).
- [x] Corrected an issue where `Prince Arthas Menethil`'s damage/knockback abilities could be usable on anyone and not just `Illidan Stormrage`.
- [x] Moved the spawn positioning of the `bloodstained stone` and `Illidan Stormrage`, it now uses the correct WotLK spawn positions as seen from the 2008 video referenced earlier.
- [x] Re-positioned `Matthias Lehner` due to the re-positioning of `Illidan Stormrage` and the `bloodstained stone`.
- [x] Put two `Boneguard Scouts` in their proper phase, they were conflicting with the quest area.

**Comment by Echinaceax** [comment] 2022-06-24 14:38
Confirmed fixed in PTR all the above 



https://i.gyazo.com/762b8ab79304baa4bef5b8b6914672a5.mp4

**Closed** 2022-07-07 07:09 UTC
Labels: Fixed on PTR - Tester Confirmed
