### ISSUE TITLE
[Item] Solace of the Defeated not proccing Twice with Beacon of Light for Flash of Light or Holy Shock.

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#6194] opened 2024-02-27 20:37 UTC
**What is Happening:**
Solace of the defeated, the trinket from ToC 25HC is not proccing correctly for Flash of Light or Holy Shock while using Beacon of Light. It works fine for Holy Light. 

**What Should happen:**
It should have the passive proc twice while Beacon of Light is applied to a tank and you heal another target. This is how it's always supposed to work but it isn't proccing correctly for heals other than Holy Light. It should be one proc for the original cast and a second proc for the Beacon of Light cast. Supposed to work similar to Meteorite Crystal.

**Comment by Echinaceax** [comment] 2024-02-27 22:15
hi @Bartok14 thanks for reporting
can you provide links for this report

**Comment by Maine1** [comment] 2024-02-27 22:18
From what I have found it shows that this only procs each time you cast a spell. Now when you cast holy light or flash of light of holy shock you are only casting 1 spell even though it is providing 2 since beacon is on the target. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/e69d137e-42ed-4788-96b2-0023f6c4c2a6)

If you can provide any evidence to show otherwise we can look into this for you

**Comment by Bartok14** [comment] 2024-02-27 22:35
> hi @Bartok14 thanks for reporting can you provide links for this report

Which links specifically do you need? I have one comment on Wowhead from 2010 you cna check out. If you need video evidence I'll need some time to provide that. 

https://www.wowhead.com/item=47059/solace-of-the-defeated#comments
Scroll to CTRI comment. Should work exactly like Meteorite Crystal which also procs with Beacon of Light spells.

**Comment by Maine1** [comment] 2024-02-27 23:04
I just checked meteorite crystal and if it works the same they have the same effect on casting spells. We will check if meteorite and if it procs the same we can go ahead on this

**Comment by Bartok14** [comment] 2024-02-27 23:06
> From what I have found it shows that this only procs each time you cast a spell. Now when you cast holy light or flash of light of holy shock you are only casting 1 spell even though it is providing 2 since beacon is on the target. ![image](https://private-user-images.githubusercontent.com/122736582/308354103-e69d137e-42ed-4788-96b2-0023f6c4c2a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNzQyOTEsIm5iZiI6MTcwOTA3Mzk5MSwicGF0aCI6Ii8xMjI3MzY1ODIvMzA4MzU0MTAzLWU2OWQxMzdlLTQyZWQtNDc4OC05NmIyLTAwMjNmNmM0YzJhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QyMjQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDkzYzVmMDc2ODJkZWUzM2ZjOGZhZWRkYmY4ZDM4ZWE4YmY1NTdkMGZjNDE4ODQxMTNlMGQ1MTA2MWNiMzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-8nwUq7GCkLuUOzNAXBBrWFFDDnMeA8MvjiVR6BmuEA)
> 
> If you can provide any evidence to show otherwise we can look into this for you

For Holy Paladins Beacon has always counted as a second cast for heals. It's why Meterite Crystals was considered to be BiS most of the expansion. Because you could cast BoL on the tank and then spam FoL to stack up 2 stacks per heal.

**Comment by Maine1** [comment] 2024-02-28 02:31
Upon testing Meteorite Crystal I can confirm It is supposed to proc x2 Holy light, Flash of Light and Holy shock with beacon on but only when the beacon target is not healed directly. If the beaconed target is healed it should only proc 1 tick.
With Solace of the Defeated however I came across this latest patch note. Now this is bad wording and unsure how this is supposed to react. 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/6fd79698-63cb-4683-87b7-59c124fad140)

It shows the change no longer effected by spells that cost 0 Base. Technically the second tick from the beacon didn't cost any base mana to tick.

**Comment by Bartok14** [comment] 2024-02-28 02:56
> Upon testing Meteorite Crystal I can confirm It is supposed to proc x2 Holy light, Flash of Light and Holy shock with beacon on but only when the beacon target is not healed directly. If the beaconed target is healed it should only proc 1 tick. With Solace of the Defeated however I came across this latest patch note. Now this is bad wording and unsure how this is supposed to react. ![image](https://private-user-images.githubusercontent.com/122736582/308400999-6fd79698-63cb-4683-87b7-59c124fad140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODkwNzgsIm5iZiI6MTcwOTA4ODc3OCwicGF0aCI6Ii8xMjI3MzY1ODIvMzA4NDAwOTk5LTZmZDc5Njk4LTYzY2ItNDY4My04N2I3LTU5YzEyNGZhZDE0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwMjUyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmFmMTg0MDNlMDA1ZDZhYWJmZTBmNzVmYjU0ODJmMWZmNjEyMjg3MDYxZDZkZWVhZDExNjg2ZGZmNTEwZWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rkMFlFWAktJxyPm8ER0loVGh3zLHfXm78jkfA8ZsVa0)
> 
> It shows that the change no longer effected by spells that cost 0 Base. Technically the second tick from the beacon didn't cost any base mana to tick.

I think this might have to do more with instant cast spell that actually cost 0 mana. Upon looking up Meteorite Crystal on Wowhead there was apparently some bugs where spells like Arcane Torrent would proc the trinket. Apparently casting Fishing would actually instand proc all 20 stacks as there is no global cooldown associated with fish casting. In this case Holy Light, Flash of Light, and Holy Shock would still cost mana to cast.

**Comment by Maine1** [comment] 2024-02-28 02:57
Yes I just read all that too. Find fish and Pet summons also. I did find this 
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/718b750c-dd9a-426b-9f19-e3b3643a7261)
Also says the same thing as solace of the defeated. Can go ahead with the fix.

**Comment by Maine1** [comment] 2024-02-28 03:03
@Rushor After a fair few hours I believe this can go ahead and work the same as Meteorite Crystal. Fix for Solace of the Defeated. normal and Heroic version and Solace of the Fallen normal and Heroic versions.
proc 2x with Flash of light and Holy shock. When healing a target and Beacon of Light is on another target

**Comment by Lumber-Jack-2** [comment] 2024-02-28 09:39
so we will copy the mechanic of Meteorite Crystal for Solace of the Defeated and Solace of the Fallen (nh + hc) yes?

**Comment by Lumber-Jack-2** [comment] 2024-02-28 09:44
ah i see now: Code for Holy Shock while using Beacon of Light for those items is added manually, so we have to add code for those items here aswell

**Comment by Maine1** [comment] 2024-02-28 14:29
> so we will copy the mechanic of Meteorite Crystal for Solace of the Defeated and Solace of the Fallen (nh + hc) yes?

Need to add proc twice when beacon is on another target for Holy shock and Flash of light. on all 4 items mentioned above.

**Comment by Lumber-Jack-2** [comment] 2024-03-03 10:37
added same mechanic like Meteorite Crystal for Solace of the Defeated and Solace of the Fallen (nh + hc) 4 cases in total

**Comment by Maine1** [comment] 2024-03-03 13:41
@Rushor 
- [x] Solace of the Fallen NM (ID 47271) - Holy shock is proccing 3 times without beacon & 6 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen NM (ID 47271) - Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen HC (ID 47432) - Holy shock is proccing 3 times without beacon & 6 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen HC (ID 47432) - Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen NM (ID 47271) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen HC (ID 47432) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated NM (ID 47041) Holy shock is proccing 3 times without beacon & 5 times with beacon.  Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated HC (ID 47059) Holy shock is proccing 3 times without beacon & 5 times with beacon.  Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated NM (ID 47041) Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated HC (ID 47059) Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated NM (ID 47041) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated HC (ID 47059) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.

**Comment by Lumber-Jack-2** [comment] 2024-03-04 11:44
code was wrongly duplicated, should be fixed now

**Comment by Maine1** [comment] 2024-03-05 01:33
> @Rushor
> 
> * [x]  Solace of the Fallen NM (ID 47271) - Holy shock is proccing 3 times without beacon & 6 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Fallen NM (ID 47271) - Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Fallen HC (ID 47432) - Holy shock is proccing 3 times without beacon & 6 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Fallen HC (ID 47432) - Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Fallen NM (ID 47271) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Fallen HC (ID 47432) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Defeated NM (ID 47041) Holy shock is proccing 3 times without beacon & 5 times with beacon.  Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Defeated HC (ID 47059) Holy shock is proccing 3 times without beacon & 5 times with beacon.  Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Defeated NM (ID 47041) Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Defeated HC (ID 47059) Holy Light is proccing 2 times without beacon & 4 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Defeated NM (ID 47041) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
> * [x]  Solace of the Defeated HC (ID 47059) Flash of Light is proccing 3 times with beacon. Should be 2 and only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.

- [x]  Solace of the Fallen NM (ID 47271) - Holy shock is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen NM (ID 47271) - Holy Light is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen HC (ID 47432) - Holy shock is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Fallen HC (ID 47432) - Holy Light is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x]  Solace of the Defeated NM (ID 47041) - Holy shock is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated NM (ID 47041) - Holy Light is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated HC (ID 47059) - Holy shock is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.
- [x] Solace of the Defeated HC (ID 47059) - Holy Light is proccing 2 times without beacon & 3 times with. Should be 1. Only 2 when a Beacon is on a target in the party/raid group and the target with the beacon is not being healed directly.

**Comment by Lumber-Jack-2** [comment] 2024-03-05 09:17
added one more mechanic from Meteorite Crystal (the procc attribute) lets see if that fixes it

**Comment by Maine1** [comment] 2024-03-05 13:10
@Rushor Seems to have done the trick all checked and working

**Closed as completed** 2024-03-06 10:30 UTC
Labels: Fixed on PTR - Tester Confirmed, Core Change
