### ISSUE TITLE
[Core] Dungeon Finder

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#2536] opened 2018-06-14 05:19 UTC
Hello,

I have been using the Random Dungeon Finder to join random heroic lich king dungeons (rhc) for a while now (5+ months), and recently there seems to be a recurring issue with it that affects multiple players at a specific time of the day. I have noticed this issue for the past 1 or 2 weeks now.

I unfortunately have no real way of providing evidence to support this, but other players can surely testify as to what is happening. Around 5:00-8:00AM server time, when the population on the server is lower, the random dungeon finder tool will often fail to match people queued individually, even though they match the roles needed for a full party. 

Example that just happened to me:

Daily heroic reset had just happened (so no instance locks can be interfering with the RDF tool), and I saw someone ask for a dps for rhc (A). Not being in queue at the moment, I queue up as dps only, and see that the tool tells me we still lack a dps. Asking people to queue up individually as dps will not fill up the group, even though the other 4 are supposedly there. The only way to get the queue to pop is to team up with other players in a party of at least (3-4?, actual number to be confirmed) after which the queue will pop and match us with solo players to fill the missing spots.

I know this is a somewhat abstract issue and it is thus difficult to provide evidence for it or reproduction steps.

Finally, when I play at different times, the queue seems to function correctly (maybe due to the larger amount of players online). And if it matters to you, I pretty much always queue as tank or heal for rhc, so it is very clear to me that there is a bug if someone asks for heals and i queue as it and nothing happens...

Thank you for considering this issue,
Oganku

**Comment by Dranah** [comment] 2018-06-14 09:28
This is not a recent issue, RDF has always been this way, on every private server i've played so far.
It is filling multiple parties at once, which means that below a certain player count it can't fill parties at all. (keeps assigning players to new groups and starts filling them only after)
I'm not sure if this is a bug or just the way it works, but i can confirm it behaves this way.

**Comment by Oganku** [comment] 2018-06-14 22:20
Thanks for supporting this case. :)

**Comment by Dranah** [comment] 2018-06-15 01:30
Okay i made some research and after i had a few spare minutes, I made some tests on the PTR too, to experiment with different scenarios regarding RDF group making.
The main issue seems to be the visual display which can be misleading, so disregard my previous comment (in other servers, it was really bugged... but here i think is simply a little unfair, exactly because the system prioritize forming groups over everything else. Something for something, i guess)

Here is the results of my tests:

1) Queueing up 1 tank, 1 healer and then 3 dps, one by one, will properly match the five into one group. (so no, it does not start forming multiple parties for no reason - there must be something with instance locks, gear requirements or people queueing in bigger groups that don't match with each other)
2) The system is able to rotate each person between being a DPS, tank or healer based on what is missing, properly.
3) **The visual display of your forming group**
This may sound odd but they are not the people that the system already assigned to you, but the pool of free players available that the system "sees" as a possible match with you. (but you may not be the first in your role's queue to be matched with them!)
Example: if there are 2 tanks and 3 dps in queue, both tanks will see only a healer missing in their RDF panel. They will both see all the 3 dps available, even though - obviously - only one tank can get a pop with them.
This can lead to people thinking there are multiple groups waiting for one role, when in fact the same pool of people are seen by everyone.
4) The system does not consider plate/cloth etc when forming groups. That's an urban legend . It only differentiates people based on the role(s) they select.
5) The system will form a group whenever it can. Even if it means it "jumps over" an individual who waited a long time, if it can fill up another group (that queued much later). 
Example: if there is 1 tank 1 heal 1 dps in queue, and a DPS queues up alone, waits for half an hour and then 2 dps in party group up too, the system will ditch the solo DPS and form a party with the 2 that are able to fill the group instantly. This is why you often have to wait longer when queueing solo, compared to grouping with a friend or two. 
6) Multiple roles selected - the system also prioritize forming groups over distributing resources properly.
This means when someone marks both tank and dps for example, and there is one group waiting for 1 dps and 5 other groups all waiting for 1 tank, the system will make the guy DPS and put him into the first group because they are first in the queue and it doesn't care that there is a much greater demand for tanks.

I'm not sure why it happens that someone calls for a dps and you don't get a pop, I have the following guesses:
- they forget to specify that they need more than just one dps to fill
- they aren't actually in queue, but forming a premade and expect you to whisper them for invite
- they aren't actually seeing their own group being formed, just the pool of players available, so when another DPS joins queue, somebody else gets a pop with a different party, and when you join the queue, there is no group ready yet and the spammers are still spamming because they aren't the ones that received the pop

**Comment by fvicaria** [comment] 2018-06-15 06:29
Thanks a lot for that Drannah. That will help.

**Comment by squalllh1989** [comment] 2018-07-01 06:04
Maybe you can think about it again after see this, i'm queued in rdf system with the only role is healer, and the system said that i'm in a queue which missing only healer, how can that happening
![wowscrnshot_070118_130344](https://user-images.githubusercontent.com/27235989/42131572-43322b6e-7d2f-11e8-9929-57428b85b6b9.jpg)

Well it's on a low level queue, but not sure if the random heroic using the same factor

**Comment by squalllh1989** [comment] 2018-07-01 06:05
You can see clearly on the left, the system said: "you queued as healer" and the asembling group said: the group is missing healer only, how about that :)

**Comment by squalllh1989** [comment] 2018-07-01 06:36
after testing arround it, it seem that even tho i queued as healer only, the system forced me to dps, and even if i leave the queue, relog, and queue again, the moment i queue, my  queue display as i was queue 25 min ago, not the moment i rejoin the queue

**Comment by Dranah** [comment] 2018-07-01 11:45
@squalllh1989 You did not show anything new. I posted above that the visual display is broken, so what you "see" being formed does not mean anything. It could be really far from reality.

The system does not "force" you to dps if you did not mark it, IF you going to get a pop because finally a group is formed, you will be healing.

Please provide an actual test with multiple characters queueing up with different roles to confirm that there is a problem with the system matching the roles.

**Comment by squalllh1989** [comment] 2018-07-01 13:15
no not really, the pop after i queue as only heal (as the screenshot show) after is actually as a dps and i wasn't change my choice of select only heal role. The thing is: the first time i queue, i select both heal and dps, then after that i cancel the queue and select only heal role, but as the screenshot say, it say i'm queue as healer but the group is missing only healer, and after that when the queue finally pop up, i have myself in a scarlet monestary - graveyard group, as a dps, so, no, it's not just a visual bug but it's actually force me to dps regardness i'm only select healer role.

**Comment by squalllh1989** [comment] 2018-07-01 13:18
Yeah and i know, as a tester, just throwing thing over like this without a proper test and a way to reproduce is not good work, i will try to find a way to actually reproduce it, but just wanna let you know that it's not a visual bug, something is actually wrong.

**Comment by squalllh1989** [comment] 2018-07-09 10:52
well after sometime tried to test this out, i still fail to reproduce the problem that i see once, it's kind of sad but i think i will give up for now >.<, maybe later when i can think of a clue how, i will try to reproduce this again.

**Closed** 2018-07-09 10:52 UTC

**Comment by Echinaceax** [comment] 2024-07-29 16:07
posting an updated comment here as of 2024 players are still regularly complaining about this in worldchat every day.

what i have seen from @squalllh1989 screenshots is that they have the "dungeon guide green flag" checked along with the healer.

here
![image](https://github.com/user-attachments/assets/179f777d-9bd7-4c8f-ab84-2062ff25502e)

i have a theory ...

has anyone tested if it still has a bug for some players when they dont select the dungeon guide role? 
![image](https://github.com/user-attachments/assets/37b7b498-ec10-4f59-ba48-9b2b3038363d)

its something worth taking into account, seeing as this bug doesnt happen to all players
