### ISSUE TITLE
Pint-Sized Pink Pachyderm - Missing Special Animation and Visible To Everyone

### ISSUE THREAD

**Issue by kamoodle5** [WoWManiaUK/Redemption#5786] opened 2022-04-04 21:55 UTC
https://www.warcraftpets.com/wow-pets/critter/elekks/pint-sized-pink-pachyderm/
https://www.wowhead.com/item=46707/pint-sized-pink-pachyderm

**What is Happening:** This baby elephant doesn't perform its special animation when idle. Also, this pet seems to be visible to everyone.

**What Should happen:** Its unique animation should occur on occasion, and the elephant should only be visible to either party/ raid members or very inebriated players (in-game, of course).

Note: There have been confirmation in the Wowhead comments that when using a leash or a toy on this pet, there will be an error message "Spell cannot be cast on stealthed target."; however, all items work fine currently. 

Here's a video of the animation:
https://youtu.be/S9vMinnObQk?t=72

**Comment by Echinaceax** [comment] 2022-04-04 23:42
confirmed bug 

https://i.gyazo.com/9b57d7aa8cc30411ffe6834b120e5bb5.mp4

**Comment by Rushor** [comment] 2022-04-05 07:43
the visibility thing i cannot add for now, since i cannot find the aura that handles it, but i found the special animation spell: 65436

the pet will cast it first after 5 seconds and then every 60 seconds

**Comment by Echinaceax** [comment] 2022-04-05 08:38
cute animation fixed in PTR 

https://i.gyazo.com/3b8c6d29d36342b8364eded17424f06a.mp4

**Closed** 2022-04-05 11:55 UTC
Labels: Fixed on PTR - Tester Confirmed
