### ISSUE TITLE
[Core] Spell effects while Out of Combat

### ISSUE THREAD

**Issue by LimitlessPain** [WoWManiaUK/Redemption#2287] opened 2018-02-24 02:08 UTC
Sorry for the odd title, but I cant really figure out how to call this issue. Feel free to change it in case its misleading/not quite on point.

The problem is some spells (which I have observed so far) like Fear or Death Grip display no effect at all when used on hostile NPCs to start the combat.
In other words, if I use Death Grip on an NPC before its in combat, the spell goes on cooldown, the death grip debuff appears on the NPC, but it stays where it was (doesnt get pulled in) and starts running towards me as if it was hit by an attack or simply got into aggro range.

The same applies for Fear, if I cast fear first on the NPC before entering combat, the fear effect debuff gets applied visually, but the NPC starts charging at me attacking and casting spells like normally (as if a curse was applied), AND recasting fear on it does not do anything besides refreshing the debuff while the NPC still ignores its effect (does not run away/still casting).

Using any of the aforementioned skills while already in combat applies their intended effect as it should.
I will put the spell IDs here, but I doubt it is a specific spell issue.
Fear - http://www.wow-mania.com/armory/?spell=6215
As for Death Grip I cant figure out which is the right spell in the armory, so I'd rather not link a wrong one.

I got it confirmed that Polymorph is not affected by this. I guess Hex isnt either.

**Comment by WhitephoenixTheBunny** [comment] 2018-02-25 10:52
Fear from warlock confirmed, the NPC under Fear started attacking me and pet.

Death Grip, i could not reproduce, i tried on several hostils NPC and all were grabbed, maybe you could give me an NPC name/id so I can reproduce?

Polymorph(Mage), Hex(Shaman), Cyclone and Entangling Roots(Druids) working fine.

**Comment by fvicaria** [comment] 2018-02-25 14:34
Fixed in dev. Will need restart.

**Closed** 2018-02-26 12:13 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev
