### ISSUE TITLE
Crafted robes won't show up in AH search

### ISSUE THREAD

**Issue by jackdexterred** [WoWManiaUK/Redemption#4566] opened 2020-05-17 18:13 UTC
**Links:**

![image](https://user-images.githubusercontent.com/65506282/82156293-5a672d80-9848-11ea-9ebf-12b317e6f3de.png)
![image](https://user-images.githubusercontent.com/65506282/82156308-6c48d080-9848-11ea-80e1-0f3919ea1191.png)

**What is Happening:**
Posting an Ebonweave Robe does not show up in the auction house under the search route of "Armor > Cloth > Chest". It does display if you are searching for it specifically by name.

**What Should happen:**
Ebonweave Robe should be posted on the auction house under the search path "Armor > Cloth > Chest"

**Comment by jackdexterred** [comment] 2020-05-17 18:16
This is actually the same for the item "Merlin's Robe" and "Royal Moonshroud Robe". so it seems to me like the level 80 High item level chest pieces aren't being linked to the correct spots in the auction house.

**Comment by jeyrella** [comment] 2020-05-17 19:01
this is a duplicate of #235.  Since that one is extremely old and was decided not to fix, will leave to Janitor to decide if he wants to revisit.

**Comment by Sharuzan** [comment] 2020-05-17 19:19
Looking at Redemptions and Frostmournes AH's, both fail to show anything the game considers a cloth robe(covering chest and legs), when looking in the "Armor - Cloth  - Chest" category.

Checking Redemptions AH at 20:13ST 39 robes were being sold on the Horde Auction House. 
None of those were shown unless you clicked on "Cloth" and just hit search.
Searching "Robe" does the trick too.

When 39 robes are on the AH on one side alone at the same time, safe to say there's a bunch sitting in the opposite factions AH undiscovered too.

Is there really no fix for it?

**Comment by svijetlo** [comment] 2020-05-18 09:19
![image](https://user-images.githubusercontent.com/61908373/82195468-a07bca00-98f8-11ea-8ed2-f6c30c1708ad.png)
![image](https://user-images.githubusercontent.com/61908373/82195586-c43f1000-98f8-11ea-8ad0-4ef86c0760d8.png)
![image](https://user-images.githubusercontent.com/61908373/82195969-60691700-98f9-11ea-8ca4-5794cac35dd5.png)

this is true i posted 3x Ebonweave Robe on AH in ptr and in search they were not shown , img show all, idk does this go for some other items but if search item by name not i its own class it will show up or you going to armor - cloth it will show up , as stated in previous old post of same kind i would say no need to fix small bug niot game change

**Comment by wow-mania** [comment] 2020-05-18 19:12
This will be at Keader's discretion.

**Comment by Keader** [comment] 2020-05-19 13:32
Fixed dear

![image](https://user-images.githubusercontent.com/7120913/82332617-01200b00-99bc-11ea-95f9-dc4f89a53578.png)

**Closed** 2020-05-20 12:31 UTC
Labels: Fix - Tester Confirmed
