### ISSUE TITLE
Buff Stacking.

### ISSUE THREAD

**Issue by AlbionSirzechs** [WoWManiaUK/Redemption#1602] opened 2017-09-12 16:56 UTC
Greetings,

I have done a little bit of a research about buff stacking and I am pretty sure Gift of the Wild (Druid buff) Should be stacking with the inscription lvl 80 scrolls (Scroll of Strength VIII)
Furthermore wowwiki says the blessing of kings stacks with blessing of sanctuary excluding the 10% stamina buff which doesn't stack. So classes should have a total of 20% str according to that website.
[http://wowwiki.wikia.com/wiki/Greater_Blessing_of_Kings](url)
and proof that Scroll of Strength VIII and Gift of the Wild Stacks are in that YouTube video
[https://www.youtube.com/watch?v=nl_S8LQ19JY](url)

**Comment by Midnaa** [comment] 2017-09-12 17:22
The proof you're showing is from another private server and we can't use that as a reference. Furthermore Wowwiki is known to have a lot of false data in it. Please find a valid source that can confirm your report.

**Comment by captainloozer** [comment] 2017-09-12 17:48
http://wowwiki.wikia.com/wiki/Greater_Blessing_of_Kings
https://wow.gamepedia.com/Greater_Blessing_of_Sanctuary

The reason the article does not state anything about Strength stacking is because the article is outdated and was never updated to reflect the changes that were made with Sanctuary in patch 3.3.0.  If it had been updated, it would have stated that stam and str do not stack.  The reasons behind this is because they are both 10% modifiers and would not stack, same with any other similar effects.  If you already have greater blessing of kings, the only thing you will get from sanctuary is the damage reduction and the resource regeneration from avoiding attacks.

I have mained a paladin since the beginning of burning crusade and distinctly remember it working this way.  

As for the scrolls + GOTW, I'll have to do some more research but regarding the paladin buffs, this is 100% working as intended.

**Comment by captainloozer** [comment] 2017-09-12 17:51
This is a post from patch 3.0.2 where raid buffs were changed.  Inscription scrolls were considered an additive stat increase buff which falls in line with Druid's MOTW.  The druid buff will overwrite any scrolls and this is intended.

http://www.wowhead.com/forums&topic=48207/mark-of-the-wild-overwriting-scrolls

Closing this issue as all points made are working as intended.

**Closed** 2017-09-12 17:51 UTC
