### ISSUE TITLE
[Quest] In Strict Confidence – Welsington missing speech

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6146] opened 2023-12-15 12:05 UTC
[In Strict Confidence](https://www.wow-mania.com/armory/?quest=12840)
Player is tasked with beating information about Westwind out of [Captain Hartford](https://www.wow-mania.com/armory/?npc=29490) and [Captain Welsington](https://www.wow-mania.com/armory/?npc=29489).
Captain Hartford works fine, she sends the player to hell.
Captain Welsington however is missing his lines, even though credit is given. Still without the lines it remains illogical how would the quest giver and player learn about  Archbishop Landgren for the next quest. Lines should pop up at death.

Missing:
Captain Welsington says: [Archbishop Landgren](https://wowpedia.fandom.com/wiki/Archbishop_Landgren) must know! Aaaaaagggghhhh.....!

https://wowpedia.fandom.com/wiki/In_Strict_Confidence#Notes
1:10-1:16 https://www.youtube.com/watch?v=xYEXFtbuN_s&ab_channel=GitGudGuides

**Comment by Maine1** [comment] 2023-12-16 14:28
Captain Welsington says: [Archbishop Landgren](https://wowpedia.fandom.com/wiki/Archbishop_Landgren) must know! Aaaaaagggghhhh.....!

Confirmed missing gossip

**Comment by Lumber-Jack-2** [comment] 2023-12-23 09:23
added the textline

**Comment by Echinaceax** [comment] 2023-12-23 12:31
> added the textline

I don't see him saying any text line gossip (Captain Welsington says: [Archbishop Landgren](https://wowpedia.fandom.com/wiki/Archbishop_Landgren) must know! Aaaaaagggghhhh.....!)

Only one that says something is Captain Hartford 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/58351bbd-d9d1-4302-9f32-c93f188e07fd)

**Comment by Lumber-Jack-2** [comment] 2023-12-23 13:02
So strange okay checking again

**Comment by Lumber-Jack-2** [comment] 2023-12-23 17:43
hm for me he does not show the texts at all now. is this some kind of chatsetting

**Comment by Lumber-Jack-2** [comment] 2024-01-08 18:39
changed the textrange, i hope it works now

**Comment by Echinaceax** [comment] 2024-01-08 23:22
> changed the textrange, i hope it works now

Still no change
Tested it on 3 chars

**Comment by Rushor** [comment] 2024-01-09 05:24
as test change i changed it to be a on-aggro text. if that also does not work we must close it, some hidden mechanic is preventing the text then

**Comment by Lumber-Jack-2** [comment] 2024-01-09 05:28
okay found the reason, a condiion was preventing the text, should be good now

**Comment by Echinaceax** [comment] 2024-01-09 11:49
> okay found the reason, a condiion was preventing the text, should be good now

Nice, much better :)
Fixed in PTR 

[Captain Welsington](https://www.wow-mania.com/armory/?npc=29489).
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/b598253d-d1bc-48b8-bd69-41941b1a9b89)
[Captain Hartford](https://www.wow-mania.com/armory/?npc=29490) 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3f5b5c63-11f5-420d-80bb-a9ef55e1e61e)

**Comment by Lumber-Jack-2** [comment] 2024-01-09 17:40
perfect thanks

**Closed as completed** 2024-01-11 08:34 UTC
Labels: Fixed on PTR - Tester Confirmed, DB Change
