### ISSUE TITLE
Valithria Abom Spam

### ISSUE THREAD

**Issue by Agrannis73** [WoWManiaUK/Redemption#4553] opened 2020-05-09 04:11 UTC
**Links:**

Valithiria is spawning aboms instead of other mobs and rapid firing portals.  She is also yelling out "failures" as if some one died without a player death. Div saw our ticket and attempted to kill the aboms.  When Div saw what was going on he indicated that we needed to report an issue.  Possible scripting issue.

Multiple types should spawn

**Comment by Rushor** [comment] 2020-05-09 05:15
duplicate of https://github.com/WoWManiaUK/Redemption/issues/4550. will be fixed soonish with next update

**Closed by Rushor** 2020-05-09 05:15 UTC
