### ISSUE TITLE
[Quest] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by agris91** [WoWManiaUK/Redemption#3388] opened 2019-07-14 14:48 UTC
**Links:**
 [Teron Gorefiend, I am...]   https://www.youtube.com/watch?v=Kyh974rKovw

**What is Happening:**

 Not transformed in Teron 

**What Should happen:**

**Comment by wow-mania** [comment] 2019-07-14 14:59
pretty sure it works.

**Comment by agris91** [comment] 2019-07-14 15:12
GM was trying to do it, it doest work!

**Comment by wow-mania** [comment] 2019-07-14 15:36
GM cannot do it.
It works

**Comment by jarvik76** [comment] 2019-08-23 17:18
If it does work, I am struggling to see how.  I have just repeated this and still seeing what agris91 experienced.
I tried getting new spectracles from Zuroc, wearing and then going back to the Altar, no change.
If there is a phasing issue, it is not at all obvious the player what the issue is or how to fix, since the quest can still be accepted.
https://youtu.be/KCIA6kILQ2Q

**Comment by GMMetaxa** [comment] 2019-09-11 18:07
Tested on non GM toon. Did all pre-quests. Ancient Shadowmoon Spirit doesnt launch the event. No Krasius.

**Comment by WhitephoenixTheBunny** [comment] 2019-09-11 18:12
I am going redo the quest myself on one of my toons
Don't close it Jani please

**Comment by wow-mania** [comment] 2019-09-11 21:17
It works. I have done it myself many times.

**Comment by Rushor** [comment] 2019-09-13 11:23
prev quest requirement for quest http://www.wow-mania.com/armory/?quest=10636 added (requires quest 10644 rewarded first now)

**Comment by Rushor** [comment] 2019-09-13 11:32
> The chain can be started at: A Ghost in the Machine (should requires: Zorus the Judicator)

also prevquest requirement added

**Comment by Rushor** [comment] 2019-09-13 11:33
issue 3 cannot be fixed by client devs, so stay as is

**Comment by WhitephoenixTheBunny** [comment] 2019-09-13 11:44
And the event sum? at last quest

**Comment by Rushor** [comment] 2019-09-13 15:06
![I](https://i.imgur.com/dh59pMY.jpg)

and can be attacked and killed now

**Closed** 2019-09-16 09:55 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev
