### ISSUE TITLE
[Boss] Razorgore The Untamed

### ISSUE THREAD

**Issue by Sugarconepk** [WoWManiaUK/Redemption#2610] opened 2018-07-20 14:39 UTC
I am writing about Razorgore the Untamed (http://www.wow-mania.com/armory/?npc=12435) and his tendency to reset in certain conditions.

He randomly aggros to enemies whenever he gets mind controlled using the Orb of Domination (http://www.wowhead.com/object=177808/orb-of-domination), and starts chasing them. And once he does even when there's a player using the orb, you lose control of him even if you've still got his point of view, you can slightly move him, but he'll just run back to his target. After whichever enemy he was targeting dies, the whole fight resets as if there was a wipe. The controller and 2 guards respawn, and the fight starts again.

**Comment by TheManiax** [comment] 2018-07-22 07:00
I confirm the first part; when [[Razorgore]](http://www.wow-mania.com/armory/?npc=12435) agroes a target, he starts moving toward it. In this time, even if you use the [[Orb of Domination]](http://www.wowhead.com/object=177808/orb-of-domination) to cast mind control, it still continues moving toward his target (while you have it's point of view without being able to control it)
He needs to reach the target, then you will be able to move him or use it's abilites
but the second part about it's getting reseted, It's obviously getting reset when it shouldn't ,but I don't know the exact conditions that makes it reset
It even resets before the first wave of adds spawn sometimes

**Comment by Sezzula** [comment] 2018-08-12 20:45
Me and my guild mates tried to do it earlier today. Problem is, we can control him using the orb but the fight always reset because the controller mob respawn VERY quickly.

**Comment by wow-mania** [comment] 2018-08-29 08:39
If this can't be reproduced in test please close it.

**Comment by TheManiax** [comment] 2018-08-30 05:08
The bug is easily reproduced
The boss resets very often
The issue is that we don't know on what pattern and for what reason it resets
Sounds hard to find the reason in-game, and I doubt you can find it in codes easily
I will close till we find more info.

**Closed by TheManiax** 2018-08-30 05:08 UTC
Labels: Confirmed, Need Informations

**Comment by WhitephoenixTheBunny** [comment] 2018-08-31 08:51
meh... :P

**Comment by Serraria** [comment] 2019-01-11 20:23
https://www.youtube.com/watch?v=BMKZbxlBFrM&feature=youtu.be This is evidence of the bug, the group I was in did eventually manage to kill it but they said they had no idea how or why it just worked after maybe 10min. :)
