### ISSUE TITLE
[Raid] Rotface on ICC 25 HC

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1336] opened 2017-07-01 23:47 UTC
Currently rotface on 25 hc having some trouble:
- The pudle is in the air, not on the ground, while still doing damage and stack like it was on the the ground (like in my screenshot)
![wowscrnshot_070217_063455](https://user-images.githubusercontent.com/27235989/27766165-867c3b56-5ef1-11e7-88b9-01bc302e36e7.jpg)

- The Vile Gas which is being cast in 25 hc mode (http://www.wowhead.com/spell=72272/vile-gas) is having it aoe much larger range than it should be. It should have a range of 8 yards, currently it is at like 10 or 12 yards.
- The target lost problem when rotface cast slim spray, this is already been reported and answer that it will not be fix at the near future, so i won't talk more about it, but it's really anoying in 25 hc mode, when it's hard already.

**Comment by fvicaria** [comment] 2017-07-03 08:44
Cannot reproduce on dev. The other issues are already explained and won't be fixed at this time.

**Closed by fvicaria** 2017-07-03 08:44 UTC
