### ISSUE TITLE
Scourge Tactics - webbed  crusaders not spawning

### ISSUE THREAD

**Issue by PitViper333** [WoWManiaUK/Redemption#1867] opened 2017-11-24 21:45 UTC
Cannot finish quest because webbed crusaders do not respawn,

**Comment by fvicaria** [comment] 2017-11-24 21:46
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by fvicaria** [comment] 2017-11-25 09:12
There was an issue but unfortunately, I could not reproduce after the restart.

**Comment by PsycsX** [comment] 2017-11-26 17:32
I'm having the same issue.  I've dropped the quest, picked it back up, logged in and out, and they aren't spawning.

-using our client
-using the latest launcher
-steps to reproduce the problem: Accept quest Scourge Tactics from Crusade Commander Entari.  Run out to Valley of Echoes to complete, but there are no webbed crusaders to be seen.
-description of how it should work: same as above, except webbed crusaders should be spawned
-NPC/Item/Spell names (or IDs) from wowhead.com or Armory: http://www.wowhead.com/npc=30273/webbed-crusader

**Comment by fvicaria** [comment] 2017-11-26 17:36
Yes. There seems to be an issue here. After a while, they disappear.

**Comment by fvicaria** [comment] 2017-11-26 18:09
Found the issue. It will be fixed tomorrow.

**Closed** 2017-11-28 12:24 UTC
Labels: Confirmed, Fixed in Dev
