### ISSUE TITLE
[NPC] Wyrmcult blackwhelp 

### ISSUE THREAD

**Issue by GMZinius** [WoWManiaUK/Redemption#6252] opened 2024-09-08 16:48 UTC
Player reported this in an in game ticket. 
I reset all, did not fix the issue.

**Links:**
NPC https://www.wow-mania.com/armory/?npc=21387
Video after I reset them https://i.gyazo.com/347297831b998b5557d2e0021b20ec0a.mp4

**What is Happening:**
They are sliding on the ground alive.

**What Should happen:**
They should be flying.

**Comment by Echinaceax** [comment] 2024-09-08 17:09
i'll try and reproduce on PTR

**Comment by Echinaceax** [comment] 2024-09-08 17:20
test 1
killed all with .damage (respawn was fine)

test 2
killed all normally with class spells (respawn was fine)

test 3 
killed all with .die (respawn was fine)

Wyrmcult Egg Spawner looks fine https://www.wow-mania.com/armory/?object=184839
 not all spawn from the Wyrmcult Egg Spawner


cant reproduce 
![image](https://github.com/user-attachments/assets/043f765a-aabd-44b4-aff7-ac4821d8aae9)

**Comment by Echinaceax** [comment] 2024-09-08 19:38
ok finally reproduced it @Rushor 

Player A 
when on the quest Whelps of the Wyrmcult https://www.wow-mania.com/armory/?quest=10747 player have to use the quest item Blackwhelp Net https://www.wow-mania.com/armory/?item=31129 

Player B 
after player A has used the quest item on the Wyrmcult blackwhelp, When the Wyrmcult blackwhelps respawn they respawn bugged for player B  

- [ ] the quest item bugs the Wyrmcult blackwhelp respawn
https://i.gyazo.com/8a5a7a53c5eb5808c62075b90a2f1b69.mp4

**Comment by Echinaceax** [comment] 2024-09-10 18:41
confirmed fixed in ptr 

https://i.gyazo.com/08aa43b32c26b0727dff0763eb7aab42.mp4

**Closed as completed** 2024-09-12 09:50 UTC
Labels: Fixed on PTR - Tester Confirmed, DB Change
