### ISSUE TITLE
[Quest] Filling the Cages - "Budd" quest pet overwrites Hunter pets

### ISSUE THREAD

**Issue by Bartolo96** [WoWManiaUK/Redemption#4548] opened 2020-05-06 11:25 UTC
Quest:  https://www.wowhead.com/quest=11984/filling-the-cages

This quest gives a minion named "Budd" if your class is an hunter this minion replaces your pet, after I completed and delivered the Quest, Budd is still with me in place of my pet and I cant abandon him or get a pet from the stable (in the stable the equipped pet slot is shown empty but I cant drag anything  into it).
I believe that after delivering the quest my own pet should come back but it doesn't.

My in game character where this happened is : Polloarrosto 
The pet that got replaced was  : PatateFritte lvl 77 Tyrant Devilsaur

Note:
I do not know if it is relevant but the time period in which I was doing this quest was when the server was continuously crashing.

**Comment by Rushor** [comment] 2020-05-06 11:42
okay, one question:

do you know a similar quest where people controle a pet? 

okay i remember the stormpeak quest with the 3 minions

**Comment by Bartolo96** [comment] 2020-05-06 11:50
I do not remember any, to be honest I'm a new player to WoW in general

**Comment by Bartolo96** [comment] 2020-05-06 13:42
I do not want to seem pushy, but is there any way you could "hotfix" my character? 
It is the only one I have and without pet I cant really play

**Comment by svijetlo** [comment] 2020-05-06 14:58
i just did quest on my hunter ,
i told Budd to go with me with my pet out 
after i gave in completed quest budd was gone and i was left wo pet 
but as soon i use ability call pet my original pet was back

**Comment by Bartolo96** [comment] 2020-05-06 15:17
Yes, Budd seems like a cool guy but I still prefer my Devilsaur to him 😂

**Comment by svijetlo** [comment] 2020-05-06 15:19
i think smt went wrong do to crashes yesterday , as in normal state quest can be don and all is back to normal , this only happen if you abandon quest or guess from crash i just got me self budd on my dk also :D

**Comment by svijetlo** [comment] 2020-05-06 15:30
![WoWScrnShot_050620_172853](https://user-images.githubusercontent.com/61908373/81196261-1ca01480-8fbf-11ea-8a98-41ecaa1d929e.jpg)
this is how stable look , and no you can not drag other pet to current pet slot , Budd took it all over

**Comment by Bartolo96** [comment] 2020-05-06 17:43
May I know an estimate of  how much time it will take to fix my character, just so I'm mentally prepared 😢

**Comment by svijetlo** [comment] 2020-05-06 17:53
@Bartolo96  if all don well and good max till next Tuesday is update, but try to make in game ticket for GM to reset you pet stable as you are now stuck with useless thing , explain it is confirmed issue after server crash , i do hope they will help you it is best i can do for you for now

**Comment by Bartolo96** [comment] 2020-05-06 18:01
@svijetlo Okay I will contact a Gm in game then, can the GM also give back my previous pet?

**Comment by svijetlo** [comment] 2020-05-06 18:02
i think your pervous pet should be in stable you just can not use do to bug mine was in stable i just cant put it to current pet slot

**Comment by Rushor** [comment] 2020-05-06 18:39
Try now pls. effect should be the same like the pets for the quest https://www.wowhead.com/quest=13005

Note: You must engage melee with Budd now to trigger the stun.

please test if that bug with the hnter pet still happens

**Comment by svijetlo** [comment] 2020-05-06 18:56
yes i still cant get rid of him what ever i do still same , 
after i 1st time abandoned quest today im stuck with him ; now i reset quest complete it again , after quest is don he is gone but if i use call pet he is back again and my stable still look same

**Comment by GMMetaxa** [comment] 2020-05-06 19:04
Transferred toon to my account. Deleted Budd, called another pet, Budd appeared.
Did unaura all, deleted cache, relogged and Budd appeared.
Deleted Budd, tried to tame another pet, Budd appeared.
Levelled the toon up and down and up again. Tried on all levels, but Budd kept appearing.
Tried Stable master, Mobile stable, first slot seems locked.
This is prolly a character bug due to crash.

**Comment by svijetlo** [comment] 2020-05-06 19:07
@GMMetaxa  or if you abandon quest as i did today , my hunter on ptr is stuck with bud and ye i did try all you just told apart form moving toon on accounts

**Comment by Rushor** [comment] 2020-05-06 19:27
we must remove it from character_pet

**Comment by Rushor** [comment] 2020-05-06 19:31
@svijetlo pls try with a new toon on dev that quest.

we will remove the pet from the players soon.

**Comment by jeyrella** [comment] 2020-05-06 19:33
Marking critical as cannot be solved for player by GM

**Comment by svijetlo** [comment] 2020-05-06 19:47
funny enough i just made new toon , went there took quest he is refusing to follow me at all , i talk to him get that 10min debuff but i do not get his cast bar nor that he follows me

**Comment by Rushor** [comment] 2020-05-07 07:58
the pet will be removed on next update (maybe even today) from all characters

updated the script even more (fix is active on ptr)

But whould always despawn after 10 minutes now and is no longer like a hunter pet

**Comment by Bartolo96** [comment] 2020-05-07 11:04
Thank you all very much for the help, the guy with the Pan is finally gone 😁

**Comment by manahansf** [comment] 2020-05-10 17:31
Just ran into the same issue.  Budd completely replaced my Hellfire Ramparts Warhound and there is no way to dismiss, abandon, stable swap, or even kill him.  Glad to see it’s not just me.
@GMMetaxa or @Rushor, any chance Fupa (lvl 80 Night Elf Hunter) can get the same hot fix?  Gotta ICC 25HC raid tonight and looks like I’ll need to relevel my wolf before hand... Cheers!

**Closed** 2020-05-12 10:01 UTC
Labels: Fix - Ready to Test, Priority - Critical
