### ISSUE TITLE
[Boss] Mimiron

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#2350] opened 2018-03-20 21:58 UTC
[Boss] Mimiron
Issue:
Phase 2:
 P3Wx2 Laser Barrage does not show the right direction of the shooting, shows as if the body is shooting towards the ground, and on next P3Wx2 Laser Barrage casts, it shows that he's shooting the barrage in the opposing (wrong) direction.

Spell ID: http://www.wow-mania.com/armory/?spell=63274

Phase 3:
Boss evades all attacks and does not progress at phase 3 (Aerial Command Unit) into phase 4 (Leviathan Mk II + VX-001 + Aerial Command Unit, all three combined) when you drop the Helicopter to 1 hp, causing it to freeze and making the raid get stuck in combat + fight in progress, or the enrage (shut-down) happens as it wipes the raid and it still implies the fight is in progress.

Aerial Command Unit ID: http://www.wow-mania.com/armory/?npc=33670

Phase 4:
When wiping on phase 4, the Vehicle (Leviathan Mk II) becomes untargetable, while everything else doesn't reset which causes a raid over.

Weeble can confirm this. 4 weeks in a row we are making ticket after one wipe here.

**Comment by CrustyMuffin** [comment] 2018-03-20 22:04
The bug about Phase 4, where you can´t start the fight anymore happens on any other wipe too. Not only by wiping on Phase 4

**Comment by Ashamedlol** [comment] 2018-03-20 22:21
https://github.com/WoWManiaUK/Redemption/issues/2251 previously posted with extra details.

**Comment by Dranah** [comment] 2018-03-21 00:57
Is there a possibility that dev is not the same scripts as Redemption?
I haven't seen any of these problems on dev when testing earlier, and i can't reproduce them now either.

We're not closing these threads because we don't "believe" you, but the devs cannot fix it if we don't find the root of the problem. I spent hours wiping on mimiron on dev realm and I could not once get the encounter to stuck. Not even with GM commands since Janitor added the overdps protection.
Without proper reproduce steps, or a video, or a series of screens, something that would help identify the issue, they won't be able to fix this.

**Comment by fvicaria** [comment] 2018-03-21 06:11
no

**Comment by Ashamedlol** [comment] 2018-03-21 11:08
They're not doable alone, as I've told the GMs "It has to be experienced in actuality".

**Comment by Ashamedlol** [comment] 2018-03-21 16:55
How to Reproduce Phase3 not transitioning to Phase4: Drop Magnetic Core (http://www.wow-mania.com/armory/?item=46029), overdps the boss (http://www.wow-mania.com/armory/?npc=33670 since it's phase 3) while he's stunned by Magnetic Core.

Issue with phase 2 and phase 4's body part (http://www.wow-mania.com/armory/?npc=33651): The visual and hitbox of P3Wx2 Laser Barrage (http://www.wow-mania.com/armory/?spell=63274) is not accurate, it's shooting in a frontal direction but hitting at the side of it too, (http://www.wowhead.com/spell=63414/spinning-up) the speed of the spin feels off but not very sure on this specific part.

Combat Bug of Mimiron: There's a npc called "Invisible Stalker (All Phases)" that's chasing you, and as you get hit by or hit any of the Boomer XP-500's (http://www.wow-mania.com/armory/?npc=34192) at the Spark of Imagination, you'll be stuck in combat for the whole raid (I believe this is the part where Hardmode gets you almost into a raid-over if this NPC is alive and you wipe).

Another bug I've noticed: Sometimes the cannon of phase 1 on the Vehicle (http://www.wow-mania.com/armory/?npc=33432 /  http://www.wow-mania.com/armory/?npc=34071) is randomly spawning, so sometimes you won't experience Plasma Blast (http://www.wow-mania.com/armory/?spell=62997) and Napalm Shell (http://www.wow-mania.com/armory/?spell=63666) in phase 1 which isn't intended.

**Comment by Dranah** [comment] 2018-03-22 00:59
@Ashamedlol 
I am not testing alone. I'm testing with a model raid of 9 characters consisting of several different classes.  
(I keep one spot open for a dev in case he wants to join and watch)
I asked for more information because some of the bugs you're reporting are the same problems as before, which I could not reproduce. 
But a few issues however seem new, though I don't know what could have possibly broken them.

Test Progress so far:
- After pretty much every wipe now, Mimiron appears to remain in combat (not properly reset). The raid can re-enter but cannot engage the encounter again. Mimiron is attackable and can be killed on top of the tank. (Obviously SHOULD not be, you have to reset him cause he won't yield loot or anything)
This bug requires to reform the raid to fix him. Reason yet unknown.
- Bomb bots outside the room work properly to me and there is no sign of "invisible stalker". They explode if you go near, leave no combat. If you attack them, you have to chase and kill them to remove combat.
- Issue with Phase3 getting stuck when ACU is affected by Magnetic Core: This is a new problem, and a different bug from the earlier overdps issue. Does not require you to kill the ACU with magnetic core active, simply using Magnetic Core at all bugs the NPC. Most likely problem with the Magnetic Core itself.
- Found an odd problem with something destroying the VX-001 before it forms up (transition between phase1 and phase2). Reason yet unknown, the npc simply collapsed and disappeared before it became targetable.

**Comment by Ashamedlol** [comment] 2018-03-22 15:30
@Dranah The NPC that gets you stuck in combat seems to be the "Computer" (137631 / AllName: ScriptName: npc_mimiron_computer)
Phase 1 missing abilities only happend to me on first attempt, didn't happen on next attempts.
As for Bomb Bots, I killed all of them and was still in combat somehow, but I'd suppose its one of the two NPCs I mentioned.

**Comment by Dranah** [comment] 2018-03-22 22:39
Test progress vol. 2:

- Can confirm combat remaining on raid after Mimiron encounter is defeated, however it can be removed by .clearcombat. Still no sign of invisible npc following you.
- Regarding P3wx2 laser barrage hit range
>> The laser beam is as wide as the space between the two cannons on the boss' body, and that is the intended way. It is possible that the visual can lag when the server lags or that it's not pixel-accurate, but then again, no boss animations are. 
This means
1. Being inside the boss' hitbox is not safe, as the damage area there covers 180 degrees (a half circle) of the boss' hitbox.
2. At range (further than 15 yards) the damage begins only along the line of the laser visual, you can be in the frontal area of the boss, yet not take a hit until the beam reaches you.
3. There is a risky area between 10-15 yards from the boss' central point, where the animations are "thinner", but the laser width is still the same as everywhere else (from one cannon to the other). 
This is just the way the animation was designed and we cannot change it.
However, even when the laser beam visual is broken, the damage works properly in a frontal path between the two cannons, so long as you watch where the boss is 'facing' with his cannons, you cannot take a hit.

**Comment by Dranah** [comment] 2018-03-23 01:25
As the first 3 bugs are game breaking that can prevent you from doing the encounter, i'm marking this thread prior.

**Comment by Ashamedlol** [comment] 2018-03-23 01:55
@Dranah After you remove it with .cl, attacking any mob will cause it to be stuck again.

**Comment by Dranah** [comment] 2018-03-23 02:00
@Ashamedlol I tried with the trash outside and had no such problem. You can be "reinfected" with combat from your raid members though, I know it's annoying as hell. 
Nonetheless, the computer NPC does follow your raid during the encounter, so it is possible that it gets stuck on you afterwards, though i can't find a visible sign of it.

**Comment by Dranah** [comment] 2018-03-28 21:42
UPDATE
1) Wipe issue - After wipes now the whole encounter gets stuck and the raid cannot re-enter due to "Encounter in progress". Nothing resets at all, everything stays where it is, vehicles, adds, fire, stuck in combat. (Compared to earlier state where you could re-enter but not engage Mimi again, but result is pretty much same - 1 wipe and raid over)
2) Issue with Magnetic Core bugging ACU still persists, no change on this one.
3) VX-002 no longer collapses randomly between phase1-phase2 transition (this may have been caused by the fix which was reverted)
4) Laser barrage still works properly to me in phase2 but has problem with texture in phase4. No change on this one.
5) Computer NPC still follows raid members and gets them stuck in combat.
6) Adds during phase3 are buggy, the Emergency Fire bots aura does not work and their spray does not hit players (they do clear the fire though). The other type of adds only engage to the raid if they are landing near you, if they spawn in distance, they just stand still where they are, stuck in combat.

**Comment by Dranah** [comment] 2018-03-29 00:48
@Ashamedlol @Unstoppablee Have your raids by any chance had an affliction warlock present?

**Comment by fvicaria** [comment] 2018-03-29 07:53
Reverted last changes. Please re-check in dev.

**Comment by Dranah** [comment] 2018-03-29 16:58
do you mean you reverted the revertion of fixes?

**Comment by Keader** [comment] 2018-06-24 20:55
Until i have full code access, is impossible fix it :/

**Closed by Keader** 2018-06-24 20:55 UTC
Labels: Won't Fix (at this point)
