### ISSUE TITLE
[Spell] Power word shield 

### ISSUE THREAD

**Issue by Nephylia** [WoWManiaUK/Redemption#1487] opened 2017-08-13 20:38 UTC
So after reporting this issue for 3 times now the Discipline Priest shields are still not fixed. The issue is the following one: If the damage is more then the shield's absorb(or left absorb) the shield will disappear without absorbing anything, This is a major issue which makes Discipline priest COMPLETELY useless and not playable in PVE. For me as mainly Disc player it is making this server unplayable atm.

**Comment by tvshadowz** [comment] 2017-08-13 20:43
Hi there Nephylia, sorry you've reported this issue 3 times but it may be because you're reporting the bug incorrectly. Pleaae follow the steps below to help our testers and devs out as much as possible!

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ .

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)

**Comment by Nephylia** [comment] 2017-08-13 20:46
the last 2 times i reported this correctly with all links and whatsoever, now i CBA doing it over and over cuz people can't fix that simple fix WHILE marking it  as "FIXED". First of all don't mark stuff as Fixed while it's not.

**Comment by Braytonx** [comment] 2017-08-13 20:49
first report: https://github.com/WoWManiaUK/Redemption/issues/1278
second report: https://github.com/WoWManiaUK/Redemption/issues/1287

**Comment by tvshadowz** [comment] 2017-08-13 20:55
We can only apologise for the inconveinence Nephylia but unfortunately I was not around at the time of your last reports. However, now I am here I can do my best in testing and fixing the issue at hand which does require your cooperation. This does also I mean I did not close any of the previous issues made about this bug. 

I can say I will put it on my head that in coming days I will test this bug and attempt to identify a fix asap. Could you link any spells, talents etc here no matter the source (e.g wowhead) and I'll make sure to make this my priority. 

Thanks! Sorry for the inconveinence.

**Comment by Nephylia** [comment] 2017-08-13 20:58
exactly, thank you for the link. and if you want that this way, please:
http://www.wow-mania.com/armory/?spell=48066 PW:S Formula: (2230+(SPx(0,8068+0,4)))x1,05x1,04x1,15 (i won't link wowhead since there are no wotlk PW:S)
What it supposed to do: After shielded it supposed to absorb every incoming damage untill the absorbing amount is gone.
What it is currently doing:  If the damage is more then the shield's absorb(or left absorb) the shield will disappear without absorbing anything

**Comment by tvshadowz** [comment] 2017-08-13 21:04
That's fab, thank your for your coopeeration :D 

I wont be back until tuesday but as soon as I'm back I will be testing this issue and identifying a fix for this issue if it is identified. Thank you again for your cooperation :)

**Comment by Nephylia** [comment] 2017-08-13 21:30
Ye np, btw it is not about the ICC buff, that was the first thing which i assumed when i created those 2 reports. But the issue persists everywhere not only in icc. Like on our 25hc halion run today the shields didn'T absorb any of the Breath damage on tank.

**Comment by tvshadowz** [comment] 2017-08-13 21:37
Ah okay that's brilliant, the more information you can give about the issue the better! 

Obviously when I'm back home I'll assess each report made along with all information given whilst testing :)

**Comment by Forrestxz** [comment] 2017-08-15 11:28
Confirmed, multiple posts seen by Janitor as well.

@fvicaria Will have to deal with it himself, this is a greater issue than just a random Disc priest bug, it's absorbs in general.

**Comment by tvshadowz** [comment] 2017-08-15 21:41
I will be testing this issue tonight to observe the full extent of the bug. I understand that the bug has been seen before in previous posts however I will be making sure the issue has been made aware to it's full extent.

**Comment by Nephylia** [comment] 2017-08-17 22:16
what does "fixed confirmed in dev" mean? is it fixed now?

**Comment by keidian** [comment] 2017-08-18 07:00
It is not yet fixed, we are still tweaking.

**Comment by tvshadowz** [comment] 2017-08-18 19:50
Update 180/08/17 20:49

The shield is absorbing magic damage but disappears if the magic damage is more than the shield limit.

**Comment by tvshadowz** [comment] 2017-08-18 20:12
Update 18/08/17 21:09

In the case of magic damage: The shield only absorbs as much as the spell power gives no matter how much damage is done. 

For example if you have no gear then the shield will only absorb around 200 damage but with gear it will absorb around 2,000. 

This should be much more as the base amount absorbed by the shield is around 2,5-3k. 

This would mean that the shield itself is absorbing no magical damage whats so ever.

**Comment by Nephylia** [comment] 2017-08-21 09:08
btw here is the correct formula for the shield absorb: (2230+(SPx(0,8068+0,4)))x1,05x1,04x1,15

**Comment by forrestxyz** [comment] 2017-08-21 11:58
The main issue we experienced right at start before any of the fixes was that:

- If the damage of the hit/spell is larger than the shield, it bypasses the shield completely not making it absorb anything and destroying the shield.

Example:

- Shield absorbing for 6k, I take a 7k hit. My health drops for 7k, shield is gone.
- Shield absorbing for 6k. I take a 2k hit (4k left on shield). I take a 5k hit afterwards, shield is gone completely without absorbing anything else.

**Comment by tvshadowz** [comment] 2017-08-21 12:01
Yes this is already known, 

Thanks! :)

**Comment by keidian** [comment] 2017-08-23 11:19
![wowscrnshot_082317_131802](https://user-images.githubusercontent.com/11052609/29613292-a1ea85d6-8805-11e7-9aa4-25a160e48ad1.jpg)
Fixed and will be closed as soon as implemented

**Closed** 2017-08-25 11:03 UTC
Labels: Confirmed, Fixed Confirmed in Dev
