### ISSUE TITLE
[Ulduar - Yogg-Saron] Laughing Skulls + Constrictor Tentacle targetting

### ISSUE THREAD

**Issue by Midnaa** [WoWManiaUK/Redemption#2179] opened 2018-02-01 16:37 UTC
**Laughing Skulls**

**How it should work:**
- There is 9(?) possible spawn locations for laughing skulls in all of the 3 brain rooms and the boss should select 3 random locations for the skulls to spawn 

**How it does work** 
- All 9 possible spawn locations are used and they are doubled too. So when you enter the according brain room you have all 9 spawn locations + 2 on the same location because for some reason they're being doubled so there's a total of 18 skulls instead of 3 per room.

Might be worth mentioning that the Influence tentacles that spawn during the brain phase are also double spawned

Ensidia Retail video of the stormwind room: https://www.youtube.com/watch?v=Pf4MAONG1vs&t=7m30s You can see there's only  3 skulls active for any possible room.

**Constrictor **Tentacles****

**How it should work:**

- Constrictor Tentacles should only be able to target people who are "upstairs" on the encounter platform

**How it does work**
- They can grab people inside the brain room and that shouldn't happen.

**Comment by Keader** [comment] 2018-02-02 14:05
Partial wrong Midnaa.
You are correct, has more skulls that should.
But only Stormwind keep has 3 skulls.
Chambers and ICC has 4 skulls in random locations

**Comment by Keader** [comment] 2018-02-02 14:45
Laughing Skull - Fixed
Checking tentacles stuff now

**Comment by Midnaa** [comment] 2018-02-02 17:16
The double spawn is fixed too?

**Comment by Keader** [comment] 2018-02-02 17:54
I dont saw it lul
Well, i will put fixed label, because all other bugs is fixed.
This double spawns in tentacles i will fix tonight.

**Comment by Midnaa** [comment] 2018-02-02 20:59
The double spawn also applied to the skulls btw, so when you look at one you take 2 ticks at the same time and loose double the sanity

**Comment by Keader** [comment] 2018-02-02 22:44
Yeah, skull is ready (sql passed to janitor)
doing now tentacles

**Comment by Keader** [comment] 2018-02-02 23:13
Tentacles reviewed, number is correct.

**Comment by Midnaa** [comment] 2018-02-06 17:28
- Currently no Skulls in brain room 
- Constrictors are fixed 
- Influence tentacles are still spawned twice ontop of each other 
- https://gyazo.com/5cf4dce426490d794a8b975e25e05423 Spell 62714 shouldn't miss Sara ever if in melee range

**Comment by Keader** [comment] 2018-02-07 00:00
Skulls fixed (was a typo in sql haha)
 Influence tentacles i will check tomorrow (i cant login in PTR DB now o.o)
No miss spell i cant confirm, has no attr that make it.
Death Ray i need confirm in sniffs.

**Comment by Midnaa** [comment] 2018-02-07 12:08
- Judging by retail https://www.youtube.com/watch?v=Pf4MAONG1vs&t=4m40s the spawndist should be around 10 yards although it won't matter much wether if its 10,15 or 20 yards but right now its only 1 yard
- Shadow Nova should never miss, no retail video ever shows a guardian dying and sara not taking damage. https://www.youtube.com/watch?v=Pf4MAONG1vs&t=50s this video shows it, while the miss chance on dev is quite high, you get around 2-3 guardians that don't do damage during tests

**Comment by Keader** [comment] 2018-02-07 12:10
Again, 1 spell can never miss IF has some attr to garant it. Shadow nova dont has it.
Checked in sniff, spawn just looks like 15~20 yards, already changed it.
Influence tentacles fixed too.
And still waiting janitor build to try reproduce issue related with double spawns of tentacles

**Comment by Keader** [comment] 2018-02-07 12:55
Double npc summon fixed too.
Ready to test after Janitor restart server :)

**Comment by Midnaa** [comment] 2018-02-07 15:19
- Double spawned skulls and Infleunce tentacles are fixed 
- All brain rooms work now 
- Green lasers stopped working, only the indicator spawns and then they disappear https://gyazo.com/6099b74df7bc9df26d7294838ee92d62

**Comment by Dranah** [comment] 2018-02-09 14:25
UPDATE:
- green lazers work again but they are almost static (barely move)
- shadow nova damage misbehaves: I never saw it actually "miss" (no sign of miss on display), but Sara simply takes no damage while I saw other nearby player take double the intended damage (50k instead of 25)

**Closed** 2018-02-10 10:10 UTC
Labels: Fix Confirmed in Dev, Fixed in Dev
