### ISSUE TITLE
[Quest] ID : 12915 / Mending Fences, faulty summoned dwarves

### ISSUE THREAD

**Issue by Tolkinz** [WoWManiaUK/Redemption#5821] opened 2022-05-17 05:07 UTC
Links: https://www.wow-mania.com/armory/?quest=12915
My Own Play links : https://youtu.be/JGZHtNj-ENI

What is Happening: 
Summoned Dwarves pretty weak and useless, they don't hold agro at all and summoned number seems to be wrong too
In the YouTube video, 4 dwarves summoned and they hold agro all the time so DPS can put free dps to the target.

What Should happen: 
This should be going like this : https://www.youtube.com/watch?v=Yvp-imxsS7c
(from 2:09, the rest is useless cuz this man kills without support of summoned dwarves)

- Tank toons can still solo this, eg. pally/Dk, didn't try this with a warrior yet but guess also fine.
- a melee dps toon like this rogue, has no heal, armor pretty squish, has a very hard time waiting for CD skills to go for next one.
- This is a solo quest, making a group with a toon not-having the quest does not solve the challenge because non-quest toon can not see the quest object & quest-doing toon. I tried and verified.

**Comment by Echinaceax** [comment] 2022-05-18 14:02
Confirmed a few issues 

- [ ] The summoned Earthen Ironbane NPCs to help are only spawning 2 and not 6
https://www.wowhead.com/spell=55818/hurl-boulder as seen in seen here from timestamp 2:14 https://www.youtube.com/watch?v=Yvp-imxsS7c

- [ ] Summoned Earthen Ironbane NPCs should be spawned at the targeted enemy and not players feet 
- [ ] 1 of the Summoned Earthen Ironbane NPCs has range attack issue 
https://i.gyazo.com/dc78bf7a056104be284d1b8c07fa7387.mp4

**Comment by Echinaceax** [comment] 2022-05-19 20:14
confirmed fixed in PTR 

https://i.gyazo.com/993195c69683e01c598f84a3c0e99f24.mp4

Note: that it is random how many Earthen Ironbane NPCs are spawned, so 1 - 6 CAN be spawned (its the luck of the draw

**Comment by Tolkinz** [comment] 2022-05-20 04:02
@Echinaceax 

I am not sure if we really have to rely on RNG.
Furthermore, aggro issue seems to be still there. 
Aggro is for individual units, not the sum of 1-6 minions, I assume, maybe I am wrong. 
Can you test it a bit more to see if more than 4 units can hold aggro?

** so we should be facing one on one if units are spawned less, right? that's pretty scary.

**Comment by mfranca0009** [comment] 2022-05-20 05:01
@Tolkinz 
How do you expect them to hold aggro when they only perform auto-attacks (200 - 300 damage) and they have no abilities attached to them; it's not possible. It is possible for them to grab initial aggro, but other than that they will only assist with small amounts of damage. Also, we are not referring to the "aggro being improved" based on RNG of multiple `Earthen Ironbane` NPCs being spawned, we corrected this because there are statements from the WoTLK patch stating that it had a random chance to spawn a different amount each time. At this time, there is no information on their correct melee damage amount from any source that we were able to see; therefore we cannot confirm with accuracy what their melee damage range should be.

Also, these changes are only applied to PTR at the moment and have not been released to live yet.

**Comment by Tolkinz** [comment] 2022-05-20 05:08
@mfranca0009 

glad you see my comment!

While re-reading the linked wowhead page, I found the following mention.
Would this be a reference?

![iron dwarves](https://user-images.githubusercontent.com/105026618/169454716-346a5c4e-693e-49d8-9517-27faf3be29b9.png)

**Comment by mfranca0009** [comment] 2022-05-20 05:14
@Tolkinz 
While this source claims they taunt, I would need proof of what actual spell is being used by them. From WoWhead, they do not have abilities listed and with that we assume they don't use any.

If you find a spell, and a direct reference of it being linked to that NPC; then we can surely add it.

**Comment by Tolkinz** [comment] 2022-05-20 05:23
@mfranca0009 

Link : https://www.wowhead.com/npc=29927/earthen-ironbane

Beside autoattack, it does seem like it has two skills TAUNT & WOUND, although how much threat or damage they do isn't specified.  Sound file name proves it.

**Comment by mfranca0009** [comment] 2022-05-20 06:52
@Tolkinz
That’s not how sound IDs work. As I said, if you can find a link to an actual spell ID for the NPC then it can be changed; stays as-is. Thanks for the initial issue report.

**Comment by Tolkinz** [comment] 2022-05-20 07:17
ok then, how about this?

https://github.com/TrinityCore/TrinityCore/issues/16683

all I’m saying is that something is still wrong

**Comment by Echinaceax** [comment] 2022-05-20 09:37
> all I’m saying is that something is still wrong

We know your OP post was relating to the trouble holding aggro, We researched a lot on this, 
Note though, Any fixed/closed reports can be reopened once new info comes in that helps the devs.

The dev isnt the one that needs to do the research but he did, its up to the reporter to gather all info for the dev to fix, then the testers confirm your info is correct

**Closed** 2022-05-21 10:32 UTC
Labels: Fixed on PTR - Tester Confirmed

**Comment by Greywolf59** [comment] 2023-12-13 14:20
Threat issue: still there. It indeed looks like the dwarves can taunt/hold aggro:
8y old ideo lvl 78. prot pala in Defensive Stance: Earthen Ironbane 3:13 - 3:27 https://www.youtube.com/watch?v=rGI8mceolWk&ab_channel=GameGuides

8y old video, visible yell from the Earthen at 2:15 - 2:18 https://www.youtube.com/watch?v=Yvp-imxsS7c&ab_channel=GitGudGuides

wotlk classic lvl 78 feral getting aggro and earthen taking it back https://www.youtube.com/watch?v=Yvp-imxsS7c&ab_channel=GitGudGuides

Admittedly I have seen some other wotlk classic videos where I cannot find the trace of Earthen using any taunt or holding aggro much.
As to Taunt spell itself I cannot find anything in databases, however considering Taunts, databases are usually a bit messy, even the official ones.
Other than that there is indirect evidence that taunt is mentioned in a few of the wowhead comments and on wowpedia while on the other hand there are no comments of players coming there to comment about them being unable to do the quest due to dying as clothie since the dwarves can't hold aggro.
Hard to find any definite answer to this issue.
