### ISSUE TITLE
[Item] Fragment of Val'anyr

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#4060] opened 2020-01-25 12:59 UTC
**Links:**
https://wow.gamepedia.com/index.php?title=Fragment_of_Val%27anyr&oldid=2128376

**What is Happening:**
It does not exist in the loot table for:

- General Vezax
- Yogg-Saron
- Rare Cache of Winter
- XT Normal Mode

**What Should happen:**
Going off the chances above I have added this:

- General Vezax 8%
- Yogg-Saron 100%
- Rare Cache of Winter 20%

**Comment by Dranah** [comment] 2020-01-26 11:57
Ok, i've finally had time to do the necessary tests and research on this:

1) Yogg indeed has a guaranteed 100% drop chance on wotlk.
Wowhead states an average 70% drop chance but the reason for that is blizz changing it for a while towards the end of MOP, at which point people begin reporting not getting a shard from yogg at times and screwing up the statistics on wowhead.
2) Many sources confirm an increased chance for the drop on hard mode keepers, council and vezax. This means the normal mode boss has a 5-10%ish chance depending on boss (like the one Kitz just added to Vezax) for drop on 25man, but on hard mode it is around 15-20%. (This does not apply to Flame Leviathan and XT hard modes). Sources confirm Algalon has slightly higher than the others, up to 24%ish.
3) Most sources agree that non-hardmode bosses have a 5-10%ish drop at average, with keepers getting fairly the higher end of it. While wowhead states extremely low drops from certain caches for keepers, this is due to wowhead having merged the cache loot for 10man and 25man kills. This is the case for Freya for example, who has 4% chance stated for her cache and it does have a 4% drop on mania right now, but this is incorrect value. Fairly 2/3 of reported data comes at average from 10man kills, so it is safe to calculate the 25man drop to be around 9-10%.

So based on the wowhead drop rates and other sources, comments, reports and calculations, the grand picture should look something like this (on 25man, of course)
                          Normal                   Hard Mode
Flame Levi:           8-9%                          8-9%
Razorscale:             5%                             -
Ignis:                     7%                              -
XT:                        9-10%                        9-10%
Kologarn:              8-9%                           -
Council:                7-8%                          14-15%
Auriaya:                 6%                              -
Freya:                    9-10%                       16-18%
Hodir:                    9-10%                       16-18% (both caches can drop at the same time!)
Thorim:                  9-10%                       16-18%
Mimiron:                9-10%                       16-18%
Vezax:                     7-8%                         14-15%
Yogg:                     100%                           100%
Algalon:                    -                               20-24%

Statistically this means:
- each full run is guaranteed 1 fragment (yogg) and there is a chance if you're unlucky that it will be your only fragment in that run
- on average you will receive 2-3 fragments per run, one from yogg, and one or two from other bosses depending on your luck
- if you do hard modes for the increased drop chance, it can get as high as 4-5 shards per run, maybe 6 if extremely lucky (such as both of Hodir's chests dropping one)
These statistics are confirmed by player reports and comments as well. Nobody has reported getting more than 6 fragments in one run and that is also fairly rare.

Based on my current tests, the numbers still need a bit of tweaking.

- Yogg guaranteed chance is fix-confirmed. (fixed)
- Vezax normal mode confirmed to have his 8%ish drop now. (fixed)
- Other values need to be corrected based on my chart (such as for keepers caches, and hard mode increases). (need fixing)

@Kitzunu if you could re-check all values i'd appreciate.

**Comment by Kitzunu** [comment] 2020-01-26 12:14
On it

**Closed** 2020-01-28 10:19 UTC
Labels: Confirmed, Fixed in Dev, Test in Progress
