### ISSUE TITLE
Mage - Fireball getting interrupted

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2346] opened 2018-03-18 17:53 UTC
Not sure exactly what's causing this, but Fireball gets interrupted for no reason from time to time.

It seems to happen on Hot Streak procs from Living Bombs mostly, but that might just be a coincidence and not the actual cause...

https://youtu.be/WxmLC7UosgQ (short clip where this happens)

Links:
http://wow-mania.com/armory/?spell=44445
http://wow-mania.com/armory/?spell=42833
http://wow-mania.com/armory/?spell=44457

**Comment by Dranah** [comment] 2018-03-19 10:59
I can't reproduce this using Hot Streak in any form, by living bomb, pyros or other fireballs at all. I need a list of procs and effects that are active on you when this thing happens.

**Comment by Zunrin** [comment] 2018-03-19 11:17
Yeah I was going to do some more testing on dev, but it was down all evening yesterday

**Comment by Keader** [comment] 2018-03-19 12:03
I cant reproduce it too.

**Comment by Zunrin** [comment] 2018-03-19 12:10
I think I found exactly what the conditions are for this to happen:
- have the tier 10 2piece set bonus (Pushing the Limits) active, and be buffed by it
- have a pyroblast traveling to your target
- get a hot streak proc

When those conditions are met, you get interrupted.

(link to the pushing the limits buff, the other spells are higher up: http://www.wow-mania.com/armory/?spell=70753)

**Comment by Zunrin** [comment] 2018-03-19 12:31
After a bit more testing, the cast is interrupted when the Pyroblast lands.

So the conditions seem to be landing a pyroblast on your target while you have a hot streak proc and pushing the limits buff.

**Comment by Keader** [comment] 2018-03-19 13:09
Thanks @Zunrin  and @TheManiax to help with tests.
Fixed by me, tested by @Zunrin  and working in Dev.

**Closed** 2018-03-19 13:36 UTC
Labels: Confirmed, Fix Confirmed in Dev
