### ISSUE TITLE
[Quest] Rifle the Bodies [12000]

### ISSUE THREAD

**Issue by 0p3ngl** [WoWManiaUK/Redemption#3298] opened 2019-05-28 12:45 UTC
**Links:**
http://www.wow-mania.com/armory/?quest=12000
[The page for the quest on WoWWiki for a reference that has not changed since 2010](https://wowwiki.fandom.com/wiki/Quest:Rifle_the_Bodies_(Alliance))

**What is Happening:**
The quest is scripted to require the short breadcrumb chain [A Disturbance In The West](http://www.wow-mania.com/armory/?quest=12439) and [To Stars' Rest!](http://www.wow-mania.com/armory/?quest=12440) to unlock it.

**What Should happen:**
The quest has 3 optional breadcrumbs (**none** should be required to get the quest). The optional breadcrumbs are:

[The Lost Courier](http://www.wow-mania.com/armory/?quest=12157) - obtained in Borean Tundea, leading you to Dragonblight
[A Disturbance In The West](http://www.wow-mania.com/armory/?quest=12439) and [To Stars' Rest!](http://www.wow-mania.com/armory/?quest=12440) - obtained in Howling Fjord, leading you to Dragonblight
[Your Presence is Required at Stars' Rest](http://www.wow-mania.com/armory/?quest=11995) - obtained in Moa'ki Harbor, leading you to the main Dragonblight quest chain if you arrived in the zone by turtle.

While the quest *should* require none of these to obtain it, requiring any of the three rather than a specific one would resolve the problem of the quest chain breaking completely for anyone who happens to complete the wrong quest.

Side note: It might be possible currently to do all 3 if you don't turn any of them in before you have them - I obtained them all on another character before encountering this issue. I completed [The Lost Courier](http://www.wow-mania.com/armory/?quest=12157) and [Your Presence is Required at Stars' Rest](http://www.wow-mania.com/armory/?quest=11995) on a character this time, finding myself locked out of the third breadcrumb option and unable to progress into the main Dragonblight quest chain.

**Comment by 0p3ngl** [comment] 2019-05-28 18:39
First, please allow me to apologize for the unintended offense of disallowed links. That is, of course, completely my fault for not realizing that the wow-mania web page actually had the full armory with all features. I don't know how I overlooked that, but I accept full responsibility for it.

I have updated all links to direct to the wow-mania armory links, aside from the one WoWWiki link - which is in no way affiliated with another server. Again, I apologize for that mistake - one which I will never again make.

Yes, the quests do work - just not the way that they should. The wow-mania armory shows this, by clearly showing that both quest 11995 (Your Presence is Requested at Stars' Rest) and 12440 (To Stars' Rest) unlock this quest. The fact that after completing the former preventing me both from doing the latter (as it should) and the quest at issue (which it should not - if anything, it should unlock it).

No disrespect or offense has been intended on my part at any step - I only wish to help resolve an issue with the quest chaining for the betterment of the server and all Alliance players. I would ask that my admittedly serious blunder not be a reason to forgo resolving this rather serious issue.

Thank you.

**Comment by Dranah** [comment] 2019-05-29 20:52
@0p3ngl I see alot of effort put into your report, it is nicely written - but it's very difficult to dig out what really the issue is. 
hint: wow-mania doesn't read anything longer than 3 lines

I can confirm this issue on the PTR, it indeed behaves this way right now. 

**How it should work**: quest 12000 should have no prerequisites to acquire, all quests that lead here are optional
**How it works atm:** the quest requires one of the breadcrumbs https://www.wowhead.com/quest=12440/to-stars-rest completed in order to pick up, however this quest can be closed by the other breadcrumb quests, making the player unable to pick up quest 12000

**Comment by Kitzunu** [comment] 2019-05-29 22:13
try now

**Comment by 0p3ngl** [comment] 2019-05-30 02:20
> @0p3ngl I see alot of effort put into your report, it is nicely written - but it's very difficult to dig out what really the issue is.
> hint: wow-mania doesn't read anything longer than 3 lines

Thank you very much for the kind words and consideration. I'll attempt to be more succinct in the future, contrary to my borderline-ocd need for clarity and detail. 
 
Thank you, also, for the example of how to do this with more brevity. I have a new character that is starting Northrend, so I shall indeed try it soon. Thank you greatly for the hard work.

**Comment by Dranah** [comment] 2019-05-30 04:43
@0p3ngl Anytime. Please keep in mind the fixes are only active on the PTR until the next update. You can expect it to be pushed to the live realm only when the thread on Github is close.

**Comment by Dranah** [comment] 2019-05-30 04:47
@Kitzunu there is no change. Still requires 12440 to obtain.

**Comment by wow-mania** [comment] 2019-05-30 07:30
![image](https://user-images.githubusercontent.com/12248683/58616278-31efc780-82b5-11e9-9d05-1c665a82aab4.png)

**Comment by 0p3ngl** [comment] 2019-05-30 08:22
![image](https://user-images.githubusercontent.com/51121720/58619212-0dcac100-828a-11e9-8720-c2fa3a68152e.png)

**Comment by 0p3ngl** [comment] 2019-05-30 08:50
Indeed, that one should also unlock it. As it is, it's set to only unlock with one of the other breadcrumbs.
![image](https://user-images.githubusercontent.com/51121720/58620968-f261b500-828d-11e9-866c-240e5e030a30.png)

**Comment by Dranah** [comment] 2019-05-30 16:24
I'm sorry but the armory is wrong, @wow-mania 
These "pre quests" are not meant to be mandatory. They are ALL optional breadcrumbs, none of them should be required to unlock quest 12000
This is from wowhead: https://www.wowhead.com/quest=12440/to-stars-rest#comments
"As long as you do not accept  Rifle the Bodies, you can do all of the intro quests leading to her."
"he never gave me the quest for some reason maybe i did a quest before hand that made this not show up"
= you can accept rifle the bodies without having done any of the breadcrumbs, and doing the quest will close the breadcrumbs
There is no way in hell "to stars rest" would be intendedly required to pick it up.
PS: EVERY single video on youtube shows players just walk into stars rest and picking up 12000 without handing in any kind of prerequisite. The quest is simply available to anyone who walk there.

**Comment by wow-mania** [comment] 2019-05-30 16:35
This will be like this. Last time I am closing. 
There is one specific path for it.
Just do it.

**Comment by Dranah** [comment] 2019-05-30 19:24
@wow-mania how is he supposed to do it when the quest he must complete is LOCKED?
How are players supposed to know that completing the wrong pre quest will block them from ever being able to obtain this?
How is this anyhow intended?
This quest SHOULD NOT HAVE ANY REQUIREMENTS TO OBTAIN. Why does it have any?

**Comment by Kitzunu** [comment] 2019-05-30 20:56
Fixed

**Comment by Dranah** [comment] 2019-05-30 21:02
You can now obtain Rifle the Bodies without prerequirements. As intended.

**Closed** 2019-06-03 11:22 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev
