### ISSUE TITLE
Deathbringer Revenant Respawn Rate

### ISSUE THREAD

**Issue by Ziogas77** [WoWManiaUK/Redemption#5541] opened 2021-06-20 20:06 UTC
**Links:** https://www.wowhead.com/npc=27382/deathbringer-revenant#comments

**What is Happening:** Deathbringer Revenants aren't respawning fast enough. It is a popular farming spot for crystalized shadow.

**What Should happen:** Deathbringer Revenant respawn rate should be fast enough for there to always be 4 revenants at all times.

**Comment by Ziogas77** [comment] 2021-06-20 20:06
*Puts on fake moustache* "-He's got a point!"

**Comment by Rushor** [comment] 2021-06-20 20:43
okay checking :)

**Comment by hawker357** [comment] 2021-06-29 11:41
From testing a looted Revenant corpse will despawn after approx 60 seconds, and an unlooted corpse will despawn after approx 120 seconds.

From the time of corpse despawn, looted Revenant took 180 seconds to respawn, and I was unable to confirm the unlooted Revenant because of the 5 min timer of WG on test realm.

Looted corpse after ~10 seconds
![Screenshot (92)](https://user-images.githubusercontent.com/79724094/123791241-1cf02300-d8d7-11eb-85fb-5781eb4dfa08.png)
Looted corpse despawn
![Screenshot (94)](https://user-images.githubusercontent.com/79724094/123791246-1eb9e680-d8d7-11eb-9eb0-77c2bf5c3602.png)
Unlooted corpse despawn
![Screenshot (95)](https://user-images.githubusercontent.com/79724094/123791249-1f527d00-d8d7-11eb-9f2d-a835ea261ade.png)
Looted Revenant spawn
![Screenshot (96)](https://user-images.githubusercontent.com/79724094/123791253-1feb1380-d8d7-11eb-9ff3-d03545011394.png)

**Comment by Rushor** [comment] 2021-06-29 12:24
will reduce despawn and respawn timer for them

**Comment by Rushor** [comment] 2021-06-29 14:42
shortened timers even more now

**Comment by hawker357** [comment] 2021-06-29 16:01
It appears I got myself confused with what mob exactly needed testing. Respawn time is currently 20-30 seconds, I advise putting that back up a bit to avoid abuse. Maybe match the respawn rate of https://www.wowhead.com/npc=30450/wailing-winds or https://www.wowhead.com/npc=29504/seething-revenant. As they are similar mobs.

**Comment by Rushor** [comment] 2021-06-30 09:10
it's fine as said in the wowhead comments, they should respawn really fast

**Comment by hawker357** [comment] 2021-07-12 11:35
https://youtu.be/KrXfM3sp3-M

Respawn needs checking again, after the mobs are killed they spawn for a short time, then despawn and respawn permanently.

**Comment by Rushor** [comment] 2021-07-14 11:51
was tiny script issue, should be fixed now

**Comment by hawker357** [comment] 2021-07-15 14:19
To clarify, expected behaviour:
Should respawn after 20-30 seconds, and should not randomly despawn.

**Comment by SolyFromTexas** [comment] 2021-07-15 15:21
hello Eltes here (one of the testers) the respawn rate seems to be at around 34 seconds now
![WoWScrnShot_071521_081955](https://user-images.githubusercontent.com/71337969/125813611-dd696ba7-5b50-41b9-b410-ba88c0a053e3.jpg)

**Comment by hawker357** [comment] 2021-07-15 15:23
Was that 34 seconds from kill or from loot?

**Comment by SolyFromTexas** [comment] 2021-07-15 15:24
> Was that 34 seconds from kill or from loot?

From loot

**Comment by hawker357** [comment] 2021-07-15 15:24
That's about right then, the respawn timer starts as soon as it dies

**Comment by SolyFromTexas** [comment] 2021-07-15 15:25
alright sweet

**Comment by hawker357** [comment] 2021-07-15 15:26
As seen in the youtube video I posted, it was randomly despawning. That was the latest fix

**Comment by SolyFromTexas** [comment] 2021-07-15 15:40
Alright After testing to see if they would despawn randomly (both alive and dead) and they seem to be ok

**Closed** 2021-07-24 07:08 UTC
Labels: Fixed on PTR - Tester Confirmed, Regression
