### ISSUE TITLE
[Raid] Zul Aman door closes after a wipe

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5740] opened 2022-03-05 10:39 UTC
**Links:**
Gong trigger: https://tbc.wowhead.com/npc=25173/zulaman-door-trigger
NO clue what links to add

**What is Happening:**
Yesterday we wiped on the third Boss, the firehawk one (some bombs were kinda misplaced on fence and in firewall so hardly visible). When we released and entered ZA, we have found the door opened by gong closed forever.

**What Should happen:**
I supposed the door should stay open wipe or not.
EDIT: Today, after +-12 hours the doors can be reopened via talking to NPC and banging the gong. Havent seen the NPC last night, maybe it has some long respawn timer?

**Comment by jeyrella** [comment] 2022-03-05 10:45
Not sure we can even being to pinpoint this one, this is the first time we heard this one in years so may be one of those spurious "bad luck combination" issues that we have to close.  i.e. we will need to reproduce this to fix.

If there are confirmed issues with another event/raid, please log in a separate ticket rather than muddying this one.

Not current content and dev branch is full so this one goes on back burner for a while.

**Comment by Greywolf59** [comment] 2022-03-05 10:47
as EDIT: today it is openable by talking to the NPC again. but right after the wipe it wasn't.

**Comment by jeyrella** [comment] 2022-03-05 10:55
Door should stay open for the remainder of that lockout. Should not be closed unless the lockout has reset.  Can you check if your raid lockout ID reset please?

**Comment by Greywolf59** [comment] 2022-03-05 10:56
Lol it did. It is expired, yea.

**Comment by jeyrella** [comment] 2022-03-06 20:05
closing for now as can't reproduce.  if it becomes a common issue, will reopen

**Closed by jeyrella** 2022-03-06 20:05 UTC
Labels: Priority - Low

**Comment by Greywolf59** [comment] 2022-03-08 13:45
New thingie: door closed on us while we were inside. Either after wipe on flame boss (like last time) pr after wiping on lynx boss. We used Divine Intervention each time to ress the dead without anyone having to release and run in. Haven't checked the ID and it is too late now.
