### ISSUE TITLE
[Quest] Orabus the Helmsman not appearing.

### ISSUE THREAD

**Issue by Frejavestergaard** [WoWManiaUK/Redemption#4720] opened 2020-07-01 16:48 UTC
http://www.wow-mania.com/armory?quest=11661

What is happening: Orabus isn't spawning when using the quest item.

What should happen: Orabus should spawn when using the quest item as shown here:
https://www.youtube.com/watch?v=eGsEu1rPcOU

**Comment by wow-mania** [comment] 2020-07-01 16:51
Pretty sure it works. 
Can someone check this on ptr, please?

**Comment by Zanguin-ManiaTester** [comment] 2020-07-01 16:55
on it, hang on 2 min

**Comment by Zanguin-ManiaTester** [comment] 2020-07-01 16:57
https://youtu.be/m3z-UaTYmMc

Confirmed not working. No ship has appeared, not even after all the time spent uploading this video and comment.

**Comment by Zanguin-ManiaTester** [comment] 2020-07-01 17:12
Got some more intel on the bug, hang on;: uploading video

**Comment by Zanguin-ManiaTester** [comment] 2020-07-01 17:13
https://youtu.be/KaREus1xUhk

ship spawns, sinks with no NPC's present.

**Comment by jeyrella** [comment] 2020-07-01 19:14
I would be tempted to say this is regression of some kind since I have completed this fine on 2 toons on live.

**Comment by Rushor** [comment] 2020-07-02 06:29
the whole event must be scripted from scratch i think - all the movement and spawns were missing since today

**Comment by Rushor** [comment] 2020-07-02 07:10
whole event fixed with all details https://i.imgur.com/V4NrkwF.jpg

small thing: creatures are stacked visualla once boat reaches the final path, but that is only tiny cosmetic detail, that can be ignored.

**Comment by Zanguin-ManiaTester** [comment] 2020-07-02 11:58
https://youtu.be/K9SkyhRgE_4

Fix confirmed : Quest is functional now, thanks!

**Closed** 2020-07-07 09:15 UTC
Labels: Fix - Tester Confirmed
