### ISSUE TITLE
[Race] Worgen and reputation tab

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#2064] opened 2018-01-09 18:15 UTC
I write this ticket upon the advice of a GM.

I have a worgen druid character now lvl 80.
The problem I'm facing is that I do not see some factions
1. in my reputation tab (ex. Kirin Tor, both Cenarion factions, ...)
2. in the tooltips of some NPC (in moonglade for example, the NPC have no faction when seen with this character)

However, I gain reputation for these factions as usual.

The problem is I don't know at which level I am.

None of the other characters of this account have this problem. This is the only Worgen I have.

Thus, I do not know if it's a character specific issue or a Worgen issue.

**Comment by squalllh1989** [comment] 2018-01-10 06:15
ok, first, i make a test on dev, and can see the rep normally on my worgen character
![wowscrnshot_011018_125114](https://user-images.githubusercontent.com/27235989/34758009-9ab9abaa-f607-11e7-8eb3-379b29ab05ee.jpg)
![wowscrnshot_011018_125254](https://user-images.githubusercontent.com/27235989/34758010-9cd0a8c6-f607-11e7-8ea8-2f6eefd28d66.jpg)
![wowscrnshot_011018_125438](https://user-images.githubusercontent.com/27235989/34758013-9ea15f7e-f607-11e7-9dcd-91816cfdb785.jpg)
I also check it on a goblin, since they are an imported race also, and it also display normally
![wowscrnshot_011018_131105](https://user-images.githubusercontent.com/27235989/34758069-ead2b064-f607-11e7-972f-9d0106557369.jpg)
![wowscrnshot_011018_131152](https://user-images.githubusercontent.com/27235989/34758072-ec148592-f607-11e7-974c-118649ef0d71.jpg)

But, later on, in a rdf hc, i meet a worgen, so i decide to ask him if his reputation with the kirintor display normally, and his answer is not.
![wowscrnshot_011018_130851](https://user-images.githubusercontent.com/27235989/34758149-4e7684b0-f608-11e7-813b-495f73c97b7f.jpg)
![wowscrnshot_011018_130909](https://user-images.githubusercontent.com/27235989/34758150-506f0bac-f608-11e7-9ff4-d5c06bb5fd02.jpg)
That's the information i tested and gathered, hope this will help.

**Comment by fvicaria** [comment] 2018-01-10 10:25
So the issue it not Worgen and is not something that always happens.
We need steps to reproduce so we can try to fix it.

**Comment by Hajzlopuc** [comment] 2018-01-10 10:47
I have checked on my characters.

_Worgen Druid_
I don't even see this guy reputation (should be Kirin Tor) in tooltip and also can't find it in a reputation tab
https://puu.sh/yYeSf/3404f57daa.png

I see the reputation on the tooltip for this guy (Keepers of Time) but it's nowhere to be found in reputation tab. (And I am pretty sure I have 'touched' many more Outland reps)
https://puu.sh/yYeSD/3ba0f24303.png

_Draenei Shaman_
This is how it should look like.
I see the reputation in tooltip and also see it in a rep tab.
https://puu.sh/yYeSP/6715a8ed5c.png
https://puu.sh/yYeSZ/ecb6f08937.png

**Comment by fvicaria** [comment] 2018-01-10 11:05
OK so the clue to the issue may be the boost.

**Comment by Hajzlopuc** [comment] 2018-01-10 16:40
I wouldn't say so. I have found something more. 
**(im still editing this post, adding screenshots)**

**Comment by fvicaria** [comment] 2018-01-12 12:18
Fixed in dev. Needs confirming.
This will require a client update.

**Closed** 2018-01-15 10:06 UTC
Labels: Fixed in Dev

**Comment by lastbullet00** [comment] 2018-01-30 15:39
This issue is up again, it can be seen i got Kirin Tor reputation but no bar for the faction in reputation tab.
![image](https://user-images.githubusercontent.com/34487562/35575220-824aa226-05e4-11e8-9c08-e45fc6b661b0.png)
