### ISSUE TITLE
[Item] Ephemeral Snowflake

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1393] opened 2017-07-17 17:44 UTC
this item (http://www.wowhead.com/item=50260/ephemeral-snowflake) is not working has how it should be.
- How it suppose to work: you gain 11 mana EACH time you heal some one, every tick of heal over time counted, for example: wildgrowth (http://www.wowhead.com/spell=48438/wild-growth) with glyph gives 6 targets a hot which ticks every second for 7 seconds:
wildgrowth cast cost 643 mana, trinket returns: 6 * 11 mana = 66 mana per second for 7 second = 462 mana regen in total.

- How is it working right now: it only give you 11 mana for 1 time per target each fight, example: wildgrowth cast cost 643 mana, trinket return: 6 * 11 mana = 66 mana FOR ONLY 1 TIMES, which result in only 66 mana regen in total.

**Comment by fvicaria** [comment] 2017-07-17 18:55
Please search before posting. 
Duplicate of #1345 


Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Closed by fvicaria** 2017-07-17 18:55 UTC
