### ISSUE TITLE
[Raid] High Priest Thekal leaves player in combat on death - Zul Gurub 

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5056] opened 2020-10-18 09:59 UTC
**Links:**
https://wow-mania.com/armory/?npc=14509

**What is Happening:**
Once [High Priest Thekal ](https://wow-mania.com/armory/?npc=14509) (and his spawns) are defeated, players are left in combat.
**What Should happen:**
Once High Priest Thekal (and his spawns) are defeated, players are not left in combat.

**Comment by jeyrella** [comment] 2021-01-08 20:03
@svijetlo could you re-test this one pls, got reports of it still leaving in combat

**Comment by Rushor** [comment] 2021-01-10 19:27
core function is still the same, so no core regression at least.

once big boss tiger is dead, all player get removed from threatlist.

maybe some kind of trigger or trashmob keeps them im combat?

**Comment by Rushor** [comment] 2021-01-15 19:34
i will add one last combat remove for that - more i cannot do

**Comment by Rushor** [comment] 2021-01-16 12:32
should be good now.

not a regression since code has not changed.

**Comment by Oganku** [comment] 2021-01-16 19:52
Still happening. I wanna say it has to do with Zealot Lor'Kan and Zealot Zath "following" the player, invisible and dead after the boss dies, but that's only a gut feeling. Reminds me of the nightmare of the Mimiron console years ago. I cannot say what would keep the player in combat otherwise. It gets cleared on his death, but as soon as you engage any other enemy in the instance, you get stuck again (due to something invisible following you I suppose).

**Comment by Rushor** [comment] 2021-01-17 13:38
very good now i could reproduce it aswell!

**Comment by Rushor** [comment] 2021-01-17 15:02
now fixed!

the issue was that the adds were removed on death but the threat of them was not removed from the player and that keept them in combat

**Comment by Rushor** [comment] 2021-01-17 17:45
also fixed that the adds respawn after some time when boss is already defeated

**Comment by Oganku** [comment] 2021-01-17 19:51
Awesome! I knew the adds were acting up. Works wonderful now.

**Closed** 2021-01-19 10:59 UTC
Labels: Fixed on PTR - Tester Confirmed
