### ISSUE TITLE
[Core] Looting

### ISSUE THREAD

**Issue by muhabayern21** [WoWManiaUK/Redemption#927] opened 2017-03-07 10:29 UTC
I found a bug when i was doing some quests(i think that was for every1). When i am need to open some chests or some quest items, when it shows a "gear wheel" to open it indicates yellow colour if you are close enough. But when you are the most far distance that indicates yellow colour (gear wheel)from that chest(quest item) it start casting but dont open that (you lose that quest item) and when you come closer to that chest (quest item) again try to open it says That item is currenty in use. I guess you need to reduce the distance that indicates yellow colour on "gear wheel" between player and chest. It isnt specific to some quest it is for all i quests i was doing(for any chest). Greetings!

**Comment by Enkiworks** [comment] 2017-03-07 14:49
I can confirm this has happened to me multiple times as well; I now make sure I'm closer to the quest item before clicking as a workaround. Also, a re-log will clear the issue with the "in use" quest item.

**Comment by Dragonfly414** [comment] 2017-03-08 05:52
This will also happen when you are one a mount and starts opening or mining... after dismounting you see the visual mining but dont get loot and you get the 'already in use'  sentice

**Comment by hotdoggidy** [comment] 2017-03-08 22:17
This is a known issue.
-Make sure when looting anything u stand AS CLOSE as possible.
-If you run into "item already in use", move AWAY from the item/box/node you are trying to loot.
-Keep moving away until it DESPAWNS from your view.
-When you move back into range again you will be able to loot it properly.
-ALWAYS make sure you are standing next to or ON the thing you are trying to loot.

**Comment by fvicaria** [comment] 2017-03-11 17:04
This issue should be fixed now. We reverted code due to the disconnection issue and it came back but now it should be ok. Please re-open if it becomes a problem again

**Closed by fvicaria** 2017-03-11 17:04 UTC
