### ISSUE TITLE
[NPC] Val'kyr Shadowguards (heroic)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4990] opened 2020-09-21 03:21 UTC
**Links:** http://www.wow-mania.com/armory?npc=36609

**What is Happening:** On heroic difficulty, both 10 and 25, Val'kyrs will often remain stuck at the location where they were pushed below 50% hp. They will not be attackable as their actual location is in air in the middle of the platform, but the visual remains and is in the way as the other Val'kyrs show up.

**What Should happen:** Val'kyrs should fly up to air and remain there, and the visuals should follow.

**Comment by fvicaria** [comment] 2020-09-21 07:16
If this is not confirmed independently by a tester we will close.

**Comment by svijetlo** [comment] 2020-09-21 09:34
close it pls fight work fine this i seen happne in 1 out of 5 kills and does not efect fight it self and it can make just bigger issues in long tearm

**Comment by bLeyaa** [comment] 2020-09-21 11:40
How can it make an issue long term, what are u talking about?

And yes it is an issue, when you are trying to target swap if you select the wrong one you are wasting time which may potentially cause people to be dropped if your valkyr cleave damage is not as good.

This IS a bug, its only your personal opinion that it should be closed because you think its fine.

**Comment by svijetlo** [comment] 2020-09-21 13:46
why would you target swap to valk that is 50% HP? 
get better UI or smt like that fight works fine and it is nick pick detail i leave it to janitor to decide as i never seen it mess up fight and it happens in 1 of 5 kills 
and to quote you valks is not attackable so now it is attackable  what are you talking abut ??' 
as i care fight works fine this is minor detail that can i do not say it will but can make other issues

**Comment by bLeyaa** [comment] 2020-09-21 14:10
It happens more often than in 1 out of 5 kills, at least in 25 man lmao

I haven't said once they're attackable, i said they're targetable.

Not to extend this argument, Janitor asked for this to be confirmed if correct or not, he didnt ask for opinions on it.

**Comment by svijetlo** [comment] 2020-09-21 14:16
as i care fight works fine 
for what you told read each of your posts and see =)
this is nick pick detail and janitor him self order that those should not be don any more if fight works i do it twice every week
i em not gona waste my time as you have personal issue with me 
other tester can do it, as for me it is fine 
and at the end it is janitor who will decide not me , not you not other testers or devs =)

**Comment by Oganku** [comment] 2020-09-21 15:25
The issue is valid, but it is minor. If janitor wishes to leave as-is, fine, but it still happens.

**Closed** 2020-09-22 09:25 UTC
