### ISSUE TITLE
[Talent] Lock and Load – procs from Frost trap on snare-immune target

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6231] opened 2024-05-16 14:32 UTC
[Lock and Load](https://www.wow-mania.com/armory/?spell=56344) is currently triggered by using [Frost Trap](https://www.wow-mania.com/armory/?spell=13809) on snare-immune target, aka raid boss.

On patch 3.2.0 Frost Trap was changed: Spell frost freezingbreath [[Frost Trap]](https://wowpedia.fandom.com/wiki/Frost_Trap): Will no longer "fizzle" on targets immune to snare effects, however Ability hunter lockandload [[Lock and Load]](https://wowpedia.fandom.com/wiki/Lock_and_Load) will not succeed when using Frost Trap if the target is immune to snare effects.

https://wowpedia.fandom.com/wiki/Lock_and_Load?so=search
https://wowpedia.fandom.com/wiki/Patch_3.2.0

**Comment by Maine1** [comment] 2024-07-21 13:09
Revert anything changed. Nobody confirmed this. We cannot confirm as mages use also TTW (Torment the weak) which also affects (Snared / slowed ) targets. TTW fire mages works on raid bosses also with invisible debuffs as slow affects on bosses. As is.

**Comment by Greywolf59** [comment] 2024-07-21 15:33
TTW works with debuffs slowing the attacks of the target which is absolutely legit. Frost Trap only slows the movement of the target and the boss movement cannot be slowed =cannot be **snared**

**Comment by Maine1** [comment] 2024-07-21 16:44
TTW says Snared or slowed, same as the tooltip for Lock n Load
Snared is stuck in place, which frost trap doesn't do, only freezing arrow and freezing trap do snare

**Comment by Greywolf59** [comment] 2024-07-22 00:50
https://wowpedia.fandom.com/wiki/Snare "reduce a victim's movement speed" … "snares, such as [Ice Trap](https://wowpedia.fandom.com/wiki/Ice_Trap) or [Earthbind Totem](https://wowpedia.fandom.com/wiki/Earthbind_Totem), and debuff-based snares (also called Slows), such as [Crippling Poison](https://wowpedia.fandom.com/wiki/Crippling_Poison) or [Piercing Howl](https://wowpedia.fandom.com/wiki/Piercing_Howl)."
All those slow the target, do not make it stuck in place.
https://www.wow-mania.com/armory/?spell=56344 = does not say anything about slow and snare, it only says target has to be trapped (meaning affected by the trap) for it to take effect.
https://www.wow-mania.com/armory/?spell=13809 = "all enemies within 10 yards will be slowed by xy%" here the slow is meant as slow of movement, it does not affect the weapon speed.
S Frost Trap is a snare (movement speed only debuff), bosses are immune to snares (movement speed debuffs), ergo Frost Trap can't trap the boss ergo the talent should not proc. But I am not going to argue about this further, not like anyone play survival and uses this tactic.

**Comment by Maine1** [comment] 2024-07-22 13:33
I completely understand what you're saying on the "snare" and I was just trying to gather more info ie "Proof" as such it should be or shouldn't be proccing, as per when we make a github post this information of proof is meant to be shared also. That being said because the tooltips blizzard created are not the best its hard to determine. I will leave this to Our dev team to make a decision regarding the matter. I just want to clear up this was never an argument only a discussion. I am here to help make the server better by getting things resolved that should be working 100% as intended, in the test team we are very thorough with our investigations to avoid any mishaps later. Thank you for your report Greywolf59

**Comment by Echinaceax** [comment] 2024-07-22 13:41
hi @Greywolf59 as you know with reports we have to make sure that what players report is 100% before we confirm it.
that is why reports made have to have all the relevent info and proof from a reliable souce explained here https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue 
testers are not here to agrue and debate with anyone, we are here to confirm the report is correct before a fix is put through to the Dev's, we are currently speaking with Janitor atm on this matter. please bear with us. thanks

**Comment by fvicaria** [comment] 2024-08-01 06:13
This won't be fixed at this point. We will re-open when more information is available.

**Closed as completed by fvicaria** 2024-08-01 06:13 UTC
Labels: Waiting Further Information, Core Change, Future Request
