### ISSUE TITLE
[Spell/Pet] Hunter pet special abilities

### ISSUE THREAD

**Issue by Rivaxino** [WoWManiaUK/Redemption#3640] opened 2019-10-17 17:06 UTC
### Scatter Shot bug
What is happening: Using Scatter Shot on a moving target makes it "teleport". The target first moves few yards in one direction then teleports to original position. 
What should happen: Scatter shot should work exactly like rogue's blind, making player disoriented in one specific location until attacked or timer is gone. 

### Pet set to passive
What is happening: for example, If web (spider) ability is used on a target the pet starts to attack and follow it. 
What should happen: As pet is set to passive it should constantly follow the owner, no matter if any abilities or attacks are being used. 

### Intervene (crab pet)
What is happening: Pet sometimes disappears after Intervene is used.
What should happen: It should still be controlled.

### General PVP issues
Resilience is not working as it should, which means taking tons of damage by all non plate players even though you play full pvp bis. There should be kinda balance between all the classes, not favorizing any of them. At the moment paladin's wings or death knights gargoyle are way too overpowered compared to any other class damage. Eg. goyle doing 3k damage/sec cannot be even compared to any burst cooldown. 
Possible fix: resilience or overall nerf of some classes' damage taken and done.

**Comment by Dranah** [comment] 2019-10-17 21:38
1) Scatter shot original issue: https://github.com/WoWManiaUK/Redemption/issues/3555 this is at "cant fix right now" status, not sure if there was any advance yet
2) Can Confirm that spider root seems to turn on the pets autoattack. There might be other spells with same problem, but they probably need to be reported separately.
spell ID 4167 (web)
**How it should work:** CC spells like spider web should not turn on the pets autoattack.
Note: It is normal for the pet to begin auto attacking and following target even on passive IF the owner uses /petattack, or any special attack of the pet (even if it's just left on autocast). However, it should not activate by only using a ranged CC ability such as the spider's web with everything disabled and the pet on passive.
3) Cannot reproduce atm. Need more specific circumstance than "sometimes"
4) Resilience's damage reduction value has been tested multiple times recently and it properly applies to everything (yes, the gargoyle strike too). I have also tested that ret pally wings is not causing their damage to bypass resilience, only other mitigation (i.eg. disperse). Therefore I can't confirm any issue regarding how resilience calculates or what could be possibly wrong with it, and I have to go with the assumption that due to the small pvp community on the server, the statistics on how "pallys and dks are op" are a little rigged. With that said, there is also LK set and it's causing some imbalance that favors plate classes, but that discussion does not belong here. Spam Janitor on forums or discord about it.

**Comment by Rivaxino** [comment] 2019-10-17 22:03
1. Hope you fix it finally as it is really old issue.
2. Waiting for fix then.
3. You need to test it in-game then. The pet simply intervenes and keeps going the same direction and disappears. Happens randomly.
4. Wings and gargoyle were just examples of inequality. However, no, the gargoyle was not hitting that much anywhere, including retail wotlk expansion. And the resilience seems to not work properly as many people feel the same problem and keep complaining about that. The problem is lack of interest about pvp in here, that's why it won't develop and we will see the same teams queing every season. Sad, because at least i am tired with how it looks like. Ah, most people queing don't have LK set, despite the arthas ring maybe. 

Thanks for answer tho!

**Comment by Dranah** [comment] 2019-10-18 00:17
@Rivaxino you're partly right about the problem with pvp, it's in a sad state but I highly doubt it has anything to do with resilience being broken. Numerically, it performs exactly as it should. So i'm still waiting for someone to point out what is wrong with it, because if it says X value reduces 24,5% damage and it reduces exactly that much on my tests, then I have to go with saying it works fine.

**Comment by Rushor** [comment] 2019-10-18 22:32
sunwell has some Resilience implementation i guess

**Comment by wow-mania** [comment] 2019-10-26 10:07
will close this for now until we can come up with more info.

**Closed by wow-mania** 2019-10-26 10:07 UTC
Labels: Confirmed, Need Informations

**Comment by Dranah** [comment] 2019-10-26 12:47
@wow-mania the root causing the spider to attack could be fixed tho
