### ISSUE TITLE
Nagrand - Flying Over Waterfalls causes death by falling damage

### ISSUE THREAD

**Issue by Nogrial** [WoWManiaUK/Redemption#179] opened 2016-07-18 23:42 UTC
Starting at 57,74 and flying north toward 55,67, while low to the water, you will eventually hit a random spot and die by falling damage. You get dismounted and are dead.
- Goblin
- Mount: Turbo-Charged Flying Machine

**Comment by Kalasbyxan** [comment] 2016-10-07 09:03
Confirmed. Dead at 57.73 while flying on Turbo-Charged Flying Machine.

**Comment by wow-mania** [comment] 2016-10-18 15:43
I could reproduce it only once after passing by loads of times.
This will be very time consuming to fix and since it's only a minor inconvenience I will mark it as "won't fix" for now.

**Comment by Keader** [comment] 2019-12-02 14:13
Fixed, using #3753 method.

**Closed** 2019-12-03 12:41 UTC
Labels: Confirmed, Fixed in Dev
