### ISSUE TITLE
[Spell] Serpent Sting

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2718] opened 2018-09-11 07:09 UTC
The talent is increasing serpent sting damage up to 46.5%, if seen here:

![serpent](https://user-images.githubusercontent.com/16576459/45343547-e4f28680-b5a9-11e8-9307-273d7ecde328.png)

0/3 talent: 456
1/3: 501
2/3: 547
3/3: 592
I refresh sting: jumps from 592 to 676
 456 + 30% = 456+136.8 = 592.8 damage, reaches nowhere to 676.

This also amplifies Chimera Shot's (http://wow-mania.com/armory/?spell=53209) damage towards Serpent Sting.

Talent ID (rank1): http://wow-mania.com/armory/?spell=19464
Talent ID (rank2): http://wow-mania.com/armory/?spell=19465
Talent ID (rank3): http://wow-mania.com/armory/?spell=19466

**Comment by crulinjr** [comment] 2018-09-11 14:13
Did you had any buff on you when you refreshed the sting from 592 to 676?

**Comment by crulinjr** [comment] 2018-09-11 14:20
Cause the talent as you said is working as intended by going from 456 to 592 but if you refresh the sting with AP or any agility buffs the damage will go up. Also apparently it does not have to do anything with the talent since you have to refresh the sting to "replicate" this bug which is not correct. What the talents does is just increasing the base damage up to 30% which it does atm.

**Comment by Ashamedlol** [comment] 2018-09-11 14:44
I did not have any buffs, try placing the talent while you have the sting on the target, get a tick in then refresh the sting, you'll see a jump in damage.

**Comment by crulinjr** [comment] 2018-09-11 14:48
If You put a point in the talent while having a sting on, the dmg should
not increase but after you refresh it.

**Comment by Ashamedlol** [comment] 2018-09-11 14:55
I just tried it again for the 15th time and had the same result, it's broken and you'll have to try it out for yourself to see.

**Comment by crulinjr** [comment] 2018-09-11 16:05
When you level up the talent while having a sting up It will increase the
dmg by 10 as it should but if you refresh it, the dmg Will be increase by
13%

**Comment by Dranah** [comment] 2018-09-11 20:10
This sounds pretty much the same as Corruption scaling with affliction talents. It gets a proper increase upon placing a talent point, and then a little extra when you refresh.

**Comment by Dranah** [comment] 2018-09-12 22:14
Thanks for the input but i've been confirming bugs for long enough to not fail accounting for these factors.
My tests were done with a naked hunter using a grey quality bow, and no other talents, buffs or glyphs that would affect SS in any way.
The question here is not if the damage is bugged, but if its possible to fix, since Keader already said most of these DOT scaling issues are unfixable at the state of current core.

**Comment by Ashamedlol** [comment] 2018-09-13 00:38
It was the same tree you put Aristo and I took off my proc trinkets+ring, I used sting then specced the talent one by one, damage increased without refreshing, then I reset the sting and the damage jumped, even throughout 5 sting refreshes the damage jump was still there.

**Closed** 2018-09-19 11:20 UTC
Labels: Confirmed, Core Issue, Fix Confirmed in Dev, Fixed in Dev
