### ISSUE TITLE
[Quest] Cipher of Damnation 10588 / Movement pathing

### ISSUE THREAD

**Issue by UniversalSoldier1985** [WoWManiaUK/Redemption#4585] opened 2020-05-24 14:25 UTC
**Links:**
https://wow-mania.com/armory/?quest=10588

**What is Happening:**
After summoning Cyrukh the Firelord, the NPC is untackable

**What Should happen:**
You should be able to attack him since the quest only completes when  Cyrukh the Firelord is slain.

**Comment by jeyrella** [comment] 2020-05-24 15:13
This is a regression of some sort.  Has worked for a very long time, see https://github.com/WoWManiaUK/Redemption/issues/23 .  And have completed this on 3 toons on Redemption in the past

**Comment by Rushor** [comment] 2020-05-24 21:35
you must talk to this guys after some time in order to start the event https://i.imgur.com/e5zmlz6.jpg

anyway, there was an issue with multiple event spawns. will fix that.

**Comment by JormagMania** [comment] 2022-12-12 15:35
Good day,

I have done that quest yesterday, Dec 11th 2022 and it seems that the pathing is still an issue. If you take a look at the video https://www.youtube.com/watch?v=heXPTpbtTmA at 2:32 mn, you can see Oronok Torn-heart walking close to the summoning ring near the altar, asking you to talk to him when ready to start the event. When I did the quest yesterday, Oronok never walked up to the altar so I waited and waited. After watching that video, I realized which step was missing to be able to kill Cyruhk. I then looked closely at the chat and saw the message from Oronok asking me to talk to him to start the event as intended. I walked up to him to realize that there were 2 Oronok. One was the NPC which you must turn the quest in and there was a copy of him, who was the "escort" Oronok to start the event. I was able to talk to him to start the escort and him and his brothers walked to the side of the fire pit and we killed Cyrukh. I believe the quest is working as intended but the pathing allowing Oronok to walk to the summoning circle is not, which will cause people to think that the quest is not working.

Jormag.

**Comment by GMZinius** [comment] 2022-12-12 16:23
Thank you for letting us know @JormagMania 
I remember your in game ticket about this 
I will reopen it to be looked into again

**Comment by fvicaria** [comment] 2022-12-12 16:33
This needs to be confirmed.
Regression only occurs when it involves code changes and not script changes.

**Comment by Rushor** [comment] 2022-12-12 17:06
Will review it and check if there is sth wrong with the quest creature

**Comment by Echinaceax** [comment] 2022-12-12 17:50
confirmed bugged for the movement part @Rushor 

at timestamp 2:16 you will see how its meant to be https://www.wowhead.com/quest=10588/the-cipher-of-damnation#videos:id=59690

- [ ] This is ours atm he stays a the back of the location and doesnt come to to player like hes supposed to 
- [ ] And pathing messed up, they walk on the benches 
https://i.gyazo.com/d53ed43ac9013d0317d298f8facee2f4.mp4

**Comment by Rushor** [comment] 2022-12-13 15:14
will add a condition that no clones can be summoned, will fix pathing and spawn position of boss

**Comment by Rushor** [comment] 2022-12-14 12:27
All mentioned issues resolved, first path of the orcs towards the attack point of the boss improved as much as possible

**Comment by Echinaceax** [comment] 2022-12-14 12:31
> All mentioned issues resolved, first path of the orcs towards the attack point of the boss improved as much as possible

Thx rushor, just waiting for PTR up then i will confirm it 😄

**Comment by Rushor** [comment] 2022-12-15 07:42
1) add movement towards player when test ".. fight when ready" happens, 2) improve path to boss even more 3) add run movement

add missing things added

**Comment by Echinaceax** [comment] 2022-12-15 08:46
- [ ] movement towards the player, " .. fight when ready" (in chat window) ❤️ 
- [ ] after kill - Oronok now has a funky walk 
- [ ] his gossip is timing slightly off "what say the elements, Torlok? I hear only silence."

**Comment by Echinaceax** [comment] 2022-12-15 12:33
Thanks @Rushor Fixed on PTR

https://i.gyazo.com/b0aac114d1b76bd3fad934f3fa136fea.mp4

**Closed** 2022-12-15 13:09 UTC
Labels: Fixed on PTR - Tester Confirmed, AIScript Change
