### ISSUE TITLE
[Boss] Mimiron-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2271] opened 2018-02-19 03:45 UTC
So we attempted Mimiron's hard mode again tonight in 10 player, fight works much better with all the mechanics, thanks Dev team. Unfortunately boss doesn't reset correctly after a wipe, we managed 2 attempts on him before trying a third and it won't let us back inside saying encounter still in progress. At this point I am out of ideas. When we finally did get back inside after calling a GM, the loot chest was in the center of the floor, the head would follow random players and the tank portion would start attacking people for melee but not use any of his abilities. So not sure what to do with that information but boss just doesn't reset correctly.

**Comment by fvicaria** [comment] 2018-02-19 08:30
Probably not related to the boss but some creature left alive or stuck somewhere. We will check.

**Comment by Bartok14** [comment] 2018-02-19 09:12
Hey was just thinking perhaps one of the creatures that was alive somewhere might have been the bomb bots that run across the pathway just outside of Mimiron, cause you can attack those and they don't agro, and seem to only explode on you if they hit exactly on. so its possible that maybe as you walk across one might agro but not run to you and then is left alive at the end of the encounter making it unable to restart properly

**Comment by Dranah** [comment] 2018-02-20 10:27
Janitor has applied a fix for overdpsing Phase3. Just to avoid confusion, we still cannot reproduce the Encounter stuck issue.

**Comment by Dranah** [comment] 2018-02-20 10:50
That fix didn't work. You can still overdps him and now he is even able to fully die.

**Comment by fvicaria** [comment] 2018-02-20 11:08
Try again, please. We just need to fine-tune it and put a cap on the max possible dps

**Comment by Dranah** [comment] 2018-02-21 00:00
Damage limit okay for 10man, insufficient for 25m. Must only apply in phase3.

**Comment by fvicaria** [comment] 2018-02-21 09:14
Fixed as much as is possible for now. 
Please retest.

**Comment by fvicaria** [comment] 2018-02-21 15:17
I am closing this one since it was deployed today.
It should be OK as per last comments from Dranah.

**Closed by fvicaria** 2018-02-21 15:17 UTC
Labels: Fixed in Dev, Test in Progress
