### ISSUE TITLE
[Quest] The Brothers Bronzebeard - Phasing issue 

### ISSUE THREAD

**Issue by Dragonfly414** [WoWManiaUK/Redemption#827] opened 2017-02-12 21:47 UTC
https://github.com/WoWManiaUK/Redemption/issues/256

I have the same issue this evening.
I got the quest, but after that, Brann disappeard and put me in a different phase. I cant get out of the phase. I dont see Brann anywhere... with our without airplane... he is'nt there...

Now my char, Flamable, is stuck in the pit, she is in a different phase. I opend a ticket already in wow... hope I can play soon again without this phase.
Hope you will relook at the quest, why he is dissapering again

Thanks for help,

Flamable

**Comment by fvicaria** [comment] 2017-02-12 22:14
Open a ticket.

**Comment by Dragonfly414** [comment] 2017-02-13 07:23
I opend a ticket, but I had to go to sleep, because it was late... this morning, there is no Ticket anymore and I am still in the phase!!!

**Comment by Dragonfly414** [comment] 2017-02-13 08:03
I am out phase now, thanks for that... but after getting quest new, back to the phase where is no brann...
After that I abbannon quest and than I came in a phase where Brann was with his flymachine... but than I dont have the quest anymore :)
Little phase bug I think... I didn't completed it... but abbandon it... 
Thanks for getting me out the phase!

**Comment by fvicaria** [comment] 2017-02-15 11:26
Please confirm on dev. This should be working fine.

**Comment by Greywolf59** [comment] 2022-11-28 16:51
I have eaxctly the same issue now on Naxxramas realm. Deleting cache, abandoning, closing the game etc did not help

**Comment by GMZinius** [comment] 2022-12-19 02:14
Thank you @Greywolf59 for commenting with information, I will reopen this issue because we have had a few tickets again recently about it

**Comment by Rushor** [comment] 2022-12-19 04:26
can assign me once it can be reproduced

**Comment by Greywolf59** [comment] 2022-12-19 10:39
PTR test:
K3
Luxurious Getaway! → Clean Up → Just Around the Corner → Slightly Unstable → A Delicate Touch
+
Opening the Backdoor → Know no Fear + (A Flawless Plan → Demolitionist Extraordinaire) → → When All Else Fails

With the quest, flying on my own to Frosthold, without using helicopter from Ricket.

Frosthold
On Brann's Tail + Sniffing Out the Perpetrator* → OBT hand in; SOtP hand in → Pieces to the Puzzle → Data Mining → The Library Console → Norgannon's Shell

*Both on Brann's Tail and Sniffing Out the Perpetrator are available at the same time. Shouldn't be so most likely. Taking them both at once as normal player would.
I can also talk to NPC and say that I have lost my Brann's Communicator before I even start doing appropriate quests.

Norgannon's Shell → Aid From the Explorer's League (Frosthold branch)
Norgannon's Shell → Exiles of Ulduar (Bouldercrag's Refuge branch)

Taking both quests.

TBA

**Comment by Echinaceax** [comment] 2022-12-19 14:21
For @Rushor 

there are 3 quests on DB so maybe the wrong quest is being use ?

![image](https://user-images.githubusercontent.com/39439201/208446584-c1042d32-1f68-441e-9a14-003fd9675699.png)

**Comment by Rushor** [comment] 2022-12-19 15:51
try now pls

**Comment by Greywolf59** [comment] 2022-12-19 16:09
Not fixed.
So before the fix: there is Brann and plane. When you take the quest Brann disappears, plane disappears and metallic orb object appears
After the fix: there is plane, orb and Brann before you take the quest. When you take the quest everything disappears. Also now you can see the Stormforged Soldiers on your way up (part of proper quest phase) if you took the quest.
But the quest is not fixed, we need the plane in quest phase to click it and get in it.

**Comment by Rushor** [comment] 2022-12-19 17:24
Updated Fix version: he will still despawn after quest accept (spell aura fades) but it will spawn a ridable flying machine with brann after that, which you can mount and then continue the quest line 

https://gyazo.com/ee81fcd5bfb9c6d35df0108fe3f432b1
https://gyazo.com/346909c6978a9ac7f52d675c83d6e36a

**Comment by Greywolf59** [comment] 2022-12-19 19:15
Works on PTR.

**Comment by Rushor** [comment] 2022-12-30 16:11
The fix works, any new issue must be inspected, because a revert would create more issues. 

"The Reckoning" got reports, what exactly is worng there

**Comment by GMZinius** [comment] 2022-12-30 16:46
> "The Reckoning" got reports, what exactly is worng there

Will explain in Dev 😄 
closing this then

**Closed** 2022-12-30 16:46 UTC
Labels: Fixed on PTR - Tester Confirmed, AIScript Change
