### ISSUE TITLE
[Boss] Valithria Dreamwalker

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2335] opened 2018-03-12 03:23 UTC
Healing the boss sometimes does not make her cast the spell to display loot. [Dream Slip](http://wow-mania.com/armory/?spell=71196)

**Comment by Keader** [comment] 2018-03-12 11:54
No repro steps? =x

**Comment by Keader** [comment] 2018-03-12 14:13
I did a possible solution
But without repro steps i cant confirm... so you need confirm it.

**Comment by squalllh1989** [comment] 2018-03-12 14:20
this is mostly happen in a bugged case, like when val is there but there is no mob stand next to her before the fight (those 4 lich stand there and start attack her when the encounter start) or some of them is missing (happen to me at least 2 time, 1 is all mob missing after the server reset mid fight, 1 time is when the raid wiped due to a ninja pull and 2/3 of the raid is still outside the room fighting a mob).
What happen is: when you heal her to full hp, she didn't do anything, just stay there, the gate is open but there is no loot.

**Comment by fvicaria** [comment] 2018-03-13 10:48
We need to find the cause of the problem, not the effects.
The no loot or heal are the effects since you can obviously tell the difference before you even start.

**Comment by GMWeeble** [comment] 2018-03-19 00:05
IT seems the issue happens if you do wipe on the boss. The boss is not able to reset the encounter to normal (Stuck at 100% but the fight stops) And gives no loot. [She does not use this spell -Dream Slip-](http://wow-mania.com/armory/?spell=71196)

**Comment by TheManiax** [comment] 2018-03-19 10:14
Same issue still persist
After a wipe, there will be no adds
And if you heal Val up to 100%, there will be no loots

**Comment by fvicaria** [comment] 2018-03-19 12:02
Should be fixed on next restart, we found the issue.

**Closed** 2018-03-19 13:36 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev
