### ISSUE TITLE
[Boss] Hodir-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2100] opened 2018-01-17 07:05 UTC
This was probably the worst out of all the bosses as most of the mechanics of the fight didn't work and made hard mode a real challenge to complete. We ended up having to replace 3 members of our raid just to get the DPS to down him within the three minute time limit.

1) The start of the fight is bugged this seems to be similar for Thorim as it seems like you need to wipe once and reset the fight before everything looks right. The main thing with this fight was that at the start you couldn't see any of the frost tomes of the frozen ally's that are supposed to help you in the fight. After a wipe this seemed to reset and we could see them at the start of the fight. Although some of them seemed to evade bug at the start of the fight and you could only aoe dps them down and not use your single target spells and attacks on them.
2) The first issue doesn't seem to matter much because even if you break out the adds from the tomes they don't seem to do any of their raid buffs for anyone. We did not see any sunlight beams that are supposed to come down and increase the damage of the raid group. Nor did any of the adds DPS the boss, and there didn't seem to be any campfires that stop the debuff on players. In the end we simply left the tomes there as it was a DPS loss trying to break them out and do the boss within the time limit of 3 minutes for the Hard Mode achievement.
3) Hodir doesn't move from his spawn location at all he might rotate around but we could not get him to move to a different location. If the adds end up working again it's imperative that he needs to run around the room with the tank so that the healers and dps can stand in the sun beams. 
4) No achievement again for killing him on Hard Mode in under 3 minutes. This was a real pain too since we put in a ticket for it and he said if we didn't have a screenshot then he couldn't do anything. The funny thing is that I had Hodir's Sigil in my inventory which you can't obtain if you don't do the achievement. I think there is also a spell he casts on himself where he empowers his punches. Then if he starts hitting the other raid members because the sun beams increasing their threat, it makes the fight more challenging. 
5) If you jump onto the snow piles that spawn so that you don't take dmg from Hodir's Flash Freeze you will get stuck in the air unable to do anything and there will be nothing your raid group can do about this. You won't get frozen in an ice tome and therefore your dps cant get you out.  

It took us 4 6 k gear score dps to come in and a Bloodlust with only 1 tank and the other dpsing with flasks and a fish feast for us to be able to do this. So is it doable? Yes. Is is attainable for the gear score of people that were expected to be in here? No. The fight needs to essentially be fixed as unless you have a high lvl geared guild from icc 25 man and HC you probably won't be able to do the Algalon Quest at all. At any rate he dropped the Sigil which was important for me so at least that did work. Right now because none of the mechanics work right the fight is kind of boring and more frustrating then anything else.

**Comment by philoudu16** [comment] 2018-01-17 14:10
Also, if you dodge the flash freeze correctly and get on the mound, you still get interrupted and stunned for half a second, which can be a pain for casters.

**Comment by Keader** [comment] 2018-01-22 13:18
Fixed npcs vanishing before wipe.
Fixed invisible npcs getting freeze.
Fixed interrupt while flash freeze cast.
Fixed helpers npc dont starting combat properly.
Fixed hodir reseting even after defeated.
Fixed combat start.
Fixed wrong Freeze npcs stucking in middle of fight.

**Comment by Dranah** [comment] 2018-01-23 11:12
Update after tests:
1. Flash freezes now appear as intended prior to the fight, no longer needs a wipe to reset.
2. Hitting the flash freezes on adds does NOT engage the boss, so it is possible to free them before engaging hodir and start with all NPCs free at the moment. This is not intended.
3. When you free NPCs BEFORE engaging hodir, they will properly start smiting/attacking, but shortly after they'll die somehow, near instantly. If you free the npcs DURING the fight, as intended, they won't even start attacking, they'll stare at the boss for a couple of seconds and then die.
4.Hodir now moves around properly following the one with aggro.
5. Flash freeze cast by Hodir is now working as intended, no getting stuck or anything, you can avoid it properly by standing on the snow pile.
6. NPC buffs are still missing from the fight, but it is hard to tell if they don't cast it at all, or they just die before they have a chance to do so. None of them lived longer than 10seconds after being freed.

**Comment by Keader** [comment] 2018-01-23 11:28
Npcs buffs is in code so i belive that they will use.
Hitting Flash Freezes dont engage boss... i will check now.

**Comment by Keader** [comment] 2018-01-23 12:30
Ok, Fixed (hitting flash freezes dont engage boss).
Fixed some other little issues, is up to test ^^

**Comment by Dranah** [comment] 2018-01-23 23:10
will reopen until further testing

**Comment by fvicaria** [comment] 2018-01-24 08:37
This has been released now.

**Comment by Dranah** [comment] 2018-01-24 10:15
Update: 
1. Attacking a flash freeze now properly engages Hodir.
2. NPCs are getting affected by Biting Cold http://www.wow-mania.com/armory/?spell=62188, resulting in their quick death after 5-10seconds. This is unintended.
3. Some NPCs suffer an instant death as they're freed, from unknown source that does not show up on the combat log.
4. Still no presence of NPC buffs during the fight, but it could be still because they fail to stay alive long enough to cast them.

**Comment by Keader** [comment] 2018-01-24 11:45
@Dranah make a new ticket for a new issues.
It's not same problems.

**Comment by fvicaria** [comment] 2018-01-24 11:46
No. it's the same script. So as far as we are concerned it is the same issue.

**Comment by Keader** [comment] 2018-01-24 11:58
Well, this is last time that i will make fixes for Thorim.
I will not keeping fixing not reported issues.
Please test everything before report, because i will fix only reported issues in main topic.

**Comment by Keader** [comment] 2018-01-24 14:07
- Crash Fixed
- Friendly Npcs getting Biting Cold fixed.


- Npcs buffs is working, he now stay alive time enought to use it.
- I cant reproduce issue with npcs getting HK, maybe was caused by Bitting cold issue.

**Closed** 2018-01-24 14:31 UTC
Labels: Fixed in Dev
