### ISSUE TITLE
[Texture] The Lich King HC - Falling through Frostmourne room floor on shapeshift

### ISSUE THREAD

**Issue by TheManiax** [WoWManiaUK/Redemption#2364] opened 2018-03-26 04:42 UTC
While in **Frostmourne** room (10hc / 25hc) casting any of druid's **shapeshift** spells will often make you fall of the texture.
Tested [Cat Form](http://www.wowhead.com/spell=768/cat-form) in Dev and I simply fell off the texture to death.

**Comment by jeyrella** [comment] 2022-04-21 17:13
While fixing #5789 we came across a possible fix for this long-outstanding issue.

**Comment by jeyrella** [comment] 2022-04-21 19:51
Appears to be caused by the redraw of gameobjects when the player's viewport changes due to collision height or object visibility. e.g.
- mage invis = changes player's scene visibility to a "ghost-like" view
- drunk = changes player's scene visibility to a wobbly screen
- bear/cat form = changes player's scene visibility due to different vertical location of the player's "eyes"

**Comment by jeyrella** [comment] 2022-04-22 07:19
Investigation further confirms the suspicion this is a deeply core problem, and fixing it would involve rewriting a significant portion of the entire core code from scratch. This is complex, resource-intensive and highly risky as it would touch on many other core functions. 
Will not be forgotten but closing again as given this nature it is highly unlikely to get priority for a significant time (has already been in mind for 5 years!)

**Closed by jeyrella** 2022-04-22 07:19 UTC
Labels: Confirmed

**Comment by GMZinius** [comment] 2024-03-29 14:50
For notes
This will be fixed soon, fixing from internal report.
