### ISSUE TITLE
[Spell] Avenging Wrath

### ISSUE THREAD

**Issue by yeahpallypowa** [WoWManiaUK/Redemption#3321] opened 2019-06-08 01:16 UTC
**Links:**

http://www.wow-mania.com/armory/?spell=31884
**What is Happening:**
Avenging Wrath from pally ignore all damage reduction and keep one shoting ppl in arena like a priest can take 4-5k crit under dispersion

**What Should happen:**

**Comment by wow-mania** [comment] 2019-06-08 08:19
Let me guess you were the one that lost the match... :)

**Comment by Dranah** [comment] 2019-06-08 08:25
There's a talent called https://www.wowhead.com/spell=53376/sanctified-wrath that allows Avenging wrath to bypass damage reductions with 50% of the damage you deal.
This 50% bypasses EVERY damage reduction, not only the 99% of dispersion. It bypasses armor, resilience, the priest's shield, everything. This means that this 50% damage will be in fact doing more damage than 50% of what you were doing before dispersion (as that total damage was still mitigated by the other effects).

I have tested the talent and it works as intended.
It cuts the damage into 2 portions, i.eg. a 294 hit > 147 passes unmodified, 147 get's affected by the Dispersion on target and only does 14 damage. The total damage you do with the effect is 162.
Apart from rounding error, the reduction bypass is a sharp 50%, as intended.

**Closed** 2019-06-08 09:15 UTC
Labels: Invalid or As-Is

**Comment by yeahpallypowa** [comment] 2019-06-08 11:19
that not mean it give a 100% crit if used and the other one is under a damage reduction buff ??

**Comment by Sudrynox** [comment] 2019-06-08 18:00
The "while affected by Avenging Wrath 50% of all damage caused bypasses damage reduction effects" is not working properly. I frequently get 100% of damage,that means when pala ret use wings all my defensive cds are useless and not working !
Now pala ret in wow mania its like superman: p
