### ISSUE TITLE
[Skil] Death Grip

### ISSUE THREAD

**Issue by Enmerkar75** [WoWManiaUK/Redemption#2175] opened 2018-01-31 22:43 UTC
Hi, after new patch 2.2.2 my Death Knight (Domine, Ally, lv80) has become unable to use pull against enemies, using the Deatg Grip skill, the chain starts from the character, hitting the opponent, but not pulling to itself as it should.
I cleaned cache after patch, I disabled addons but nothing changes, it still does'nt work.
Thanks for the attention.

**Comment by squalllh1989** [comment] 2018-02-01 05:36
I can confirm that, i have that issue with my dk also, like 50-60% of the time my [Death grip](http://www.wowhead.com/spell=49576/death-grip) , it fail to grip the target to me, they just run toward me like a normal taunt.

**Comment by fvicaria** [comment] 2018-02-01 08:15
So the other 50% works normally?

**Comment by squalllh1989** [comment] 2018-02-01 09:30
yeah 50% of the time it work normally, 50% of the time it not

**Comment by fvicaria** [comment] 2018-02-01 09:41
It's fixed in dev now.

**Comment by squalllh1989** [comment] 2018-02-01 09:48
Nope, i just tested it right now, it seem there is still isue with some mob, most of the time ranged one.
I tried to test this out when i see you marked it fixed on dev, so i create a dk and try to spam death grip as much as i can on anything i can. But since new dk must finish the quest line so the kind of mob i can test on is limited atm, will try on something else when i get out of this area. For now, i found 1 mob at the dk start area that is not getting pulled by death grip for example: ["Scarlet medic"](http://www.wow-mania.com/armory/?npc=28608),all other mob that i tested on work seem fine.

**Comment by fvicaria** [comment] 2018-02-01 10:01
I will re-check what the issue is with that one.

**Comment by fvicaria** [comment] 2018-02-01 10:09
Just tested and it worked fine. I am not sure why it did not for you.

**Comment by fvicaria** [comment] 2018-02-01 14:13
Please re-test.

**Comment by Enmerkar75** [comment] 2018-02-01 14:32
Tested on dozens of mobs, it would seem to work properly.
Thanks Dev.

**Comment by squalllh1989** [comment] 2018-02-01 14:39
It seem it work fine now, not sure why it not work while i test it last time.

**Comment by Enmerkar75** [comment] 2018-02-01 14:40
No, sorry, problem persists, three mobs have only had taunt without a pull, mob lv 70, therefore also low resistance.
As they have already said it seems that the problem is a percentage of success, as if hit chance was very low.

**Comment by squalllh1989** [comment] 2018-02-01 15:21
Can you link the mob, or at least their name ? Are you having chance that you can't pull them off, or it happen everytime you pull that specific kind of mob ?

**Comment by Enmerkar75** [comment] 2018-02-01 15:31
Murkblood scavenger, lv 64 humanoids, 2 on 3 just tainted, while on beasts it seems to work a little better, but what I mean to say, is that it would seem to work a little worse than before the patch

**Comment by Enmerkar75** [comment] 2018-02-01 15:37
however, in general it works, definitely better than yesterday, yesterday did'nt even pull the kobolds lv1

**Comment by squalllh1989** [comment] 2018-02-02 06:46
Hmm, i tested the mob at that area just now, i have no problem grip those [Murkblood scavenger](http://www.wow-mania.com/armory/?npc=18207), but instead i got a problem with grip those [Murkblood Raider](http://www.wow-mania.com/armory/?npc=18203), like in about 20 try to grip them, i have like 1-2 fail at grip, it seem that the grip is having a random small chance of fail here, can't figure out the reason if the cause, but it work much more better than before.

**Closed** 2018-02-07 10:05 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev
