### ISSUE TITLE
Spell] Bogblossom Pollen - Not exploding / Throwing player 

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5938] opened 2022-11-04 14:06 UTC
With the quest [The Ward of Wakening](https://www.wow-mania.com/armory/?quest=10961) in the log, the [Bogblossom](https://www.wow-mania.com/armory/?object=185497) becomes interactable, but atm, I am not able to interact with more than half of the one I have found. This is not the first time I do the quest, and I never had this issue before.
They are all "shiny" and have the interaction bottom, the animation is there, but the item is not picked.

Example of 2
![image](https://user-images.githubusercontent.com/31921098/199993113-4f70c7c8-b115-43c0-a046-11911ba94ea0.png)
![image](https://user-images.githubusercontent.com/31921098/199993236-d51668be-30b5-40c5-87d4-10a2f7a76b65.png)

**Comment by GMZinius** [comment] 2022-11-04 14:10
Thank you @WhitephoenixTheBunny for reporting

**Comment by Rushor** [comment] 2022-11-04 16:30
Can check it once confirmed :)

**Comment by WhitephoenixTheBunny** [comment] 2022-11-04 16:35
I have deleted cache, abandoned quest and retook, same issue...

**Comment by GMZinius** [comment] 2022-11-05 02:16
> Can check it once confirmed :)

After doing this test I did some research and the ones that are bugged are because the spell Bogblossom Pollen blast that throws you high in the air off the mushroom is bugged https://www.wow-mania.com/armory/?spell=39558

it give the buff but no explosion or throughing me anywhere 

https://i.gyazo.com/886f04f57f12a379ad1aade114525bf0.mp4

_Bogblossoms are located on top of the giant mushrooms in [Zangarmarsh](https://wowpedia.fandom.com/wiki/Zangarmarsh).
They're quite fragile and may explode violently if mishandled. Picking it can result in a Bogblossom Pollen blast that throws you high in the air off the mushroom, so be ready to shift to flight form to avoid taking damage._

https://wowpedia.fandom.com/wiki/Bogblossom

**Comment by Rushor** [comment] 2022-11-05 07:20
fix applied :)

**Comment by GMZinius** [comment] 2022-11-05 11:37
Confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/108176634/200117968-0a31643e-1b75-4d83-b126-f53e43e1b52a.png)

In flight form https://i.gyazo.com/57095a5faad71e317287841188d80768.mp4

Without https://i.gyazo.com/57095a5faad71e317287841188d80768.mp4

**Closed** 2022-11-08 09:56 UTC
Labels: Fixed on PTR - Tester Confirmed
