### ISSUE TITLE
[Quest] Not a Bug - Icecrown

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#4821] opened 2020-08-02 21:56 UTC
**Links:**
I saw all this information under "Closed", and all the information is here: [https://github.com/WoWManiaUK/Redemption/issues/4758]

**What is Happening:**
I killed every Enslaved Minion in the area, and I could not use Rod of Siphoning on most of them. The screen message kept saying "You can't do that yet."  I tried multiple times per corpse: click the corpse, then click the rod. I clicked the rod both in my bag and from the action bar where I'd dragged it.  

1. I tried it on my Horde Shaman, Vladsham. No luck on all kills.
2. Logged all the way out, then back in on my Horde Priest, Vladivostok. 1st kill on upper level = no luck. Next 2 kills of Enslaved Minions = yes! I got 1 Dark Matter each time. But then I killed more Enslaved Minions on the stairs and lower level, and I kept getting the "You can't do that yet" message. I waited for my battle buffs to wear off and tried again, but still no luck. 
3. Logged out, checked that Wow-mania was not Read-only, used the Launcher (as always!) to check for patch updates, cleared cache, logged into my Horde Hunter, Vladdhunter, and had same experience as on my priest: able to get 2 Dark Matters on upper level, then same error message for all the kills following.

It didn't make a difference if I clicked the rod before or after looting the Enslaved Minion corpse.

![Wow, Not a Bug, screenshot](https://user-images.githubusercontent.com/25782570/89133064-d0de0800-d4e6-11ea-8c03-5fe1b4325000.png)

**What Should happen:**
I should be able to gather 1 Dark Matter per corpse as in Zanguin's video in the Closed Issue I linked to above.

**Comment by jeyrella** [comment] 2020-08-02 23:16
Yep.  Forgot to re-log this one after the PTR was fixed.  Was confirmed it was linked to #4758

**Comment by Rushor** [comment] 2020-08-03 06:14
Mostly a revert happened here i think

**Comment by jeyrella** [comment] 2020-08-03 17:10
I think so too

**Comment by Rushor** [comment] 2020-08-03 20:09
try now again. remember that you only have 10 seconds to use the rod on the minion. that is the blizzlike mechanic

**Comment by Rushor** [comment] 2020-08-03 20:09
and t was not revert actually

**Comment by Boobarnes** [comment] 2020-08-03 20:27
Thanks for the speeeeeeeeeeeeeedy resolution!!! It's working now.

**Comment by Rushor** [comment] 2020-08-03 20:32
Okay what then it is already on live and no revert at all. I do not understand but ok.

**Comment by jeyrella** [comment] 2020-08-03 21:55
............
Ok that is really odd.  Psygoa can attest that I had exactly the same problem on live.

**Comment by jeyrella** [comment] 2020-08-03 21:58
Nope.  This is definitely still funky.  Tried on PTR and got the same as the OP.

![image](https://user-images.githubusercontent.com/46089380/89231060-76bf6e80-d5dc-11ea-906e-8be07e14c579.png)

**Comment by jeyrella** [comment] 2020-08-03 22:02
Actually.  It isn't the first one.  seems to be able to happen randomly.  Got it on 3rd one and no matter how many more I killed it still wouldn't work until I dropped quest and re-took it.
![image](https://user-images.githubusercontent.com/46089380/89231510-678cf080-d5dd-11ea-91ec-8e1c0622aa6e.png)

**Comment by jeyrella** [comment] 2020-08-03 22:03
Am marking as regression as I can see my spriest completed this last year no problems.

**Comment by jeyrella** [comment] 2020-08-03 22:05
Also this Summoner seems to be spawned inside the floor,  doesn't move, and evades on combat
![image](https://user-images.githubusercontent.com/46089380/89231762-dec28480-d5dd-11ea-8a33-a55ab758b56d.png)

**Comment by Rushor** [comment] 2020-08-04 06:27
okay you can now use the rod on the creature after death for 60 seconds. this should prevent confusions.

also moved that one wonky creature to a better place close to the big fire next to him.

fixed once ptr is restarted

**Closed** 2020-08-04 08:13 UTC
Labels: Confirmed - Improvement needed, Fixed - But not in dev yet

**Comment by jeyrella** [comment] 2020-08-04 09:41
Yep. Both rod seems to work, and summoner is spawned in a good spot.  Thanks @Rushor 
https://youtu.be/u0hb7UqB7BM

**Comment by jeyrella** [comment] 2020-08-06 09:08
Retested.  Seems to work, and previously trapped summoner is in a good place
![image](https://user-images.githubusercontent.com/46089380/89513679-c6fd2300-d7cc-11ea-9184-08454025d530.png)
