### ISSUE TITLE
stuck.

### ISSUE THREAD

**Issue by kallemeisner** [WoWManiaUK/Redemption#2641] opened 2018-08-04 11:25 UTC
The guardians at horde faction will teleport you to the area if ally enter the horde place. normally you can move after 3 sec but here they spam it.

**Comment by Keader** [comment] 2018-08-04 11:29
I know what cause it haha
Is a "cool bug" anyway.
Has same behavior in some conditions in ally side too.

**Comment by kallemeisner** [comment] 2018-08-04 11:30
Really*? xD


Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Keader <notifications@github.com>
Sendt: Saturday, August 4, 2018 1:29:56 PM
Til: WoWManiaUK/Redemption
Cc: kallemeisner; Author
Emne: Re: [WoWManiaUK/Redemption] stuck. (#2641)


I know what cause it haha
Is a "cool bug" anyway.
Has same behavior in some conditions in ally side too.

**Comment by wow-mania** [comment] 2018-08-04 11:33
Just log out and back in. This is a known random issue and we have to live with it.

**Comment by kallemeisner** [comment] 2018-08-04 11:34
Tried that and did not Work so had to unstuck myself

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Janitor <notifications@github.com>
Sendt: Saturday, August 4, 2018 1:33:52 PM
Til: WoWManiaUK/Redemption
Cc: kallemeisner; Author
Emne: Re: [WoWManiaUK/Redemption] stuck. (#2641)


Just log out and back in. This is a known random issue and we have to live with it.

**Comment by wow-mania** [comment] 2018-08-04 11:36
That works too. :)

**Comment by Keader** [comment] 2018-08-04 11:38
It's not random, i know the cause xD

**Comment by wow-mania** [comment] 2018-08-04 11:38
It's fixed. It's just the position.

**Comment by kallemeisner** [comment] 2018-08-04 11:39
okay :)

**Comment by kallemeisner** [comment] 2018-08-04 13:25
oki

**Comment by Keader** [comment] 2018-08-04 19:11
Fix work.
Will be in redemption in next update.

**Closed** 2018-08-06 10:35 UTC
Labels: Fix Confirmed in Dev, Fixed in Dev
