### ISSUE TITLE
[Boss] Mimiron Encounter Vol. II

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2651] opened 2018-08-08 13:02 UTC
Yesterday I attempted to do Mimiron on hard mode on alliance side. Apparently there are two issues with this fight however I can only definitively say about one of them as the other was through word of mouth with someone in my raid. The first issue which I can confirm is with the laser barrage in phase 4. The phase 2 laser barrage works correctly however, in phase 4 the animation is completely off. Mimiron mid section just goes all over the place and the lasers sometimes go through his body. Essentially the animation is not working correctly because you can be standing in an area with no lasers but you will still die due to laser barrage. So this was an issue for both the hard mode and easy mode versions of the fight that we tried. The second issue which I can't confirm because my raid leader told me not to do it was that the adds that spawn in phase 3 apparently if you loot them it bugs the fight. As I said I can't confirm this as we just killed the head by having the ranged DPS kill it in the air instead of using the item to bring him to the ground. 

Thanks for all the hard work you guys put into this, I know it took a while but the community is really appreciative of your efforts and the fight is nearly perfect now.

**Comment by Dranah** [comment] 2018-08-08 16:31
The phase4 laser barrage has been reported in every single mimiron thread so far, it is a known issue that our devs claim to be unable to fix for now. It has been declared multiple times. Please do a bit of research before opening a new report for it every time.
The laser works properly if the boss is positioned more-or-less in the center of the room. If the beam would be touching a wall, it will break.

Your raid leader's idea of not looting the adds comes from the fact Magnetic Core effect used to bug Mimirons transition from phase3 to phase4. This bug has been fixed with a workaround, you are safe to use the Core now as the ACU will dispel every stun effect at 5% health and descend to the raid before he dies.
Again this information has been written in the previous Mimiron thread, and also the Changelog on discord afterwards.

**Comment by Bartok14** [comment] 2018-08-08 18:10
Thanks for the reply Dranah. My goal is not to duplicate threads of existing issues. I'm simply trying to report things that I notice with the encounters. For the phase 4 encounter yesterday, we tanked Mimiron in the center of the room and the laser barrage was still visually bugged. I will try to post a screenshot or video of this next time I do it so that I can show you. 

The main issue with reporting duplicate bugs seems to be that you add the title fixed in dev and fixed and then close the issue. So the community still thinks that either you are unaware of the bug or that you think that you have fixed the issue when in reality that isn't the case. I checked the last Mimiron post and there was no mention of laser barrage so I thought it was something you may have missed and that's why I reported it. There isn't another Mimiron post before that one for 4 months previous which is probably the original post that I made. How far back do you want me to look before reporting a bug? Anyways thanks for the hard work you guys are doing. Like I said with the exception of the phase 4 laser barrage the encounter it practically flawless now. So thanks for fixing the previous bugs that I mentioned and many others.

**Comment by Dranah** [comment] 2018-08-08 19:48
Sorry if i was a bit harsh, it just grows old explaining the same thing in every thread. Though those may have been opened months ago, but as you can see there has been active testing&development since then, so to me it really feels like they were yesterday. 
Anyway, there is no need for screens or videos on this matter, I know exactly how the fight behaves after months of testing. It was not overlooked, not disregarded, simply it is a deep texture issue that might be impossible to fix at the current state. (and bear in mind our dearest @Keader hates mimiron to the roots as a dev). Most of the recent fixes are workarounds I have forced down his throat. 
For this case, however, im afraid our only option would be to reduce the laser visual length even further, so it would have a larger area where it would work properly.
Do you/your raid environment think that would be improvement compared to the current state?

**Comment by Bartok14** [comment] 2018-08-08 20:25
Yeah I can imagine that Keader having worked on it for months would be sick of it by now. As for the laser barrage issue I mean the raid really just needs to see the direction that it is traveling in. After some thought it seems that the initial location that it occurs seems to be correct, although my sample size it quite small for this (2 attempts). The main problem with this for hard mode is that there is fire on the ground to avoid also.  So it makes it that much more challenging to determine where to stand and which way to run. In normal mode we managed to zerg the boss with half our raid wiped at the end because of laser barrage. The main issue I have is that the sigil for the hard mode quest is unobtainable if you can't kill it on hard mode. Therefore you can't get the key to algalon, and don't have access to one of holy paladins BiS trinket. Maybe if you have the normal version drop the sigil as well, or have it added to inventory upon starting the quest. If that happens I can leave this fight alone and you guys can't focus on something else. But I know Janitor doesn't like half assed measures of fixing things so it would have to be up to him.

**Comment by Dranah** [comment] 2018-08-08 21:01
Well, you see this is why player feedback is important. Devs dont raid. I do, but I never considered this visual problem to be a gamebreaking issue, probably because I'm always watching the hand of the boss rather than the beam. But that does not mean it cannot be a huge problem for others. If this really gives raiders so much trouble, i'm sure we can find out something - for a start, i'll try to get keader to reduce laser distance again. This means you will have a tiny barrage, but at least in the right direction, hopefully. Until we can figure something better. Note that the damage will still go all the way to the wall so ranged dps needs to be alert.
Sigils on normal mode probably wont happen XD

PS: For the record, as much as we all love keader, it is only fair to note that he hasnt been "working for months" on mimiron alone. Janitor and our ex-dev Val has great amount of work done on this fight as well.

**Comment by Bartok14** [comment] 2018-08-09 05:42
So I retried this boss tonight on Horde mode and can say the following. If anyone is having trouble doing this boss in phase 4. When he goes to do laser barrage keep an eye on the initial position that he starts in and run behind the boss from that point. After you are behind the boss just stay put and don't move otherwise you will run into an invisible laser barrage. Also its a little easier to run behind the boss if you all try to get in a bit closer to him. This is the best mitigation technique that i can say for now. Good Luck.

**Comment by Keader** [comment] 2018-08-11 12:26
This visual issue is super game breaking.
Script is correct, but core cant process correct visual and we cant find why.
Right now, it's impossible to fix (with my knowledge).
We have 2 choices: 1 - Dont Touch on It and stay with visual bug or disable this spell.
In other server that i contribute, we just disabled it.

**Comment by Bartok14** [comment] 2018-08-11 19:25
I should note that we tried this again last night and feign death and or invisibility bugged this fight once again so that it doesn't actually start. We wiped and the mage and Hunter used this ability they then died so we could go back in and when you start the fight nothing happens. Mimiron just keeps fixing his tank so I dunno at this point. We been trying to fix this for 6 months it seems.

**Comment by Bartok14** [comment] 2018-08-11 20:08
Best optuon probably to remove the laser barrage until a working fix is created. That way people won't wipe to this boss.

**Comment by Dranah** [comment] 2018-08-12 11:43
That'd odd because Invisibility/Feign death was not bugging the fight before. Warlock's haunt was, which was solved. This looks like a new problem. May I know which phase did you wipe in? I'll try to reproduce.

PS: Removing laser barrage entirely would make the fight significantly easier (than blizzlike, not only current state). While the visual issue is definitely a problem, it does not make the fight "impossible to complete" by any means. 90% of pugs are failing the laser barrage even when the visual is working properly... I'm sure some people indeed die because of confusion, but others simply use this bug as an excuse. I disagree with removing the entire mechanism.

**Comment by Bartok14** [comment] 2018-08-12 12:41
The bug we encountered was we trying to wipe the fight right after the first explosion he does in phase 1 I think the boss got pushed to phase 2 along the way and during the transition the mage and Hunter used feign death and invisibility. We couldn't get back into the instance cause they were in combat so they walked to the outside ring and killed themselves with bombs. When we got back in we were combat bugged and couldn't use the teleporters so had to .cl port into the room. Then we tried to wipe on Mimiron so that we could get rid of the combat bug. But at that point his fight wouldn't start anymore. You press the button and nothing happens. I'm pretty sure we previously reported this also a while back. And it should be noted that this combat bug happens to the first person that enters the spark of imagination. Whoever tele ports in there combat bugs the whole raid and everyone has to leave while the person dies to Mimiron. 

I think you guys should try to fix laser barrage if you can but it's been 6 months at this point trying to fix this boss.

**Comment by Dranah** [comment] 2018-08-12 13:12
Thanks for the detailed description, I will look into it.

I understand from your point of view it's just bugs after bugs each week and after 6months it grows old.
It is not my aim to make your life harder or stand between you and your Meteorite Crystals.
From my point of view, it's been 6 months of constant begging, nagging and spamming on discord so that our devs, who detest mimiron as it is, would agree to make small changes here and there to improve the quality of the fight. Coming up with newer and newer ideas to go around problems. And now when it is "nearly perfect" as you said, everyone is vouching to go the easiest path, to simply remove a key mechanism overall, castrating the blizzlike essence of the fight as it is. Please understand I will do my best to prevent this.

**Comment by Dranah** [comment] 2018-08-20 16:57
@Bartok14 
There is a constant combat bug in the area which is being worked on in another thread.
Apart from that, after testing how the fight behaves when someone uses Invisibility/feign death, i found the following:

- Feign death properly takes you out of combat and resets fight, no matter when it's used. (only exception is standing inside a fire patch as it cancels feign sooner than it would become active at all. In this case it behaves as if you didn't use the spell at all)
- Invisibility CAN bug the fight. I did not succeed reproducing your "cant start" issue, but I managed to produce 2 completely different problems:
1) If used during transition, it does not reset fight, despite the mage leaving combat. As soon as you click off the buff, or it expires, you're back into the encounter with some visual bugs on VX-001.
2) If used during a regular phase, it gets the fight stuck. Combat persists, boss is untargetable, so is his vehicle. Red Button is stuck inside. The Mage needs to die outside on bombs to reset fight. When the mage dies, fight resets. Though I managed to start the fight again afterwards by clicking Red Button, it came with a side effect: Leviathan MKII receives the "Emergency Mode" hard mode buff twice, increasing his health and damage even further (not only visual).

**Comment by Dranah** [comment] 2018-08-30 21:33
Update:

Apparently laser barrage isn't bugged, only the wall textures are. They break ALL and any visual effects in the same manner therefore there is nothing to fix on the laser, as it is not the source of the issue.

So we have the following bugs still being worked on:

1) Wall Texture
2) Invisibility misbehaving
3) Emergency Mode buff effect capable of duplicating

**Comment by Dranah** [comment] 2018-09-09 23:32
UPDATE:
After some more intense testing, it looks like laser barrage issues are caused by two different problems.
Clipped laser is caused by textures, however orientation bugs are not. Possibly the latter can be fixed. (waiting for keader's feedback on that part)

Emergency Mode buff problem seems to be lag-related and therefore cannot be steadily reproduced.

**Comment by Keader** [comment] 2018-10-20 15:13
@Dranah Test if invisibility issue is fixed.

**Comment by Dranah** [comment] 2018-10-20 20:11
It isn't.

**Comment by Keader** [comment] 2018-10-20 20:32
wait?
is to make invisibility reset fight or not? i'm confuse right now.

**Comment by Keader** [comment] 2018-10-21 17:01
test now @Dranah

**Comment by Dranah** [comment] 2018-10-21 19:35
Still the same.

**Comment by Keader** [comment] 2018-10-21 21:19
what? i make mimiron always see invisible targets and my protection ignore invisible targets o.o

**Comment by Dranah** [comment] 2018-10-22 14:13
UPDATE:
Workaround for encounter issues caused by Invisibility, Feign Death and Stealth/Vanish
While in Spark of Imagination (Mimiron area):
- These effects will no longer cancel combat and put the player into invisible/stealth/feigned state 
- They will still properly reset aggro, and rogues will still get their Overkill proc from Vanish
- Stealthed targets will be unstealthed periodically every 2-3sec after the encounter begins

Outside Spark of Imagination, they will still work fully as intended.

**Closed** 2018-10-24 09:20 UTC
Labels: Confirmed, Fix Confirmed in Dev, Tweaking
