### ISSUE TITLE
[Quest] What Do You Feed a Yeti, Anyway? id:14112

### ISSUE THREAD

**Issue by Miamini** [WoWManiaUK/Redemption#4198] opened 2020-03-07 14:51 UTC
**Links:**

https://www.wow-mania.com/armory/?quest=14112
**What is Happening:**
Sharks that spawn keep regaining health even after talking and debug with gm.
![WoWScrnShot_030720_154607](https://user-images.githubusercontent.com/61911455/76145631-6fc31d00-608b-11ea-88b1-a92e3c9532a5.jpg)

**What Should happen:**

As I have seen
 and know about the quest you should be appel to kill them normally(no quest item use).

**Comment by Rushor** [comment] 2020-03-07 15:04
Will fix

**Comment by Blyatman1** [comment] 2020-03-07 19:00
I've never had any issues with this quest myself. You're meant to use the Fresh Chum while you're in the water. Sharks will evade of they're on the ramp onto the boat, or on the boat itself. If you're in the water, you won't have an issue.

**Comment by Rushor** [comment] 2020-03-07 19:55
you can now only use the item in the water. (as it should be)

**Comment by Miamini** [comment] 2020-03-07 20:00
Okay, it was just not what I saw on videos there people use it on the boat too but it might have been a later thing. So I just assumed it was broken.

**Comment by Rushor** [comment] 2020-03-08 10:34
the issue is not fixed on live yet, pls let it open until fixed

**Closed** 2020-03-10 09:58 UTC
Labels: Fix - Confirmed, Fix - In Dev/PTR
