### ISSUE TITLE
[Quest] Help Tavara cannot be taken if optional prequest is skipped- 9586 - Azuremyst

### ISSUE THREAD

**Issue by camponey** [WoWManiaUK/Redemption#3320] opened 2019-06-08 00:52 UTC
**Links:** Quest link: This bug was previously reported back in Aug 5, 2017 (https://github.com/WoWManiaUK/Redemption/issues/1455). It is not working for me. Quest link (https://www.wowhead.com/quest=9586/help-tavara).

**What is Happening:**  When I use Lesser Heal or Gift of the Naaru, it does not complete the quest.

**What Should happen:**  When I cast Lesser Heal on the NPC, it should heal her and complete the quest.

Additional Notes: This is a priest-only quest. The NPC is already at full health and I suspect that's what's causing the quest to not recognize the heals. Character name: Shadhea

**Comment by wow-mania** [comment] 2019-06-08 08:19
![image](https://user-images.githubusercontent.com/12248683/59144336-70c90000-89ce-11e9-9193-11f10b8b3e78.png)

If it worked then, it works now.

**Comment by camponey** [comment] 2019-06-08 08:57
It would be great if it would complete for me. I used the same ability shown in your screenshot. Guess I'll abandon the quest and move on.
![help_tavara](https://user-images.githubusercontent.com/5051153/59144810-680e0500-89a1-11e9-8085-4ac7a92a14b8.jpg)

**Comment by WhitephoenixTheBunny** [comment] 2019-06-08 14:45
Open a ticket in game, looks like the NPC didn't reset from previous quest.

**Comment by camponey** [comment] 2019-06-08 15:09
Will do.  Thank you, Phoenix!

**Comment by Echinaceax** [comment] 2022-01-09 17:21
Update on this quest tested with and without **Word from Azure Watch**

Players must complete **Word from Azure Watch** which is picked up from **Aeun** on the way to Azuremyst Isle or this quest bugs 

works if **Word from Azure Watch** has been handed in 
![no issue for me ](https://user-images.githubusercontent.com/39439201/148693056-dd11bc55-e1a8-4c5b-9e19-1818e46e691f.jpg)

not working if not completed **Word from Azure Watch**

![bugged now ](https://user-images.githubusercontent.com/39439201/148693130-7fd37a82-71c1-4507-96eb-d216d47b8a33.jpg)

**Comment by Rushor** [comment] 2022-01-11 11:49
will remove the condition of "Word from Azure Watch" then :)

**Comment by Rushor** [comment] 2022-01-16 08:04
credits and event will now work even if that prequest has been done or not

**Comment by Echinaceax** [comment] 2022-01-16 11:27
confirmed fixed in PTR without "Word from Azure Watch" quest 
![confirmed2](https://user-images.githubusercontent.com/39439201/149657929-86037621-f60f-4131-915d-8fb030dccad4.jpg)
![comfirmed text](https://user-images.githubusercontent.com/39439201/149657934-7d9a4315-c5ec-4280-88e6-d1bc1f87585e.jpg)

**Note**
There is a slight delay on quest completion but it does work now 😄 thanks

**Closed** 2022-01-19 08:52 UTC
Labels: Fixed on PTR - Tester Confirmed
