### ISSUE TITLE
Hunter's pet totally disappears when using Call Stabled Pet

### ISSUE THREAD

**Issue by DuneAsD** [WoWManiaUK/Redemption#4140] opened 2020-02-20 09:23 UTC
**Links:**
Call Stabled Pet
https://www.wow-mania.com/armory/?spell=62757#.

**What is Happening:**
While using Hunter's ability Call stabled Pet, my pet disappeared when I tried to change pet.

**What Should happen:**
Hunters should be able to change pet while using Call Stabled Pet ability without fear of game deleting the pet.

**Comment by Rushor** [comment] 2020-02-20 11:32
do you tried that while you was mounted?

**Comment by Kitzunu** [comment] 2020-02-21 18:32
I will close this as Cannot Reproduce as one of our testers has tested it and no luck.

You need to provide more information regarding how you manage to get this to bug out

**Closed by Kitzunu** 2020-02-21 18:32 UTC
Labels: Invalid - Cannot Reproduce
