### ISSUE TITLE
[Quest] Stasis Chamber of Bash'ir - 10974 - Blade's Edge Mountains

### ISSUE THREAD

**Issue by yoopieb** [WoWManiaUK/Redemption#4788] opened 2020-07-24 09:27 UTC
**Link:**
https://www.wowhead.com/quest=10974/stasis-chambers-of-bashir

**what is happening:**
'Ethereum Stasis Chamber Alpha" object is not to be found.

**What Should happen:**
I got a key for the object named above, but the object is no where to be found.
I checked with wowhead, and youtube if i was doing it right. After that i disabled all addons, deleted cache (incl relog), retake the quest (2x).
I have spend yesterday over 45 minutes here to find it, and for another 20 minutes this morning.
The GM that was helping me couldn't see the object either.

I am using the wow-mania loader, and i am up to date.

**Comment by jeyrella** [comment] 2020-07-24 09:38
Well, I've done this multiple times on Redemption so I do know it has worked in the past.  Will check tonight.

**Comment by jeyrella** [comment] 2020-07-24 09:47
Actually, I just did now.  It's exactly where it's supposed to be, right where wowhead comments say it is.
https://youtu.be/mW2CtcWyedg
I need a video of your issue if you want me to check more.

**Comment by jeyrella** [comment] 2020-07-24 09:48
I will leave open for 24 hours in case you have more evidence.  Looking forward to helping you test this issue :)

**Comment by Rushor** [comment] 2020-07-24 10:25
maybe the object did not respawned fast enough?

**Comment by yoopieb** [comment] 2020-07-24 11:08
I just recorded myself back there. I know this is with addons ON, but like i said in orriginal post, also tried without, and GM didn't see it. Hope this is of use for you.
https://youtu.be/lYhpq2NZWfo

**Comment by jeyrella** [comment] 2020-07-24 16:48
What about all the other spawn points?   There are 6 in total.

**Comment by yoopieb** [comment] 2020-07-24 17:13
I have been flying over the whole place for over an hour.
The quest is so far into Netherstorm that not many people do it.(also comes after the 120 quest line) With those things in mind reset timer (special with an over night) shouldn't be the problem either. The object just was not there. 

Just flew a other toon there, the only orb there is to see on the server are the normal "ethereum stasis chamber"

**Comment by jeyrella** [comment] 2020-07-24 23:05
@Rushor confirmed yoopieb's suspicions this does not spawn.  Can you check spawn time pls for object https://wow-mania.com/armory/?object=185512
Opened, abandoned & retook, waited 16 mins and no respawn

**Comment by jeyrella** [comment] 2020-07-25 01:06
3 hours later, still not respawned.  Definitely something wrong here.

**Comment by Rushor** [comment] 2020-07-26 11:59
the issue is that the object does not "close" again. added a 300 second timer for autoclose. fixed once prt restarted

**Comment by Rushor** [comment] 2020-07-30 07:49
applied

**Comment by jeyrella** [comment] 2020-07-30 10:48
Well it does re-close again after exactly 5 mins but then immediately disappears

**Comment by jeyrella** [comment] 2020-07-30 10:49
https://youtu.be/HL5DWFEQfhQ

**Comment by Rushor** [comment] 2020-07-30 13:45
this seems to be more complicated than expected :o

**Comment by Rushor** [comment] 2020-07-30 16:29
will work this out in a different way

**Comment by Rushor** [comment] 2020-07-30 16:38
okay now it should always respawn

**Comment by Rushor** [comment] 2020-07-30 16:48
it will may take a bit longer than 5 minutes for respawn but IT WILL respawn always :)

**Comment by jeyrella** [comment] 2020-07-30 20:03
Confirmed.  Wasn't watching exactly when, but it was before 20 mins :D
![image](https://user-images.githubusercontent.com/46089380/88968959-0b0d9680-d2a8-11ea-8fc8-515e88498196.png)

**Closed** 2020-08-04 08:13 UTC
Labels: Fix - Tester Confirmed

**Comment by jeyrella** [comment] 2020-08-06 08:53
Retested after complaints.  Appeared after exactly 7 mins
![image](https://user-images.githubusercontent.com/46089380/89512144-b3e95380-d7ca-11ea-80c6-8b4391724c22.png)
