### ISSUE TITLE
[Quest] Help Those That Cannot Help Themselves

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#2591] opened 2018-07-15 15:39 UTC
The Quest “Help Those That Cannot Help Themselves” (http://www.wow-mania.com/armory/?quest=11876) consist in free 8 Mammoth Calves with the provided item “D.E.H.T.A Trap Smasher” (http://www.wow-mania.com/armory/?item=35228), that item should have a 15 seconds cooldown, at the moment it doesn’t have any cd and if you spam it in one trapped calf, the 8 will count.

Quest giver: Arch Druid Lathorius <D.E.H.T.A> (http://www.wow-mania.com/armory/?npc=25809) 

![screenshot_82](https://user-images.githubusercontent.com/31921098/42735525-a73b02ce-884d-11e8-9f2d-9b3d8c2e37ad.jpg)

**Comment by wow-mania** [comment] 2018-07-15 16:13
Duplicate of #2588

**Comment by WhitephoenixTheBunny** [comment] 2018-07-15 16:39
Nope, the item have no cooldown that why u can spam the item in one calf

**Comment by Keader** [comment] 2018-07-15 18:19
Is working...

**Closed by Keader** 2018-07-15 18:19 UTC
