### ISSUE TITLE
[QUEST] Rescue from Town Square - does not count kills when first hit from max range

### ISSUE THREAD

**Issue by Tolkinz** [WoWManiaUK/Redemption#5814] opened 2022-05-06 02:31 UTC
**Links:**
https://www.wow-mania.com/armory/?quest=12253

**What is Happening:**
Killed many geists but nothing counted
I have done this with many other alts, but pet class has problems with recognizing as [rescue].
This hunter case is serious, nothing counted so far, still 0/6.
I made a 2men group with another melee class and tried, still same.

**What Should happen:**
Killing a geist bonded with a villager should be counted as a rescue.

* player name : Killemall

**Comment by svijetlo** [comment] 2022-05-06 07:56
i did this quest 2 days ago worked perfectly

**Comment by Tolkinz** [comment] 2022-05-06 08:11
my other toons all did good. it only happened yesterday.

**Comment by Rushor** [comment] 2022-05-06 08:38
Only if you find a way to reproduce it we can inspect and fix actually

**Comment by Tolkinz** [comment] 2022-05-06 08:40
I tested 2abt 2 hrs ago and it was same, in Zul'drak, can visit if someone can come and confirm
this q is still in 0/6 status

**Comment by Rushor** [comment] 2022-05-06 09:05
Can you try to do the quest without a pet and then see if it works?

**Comment by Tolkinz** [comment] 2022-05-06 09:52
I tried just ago.
Im in wintergarde keep now, no pet, just killed with a bow/frost trap, nothing happens.
Not in a group, solo, 0/6 again. 
This q opens next quest line but its blocked. No way to resolve it from my side.

**Comment by jeyrella** [comment] 2022-05-06 09:53
Have you tried dropping the quest and re-taking it?

**Comment by Tolkinz** [comment] 2022-05-06 09:55
did it yesterday, no effect.
OK, I will do it again.

[](https://drive.google.com/drive/folders/1OyPuJ7zWrEflfkpkcU-FR6LOxfwNSxbT)

**Comment by Tolkinz** [comment] 2022-05-06 10:01
nothing happens

**Comment by jeyrella** [comment] 2022-05-06 12:57
@Tolkinz Thanks for the extra detail.
Can you confirm you’re using client 2.9.5 started from the launcher, with cache cleared?

P.s. “I did it fine” _does_ help, as it builds a picture about scenarios in which it DOES work

**Comment by Tolkinz** [comment] 2022-05-06 13:46
okay, cache cleared, client 2.9.5, no group, sent pet charged-in,
town girl yells happily but never gave me the credit.......
I just give up this quest line..
![WoWScrnShot_050622_224425](https://user-images.githubusercontent.com/105026618/167145503-a7fa20b3-4a87-4fa2-86b9-5a08fff5d747.jpg)

**Comment by Rushor** [comment] 2022-05-07 09:05
Are you possible in a hidden raid?

Try /script LeaveParty()

Soemtimes player are in raid hidden and thus do not get a quest credit.

**Comment by Franciss983** [comment] 2022-05-07 12:14
I just did it on live server 10 minutes ago on my hunter.
heres video:
https://www.youtube.com/watch?v=K1xJSTCYqB0

**Comment by jeyrella** [comment] 2022-05-07 12:51
@Tolkinz Well.  At this point we really have no idea what could possibly be the issue (in terms of code at least), we've had multiple people testing with multiple accounts and toons, both on live and PTR - i.e. we've ruled out all the scenarios we can think of here, and can't reproduce at all.  The quest itself is not broken at a core level, and your issue does not seem to be class or faction related.  Even your own alts have completed it fine.

It's looking increasingly like a profile issue or perhaps a database issue with your specific toon, so all I can suggest at this point is to raise a GM ticket in-game and ask them to manually complete the quest for you, referencing this ticket (and/or point the GM to myself), as the test team and devs can't reproduce it and have no further ideas.

Thanks for raising, please don't let it put you off raising further issues in the future.  If you get similar problems with more quests, please raise with GMs as we may need to look at recreating your profile manually somehow.

**Comment by Tolkinz** [comment] 2022-05-08 11:30
it's closed, but I think it would be helpful in anyway to leave a recorded screen, taken just ago.
like 5 min ago. HD being under process from youtube

[https://www.youtube.com/watch?v=q8fUR-zFBPU](url)

**Comment by Echinaceax** [comment] 2022-05-09 12:49
thanks for more info @Tolkinz 
we will check this out

**Comment by Echinaceax** [comment] 2022-05-09 13:13
> I just did it on live server 10 minutes ago on my hunter. heres video: https://www.youtube.com/watch?v=K1xJSTCYqB0

From watching your video Hetah, your damaging first so its counting 

new info from players video, they are sending pet first (this is when its bugged)
https://youtu.be/_DrSuzg9pOc

can you confirm and reopen please

**Comment by Franciss983** [comment] 2022-05-09 15:09
Hello,

hunter test:
video: https://www.youtube.com/watch?v=Mr3saSMa_zE

warlock test:
video: https://www.youtube.com/watch?v=rAjO-O8E0UU
video2: https://youtu.be/THqmrxfsaQk

warrior test:
https://www.youtube.com/watch?v=OA6r_QAgzDo

It looks like max. range is issue.

**Comment by Echinaceax** [comment] 2022-05-09 15:23
Confirmed Hetah test with him, both checked and is max range issue
checked also melee class too

- [ ] Max range issue for casters and pets classes

**Comment by Rushor** [comment] 2022-05-09 18:40
I can resolve this issue if you wish, since i already know where the issue in the Script is

**Comment by Rushor** [comment] 2022-05-19 17:30
credit should be given better now

**Comment by Echinaceax** [comment] 2022-05-19 21:55
Confirmed fixed in PTR 

checked hunter and warlock from range

**Closed** 2022-05-21 10:32 UTC
Labels: Fixed on PTR - Tester Confirmed
