### ISSUE TITLE
[Quest] The Light of Dawn

### ISSUE THREAD

**Issue by GildedHero** [WoWManiaUK/Redemption#1863] opened 2017-11-23 12:32 UTC
Hello, this is a known issue for the community as for the last major DK quest is bugged, you can go do the fight for lights hope, the only problem is you cant complete it after, thus not being able to move forward. please fix and thank you so much

http://www.wowhead.com/quest=12801/the-light-of-dawn

**Comment by Plege** [comment] 2017-11-23 12:42
please give more information. under what circumstances does that happen?
i myself leveled a DK recently not encountering any trouble with that quest.
so in order to fix it we need to know what does not work under which circumstances

regards

**Comment by fvicaria** [comment] 2017-11-23 15:50
How you can't complete it? You have given next to no info here.
Is the NPC not there? Is there no option to complete? I have no idea of what is happening.

**Comment by GMWeeble** [comment] 2017-11-23 17:02
Quest works fine, the only few problems that can happen is that Higlord Darion Mograine needs reset to start the fight or that the fight itself resets if you are not close enough to him during the fight. Other then that the quest works fine.

**Comment by GMWeeble** [comment] 2017-11-25 00:15
After looking in to it with a lot of tickets the issue is handing the quest in. Higlord Darion Mograine is not giving any options to hand it in.
https://gyazo.com/e3aba2ccec70f35407ee5539450e7004
Here I have the quest completed but no option to hand in.

**Comment by fvicaria** [comment] 2017-11-25 11:19
Fix has been applied to Elysium already. Feel free to test it there.

**Closed** 2017-11-25 15:55 UTC
Labels: Confirmed, Fixed in Dev
