### ISSUE TITLE
[Raid] Molten Core Portal access 

### ISSUE THREAD

**Issue by JormagMania** [WoWManiaUK/Redemption#5950] opened 2022-12-12 18:46 UTC
**Closing this as I can't find a video of 2009 with anyone leaving MC into BRM, no proof atm**

**What is Happening:** When entering the Molten Core (MC) once attuned via our good friend https://www.wowhead.com/classic/npc=14387/lothos-riftwaker  

![Screenshot (3524)](https://user-images.githubusercontent.com/120397554/207127591-1d2d8d7f-3d8f-46b6-9b23-718b24280bde.png)

and then turning around and using the portal to leave MC, the portal takes us inside Blackrock Depth  (BRD) instance. 

![Screenshot (3525)](https://user-images.githubusercontent.com/120397554/207127685-96fd9568-8e9e-4f7e-8f91-ee49c8d045ab.png)

![Screenshot (3527)](https://user-images.githubusercontent.com/120397554/207127818-89f31428-1e97-4027-99f8-4be25fcdd33c.png)

**What Should happen:** We should be teleported back out to our good friend Lothos Riftwalker in Blackrock Mountain (BRM) not inside BRD instance. That way, people used to leave MC to help summon other raid members in BRM and zone back in to MC via Lothos.

Thank you.

Jormag.

**Comment by Echinaceax** [comment] 2022-12-12 19:09
@JormagMania Closed due to no 2009 proof atm

**Comment by WhitephoenixTheBunny** [comment] 2022-12-13 09:25
I have found this video from 9 years ago, explaining how to attune to MC
https://www.youtube.com/watch?v=osxqj9YYVvM
Video is in portuguese, but at minute 7'48 you can see the player, after doing the quest entering the raid and leaving it to be ported to lothos e turning the quest.

**Comment by Rushor** [comment] 2022-12-13 12:21
Can assign me once confirmed :)

**Comment by Hajzlopuc** [comment] 2022-12-13 12:36
https://puu.sh/Ju0vS/745f4cab95.mp4
https://puu.sh/Ju0uT/754de64e75.mp4

right now from retail

**Comment by Rushor** [comment] 2022-12-13 15:02
fixed in ptr

**Closed** 2022-12-15 11:04 UTC
Labels: Confirmed, Fixed on PTR - Tester Confirmed
