### ISSUE TITLE
[NPC/Dungeon] Trollgore - Drak'tharon Keep

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4265] opened 2020-03-18 13:57 UTC
**Links:** 
https://youtu.be/K6O3ou0TiOA?t=213 ; 
https://www.wowhead.com/npc=26630

**What is Happening:** Trollgore does not summon any adds when the fight begins and hence no [Corpse Explode](https://www.wowhead.com/spell=49555/corpse-explode) 

**What Should happen:** Boss should summon adds and cast the ability mentioned above.

P.S. I wasn't paying much attention to other boss abilities, if he uses them. If possible someone please check this.

**Comment by jeyrella** [comment] 2020-03-18 16:36
This sounds like a duplicate of #4045 which may have progressed.  @bLeyaa can you check that one and confirm it is the same as you're describing here.  If so we should re-open #4045 and mark as regression.

**Comment by bLeyaa** [comment] 2020-03-18 16:55
Yeah i suppose that's about the same thing. :)

**Closed** 2020-03-18 21:21 UTC
Labels: Invalid - Duplicate
