### ISSUE TITLE
[Quest] You, Robot; Negatron always visible, missing pathing

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5741] opened 2022-03-05 23:20 UTC
**Links:**
Quest:
https://www.wow-mania.com/armory/?quest=10248
Negatron
https://tbc.wowhead.com/npc=19851/negatron
https://www.wow-mania.com/armory/?npc=19851

**What is Happening:**
Negatron is always spawned and visible near the bridge. Does not move, does not run to the player and quest giver's station when you start controlling the Scrap Reaver

**What Should happen:**
Negatron should be only visible or only spawned when you use the control and spawn the Scrap Reaver under your command. Then Negatron should start immediately running towards the station where you use the controller and probably attack the robot or the player.
The rest is working fine.

**Comment by Echinaceax** [comment] 2022-03-05 23:32
comfirmed spawned 

![image](https://user-images.githubusercontent.com/39439201/156903076-a9abaa5b-017c-425d-8bdb-a99342098538.png)

youtuber states on video should be summoned when you have your pet at 0:14 timestamp

**Comment by mfranca0009** [comment] 2022-03-24 01:26
### Further Problems
- [ ] When the `Scrap Reaver x6000 Controller` buff expires on the robot, the `Scrap Reaver X6000` should not continue following the player that previously controlled it; this currently happens...

- [ ] The `Scrap Reaver X6000` does not automatically follow the player, he gets stuck in the `Stay` command behavior when first using the `Scrap Reaver X6000 Controller` quest item.

- [ ]  After combat ended, he will not automatically start following you and just sit in the spot he last killed a mob because it gets stuck in combat. (e.g., using the `Scrap Reaver X6000` to slay a `Shaleskin Flayer`. After the `Shaleskin Flayer` dies, the robot will just stand there until the `Follow` command is clicked/used).

- [ ] When leaving `The Proving Grounds` area, the `Scrap Reaver X6000` is never removed from you and forcefully dismissed. He still remains as a minion of the player that controls him. The item clearly states, if leaving `The Proving Grounds` area, then you will lose control of the `Scrap Reaver X6000`; this is not functioning properly.

- [ ] On top of him having to be summoned in instead of being spawned and visible all the time, he should start out as being `unattackable`, but he is currently attackable; needs to start with `UNIT_FLAG_NON_ATTACKABLE` and `UNIT_FLAG_IMMUNE_TO_PC`.

- [ ] When dismissing the `Scrap Reaver X6000`, the robot will be stuck at the position you dismissed him at. If the player dismisses the pet or forcefully gets dismissed because of leaving `The Proving Grounds`, it should more likely be teleported back to its spawn position or forcefully be despawned.

**Comment by Rushor** [comment] 2022-03-26 16:18
this is my issue

**Comment by Rushor** [comment] 2022-04-02 10:25
> ### Further Problems
> 
>     * [ ]  When the `Scrap Reaver x6000 Controller` buff expires on the robot, the `Scrap Reaver X6000` should not continue following the player that previously controlled it; this currently happens...
> 
>     * [ ]  The `Scrap Reaver X6000` does not automatically follow the player, he gets stuck in the `Stay` command behavior when first using the `Scrap Reaver X6000 Controller` quest item.
> 
>     * [ ]   After combat ended, he will not automatically start following you and just sit in the spot he last killed a mob because it gets stuck in combat. (e.g., using the `Scrap Reaver X6000` to slay a `Shaleskin Flayer`. After the `Shaleskin Flayer` dies, the robot will just stand there until the `Follow` command is clicked/used).
> 
>     * [ ]  On top of him having to be summoned in instead of being spawned and visible all the time, he should start out as being `unattackable`, but he is currently attackable; needs to start with `UNIT_FLAG_NON_ATTACKABLE` and `UNIT_FLAG_IMMUNE_TO_PC`.
> 
>     * [ ]  When dismissing the `Scrap Reaver X6000`, the robot will be stuck at the position you dismissed him at. If the player dismisses the pet or forcefully gets dismissed because of leaving `The Proving Grounds`, it should more likely be teleported back to its spawn position or forcefully be despawned.

The Further issues above can be ported in a separate issue since they concern any kind of quest item creature, will concentrate on the issues mentioned in first post to get fixed

**Comment by Rushor** [comment] 2022-04-03 09:56
- once quest is taken negatron will spawn and run towards the player - that is a good solution
- static spawn of Negatron is removed
- after death of Negatron he will despawn after 10 seconds and the reaver will despawn aswell
- added UNIT_FLAG_NON_ATTACKABLE and UNIT_FLAG_IMMUNE_TO_PC for negtraon on spawn, he will remove it once he is close to the questgiver
- scrap bot will despawn now when leaving the intended area
- scrap bot will follow on charm
- scrap bot will follow every few seconds when outfight
- if  charm buff expires scrap bot will despawn
- . respawn timer of scrap bot reduced

**Comment by Echinaceax** [comment] 2022-04-03 10:30
confirmed fixed in PTR 

despawn on quest complete
https://i.gyazo.com/8ab279c49704bfc3f263c276a09a82b5.mp4

Despawn if leave the area 
https://i.gyazo.com/a354dd3f537b69882d2747270fd05e0c.mp4

**Closed** 2022-04-05 11:55 UTC
Labels: Fixed on PTR - Tester Confirmed
