### ISSUE TITLE
[Ruby Sanctum - Halion] Living Ember / Inferno

### ISSUE THREAD

**Issue by Midnaa** [WoWManiaUK/Redemption#2091] opened 2018-01-16 09:09 UTC
**How it does work:** 
- **Living Embers** do not get stacks of http://www.wowhead.com/g00/spell=75888/awaken-flames?i10c.encReferrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmRlLw%3D%3D&i10c.ua=1 when they are close to the **Living Inferno** that has the aura http://www.wowhead.com/spell=75886/blazing-aura

**How it should work:**
- **Living Embers** should get stacks of **Awaken Flames** each time **Blazing Aura** ticks and if they're within 15 yards of the **Living Inferno** 

This applies only to 25 Heroic because these adds don't even spawn in 10 man so don't be confused because for some reason the entries + the spells for the 10 man version exist but **are not in use.**

I am pretty sure that this has something to do with **Conditions** table because when you try to manually cast the spell **Awaken Flames** you get the "Invalid Target" error message.

This allows the group to stack up the **Living Inferno** with the **Living Embers** and therefore completely ignore the mechanic.

**Comment by Keader** [comment] 2018-01-16 11:58
I cant reproduce.
Tested now in dev...
![image](https://user-images.githubusercontent.com/7120913/34987824-aafd4346-faa3-11e7-88a0-b58fdb9d30c5.png)

**Comment by Midnaa** [comment] 2018-01-16 12:10
Did you test during the encounter aswell? Might've been ninja fixed so just close the issue then.

**Comment by Keader** [comment] 2018-01-16 12:17
Yeap, working in raid situation too.
Closing.

**Closed by Keader** 2018-01-16 12:17 UTC
Labels: Cannot Reproduce
