### ISSUE TITLE
Hall of Reflection 5 hc reset bug + Insta kill purple pool (Marwyn)

### ISSUE THREAD

**Issue by Daddy6999** [WoWManiaUK/Redemption#5768] opened 2022-03-26 16:21 UTC
Hi.

The title says it all.

The pools did 5-10k per tick.

Got ss.

Thanks!

**Comment by Daddy6999** [comment] 2022-03-26 16:21
Character: Passiondaddy

**Comment by Daddy6999** [comment] 2022-03-26 16:23
![WoWScrnShot_032622_182002](https://user-images.githubusercontent.com/102427594/160248383-498ffc81-9989-45ce-b3ee-05be54513890.jpg)
![WoWScrnShot_032622_181943](https://user-images.githubusercontent.com/102427594/160248384-dcbd91b1-7695-4b30-bfbf-dc276df74423.jpg)
![WoWScrnShot_032622_181948](https://user-images.githubusercontent.com/102427594/160248386-a3410b3e-0cff-4a09-b04b-d095bdef291d.jpg)

**Comment by Rushor** [comment] 2022-03-26 16:24
once confirmed, i will fix this. else simply close

**Comment by Echinaceax** [comment] 2022-03-26 16:27
go for it @Rushor it was one of your earlier fixes it seems

**Comment by Rushor** [comment] 2022-03-26 16:31
thats a new issue

**Comment by jeyrella** [comment] 2022-03-26 18:42
@Daddy6999  your title is actually not clear, to be fair.

As far as we can tell, the pools are *intended* to do that much damage - this is the HC version of the final 5-man dungeon in WotLK; it's intended to be really tough, and demanding on your healer, and ensure you actually use tactics throughout.
The tactics on this section are intended to make you take killing mobs slowly, rather than rushing in and zerging, which sounds like what happens here.

"Reset bug" is not descriptive either.  How/when/where did it "reset" ?  We have had previous reports with this dungeon but have never been able to record or reproduce anything like this.

**Comment by Oganku** [comment] 2022-03-28 00:06
The pools don't even deal any damage, they only apply a stacking +% shadow damage taken debuff. You just have an idiot dispelling the debuff [Shared Suffering] on a target (probably) afflicted by stacks of the pool, which causes it to instantly deal its remaining damage to nearby allies.

**Comment by Daddy6999** [comment] 2022-03-28 07:20
@jeyrella So unless I record a video you do not trust a party of 5 players? The pools are not intended to insta kill you. And the encounter resets in the mob "waves" part.

The INSTA kill pools is new. And the Reset part is 1 year if not older because I have been experiencing it before.

What could you possibly not understand? "How/when/where did it "reset" ?" - I don't know man, I am not a tester, and I am not getting anything in return for this. As far as I know back on my days 1 year ago it was because the ROGUE mob was teleporting out of bounds and it was resetting the Encounter.

The reset part is a really old bug, again. Test them, fix them, do them. And thank you for your time,

Daddy.

**Comment by jeyrella** [comment] 2022-03-28 07:23
We are closing this as we cannot find any issue, and we have given time to respond and clarify your ticket.
If you do have further information please respond.
In the future please do consider creating a full report with details.

**Closed by jeyrella** 2022-03-28 07:23 UTC
Labels: Waiting Further Information

**Comment by jeyrella** [comment] 2022-03-28 08:52
The pools do *not* themselves insta kill you.  They apply a stacking debuff that when your healer mistakenly dispels Shared Suffering, dramatically increases the damage taken, which _can_ instantly kill.  I recommend reading the dungeon tactics.

You know it reset, but don't know exactly when?  Were you not looking at the screen at the time?

We have indeed spent dozens of hours on this dungeon testing.  We can only test so much, and if we are given very vague starting points, it makes our task insanely hard.  We are all volunteers here, we need more clarity on where to even start in order to help.

As for recording, it is not that a matter of trusting players, but that a video allows us to do a frame-by-frame analysis of exactly what triggers and when, since we are unable to reproduce it.  When trying to diagnose a deep issue like this potentially is, anything else is technically "vague" in description.
