### ISSUE TITLE
[Quest] The Earthen Oath - Quest credit given by wrong NPCs

### ISSUE THREAD

**Issue by Tolkinz** [WoWManiaUK/Redemption#5822] opened 2022-05-17 09:11 UTC
**Links:**
https://www.wow-mania.com/armory/?quest=13005

**What is Happening:**
summoned minions do NOTHING
play video link : https://youtu.be/lU7JEwtk2jI

**What Should happen:**
summoned minions should work HARD ;P

** for this quest, I have no idea how to kill the elites if they do not work at all.
Formed a group with my second account DK tank, kill didn't count.

**Comment by Echinaceax** [comment] 2022-05-17 10:32
Thanks for reporting @Tolkinz 
We will check this out

**Comment by Echinaceax** [comment] 2022-05-17 12:29
@Tolkinz note you have to use the pet bar to cast the spells https://i.gyazo.com/5aed6b44c7cdd1c202720b7d8a4b544f.mp4

Did confirm a few issues though

- [ ] Pet bar spell 56491 is slow to react 
- [ ] Player gets quest credit from the fighting npcs Earthen Warder https://www.wow-mania.com/armory/?npc=29981 
That shouldnt happen 

whats happening atm https://i.gyazo.com/dd3fda9a16926857a356bb076f8c62f0.mp4

**Comment by Echinaceax** [comment] 2022-05-17 16:24
> o dang..... I didnt even realize there was a pet bar.... sorry

Thats ok 😄 
I found a new issue while checking it, so all good

**Comment by Rushor** [comment] 2022-05-19 17:53
The problem here is that the npcs on retail are actually not created to kill the other npcs, they are more like in a endless fight

**Comment by Echinaceax** [comment] 2022-05-19 17:58
> * Earthen Warder https://www.wow-mania.com/armory/?npc=29981
>   Earthen Elite https://www.wowhead.com/npc=29980/earthen-elite

Yes i know 
Earthen Warder https://www.wow-mania.com/armory/?npc=29981
Earthen Elite https://www.wowhead.com/npc=29980/earthen-elite

should NOT give quest credit

**Comment by Rushor** [comment] 2022-05-19 18:01
They dont actually give creditsy, they just kill the npcs so it does not care them who they were killed from,

Need to think about a solution that the credit is only given when a player/pet/charm attacks them

**Comment by mfranca0009** [comment] 2022-05-19 18:04
Target type 16 (INVOKER_PARTY) fixes this immediately, no reason to have target type 21 with a 100-yard radius.

**Comment by Rushor** [comment] 2022-05-19 18:10
perfect, added that

**Comment by Rushor** [comment] 2022-05-20 06:52
The last mentioned issue is not created by my fix? New issue always? If yes please test if this happens with other kind of tempsummons created by an item aswell and assign a new issue to me for next week, then i can check :)

Anyway player should always get the credit now, no matter if a charm (the creatures summoned by the item) or a hunter pet of the player kills them

**Comment by Echinaceax** [comment] 2022-05-20 08:57
> The last mentioned issue is not created by my fix? New issue always? If yes please test if this happens with other kind of tempsummons created by an item aswell and assign a new issue to me for next week, then i can check :)

It wasnt on the report because it was working fine, i checked it for OP remember (OP didnt realize they had to use the pet bar)
so ofc i checked it, 

The extra issue i found was as i was testing the OP report

**Comment by Echinaceax** [comment] 2022-05-20 09:07
Confirmed fixed in PTR 

all fixed thanks @Rushor 

https://i.gyazo.com/51bdafb3f69f43c6b5ee09156d2fc97c.mp4
https://i.gyazo.com/3a6803244b9a408e5e7f899c97a5c6d8.mp4

**Comment by Rushor** [comment] 2022-05-20 13:13
alright thanks!

**Closed** 2022-05-21 10:32 UTC
Labels: Fixed on PTR - Tester Confirmed
