### ISSUE TITLE
[Dungeon] - Arthas, multiple issues, missing wave markers - The Culling of Stratholme

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6035] opened 2023-09-01 20:10 UTC
**Links:**

**What is Happening:**
Arthas can get stuck when doing the first pull in the town hall in Heroic Culling of Stratholme
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/caf816d2-6c75-498a-8adc-43b1af97fa34)
![image](https://github.com/WoWManiaUK/Redemption/assets/2725389/3bbc8739-2b5f-4de9-98e9-80692f271134)

**What Should happen:**
Arthas should move after each pull is defeated.

**Comment by bigchipbag** [comment] 2023-09-01 20:11
Not sure if it's relevant, but we defeated the first group very fast, and it seemed like one of the mobs spawned with half health.

**Comment by GMZinius** [comment] 2023-09-01 20:24
Thank you for reporting this issue @bigchipbag 
We have had tickets about this issue, nice to see someone reported it 
It will be checked out.

**Comment by Echinaceax** [comment] 2023-09-02 13:38
I did all waves without issue last night 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5814432c-bcea-4462-bc34-8c5bcb3f7ae4)


though it does seem from looking through the past reports https://github.com/WoWManiaUK/Redemption/issues/4390 that they couldnt reproduce it 

When a random bug happens like this its very hard to find the cause, this is why they closed it without a fix 

i will do my best to reproduce this when i can
1, What i did notice tho is, that Arthas sometimes is facing the wrong way when he does some of his dialogs

My theory atm is: I think that somehow the none skippable dialogs are actually skippable which is causing Arthas to be facing the wrong way and maybe this is what is causing him to bug out 

I will do more tests to see if im right, because from looking through other reports its clear that Arthas doesnt bug at the same point each time

**Comment by Lumber-Jack-2** [comment] 2023-10-08 10:58
Just a info: The wave marker cannot be added atm

**Comment by Lumber-Jack-2** [comment] 2023-10-08 11:32
- Arthas event start dialog takes 2 clicks (should be only once) > this works fine for me https://gyazo.com/d1d8b668c0b46b70de0ae70cc17e2fc0
 
 The position stuff for Arthas can be ignored for now because we have no option to change his orientation during his escort path atm

**Closed** 2023-10-08 13:56 UTC
Labels: Confirmed, Invalid - Intended/Blizzlike/As-Is/Won't fix
