### ISSUE TITLE
[Spell] Death Knight- Offhand Frost Strike and Threat of Thassarian interaction

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#5358] opened 2021-03-09 13:29 UTC
**Links:**
https://www.wow-mania.com/armory/?spell=55268
https://www.wow-mania.com/armory/?spell=66192
https://www.wow-mania.com/armory/?spell=50138

**What is Happening:**
DK ability Frost Strike while dual wielding is hitting with 100% damage with main hand and offhand.

**What Should happen:**
Main hand attack should do 100% of damage.
Offhand attacks should suffer 50% damage penalty that can be mitigated with Nerves of Steel talent that increases offhand damage by 25%, therefore bringing offhand damage to 62,5% before other damage increasing talents are taken into consideration.
This particular interaction was reported also on Blackwing Lair server. Talent is not changed in cataclysm, FS damage % is buffed in cataclysm.
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2531

Some screenshots, they are not 100% same due to RNG. Both MH and OH weapons were identical

![WoWScrnShot_030921_152500](https://user-images.githubusercontent.com/32513041/110477302-aa6ef380-80eb-11eb-846b-a806d1582c0f.jpg)
Second crit should be around 2555 with rough math if you calculate it from the first strike.

![WoWScrnShot_030921_150614](https://user-images.githubusercontent.com/32513041/110477038-5c59f000-80eb-11eb-9910-50d0977d88e5.jpg)

![WoWScrnShot_030921_152356](https://user-images.githubusercontent.com/32513041/110477212-90351580-80eb-11eb-8106-074587cbe352.jpg)
Second hit should be 2562 if you calculate it from MH. Obviously its calculated from offhand damage but to illustrate that its not 62,25%

**Comment by festerhowl** [comment] 2021-03-09 13:43
>Second hit should be 2562 if you calculate it from MH. Obviously its calculated from offhand damage
Exactly. Might need to crunch some numbers to check if its impossible for off-hand to hit 3808

**Comment by svijetlo** [comment] 2021-03-11 13:11
so after some testing i can openly say this only happen for Frost strike 
did all test wo Oh dmg mod talent so just Threat of Thassarian
so i did some hits lot of them with death strike those are cca numbers , (scared to post lot of ss so github does not lock me again) i also used crap weapons' to exclude any other effect and char was lvl 60 still 
death strike OH dmg 142 - Mh dmg 298 
plague strike OH 130 - Mh 305
blood strike OH 232 -Mh 540
FROST STRIKE OH 790 - mh 940 
i made small fight act on dummy and will post ss 
![image](https://user-images.githubusercontent.com/61908373/110792365-935b0d80-8273-11eb-9ab3-a8983c93d521.png)
i use addon for dmg Details so it counts MH and OH hit as same spell but in different bars

**Comment by festerhowl** [comment] 2021-03-11 15:55
![Screenshot (167)](https://user-images.githubusercontent.com/43633844/110814982-fbc7e000-82af-11eb-80a5-605fb90b1171.png)
could it be that the tooltip isn't updated and therefore causing confusion regarding the damage modifier of OH frost strike? I found this at https://wowwiki-archive.fandom.com/wiki/Threat_of_Thassarian

**Comment by Kilju** [comment] 2021-03-11 18:11
Warlords of Draenor Patch 6.0.2 (2014-10-14): Removed. Effects merged into [Might of the Frozen Wastes].
**Mists of Pandaria Hotfix (2013-03-05): "Threat of Thassarian now increases the damage of Frost Strike by 50% (was 40%)."
Mists of Pandaria Patch 5.0.4 (2012-08-28): Now given automatically to Frost death knights. No longer affects Rune Strike or Blood Strike, and causes Frost Strike to deal an additional 50% damage when dual wielding.**
Wrath of the Lich King Patch 3.2.2 (2009-09-22): Threat of Thassarian now also causes Rune Strike to use both weapons when dual-wielding.
Wrath of the Lich King Patch 3.2.0 (2009-08-04): Added.

**Comment by svijetlo** [comment] 2021-03-12 11:17
As kilju told change and my look around show it changes came much later

**Comment by Aristo14** [comment] 2021-03-17 21:43
I'm not a tester but I get some different results; 

![fstestuntalented1](https://user-images.githubusercontent.com/38132718/111542046-85c0ee80-8771-11eb-9cd0-2c96ee5078c7.png)

![fstestuntalented2](https://user-images.githubusercontent.com/38132718/111542078-907b8380-8771-11eb-913e-2d745b7ac102.png)

![fstestuntalented3](https://user-images.githubusercontent.com/38132718/111542109-9b361880-8771-11eb-8e75-5d153b0f403b.png)

This is without https://www.wow-mania.com/armory/?spell=50138

The weird thing is that this is actually very close to the  62,5%  even without the talent.

**Comment by Aristo14** [comment] 2021-03-17 21:47
![fstestnerves1](https://user-images.githubusercontent.com/38132718/111542535-27e0d680-8772-11eb-946f-fc533c48e423.png)

![fstestnerves2](https://user-images.githubusercontent.com/38132718/111542554-2dd6b780-8772-11eb-8638-6eee88562c3f.png)

![fstestnerves3](https://user-images.githubusercontent.com/38132718/111542579-33cc9880-8772-11eb-9593-4c3a894662d0.png)

This is WITH https://www.wow-mania.com/armory/?spell=50138

Same numbers overall 205mh  and 135oh  and again around 62,5% 

I tested without gear and statless weapons, without any talent interacting with FS or dmg. 

![fstesttree1](https://user-images.githubusercontent.com/38132718/111542807-7d1ce800-8772-11eb-939d-3e9315b412c5.png)
![fstesttree2](https://user-images.githubusercontent.com/38132718/111542819-81e19c00-8772-11eb-8936-a6f5c917ac34.png)

To me it seems to be working correctly WITH talent but not correct WITHOUT.

**Comment by jeyrella** [comment] 2021-03-17 22:04
So, since the above is on live...  what is it that we have actually fixed on PTR, if it wasn't broken in the way we thought it was?

Janitor, pls do not push this one live yet.  I believe we need to do more research/digging/testing to have 100% confidence we're doing the correct thing here.

**Comment by Aristo14** [comment] 2021-03-17 22:11
![Screenshot_4](https://user-images.githubusercontent.com/38132718/111544589-fb7a8980-8774-11eb-9af4-27b1ad6f00b5.png)

![Screenshot_4](https://user-images.githubusercontent.com/38132718/111544594-fd444d00-8774-11eb-93ac-9ced28e4500c.png)

Obliterate, Blood Strike, Death Strike  do not seem to interact with
![Screenshot_6](https://user-images.githubusercontent.com/38132718/111545017-ac812400-8775-11eb-8d2f-f7b813770eea.png)

![Screenshot_7](https://user-images.githubusercontent.com/38132718/111545241-0681e980-8776-11eb-916f-91f521aede3f.png)

Obliterate, Blood Strike, Death Strike and Plague Strike do not seem to interact with it at all. 

all tested same way and with the https://www.wow-mania.com/armory/?spell=50138 and  https://www.wow-mania.com/armory/?spell=66192

**Comment by jeyrella** [comment] 2021-03-17 22:19
This sounds like we're fixing the wrong thing, and maybe accidentally getting a better result?  

I don't know DKs so @svijetlo @hawker357 I need your full input on this one.

**Comment by Aristo14** [comment] 2021-03-17 22:34
Frost Strike seems to interact with https://www.wow-mania.com/armory/?spell=66192 + https://www.wow-mania.com/armory/?spell=50138 correctly to a 62,5% offhand level. 

Frost Strike seems to interact with the Nerves of Cold Steel even untalented. 

Obliterate, Plague Strike, Blood Strike and Death Strike do not seem to interact with nerves of cold steel at all and are even below a 50% off hand dmg level.  

The proposed issue was posted with gear etc and critted.. this might be related to crit but not the talents or abilities. (lot of posible interactions with the dmg outcome)

**Comment by Keader** [comment] 2021-03-17 23:54
"Description: When dual-wielding, your Death Strikes, Obliterates, Plague Strikes, Rune Strikes, Blood Strikes and Frost Strikes have a $s1% chance to also deal damage with your offhand weapon."

The issue here is about Threat of Thassarian making frost strike (OFF HAND) do ~100% of damage, like main hand.
And it's fixed.
If damage of frost strike (main spell) is wrong, it belong to another issue.

**Comment by Aristo14** [comment] 2021-03-18 00:33
Well on live my tests show it doesnt do 100% but the 62,5% regardless of having nerves of cold steel talented or not. 

Threat of Thassarian only makes it so that it actually hits with OH as well and on most abilities it doesnt even do 50%

**Comment by festerhowl** [comment] 2021-03-18 01:02
I didn't really think about doing my own research on this matter as @svijetlo had already confirmed the bug but i had to now after @Aristo14 provided new screenshots. I didn't use any talents that could affect damage on any of my abilities and i unequipped all gear and bought  2x Cutlass from stormwind city. Here are my results:
![Screenshot (203)](https://user-images.githubusercontent.com/43633844/111557426-a65d6880-87b2-11eb-8ca3-c259b05f40d8.png)

1. Without Nerves of Cold Steel:
 
![Screenshot (201)](https://user-images.githubusercontent.com/43633844/111557125-128b9c80-87b2-11eb-8fbe-146c41c5d61d.png)

The off-hand damage of Frost strike seems roughly around 62.5% without the talent when it should be 50%

2. With Nerves of Cold Steel:
 
![Screenshot (204)](https://user-images.githubusercontent.com/43633844/111557912-a1e57f80-87b3-11eb-98ae-32b1e4c71c01.png)


The off-hand Frost strike is still roughly 62.5% when the talent is taken and is therefore working as intended on live. pls revert any changes that may have been made to this spell. The problem now is not how the off-hand frost strike is doing 100% damage but rather why it is doing 62.5% damage without nerves of cold steel when it should be 50%

_I also noticed that plague strike, obliterate, blood strike and death strike off hand are doing less than 50% damage even when nerves of steel is taken, I will make a new report with the relevant screenshots unless @Aristo14  wants to._

**Comment by Aristo14** [comment] 2021-03-18 01:08
You came to exact same results @festerhowl thanks. 
I don't see how we can show it more clearly.

**Comment by Keader** [comment] 2021-03-18 01:12
Fuck this shit, you guys dont even know what is wrong or not, giving me wrong information.
I will not touch on this anymore, reverting everything.

**Comment by svijetlo** [comment] 2021-03-18 01:14
close post and in future if ppl are not sure and do not provide correct data form back in time i will not test it , sorry but you burn everyone time and i me not personal escort or tester for anyone

**Comment by Keader** [comment] 2021-03-18 01:14
Will be reverted tomorrow (i cant build tonight)

**Closed** 2021-03-18 01:52 UTC
