### ISSUE TITLE
[Raid] Sunwell Plateau - Kil'jaeden lacking mechanics

### ISSUE THREAD

**Issue by lindemiel** [WoWManiaUK/Redemption#5112] opened 2020-11-10 23:55 UTC
Link to boss: https://www.wowhead.com/npc=25315/kiljaeden
Link to Shadow Spikes: https://www.wowhead.com/spell=46589/shadow-spike
Link to Darkness of a Thousand Souls: https://www.wowhead.com/spell=46605/darkness-of-a-thousand-souls
Link to Dragon Orbs: https://www.wowhead.com/npc=25653/power-of-the-blue-flight

During the third phase of the Kil'jaeden boss fight (final in instance), something called Orbs of the Blue Dragonflight are supposed to spawn that can turn players into dragons with a set of skills. One of these skills is a shield (Shield of the Blue), which is essential for surviving one of Kil'jaeden's skills called Darkness of a Thousand Souls that does a massive amount of unavoidable damage to the entire raid party. Without these dragon orbs, killing Kil'jaeden is essentially impossible without completely nuking the boss with a full team or a group of fully geared people. Most players (non-plate especially) are immediately one shot by it.

To clarify, phase one involves the fight against the Hands of the Deceiver. Once they are dead, Kil'jaeden arrives and begins phase two. When he is at 85%, he begins phase three. The dragon orbs are supposed to begin to appear after the Shadow Spikes have finished. 

We have done this raid twice now and both times no dragon orbs have ever spawned.

**Comment by Oganku** [comment] 2020-11-11 00:36
I confirm that fight is lacking some mechanics, including the orbs. I'll check on PTR to confirm exactly, but it does make phase 3 way harder since you can't really survive darkness of a thousand souls without the shield.

**Comment by Oganku** [comment] 2020-11-11 04:08
1. The 3 Hands of the Deceiver that consist of phase 1 of the fight are all double spawned. Therefore players have to face 6 instead of the intended 3. 3 of them appear as dummies and do not respawn if you wipe, nor do they activate phase 2 upon death. They should be simply deleted. 
![image](https://user-images.githubusercontent.com/34783736/98762726-4c810800-23a6-11eb-8383-531081f78eab.png)
The dead ones are the one that shouldn't exist

2. The [Shield Orbs](https://www.wow-mania.com/armory/?npc=25502) that orbit KJ path properly, but they stick to the ground, making them attackable by melee. From https://youtu.be/Uf7j4IIIZrU?t=128 , we can see that they are definitely meant to fly and be dealt by ranged. Tactics and guides also mention that aspect. They properly go from 1 to 2 to 3 spawned depending on the phase.

3. After reaching 85% KJ properly starts channeling [Shadow Spike](https://www.wow-mania.com/armory/?spell=46589) but interrupts the cast after a few seconds (about 3, presumably when the first missile should be fired). The channel is supposed to last for 28 seconds, during which the raid is periodically bombarded by shadow spikes. He will not use any other spells during the remainder of the channel and just sit there kinda stupidly doing nothing for ~25 seconds, after which he resumes his usual spells.

4. Last but not least, the [Orbs of the Blue Dragonflight](https://www.wow-mania.com/armory/?object=188114#spells) that play a big role in the 3rd to 5th phases of the fight, are missing altogether.
![Orbs](https://user-images.githubusercontent.com/34783736/98763425-fe6d0400-23a7-11eb-9425-30b076b7d8ff.png)
You can easily see the 4 orbs periodically throughout the fight in [this video](https://www.youtube.com/watch?v=Uf7j4IIIZrU). Screenshot above taken from said video.

The 4 orbs are meant to be visible all the time, but become empowered (usable) only upon certain conditions. Upon finishing the first cast of Shadow Spikes after reaching 85% HP, one of the 4 orbs should randomly become empowered (usable) and grant the raid with 1 use of the dragon power (2 casts of [Shield of the Blue](https://www.wow-mania.com/armory/?spell=45848) per dragon). This ability is how the raid is meant to survive [Darkness of a Thousand Souls](https://www.wow-mania.com/armory/?spell=45657). After reaching 55%, Shadow Spikes is cast another time, after which another orb becomes empowered. Finally, after reaching 25%, a last set of (broken) Shadow Spikes is cast, after which Anveena starts some roleplay. At the end of it, she sacrifices herself and all 4 orbs should become usable.

The buff granted upon using an orb is the following: [Power of the Blue Flight](https://www.wow-mania.com/armory/?spell=45833) and grants multiple abilities: [Blink](https://www.wow-mania.com/armory/?spell=45862), [Breath: Revitalize](https://www.wow-mania.com/armory/?spell=45860), [Breath: Haste](https://www.wow-mania.com/armory/?spell=45856) and [Shield of the Blue](https://www.wow-mania.com/armory/?spell=45848) (can only be used max 2 times per buff). 

**Note: All hyperlinks for spells from this comment refer to the spell, object or NPC on wow-mania armory.

**Comment by Rushor** [comment] 2020-11-16 22:09
I can only fix point 1 and 2 for this week - rest will be done next week

**Comment by Rushor** [comment] 2020-11-16 22:15
1. and 2. issue fixed

**Comment by Rushor** [comment] 2020-11-16 22:16
3 and 4 will be fixed within next week

**Comment by Oganku** [comment] 2020-11-16 22:42
1 and 2 confirmed fixed.

**Comment by Oganku** [comment] 2020-11-18 22:14
Re-opening for 3 and 4. Issue 4 being the most important of the two.

**Comment by Rushor** [comment] 2020-11-23 19:36
will be set on hold for next week - this is much more complicated than expected

Status: On Hold for next Week. I will return to this!

**Comment by Oganku** [comment] 2020-11-27 23:03
@Rushor http://trinitycore.github.io/codebrowser/TrinityCore3.3.5/src/server/scripts/EasternKingdoms/SunwellPlateau/sunwell_plateau.h.html#DataTypes::DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_2

https://trinitycore.net/dir_1c9635b3a0e2edad59d2e8fbac3428dd.html

https://gitlab.com/trinitycore/TrinityCore_434/blob/4d0031bbd3511bdbbc01e4166811c892f4584d54/src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp

This might be useful, or maybe not. Just sharing in case it is.

**Comment by Rushor** [comment] 2020-12-02 10:19
thanks yes, that is the script where we are fixing it :>

**Comment by Oganku** [comment] 2020-12-02 18:20
Just to remember

**Comment by wow-mania** [comment] 2020-12-02 18:36
Marking as regression since this was previously fixed and closed.

**Comment by Oganku** [comment] 2020-12-02 18:39
![image](https://user-images.githubusercontent.com/34783736/100916321-93dd4e80-34a3-11eb-8b21-cab5c9887f7d.png)
![image](https://user-images.githubusercontent.com/34783736/100916349-9cce2000-34a3-11eb-8a0d-7df518348ac3.png)

Original issue (4), and most important one, still persists. Issue is more complicated than expected so it has not been fixed yet.

**Comment by jeyrella** [comment] 2020-12-04 12:36
This is not a regression, it's a split-week fix due to multiple issues and amount of work.  Perhaps it might have been better to split into two tickets, but they are related.

**Comment by Rushor** [comment] 2020-12-06 17:42
1. Shadow Spike will now be casted to random raid member

2. Orbs are spawned now. By default all orbs can not be used. At 85 percent hp, 35 seconds after Shadow Spike channel, one orb can be used one time. At 55 percent again, 35 seconds after Shadow Spike channel, one orb can be used. At 25 percent, 35 seconds after Shadow Spike channel, all 4 orbs can be used.

The usable orbs get a blue visual at the button. Orbs can only be used one time during phase by one player. The will summon a drake one one time per fight. The dragon is freindly now towards player and has 4 abilities.

On reset of the boss or on death all drakes and visuals will be despawned.

**Comment by Oganku** [comment] 2020-12-06 19:41
Issue 3 fixed confirmed. https://imgur.com/a/4hkmGAc 

Issue 4 fixed confirmed. https://imgur.com/a/Cu2zagH 

Awesome work for this fight overall! Just waiting for authorization to tag it as confirmed.

**Closed** 2020-12-08 10:44 UTC
Labels: Fixed on PTR - Tester Confirmed
