### ISSUE TITLE
[NPC] Crazed Colossus - Dissension Amongst the Ranks... 

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6031] opened 2023-08-20 17:14 UTC
https://www.wow-mania.com/armory/?quest=10776
https://www.youtube.com/watch?v=wMwo7V7_MYc

Slaying the giants in the disguise doesn't give credit.
They should also shrink and spawn the shardlings as they weaken. 

See the video above.
As they weaken they should shrink and spawn the shardlings, and when I kill the colossus in the disguise I should get the credit.

**Comment by Echinaceax** [comment] 2023-08-20 17:44
thanks for reporting @stealer0517 
I see no problem with the quest credit 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/db75c57f-481b-4198-9af6-e888ff18aa89)

But issues with this part @Rushor 
- [ ] Crazed Shardling NOT being summoned https://www.wow-mania.com/armory/?npc=21936#summoned-by
- [ ] Crazed Colossus not going smaller (that could be due to no Crazed Shardling spawning)

**Comment by stealer0517** [comment] 2023-08-20 17:47
The credit issue may be because I'm needing someone else to help kill these elites. 
I've tried the normal being in a group and getting carried, and I've tried not being in a group, doing first damage, then getting carried but I'm still at 0/5.

**Comment by Echinaceax** [comment] 2023-08-20 17:53
I can log my ally char and see whats going on if you like?

**Comment by stealer0517** [comment] 2023-08-20 17:59
yeah we can try that.

**Comment by Echinaceax** [comment] 2023-08-20 18:00
> yeah we can try that.

Be there in 5 mins only Sashia

**Comment by Echinaceax** [comment] 2023-08-25 12:08
Confirmed fixed on PTR 

spawns Crazed Shardling each calculated % of his health, and Crazed Colossus reduces size each time one is spawned

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0822e4df-3d5f-43a1-801a-286510a8a2c4)

**Closed** 2023-08-25 13:58 UTC
Labels: Fixed on PTR - Tester Confirmed, Code Change, AIScript Change
