### ISSUE TITLE
[Talent] Bloodworms

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2558] opened 2018-06-25 17:14 UTC
![bloodworm](https://user-images.githubusercontent.com/16576459/41864517-f85d7542-78b2-11e8-8480-41a196fa2e0a.png)

The worms aren't properly scaling per level/AP, as 20-35 damage is too low for a level 80 environment.

Based on a retail video: https://youtu.be/my9wslCEfl8?t=3m34s
If you look closely, every notification of orange "pet [#hits]" is worms, so if it's 200 and 2 hits, each worm is dealing 100 damage and the range of the worm damage is usually 103-110 in that video, sometimes critting, sometimes reaching 120 so technically average dmg is 110.

Talent ID: http://www.wow-mania.com/armory/?spell=49027 R1 / http://www.wow-mania.com/armory/?spell=49542 R2 / http://www.wow-mania.com/armory/?spell=49543 R3

ID of Bloodworms: http://www.wow-mania.com/armory/?npc=28017

**Comment by Keader** [comment] 2018-06-25 19:00
This issue is real, but i realy dont know how fix it.
It should be fixed by pet stat system, but it is not ready.
Even hackfix, last time that i try fix it i make bloodworm overpower.

**Comment by Ashamedlol** [comment] 2018-06-25 19:38
I tried using Horn of Winter after they spawned, their damage increased to 60.

Aren't you able to modify their damage based on buffs since their scale's messed up?

**Comment by Keader** [comment] 2018-06-25 19:45
I will try think in some formula with @Dranah =(

**Comment by Dranah** [comment] 2018-06-25 20:22
The issue is that the problem is twofold.
While they don't properly scale with your attack power (do less damage when testing alone, like on ur screenshot), they do scale with raid buffs that aren't even meant to affect them (i.eg. STR of earth totem, trueshot aura etc.).
This results in their damage output being nearly "intended" in a raid environment, and the problem with the poor AP scaling only appearing when the DK is soloing/pvping.
So if you simply modify their AP scaling, it WILL make them overpowered in parties, since there is an opposite kind of scaling issue with raid buffs.

**Comment by Ashamedlol** [comment] 2018-06-25 21:29
But they shouldn't benefit from raid buffs, is that adjustable? I saw that they don't get improved talons from an old post for example.

**Comment by Ashamedlol** [comment] 2018-06-27 12:33
![donezo](https://user-images.githubusercontent.com/16576459/41974016-681049c4-7a1f-11e8-996d-24327dfc8829.png)

@Dranah This is nowhere near "intended", still the same result inside an ICC.

**Comment by Keader** [comment] 2018-06-28 14:01
Someone can test?
In my sniffs show 250-350 of damage.
I make a DK full geared and got 250-350 too
Looks close of correct now

**Closed** 2018-06-29 07:38 UTC
Labels: Confirmed, Fix Confirmed in Dev, Fixed in Dev
