### ISSUE TITLE
[Dungeon] Halls of Reflection - event resetting

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4483] opened 2020-04-23 01:54 UTC
**Links:** http://www.wow-mania.com/armory?zone=4820

**What is Happening:** While doing the waves between the first two bosses, if a player is stood near a wall and the mercenary mob does shadowstep on him, it will reset the waves and bug the dungeon.

**What Should happen:** Incoming add waves should not reset and the dungeon should not bug out. Shadowstepping mobs should not go behind the wall (assuming that this is what's causing it)

**Comment by svijetlo** [comment] 2020-04-23 02:02
bit of known issue , some other problem that made it were fixed 
will have to check that one tomorrow also 
but if you run to enter of dung and run back to middle it will reset the encounter form 1 , if you did one boss it wont reset boss fight

**Comment by Keader** [comment] 2020-04-23 02:04
we need a reproduce steps.

**Comment by svijetlo** [comment] 2020-04-23 02:05
yes pls what race-class -speck 
all info we can get as that is not sure to reset it i seen on ptr rogue enemy half in wall and no reset

**Comment by bLeyaa** [comment] 2020-04-23 02:09
Well reproduce step would be to stand by the wall and get the mob to shadowstep you? Don't know how exactly it happens, i know i've had it happen couple of times.

Last time it happened i think it was the hunter that was by the wall, MM spec i believe, dont know the race but it was horde. Faction shouldnt matter as i had it on alliance as well. Don't know if maybe his feign death could affect it?

**Comment by svijetlo** [comment] 2020-04-23 02:12
i did that all cant find old post now , race matters as shadomeld did reset fight if you do it between waves as i told i seen rogue enemy half in wall and it did not reset will just try tomorrow again

**Comment by svijetlo** [comment] 2020-04-23 02:17
https://github.com/WoWManiaUK/Redemption/issues/4192

https://github.com/WoWManiaUK/Redemption/issues/4086

**Comment by bLeyaa** [comment] 2020-04-23 02:18
It was today, around 22:00 server time

**Comment by svijetlo** [comment] 2020-04-23 02:18
will go tomorrow again if it is form that mob till better fix just remove him ability

**Comment by bLeyaa** [comment] 2020-04-23 02:31
Well, now that you mention these spells, they might be the trigger as well. Spells such as feign death / vanish / invisibility / shadowmeld....

**Comment by svijetlo** [comment] 2020-04-23 02:34
Spells such as feign death / vanish / invisibility / shadowmeld.... they all reset aggro / target  i tested all of those they no longer reset fight

**Comment by Oganku** [comment] 2020-04-23 03:16
Just hug the walls in the little alcove where people LOS and make sure your back is right against the wall. If you get targeted by mercenaries and they shadowstep to you, they will fall through the map and reset the waves. You then have to walk to the center to restart from wave #1. A shaman casting thunderstorm can also push mobs outside the walls if they're barely outside (clipped partially into them).

**Comment by jeyrella** [comment] 2020-04-23 03:34
Mercenary shadowstepping was the exact issue that was supoosed to be fixed in #4086 by @Keader .  Did seem to be resolved at the time.  Perhaps there is some regression with some of the patches being reverted?

@Keader - perhaps might be good to check the map protection boundaries as a start, see if they have changed back from 4086's fix...

**Comment by Rushor** [comment] 2020-04-23 06:56
some code has been reverted at some point. maybe it just got lost

**Comment by svijetlo** [comment] 2020-04-23 13:31
i em there atm , i em kissing wall with my back and shadow mercenary if he does his shadowstep atm can not pass wall he just stay in front of me if there is no room behind me

**Comment by bLeyaa** [comment] 2020-04-23 13:44
Are you doing it alone or in a group with someone? Testing it alone may not have the same effect as you're the only and primary target to them...

Also, try the walls around the area where the doors open when you continue towards Lich King event, that's where it mostly happens to me. Not that those walls should be any different between each other but idk...

**Comment by mamgy** [comment] 2020-04-23 13:52
Last time, when HoR did reset for me, there was no mercenary. So maybe its not mercenary that is causing encounter to reset this time.
Mage is making a copy of himself while he blinks/teleports to different location.

**Comment by svijetlo** [comment] 2020-04-23 13:55
yes been to area in back where you continue the dung to Lk also invited my alt on other acc here , been with all other adds that can spawn

**Comment by bLeyaa** [comment] 2020-04-23 14:19
@mamgy has a point

**Comment by bLeyaa** [comment] 2020-04-23 15:56
Dunno if this helps anything... not the best angle...

Priest / Mage / Mercenary are alive... https://youtu.be/hHHEjN-efqQ?t=90

Also, found this guy dead behind the doors towards Lich King event, after 2nd boss was killed (once we eventually got to clear the 10 waves)... Dunno if it matters, or if he's usually there... i haven't noticed lol

![WoWScrnShot_042320_175152](https://user-images.githubusercontent.com/61625377/80120721-b44b3f00-858b-11ea-850d-f774a8175f61.jpg)

**Comment by svijetlo** [comment] 2020-04-23 16:00
he is there it is part of dung he was in  group with jaina and 2 other that run forward and he gets killed

**Comment by svijetlo** [comment] 2020-04-23 16:07
ok ok ok , did mage of your group use that talent of his for those clones idk name of skill, if so one might be phased out and if they try to attack it , as i seen rogue shadowstep mage of your group then runs back to tank then it resets

**Comment by bLeyaa** [comment] 2020-04-23 16:14
The resto druid is standing straight behind the mage, against the wall.... I think the mercenary did shadowstep on him and then run back to tank when it reset... Mage from what i can see did not use mirror images if thats what you're thinking

**Comment by svijetlo** [comment] 2020-04-23 16:16
ye ye just watched it on 0.2 speed this is rly strange , nothing was out trou wall or smt like so i rly can not figure out what might cos it

**Comment by Keader** [comment] 2020-08-02 17:22
Looks like @jeyrella got a way to reproduce, caused by mage hallucination.
I'm disabling hallucination spell, since it's a invisible spell, and always cause evade on npc.
check if waves still reset @jeyrella

**Closed** 2020-08-04 08:14 UTC
Labels: Fix - Ready to Test
