### ISSUE TITLE
[Quest] Kickin' Nass and Taking Manes

### ISSUE THREAD

**Issue by MihailoVasovic** [WoWManiaUK/Redemption#1495] opened 2017-08-17 13:48 UTC
Issue is same as https://github.com/WoWManiaUK/Redemption/issues/325

**Comment by captainloozer** [comment] 2017-08-17 14:41
Greetings, MihailoVasovic!  Thanks for your report.

I was not able to reproduce this issue.  I tested by using the quest tracker link of the boot as well as using the boot directly from the bag, each produced the intended result of Nass moving towards the dead NPC and giving credit.  If you are able to reproduce the issue, especially with more information of exactly how you are attempting to interact with Nass using the quest item (directly from the bag or from quest tracker), please feel free to report again.

![nass1](https://user-images.githubusercontent.com/9828794/29417768-f3c7cd4e-832f-11e7-9fc2-02c5c528e8c6.png)

**Comment by tvshadowz** [comment] 2017-08-17 14:41
This was tested with me there.

**Closed by tvshadowz** 2017-08-17 14:41 UTC

**Comment by MihailoVasovic** [comment] 2017-08-17 16:01
I reloged, and it worked. Don't know what was problem

**Comment by captainloozer** [comment] 2017-08-17 17:31
MihailoVasovic, thank you for responding with that information.  Glad to hear that it was fixed for you after logging out and then back in.
