### ISSUE TITLE
[Spell] Attuned to Nature 10 Dose Reduction - Freya -Ulduar

### ISSUE THREAD

**Issue by Nimsy** [WoWManiaUK/Redemption#1623] opened 2017-09-15 19:29 UTC
Issues with Freya (10man Version)
http://www.wowhead.com/npc=32906

When you fight Freya the adds that she summons adds which you must kill to reduce her stacks of Attuned to nature (http://www.wowhead.com/spell=62519). 2 types of adds work as intended and remove stacks of this buff once killed. The third type (when she summons a water spirit, storm lasher, and snaplasher) do not remove stacks once killed and this makes her impossible to defeat.

**Comment by captainloozer** [comment] 2017-09-16 22:37
Hi Nimsy, and you thank you for your report.

I filmed about 5 minutes of the fight so the effects can be seen by everyone.  Most of the fight works as intended.  Here is the description of how many stacks of http://wow-mania.com/armory/?spell=62519/ Attuned to Nature should be removed by killiing each mob near her:

Conservators by 25
Detonators by 2 (each)
Ancient Water Spirit by 10 http://wow-mania.com/armory/?npc=33202
Storm Lasher by 10  http://wow-mania.com/armory/?npc=32919
Snaplasher by 10 http://wow-mania.com/armory/?npc=32916

Once she has no more of this buff left, phase 2 begins.  If all three are killed next to her, she should lose a total of 30 stacks.  As can be seen in the video at 2:13, these three mobs are not removing stacks.

Freya uses this spell to summon these three mobs http://wow-mania.com/armory/?spell=62686

The spell used to remove 10 stacks from her is http://wow-mania.com/armory/?spell=62525

I'd imagine that if you're lucky enough to get a bunch of conservators and detonators instead, you could probably finally push to stage 2, but the fight should not last nearly this long if it were working correctly.

I also found this code which is relevant to how this mechanic works, maybe it will be of some use to you
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Northrend/Ulduar/Ulduar/boss_freya.cpp

**Comment by captainloozer** [comment] 2017-09-17 12:51
Tried again this morning, these three NPC's are still not applying the 10 dose reduction.

https://youtu.be/IHie1q3E5Fw

**Comment by captainloozer** [comment] 2017-09-17 14:34
Tested again, 

Ancient Water Spirit  http://wow-mania.com/armory/?npc=33202
Storm Lasher  http://wow-mania.com/armory/?npc=32919
Snaplasher http://wow-mania.com/armory/?npc=32916

Currently killing these 3 mobs still does not apply http://wow-mania.com/armory/?spell=62525

**Comment by captainloozer** [comment] 2017-09-17 15:42
With the lastest change, none of the adds are removing stacks anymore.

**Comment by fvicaria** [comment] 2017-09-18 07:39
Fixed in dev.

**Closed** 2017-09-18 09:16 UTC
Labels: Confirmed, Fixed in Dev, Tweaking

**Comment by captainloozer** [comment] 2017-09-18 13:44
Confirmed working in dev.  All adds during boss encounter remove the correct amount of stacks.
