### ISSUE TITLE
[spell] {DK} Death Grip

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5334] opened 2021-03-01 14:33 UTC
Issues: 1. Mobs after being aggroed by death grip stop in mid-air to cast their spells instead of being fully pulled to the caster.
            2. Sometimes the spell doesn't work on mobs and even players despite them not resisting the spell/ being untapped. 
           3.. Death grip has a bugged animation that makes the target(mostly players) teleport to you instead of being pulled to you.(there is also a delay in the time it takes for the target being teleported to the caster)
           4. Gripping any mob who is casting a spell does not interrupt them like it does to a player.

if you have ever played a dk and tried to grip the skeletal mages at the start of icc you will have noticed most of these issues pretty easily. I don't know how many times the death grip bugs have been reported here - i see a fix for this spell in almost every other changelog but somehow it still returns to being buggy

**Comment by jeyrella** [comment] 2021-03-01 15:25
fester, pls cut the attitude a bit, we're here to help.  no need to antagonise.  often these issues are with mob issues which is why it "keeps coming back" as they're looked at on one-by-one basis

it also helps us a LOT more if you can give some kind of reference, or screenshot of it happening.  the more detail/evidence you give, the quicker & easier it is to resolve it

points 1, 2 and 4 are hard to test & reproduce if you cannot give specific examples
point 3 may be intended.  if deathgrip is resisted then you go to the player, not the other way around.  need some evidence that shows this happened even when it was not resisted.

**Comment by festerhowl** [comment] 2021-03-01 17:56
> fester, pls cut the attitude a bit, we're here to help.

see now you are escalating things. i was genuinely curious about what could have gone so wrong with that spell, that after so many fixes its still bugged. If i wanted to antagonize, it would've been way more obvious trust me. But anyways, that was not the point of the post.

>points 1, 2 and 4 are hard to test & reproduce if you cannot give specific examples

1. Try to aggro any mob that can cast a spell. Any mob in a northrend dungeon or raid, for example the servants of the throne(skeletal mages) at icc. When you death grip them out of combat they stop mid-air and start casting their respective spells. Sometimes even after you grip them when their spell is on cooldown, they will try to return to their original spot. 
2.  2nd issue is rare and has only happened to me twice- one in an rbg when i was trying to grip a mage, and the other time when i was trying to grip a dungeon mob.
3. you don't go to the player if they resist death grip, that happens when they reflect your spell such as warriors using spell reflection or others using a specific meta gem.
4. while checking issue 1, wait for the mob to begin casting a spell and death grip it.

**Comment by Keader** [comment] 2021-03-06 21:11
Fixed.
Animation cancel, nothing that i can do about it.
Fixed interrupt and fixed issue with gripping npcs like skeletron mage of icc

**Comment by bLeyaa** [comment] 2021-03-07 10:25
Related to 2nd mentioned issue in the OP please check the faction champions fight in TOGC as Death Grip fails very very often there for some reason.

**Comment by hawker357** [comment] 2021-03-07 23:41
Have tested in ICC on PTR, all skeletons are death gripped as expected, inturrpting abilities and pulling the mob to the player.
The Ymirjar Huntress is having issues only while casting Rapid Shot (71251), it will interrupt and start to pull the mob, but the mob will stop mid-air and run around a bit before running to the character.

**Comment by Keader** [comment] 2021-03-07 23:54
> Have tested in ICC on PTR, all skeletons are death gripped as expected, interrupting abilities and pulling the mob to the player.
> The Ymirjar Huntress is having issues only while casting Rapid Shot (71251), it will interrupt and start to pull the mob, but the mob will stop mid-air and run around a bit before running to the character.
> 
> https://www.wowhead.com/spell=71251/rapid-shot
> https://www.wowhead.com/npc=37134/ymirjar-huntress

nice, will check it now

**Comment by Keader** [comment] 2021-03-08 01:29
Fixed your case hawker

**Comment by jeyrella** [comment] 2021-03-08 17:21
This was confirmed fixed by Svijet, whose github account has become corrupted.

**Comment by hawker357** [comment] 2021-03-08 22:21
I'll do another sweep of ICC trash in case I missed anything, I think there's a mob along with the other Ymirjar NPCs that need checking other than the huntress'.

Still need to check the faction champions in ToC5 too.

**Comment by bLeyaa** [comment] 2021-03-08 22:24
Correction, it's the TOGC raid, not dungeon :)

**Comment by hawker357** [comment] 2021-03-09 11:22
Just retested the ICC trash, the Huntress is still inconsistent with DG, even when not casting Rapid Fire.

All other mobs are working fine, full sweep done.

**Comment by hawker357** [comment] 2021-03-09 13:08
Seem that the taunt mechanic of DG is broken on the Horde Champions in TOGC normal:

Liandra Suncaller
Narrhok Steelbreaker
Erin Misthoof
Ginselle Blightslinger
Caiphus the Stern
Maz'dinah
Broln Stouthorn
Gorgim Shadowcleave

The pull animation is also quite inconsistent on all of them.

**Closed** 2021-03-11 10:19 UTC
Labels: Fixed on PTR - Tester Confirmed

**Comment by festerhowl** [comment] 2021-03-11 11:22
>  Also DG doesn't seem to interrupt any abilities, will need to confirm if this is blizzlike

are the issues fixed in ptr? look like the report got closed

**Comment by Keader** [comment] 2021-03-11 11:24
since it's bad script cases, i need go into each case and do a fix...
so, i will continue this week.
