### ISSUE TITLE
[Achievement] Winter Veil - Simply Abominable

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#1951] opened 2017-12-15 18:06 UTC
achievement=279

Upon completing "Stolen Winter Veil Treats" quest chain (http://wowwiki.wikia.com/wiki/Quest:Stolen_Winter_Veil_Treats_(Horde)) the player recieves a special gift from "Great-Father Winter" in org (npc=13445) and SHOULD be awarded "Simply Abominable". 

Currently on redemption the quest chain (H) does not award this achievement upon completion.

**Comment by fvicaria** [comment] 2017-12-15 18:10
Please use Armory or in the worst case wowhead.com for links.

**Comment by fvicaria** [comment] 2017-12-15 18:12
That quest on its own gives no achievement.
Check the required criteria here:
http://www.wow-mania.com/armory/?achievement=279

**Comment by squalllh1989** [comment] 2017-12-15 18:30
please, what the archivement said is: "Complete the quest to retrieve Smokywood Pastures' stolen treats and receive a Smokywood Pastures' Thank You." it mean that after you complete the quest and get your "thank you" reward (which is a gift box), you should have the archivement.

**Comment by squalllh1989** [comment] 2017-12-15 18:32
and please notice that i already completed  ["A Smokywood Pastures' Thank You!"](http://www.wow-mania.com/armory/?quest=6984) which is the requirement for the archivement

**Comment by fvicaria** [comment] 2017-12-15 18:38
It works.
![image](https://user-images.githubusercontent.com/9414661/34055463-21f57c20-e1c7-11e7-90f1-51291ba83bec.png)

**Comment by squalllh1989** [comment] 2017-12-15 18:43
did you tested it on horde side ? because i just completed the quest and didn't have the achivement

**Comment by hotdoggidy** [comment] 2017-12-15 18:47
I completed it on Redemption about 2 hours ago and did not get the achievement. When i asked a GM for credit they said i did not have the quest completed in my log. 

Am i now stuck with no quest AND no achieve?

**Comment by fvicaria** [comment] 2017-12-15 18:49
I did it on Redemption 5 minutes ago.

**Comment by squalllh1989** [comment] 2017-12-15 18:50
yeah the problem is that we didn't have it and we have completed the quest, now what can else can we do lol

**Comment by squalllh1989** [comment] 2017-12-15 18:51
i will try to find out why in dev then

**Comment by fvicaria** [comment] 2017-12-15 18:51
A GM needs to remove a quest from you. He can do that even if you have already completed it. It's as if you have never done it.

**Comment by hotdoggidy** [comment] 2017-12-15 18:55
Weeble was with me. told me he could NOT see the quest credit in my log. it IS as if i never did the quest but i completed it a couple hours ago. i still have the mageroyal from the gift.

How can it be removed if he cant see it?

**Comment by fvicaria** [comment] 2017-12-15 18:57
It can. It's GM magic. :)

**Comment by fvicaria** [comment] 2017-12-15 18:57
Have you changed faction on this char? If so he may need to remove both versions.

**Comment by hotdoggidy** [comment] 2017-12-15 18:58
never. stoner is horde forever. i didnt get achievement last year either

**Comment by squalllh1989** [comment] 2017-12-15 19:05
Ok i found out the problem:
- What should happen: after complete the quest [You're a Mean One...](http://www.wow-mania.com/armory/?quest=6983), it should open up [A Smokywood Pastures' Thank You!](http://www.wow-mania.com/armory/?quest=6984) and after you complete that quest, it give you the achivement.
- What acually happened: after complete the quest [You're a Mean One...](http://www.wow-mania.com/armory/?quest=6983), it open up [Treats for Great-father Winter](http://www.wow-mania.com/armory/?quest=6962) which the reward given is just a [Smokywood Pastures Gift Pack](http://www.wow-mania.com/armory/?item=17727), that is the reason you can get the achive, as you add it yourself and complete it, not follow the quest chain, and we didn't get the achive and stonne haven't ever complete it, as the chain give us the wrong quest.

**Comment by squalllh1989** [comment] 2017-12-15 19:06
and we was confused by it, as the reward of it is  Smokywood Pastures Gift Pack, which really should be "A Smokywood Pastures' Thank You!"'s reward :v

**Comment by squalllh1989** [comment] 2017-12-15 19:08
also the quest  [Treats for Great-father Winter](http://www.wow-mania.com/armory/?quest=6962) should have no requirement to open up, as everyone that doesn't completed [You're a Mean One...](http://www.wow-mania.com/armory/?quest=6983) will just see a yellow ! mark over the npc but can't take the quest out.

**Comment by fvicaria** [comment] 2017-12-15 19:20
Not true. It's all exactly as you said.
I will check a brand new char again but in the db it is all correct.

**Comment by squalllh1989** [comment] 2017-12-15 19:23
yeah i tried on my test char on dev and that's what happened, i didn't add the quest  "A Smokywood Pastures' Thank You!" but only add  "You're a Mean One..." and didn't have the achivement after complete what the chain give me

**Comment by hotdoggidy** [comment] 2017-12-15 19:48
same as Squall, didnt get the appropriate quest. Gm reset "Your'e a mean one..." so i could try again but no beans.

**Comment by fvicaria** [comment] 2017-12-15 19:52
![image](https://user-images.githubusercontent.com/9414661/34058010-6de17698-e1d1-11e7-9bb3-398e1c83a237.png)

You have to do  "Your'e a mean one..." first

**Comment by fvicaria** [comment] 2017-12-15 20:02
Do it with a clean char and in order. It works.

**Comment by squalllh1989** [comment] 2017-12-15 20:30
Ok this is what i was do: i start the quest chain, with ["Stolen Winter Veil Treats"](http://www.wow-mania.com/armory/?quest=6963), after i complete it, it open up ["Your'e a mean one..."](http://www.wow-mania.com/armory/?quest=6983), i complete ["Your'e a mean one..."](http://www.wow-mania.com/armory/?quest=6983), and this time, [Kaymard Copperpinch](http://www.wow-mania.com/armory/?npc=13418), the npc that i just turn in ["Your'e a mean one..."](http://www.wow-mania.com/armory/?quest=6983), DID NOT give me  ["A Smokywood Pastures' Thank You!"](http://www.wow-mania.com/armory/?quest=6984), i just test it again in dev, it still doesn't work.

**Comment by fvicaria** [comment] 2017-12-15 20:40
Can you try alliance side on dev please.

**Comment by squalllh1989** [comment] 2017-12-15 22:07
quest line work perfectly fine on alliance side
![wowscrnshot_121617_050637](https://user-images.githubusercontent.com/27235989/34062402-fa33c46e-e21e-11e7-9162-52ff8f3cf0d7.jpg)
![wowscrnshot_121617_050700](https://user-images.githubusercontent.com/27235989/34062403-fb64205e-e21e-11e7-861f-fc0a0af1a865.jpg)

**Comment by squalllh1989** [comment] 2017-12-15 22:25
It work on horde side now also in dev

**Comment by fvicaria** [comment] 2017-12-15 22:28
Thank you. I will compare both.

**Comment by hotdoggidy** [comment] 2017-12-15 22:28
https://youtu.be/7YqdFo9feT4 My attempt on a different toon Horde side.

**Comment by squalllh1989** [comment] 2017-12-15 22:39
It's fixed on dev now, to make sure that this is a bug and not my mistake, i redo what i did (and was good) in dev on other toon on redemtion and this problem still persis at the end: after completed  "Your'e a mean one...", the quest giver still doesn't give me  "A Smokywood Pastures' Thank You!". So we should wait for the next update to be able to get the achivement.

**Comment by fvicaria** [comment] 2017-12-15 22:40
Awesome that helped a lot. It was a faction mask issue. Easy fix, just difficult to spot. :)

**Closed** 2017-12-16 12:31 UTC
Labels: Fixed Confirmed in Dev

**Comment by hotdoggidy** [comment] 2017-12-16 16:44
Working perfectly Horde side on Redemption now. Thanks for quick fix. happy holidays!
