### ISSUE TITLE
Able to reproduce the Southsea Freebooter sap shooting bug

### ISSUE THREAD

**Issue by Wulfsg** [WoWManiaUK/Redemption#1610] opened 2017-09-14 04:27 UTC
"I noticed that while I was out killing Southsea Freebooters for the quest "Southsea Shakedown" in Tanaris, if you sap them to kill the target next to them, they can still shoot, while not losing the sapped debuff. I did pull aggro on them when I started fighting the mob next to it, a Southsea Pirate, but normally this means that once the debuff wears off, they will attack me, it prevents me from stealthing even while they're still debuffed, etc. Generally they don't perform actions, however."

The above is copied from my previous submit, which was tagged for being unable to reproduce, so I went and gathered as much more information as I could. I'm three levels lower than the Southsea Freebooter in question, although it's level varies by 1. It's a camp, with one Southsea Freeboter and one Southsea Pirate standing across from each other (It might be this specific freebooter, I've include a screenshot for reference). The fight goes as such:
-I walk up to the camp and sap the Freebooter.
-Proceed to engage the Pirate that is already near it, gaining aggro on both the freebooter (although it retains the sapped debuff) and the pirate who fights back.
-Throughout the fight, I'll randomly take ~80 damage. Checking the combat log says the Freebooter is using shoot.
-I'll continue to be shot even after the Pirate has died, until I either kill said freebooter, or break combat, either via running away or Vanish

Hopefully the screenshots and the more detailed description will help. 
![wowscrnshot_091417_001727](https://user-images.githubusercontent.com/31938611/30412149-87122f9a-98e3-11e7-8fca-70e57b39c203.jpg)
![wowscrnshot_091417_001731](https://user-images.githubusercontent.com/31938611/30412152-8a0adf6c-98e3-11e7-8a27-b93a9fdb9497.jpg)

**Comment by Wulfsg** [comment] 2017-09-14 04:41
Went and checked another camp after this one. The Southsea Freebooter in this screen shot is one that pats back and forth to the camp. I sapped him near the camp and pulled the camp to test it. Sure enough, I got the aggro for the sapped target, and it also started to shoot me. 
![wowscrnshot_091417_003813](https://user-images.githubusercontent.com/31938611/30412425-6c23462c-98e5-11e7-9a39-7221db7d5671.jpg)
![wowscrnshot_091417_003815](https://user-images.githubusercontent.com/31938611/30412427-6e1ef64c-98e5-11e7-88fd-88744ff0043c.jpg)

**Comment by fvicaria** [comment] 2017-09-14 10:14
Any rogue wants to test this? :)

**Comment by Anthonhed** [comment] 2017-09-14 16:01
I can confirm that the Freebooter still uses Shoot while it is Sapped and is dealing damage aswell:
![wowscrnshot_091417_175143](https://user-images.githubusercontent.com/26274880/30440380-a28d419a-9976-11e7-9751-b6e21cabbdae.jpg)

**Comment by captainloozer** [comment] 2017-09-14 16:59
@fvicaria I tested yesterday on dev and I could not reproduce.  I have not tried on Red

**Comment by Anthonhed** [comment] 2017-09-14 17:01
@captainloozer I tested that on Red

**Comment by fvicaria** [comment] 2017-09-16 08:47
If this cannot be reproduced in Dev it can be marked as fixed. I will push this Monday.

**Comment by captainloozer** [comment] 2017-09-16 18:50
Was able to reproduce on dev using the spots they're showing on the previous post.  It seems to have something to do with the mobs in the camps being linked when pulled.  I can not reproduce this bug anywhere else, for example, where the freebooters are roaming around not tied to any other mobs.  I've provided videos of both instances.

At the camps - https://youtu.be/rbjoNq4uAdg

Roaming - https://youtu.be/3z5Ca5jryfQ

**Closed** 2017-10-17 08:21 UTC
Labels: Confirmed, Fixed in Dev, Tweaking
