### ISSUE TITLE
auctions

### ISSUE THREAD

**Issue by hagigol** [WoWManiaUK/Redemption#4147] opened 2020-02-22 10:31 UTC
![SnipSnip_Capture_2020-02-22-1121AM_1](https://user-images.githubusercontent.com/61333828/75090791-d2ce9300-5566-11ea-9301-885436e5f215.Png)

auction house is not working properly. I put some titanium bars for sale on ah and i can't cancel the auction. Can buy some stuff but some is like inactve. I tried to buy bars from my brothers account but the are like not active... I remove all addons and relog and nothing changes.

**Comment by hagigol** [comment] 2020-02-22 10:32
put another item for sale on ah. Added but inactive can't bid, buy from another account.

**Comment by Kitzunu** [comment] 2020-02-22 11:08
Duplicate of #4144

**Closed by Kitzunu** 2020-02-22 11:08 UTC
