### ISSUE TITLE
Core/Spell: Mind Controll Effects

### ISSUE THREAD

**Issue by Kilju** [WoWManiaUK/Redemption#4001] opened 2020-01-14 04:23 UTC
Making a github post on the request of Game Master Vousalan, This has been reported to Developer Kitzunu already few days ago.

**Spell in question**
http://www.wow-mania.com/armory?spell=67839
ID: 67839
Name: Mind Amplification Dish

**Explanation of the problem**

While mind controlling an npc which has no combat scripts, the npc in question will follow you after an successfull mind control. The NPC goes back to hostile but will follow you forever. NPCs who fight opposite faction will properly reset and try to engage you in combat after the mind control (Tested on High Overlord Saurfang ID: 14720 and Orgrimmar Grunt 3296)

Video of initial testing: https://www.youtube.com/watch?v=ZVCwIiBSSMg&feature=youtu.be

**Further testing which has not been submitted yet to a developer:**
The mind control persist through zones as well. For this I don't have a video.
For example you can take an npc to ratchet and then board the boat. The NPC will stay where the boat disappears. Another player confirmed this to me when I was in booty bay waiting for the return boat. When returning with the boat the npc will start following you again.
I tested this 2 times. First time the NPC stayed on me. Second time it most likely fell through the earth as I tried looking for it between ratchet & orgimmar for 30 minutes.

Only way to break the mind control based on testing: 1. Die 2. Release corpse (Or kill NPC and it respawns as normal)

**What should happen:**
Non-combat NPCs should return to their spawn point after mind control. no proof but this is common logic and sense to me.

**Comment by Rushor** [comment] 2020-01-14 09:08
This is a generic issue for all MC effects

**Comment by Rushor** [comment] 2020-01-14 11:14
fixed on charm end they will return to homespot, no longer endless follow

**Comment by Kitzunu** [comment] 2020-01-14 11:17
How will this work if they are charmed, and then the charm breaks, but they are in the "normal" range of the homespot where they are usually able to attack the player.
Will they return, or will they fight the player as intended?

**Closed** 2020-01-14 11:28 UTC
Labels: Fixed in Dev
