### ISSUE TITLE
Soulless Ghoul Nonstop Casting-OverPowered Mob

### ISSUE THREAD

**Issue by Allelya** [WoWManiaUK/Redemption#4054] opened 2020-01-23 16:07 UTC
No addons being used. I know, I'm crazy.

Am I using our client? Yes. Downloaded directly from your site

Am I using the latest Launcher? Yes. Downloaded directly from your site.

Did I include the steps to reproduce the problem? Enter combat with a Soulless Ghoul mob in Ruins of Andorhal, Western Plaguelands, not far from Chillwind Camp.

Did I include the description of how it should work? I've never seen a mob capable of spamming a cast over and over, with no lapse between casts and not running out of mana. Soulless Ghoul mob should not be hitting so hard if it's going to be nonstop casting the same spell (while also invisibly casting another spell). While not a "trivial" mob, it's still just a common mob/non-elite.

Did I include the description of what is happening? So basically, I'm level 53, and the Soulless Ghoul mob is level 55. I enter combat with said mob. The mob begins to cast Shadow Bolt Volley repeatedly. No lapse between casting, it's literally NONSTOP. My health and mana drop in a matter of seconds. I look at my combat log and it shows that the Shadow Bolt Volley was hitting me for 390-430 each time (remember he is casting NONSTOP) and Mana Burn was draining me for 530-1060 mana each tick as well, yet I didn't see him cast it at all. I'm playing a Paladin, both spells against undead have a cooldown, so I had to try and time my combat with each of these mobs in order to burn them down as fast as I could without them killing me first. This area is VERY littered with these mobs in close proximity to each other.

Did I include NPC/Item/Spell names (or IDs) from wowhead.com or Armory? I didn't see an ID, but Soulless Ghoul/none/Shadow Bolt Volley. https://classic.wowhead.com/spell=27831/shadow-bolt-volley
Be descriptive and precise.

**Comment by jarvik76** [comment] 2020-01-23 16:27
Soulless Ghoul:  https://www.wow-mania.com/armory/?npc=1794

**Comment by wow-mania** [comment] 2020-01-23 16:29
Can someone confirm this please?

**Comment by jarvik76** [comment] 2020-01-23 16:32
am doing.  so far i see it casting with appropriate cast time and mana usage, casts 3 times + mana burn until mana runs out

**Comment by Rushor** [comment] 2020-01-23 16:37
Will check

**Comment by wow-mania** [comment] 2020-01-24 17:02
If this cannot be reproduced just close it please.

**Comment by jarvik76** [comment] 2020-01-24 19:18
@Allelya: I cannot reproduce this **as an error**.
What I notice, is that Shadow Bolt has a flight travel time; but mana burn does not - giving the *appearance* that it is being cast at the same time.
There is a casting animation and NPC is shown as casting in the target interface.
Mob stops casting these after 3 shadow bolts + a mana burn, at which point it is out of mana and reverts to physical combat.

Damage of the spell although high, when adjusted for level seems to match the amount in wow-mania armory and others.

Given the extreme density of the mobs, and the high damage of the casts, it does indeed make this area exceptionally challenging.  Is hard to determine if either density or damage caused was blizzlike.   Am closing this in the absence of any evidence to the contrary; if you have these please supply..

**Closed by jarvik76** 2020-01-24 19:18 UTC
