### ISSUE TITLE
[Quest] It's All Fun and Games - The Ocular does not respawn or take damage from item - Icecrown

### ISSUE THREAD

**Issue by Tawana-wowmania** [WoWManiaUK/Redemption#5762] opened 2022-03-14 13:16 UTC
**Links:**

**What is Happening:**
The quest Item isn't doing damage to The Occular

**What Should happen:**
The quest item should destroy the Occular so the quest can complete

**Comment by Tawana-wowmania** [comment] 2022-03-14 13:36
I took and dropped the quest several times the issue I had was with the quest item not working as it was intended

**Comment by Echinaceax** [comment] 2022-03-14 13:38
Horde https://www.wow-mania.com/armory/?quest=12892
Ally https://www.wow-mania.com/armory/?quest=12887

Received video from GM that send player here 
Will check issue 
Thanks for reporting @Tawana-wowmania

**Comment by Echinaceax** [comment] 2022-03-14 14:30
All looks fine on PTR atm, as @svijetlo said its when the Eye is there at the same time
i will see if i can bug it then update here

Atm no eye and the Occular seems fine 
![image](https://user-images.githubusercontent.com/39439201/158193366-5e2e2bda-47d5-4fc2-9fcb-6753f58a33f2.png)

**Comment by Echinaceax** [comment] 2022-03-16 23:31
update bugged on prt now 

https://i.gyazo.com/21ba53635d3f6c04d204d08a59feaceb.mp4

**Comment by mfranca0009** [comment] 2022-03-18 01:11
A fix and overall core update related to object visibility distance is being worked on and will be completed soon.

**Comment by mfranca0009** [comment] 2022-03-21 20:06
### Issues corrected
- [x] Object visibility functionality has been updated on core, you are now able to see him at the appropriate view distance (200 yards).
- [x] Added further detailed functionality to prevent constant evading which prevented the quest item to seem "bugged".
- [x] Increased aggro range implemented to match his far cast range reach for "Deathly Stare"
- [x] Regeneration of health is not applicable to this creature, therefore it has been disabled
- [x] Confirmed quest credit is only given to the current victim (who tapped the target first) and their party members.
- [x] Confirmed quest credit is given even dead before release (as long as you're in range); you will not get quest credit after release at graveyard because the range is too far.
- [x] When a victim has died, Ocular will successfully move to the next victim that is nearby (within 100 yards).
- [x] After The Ocular casts "Deathly Stare" multiple times with a normal cast speed, he will start to cast it faster. Confirmed evidence from 3.x.x WotLK build on WoWhead.

**Comment by Echinaceax** [comment] 2022-03-21 20:09
confirmed all above fixed in PTR 

Single player 

![image](https://user-images.githubusercontent.com/39439201/159355279-975a9427-89a3-4a18-adb1-961515d4bc49.png)

Grouped players 

![image](https://user-images.githubusercontent.com/39439201/159355371-c6e73e61-7e19-4389-9a3a-8c8217190c5c.png)

Grouped player dead still get quest credit if in range 

![image](https://user-images.githubusercontent.com/39439201/159355494-4a7edcc4-3145-4059-8f3e-bc76396e6b61.png)

**Closed** 2022-03-28 11:25 UTC
Labels: Fixed on PTR - Tester Confirmed
