### ISSUE TITLE
[Boss] Razorscale - Ulduar

### ISSUE THREAD

**Issue by Zunrin** [WoWManiaUK/Redemption#2207] opened 2018-02-06 11:09 UTC
We tried to do Ulduar 25 yesterday and had an issue with Razorscale.

**How it should work:**
During P1 (until Razorscale reaches 50%), Razorscale flies, is untargetable, and adds spawn, while friendly NPCs repair harpoon turrets. Once the turrets are all up, you need to use all four (all two on 10man) to bring Razorscale down, stun her, and you'll then be able to dps Razorscale. After a certain amount of time, she will breathe fire and fly back up, and once again adds will spawn while turrets are being repaired.

**How it works on Redemption:**
When all four turrets were repaired for the first time, we used them and Razorscale simply got stunned in the air, and we were unable to damage her. After a while adds started spawning again and turrets started being repaired again. The next two or three times we tried using the turrets, Razorscale came down as expected, but she was evading. After that she was going to hit berserk timer, so we couldn't wait for another ground phase.
We then called GMs and once again on the first "ground" phase, Razorscale got stunned mid air and we were not able to damage her.
This was on 25 man difficulty.

**Comment by TheManiax** [comment] 2018-02-06 19:31
I couldn't reproduce
If any other tester want to recheck, I won't tag it yet

**Comment by Dranah** [comment] 2018-02-10 21:20
I managed to reproduce this.
It happens when Razorscale is hit by the harpoon while casting "devouring flames". May affect any of the ground phases, not only the first.

**Comment by Ashamedlol** [comment] 2018-02-10 22:51
Also happens if he gets harpooned while he's attacking someone, Dranah.

**Comment by Dranah** [comment] 2018-02-11 00:56
What do you mean by "attacking?"
I mean, technically she constantly keeps shooting attacks, but I could only ever see her bug when she was mid-cast devouring flames as the harpoon lands.

**Comment by Ashamedlol** [comment] 2018-02-11 05:22
When she targets someone and shoots a fireball, that's what I mean.
According to my attempts on Redemption, you shoot the harpoon as she shoots so you catch her offguard (debug) and she drops down, it could've been random but she has to do no actions at all.

**Comment by Dranah** [comment] 2018-02-11 17:24
Additional problem:
- Razorscale's Devouring Flames should always target the closest enemy, be it a player or a pet. Currently his target seems random, it isn't always the closest guy who gets it. (Though his first cast usually goes on the closest person)

**Comment by Dranah** [comment] 2018-02-12 22:01
UPDATE:
- Razorscale seems to descend halfway (not always though oO) when he is hit during devouring flames by the harpoons. Still stays in the air. Bugs out afterwards, becoming untargetable (need fix)
- Devouring flames targetting is still random (need fix)

**Comment by philoudu16** [comment] 2018-02-13 12:43
UPDATE:

_Before first ground phase:_
Razorscale is targetable.

_First ground phase:_
Razorscale will fly down, walk freely on the platform for ~10 seconds (moving towards his target), and will then get stunned. When he flies back up he becomes untargetable.

_Other ground phases (final harpoon fired **during** devouring flames cast):_
Razorscale will fly down a couple yards before getting stunned. He is then targetable but is too high to be attacked. When he starts flying again, he becomes untargetable.

_Other ground phases (final harpoon fired while devouring flames cast is **not** being cast):_
Razorscale flies all the way down to the platform, but then starts "walking" back up in the air before getting stunned. He is then targetable but too high to be attacked. When he starts flying again, he becomes untargetable.

**Comment by philoudu16** [comment] 2018-02-13 13:41
UPDATE (with the newest version):

Razorscale starts in the air as expected.
On the first ground phase, he comes down and gets stunned immediately as expected.
However, when the ground phase finishes, he will cast Flame Breath towards the tank, rather than towards the harpoons. Also, after the first ground phase, Razorscale does not fly back up, but flies at ground level, so is still attackable by the raid.
Finally, after the ground phase, once Razorscale starts flying again, he can target friendly NPCs to cast his devouring flame on, which I don't think should happen.

**Comment by fvicaria** [comment] 2018-02-13 14:17
All issues fixed. I will apply it tomorrow in Red.

**Comment by Dranah** [comment] 2018-02-13 16:24
UPDATE:
Above issues fixed.

New problem:
- Razorscale should not acquire target and turn around before he uses his breath at the end of the temporary ground phases. Currently he does so, breathing wherever.

**Comment by fvicaria** [comment] 2018-02-13 16:51
Fixed.

**Comment by philoudu16** [comment] 2018-02-13 17:26
UPDATE:

- Razorscale turns towards the main threat before casting flame breath which may cause unexpected damage.
- On 25 man (we were unable to reproduce the issue on 10man so far), Razorscale will evade (most of the time) if someone stands under her when she lands.

**Comment by fvicaria** [comment] 2018-02-13 17:47
Final changes applied. It no more changes will be made.

**Comment by Dranah** [comment] 2018-02-13 20:20
Razorscale still acquires a target and turns before breathing as ground phase ends. Guess it stays as-is.

**Comment by flumby** [comment] 2018-02-13 20:43
Only bug with this is everyone has to be away from her landing zone, otherwise she will bug until she casts her breathe, everyone will get casting (evade) and melee get too far away.  If noone is in the centre you can run up to her and hit her.

**Comment by Dranah** [comment] 2018-02-13 21:18
Evade bug still happens but
- only 25man
- never the first air phase
- it seems to require her 1# aggro target to be under her hitbox as she lands - that'll be most likely a healer

**Comment by Dranah** [comment] 2018-07-24 20:33
New problem arose:

Devouring Flame http://www.wowhead.com/spell=64704 is able to target dead bodies of players.
The spell has been fixed so that it targets nearest raid member to Razorscale (as it should).
However it fails to check if the target is dead or alive. If the nearest raid member is dead, it will attempt to target him, but obviously the spell will fail because target is dead.
This results in Flames not appearing any more, because Razorscale is stuck targetting a dead person.
Spell needs to check for target living/dead status and select NEAREST LIVING party member.

**Comment by wow-mania** [comment] 2018-07-24 21:05
How was this confirmed fixed before? Is it a new problem or a regression?

**Comment by Dranah** [comment] 2018-07-24 21:06
I started my post with "New problem arose" ....
You wanted me to reopen threads instead of making new for everything. So i did.

**Comment by Dranah** [comment] 2018-07-26 22:12
Can't target dead players anymore.

**Closed** 2018-07-28 09:18 UTC
Labels: Fix Confirmed in Dev, Fixed in Dev
