### ISSUE TITLE
Horde Expedition Reputation BUG

### ISSUE THREAD

**Issue by vamdos** [WoWManiaUK/Redemption#2360] opened 2018-03-24 20:10 UTC
Hi there!

GM Psygoa told me to write a issue here, I have updated my client to the newest one and also tried to delete cache, but it didnt solve the problem. Everytime i kill a mob in raid or dung i dont get the reputation on my character.

**Comment by fvicaria** [comment] 2018-03-24 20:39
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by squalllh1989** [comment] 2018-03-24 22:25
can you please explain more of your case, like where do you kill a mob, do you wear any tabard, what race, class of your char. The rep of Horde Expedition will only be given to you when you kill mob in a level 80 dungeon, or a heroic dungeon

**Comment by vamdos** [comment] 2018-03-25 00:16
Im orc warrior, And of course in those kind of dungeons... i dont wear any
tabard or shirt. so I dont know whats going on. my character is vamse on
redemption server. please look into this

Den lör 24 mars 2018 23:25Acalys <notifications@github.com> skrev:

**Comment by squalllh1989** [comment] 2018-03-25 01:19
please clarify "those kind of dungeons" is which one, ty

**Comment by squalllh1989** [comment] 2018-03-25 01:33
Maybe you misunderstood something about "those kind of dungeon", when i say "level 80 dungeon" it consis of Hall of lightning, Forge of soul, Pit of saron, and Hall of reflection on nornal mode, and all northen dugeon in heroic mode. And while count as level 80 dungeon, the Trial of the champion won't give you rep when you kill mob there. If you are in some where like hall of stone normal then of course those mob that you kill in there won't give you rep

**Comment by squalllh1989** [comment] 2018-03-25 01:35
Pit of sauron normal: give rep
![wowscrnshot_032518_082519](https://user-images.githubusercontent.com/27235989/37870751-42af273e-3007-11e8-86b2-f904bfe6c1a5.jpg)
Hall of lighting normal: give rep
![wowscrnshot_032518_082618](https://user-images.githubusercontent.com/27235989/37870755-5e6b97e6-3007-11e8-87a3-25e3e57cd87b.jpg)
Hall of stone normal: not give rep
![wowscrnshot_032518_082718](https://user-images.githubusercontent.com/27235989/37870757-6d0e951e-3007-11e8-9f09-fee566a19dda.jpg)

**Comment by squalllh1989** [comment] 2018-03-25 04:59
well i will close this for now, if you still have the problem while doing one of those dungeon please add the information here and i will try to test it out, but i don't think that problem should happen, only reason i think is you are killing thing from dungeon that didn't give rep.

**Closed by squalllh1989** 2018-03-25 04:59 UTC
Labels: Need Informations

**Comment by vamdos** [comment] 2018-03-25 12:34
Bro!!! I did ICC10 POS FOS .. HOR doesnt matter dude.. Why would I lie
about this? I can send you screenshots if you like. I still didnt got the
reputation from the mobs

Den sön 25 mars 2018 03:33Acalys <notifications@github.com> skrev:

**Comment by squalllh1989** [comment] 2018-03-25 13:01
yeah if you didn't has rep in fos pos then yes, it's a trouble, but icc didn't have any Horde Expedition given in there, it give Argent Verdict. Please post 2 screen shot, 1 show your stand with the Horde Expedition in the reputation tab, 1 show that you killed a mob in fos/pos/hor and didn't get rep, then i think with those prove janitor will look over and solve your char's problem. And by the way, i didn't say that you lie, i just want to ask more information that i need to reproduce the bug that you report, as your report lack information, and can't reproduce the bug mean i can't confirm it.
