### ISSUE TITLE
NPC: Isfar, interaction lines are not working

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2576] opened 2018-07-09 21:44 UTC
http://www.wowhead.com/npc=18933/isfar

This NPC has 4  interactions, 2 of them aren't working:
- Where can I find the relic of Terokk?
- Who is this Terokk you keep mentioning?

**Comment by squalllh1989** [comment] 2018-07-10 03:47
Confirmed that the action "Where can I find the relic of Terokk?" is not working, but "Who is this Terokk you keep mentioning?" is working, here is the npc's response:
![wowscrnshot_071018_104623](https://user-images.githubusercontent.com/27235989/42488215-9f450e84-842e-11e8-92ff-d78adfd03987.jpg)

**Comment by squalllh1989** [comment] 2018-07-10 03:52
relate to this, i can't find the text for the action, but i found a grey item which is given with the quest he gave with this text: 
"When I was last in the halls, Talon King Ikiss carried Terokk's Quill with him, as a sign of his authority. He probably still carries it to convince his followers that he is Terokk reborn.
My brother, Darkweaver Syth, wore Terokk's Mask while leading the Sethekk rituals.
As for the Saga of Terokk, it is kept within a circle of runes in the great vaulted chamber just outside Talon King Ikiss's own."
I think since the text is in this item, you can remove that action in npc, or if you can make this text into it. When i check wow head they only have the text of other 3 action, so it make sense that the npc won't have this action as it's already in the quest item's text.
![wowscrnshot_071018_105012](https://user-images.githubusercontent.com/27235989/42488369-5eb6eddc-842f-11e8-8224-a7cf4a0ae934.jpg)

**Comment by wow-mania** [comment] 2018-07-10 08:28
As far as I can see that one was removed in 3.3.5a. So it shouldn't even show.
I will confirm

**Comment by wow-mania** [comment] 2018-07-10 09:04
Found the dialog. It's fixed in dev.

**Closed** 2018-07-10 10:13 UTC
Labels: Fixed in Dev
