### ISSUE TITLE
[NPC/Dungeon] Arthas can get stuck in The Culling Of Stratholme

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4390] opened 2020-04-07 15:16 UTC
**Arthas** can get stuck looking at the wall in this specific location during **The Culling Of Stratholme**. It used to be possible to kill one of the 3 citizens (the right one) when you enter this building to have him bug here for a second. But now it's not possible to kill the citizen anymore and he can get stuck here even though all mobs in the building are cleared.

![image](https://user-images.githubusercontent.com/6956790/78686276-2288d400-78f3-11ea-938f-a3692b96e846.png)

**Comment by Keader** [comment] 2020-04-07 15:28
@Rushor waypoint problem?

**Comment by Rushor** [comment] 2020-04-07 15:36
hmm i have not changes there anything? is this generic issue?

**Comment by wow-mania** [comment] 2020-04-07 15:46
If this is a corner case we just mark it as-is.

**Comment by yani** [comment] 2020-04-07 15:49
It used to be possible to kill the right citizen and Arthas would get stuck there for a bit. But in the last dung I did it was not possible anymore to kill the citizen. Maybe it has something to do with that?

**Comment by Rushor** [comment] 2020-04-07 16:27
which citizen bug him out?

**Comment by yani** [comment] 2020-04-07 18:06
> which citizen bug him out?

When you enter the building during this part of the dung, there are 3 citizens inside of the building at the entrance. These transform into mobs that should be killed after some dialogue. It used to be possible to kill the right one which changed some of the mechanics of the pathing or Arthas.

**Comment by Rushor** [comment] 2020-04-07 18:36
ehh but they are killable - it was like that already before

**Comment by Oganku** [comment] 2020-04-07 19:10
He's talking about #4381 that was just applied this morning. Might be related

**Comment by Rushor** [comment] 2020-04-07 23:05
> It used to be possible to kill the right one which changed some of the mechanics of the pathing or Arthas.

ah well they should not be attackable by default.

if someone could add a 100 percent reproduction would be awesome :)

**Comment by yani** [comment] 2020-04-07 23:12
Maybe look at the reason he gets stuck there when the citizen was killed before the fix of #4381?

**Comment by squalllh1989** [comment] 2020-04-08 06:19
this seem to be random happen and does not relate to the citizen since i just do this 10 min ago and have no trouble of him stuck there and the citizen is not attackable before transform.

**Comment by Aristo14** [comment] 2020-04-08 07:59
Will close this as-is since it seems to be random occurrence.

**Closed by Aristo14** 2020-04-08 07:59 UTC
