### ISSUE TITLE
[NPC] Val'kyr Shadowguard - Not dropping people from the edge

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5965] opened 2023-01-16 23:15 UTC
**Links:**

**What is Happening:**
Summon Valkyr abilitiy. Valkyrs not dropping people from the edge, but keep them in place until they die from aoe dmg like infest

**What Should happen:**

**Comment by Echinaceax** [comment] 2023-01-17 00:17
Thanks for reporting @theonykry 
this https://github.com/WoWManiaUK/Redemption/issues/5928 fix is reverted on next server update  which maybe have caused this issue

**Comment by hammereddann** [comment] 2023-01-20 22:24
@Rushor This is still not fixed,, Happened tonight someone grabbed and stayed until infest killed them. Also the Defile and Valkyr timers are far too close together now. On the 5th wave of valkyrs its far too close

**Comment by Echinaceax** [comment] 2023-01-21 11:47
reopening this one @Rushor , seems it wasnt caused by the previous fix

**Comment by Echinaceax** [comment] 2023-01-21 11:50
> Also the Defile and Valkyr timers are far too close together now. On the 5th wave of valkyrs its far too close

Do you remember when this started @hammereddann ?
because rushor said nothing changed only the stun/slow fix he did (which he reverted now)

**Comment by svijetlo** [comment] 2023-01-21 12:44
this problem started after change notes of  — 02/01/2023 11:17
and only thing done to icc there , sindy mechanic , 
i know for fact things to raid should not be add or remove just randomly  cos it can effect whole raid

**Comment by Rushor** [comment] 2023-01-21 15:23
No this is totally unrelated and does Not affect valkyrs at all

**Comment by Rushor** [comment] 2023-01-21 17:17
i get dropped of on ptr https://gyazo.com/7e8b2d587c5b1f3216daaea7ef02d4d4
(i am just not falling down due to gm fly mode, but yeah it works for me)

**Comment by Rushor** [comment] 2023-01-21 17:17
added a check to that infest and valk summon timer do not interfer too close with each other. but that issue existed even before that valk correction

**Comment by Rushor** [comment] 2023-01-21 17:53
emote for the targeted player added, nothing more i can do there https://i.imgur.com/QxoCwg2.jpeg

**Comment by Echinaceax** [comment] 2023-01-21 19:00
> i get dropped of on ptr https://gyazo.com/7e8b2d587c5b1f3216daaea7ef02d4d4 (i am just not falling down due to gm fly mode, but yeah it works for me)

Same for me, https://i.gyazo.com/9f42ef6cb9f8a5278915d38d44e3d777.mp4
We need more info 

Affecting a particular class?
Spells used 
need a video of this happening

**Comment by hammereddann** [comment] 2023-01-21 21:35
@Rushor It was a paladin grabbed because he didnt stack in the correct place on 25hc and he stayed in the grasp of the valkyr until he died from Infest. Regarding the timers, I spoke to another raid leader and we only noticed this change in time after this vakyr issue. We did all take 2 weeks break from raiding also in both guilds so it might have affected sometime over xmas break

**Comment by hammereddann** [comment] 2023-01-21 21:38
> > i get dropped of on ptr https://gyazo.com/7e8b2d587c5b1f3216daaea7ef02d4d4 (i am just not falling down due to gm fly mode, but yeah it works for me)
> 
> Same for me (mage) https://i.gyazo.com/9f42ef6cb9f8a5278915d38d44e3d777.mp4 https://i.gyazo.com/86fad3cc486fdbf2e62d68fb90ecd90b.mp4 We need more info
> 
> Affecting a particular class? Spells used (stun) or ... need a video of this happening

Is it the same coding used in 10n to 25hc? does it mater if its on the single valkyr or multiple???

**Comment by hammereddann** [comment] 2023-01-21 21:41
> > Also the Defile and Valkyr timers are far too close together now. On the 5th wave of valkyrs its far too close
> 
> Do you remember when this started @hammereddann ? because rushor said nothing changed only the stun/slow fix he did (which he reverted now)

Around xmas time i believe. It seems to be in 25hc most of the stuff. Not sure if testing in 10n will have the same effect imo

**Comment by Echinaceax** [comment] 2023-01-21 22:05
> Around xmas time i believe. It seems to be in 25hc most of the stuff. Not sure if testing in 10n will have the same effect imo

Thanks for extra info, we will test on 25man tomorrow see if we can repro

**Comment by hammereddann** [comment] 2023-01-21 23:22
> > Around xmas time i believe. It seems to be in 25hc most of the stuff. Not sure if testing in 10n will have the same effect imo
> 
> Thanks for extra info, we will test on 25man tomorrow see if we can repro

In 25 hc would be better, heroic is ofc harder than nm and its on the 5th set of valkyrs that come where the defile comes before the last valkyr even grabs a person. This is why i ask if you can test on 25 :)

**Comment by hammereddann** [comment] 2023-01-22 07:59
> added a check to that infest and valk summon timer do not interfer too close with each other (5 seconds delay to each other), but that issue existed even before that valk correction

Not infest, Defile and val'kyr

**Comment by Rushor** [comment] 2023-01-22 09:50
Yes that i meaned aswell, infest is not the problem :)

**Comment by GMZinius** [comment] 2023-01-22 11:23
On live after server restart (Janitor request to close this now)

**Closed** 2023-01-22 11:23 UTC
Labels: Fixed on PTR - Tester Confirmed, Code Change, AIScript Change
