### ISSUE TITLE
[NPC/Raid] Bellowing Roar - Spinestalker (Icecrown Citadel)

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4262] opened 2020-03-18 03:03 UTC
**Links:** https://www.wowhead.com/spell=36922/bellowing-roar

**What is Happening:** Spell can currently be interrupted by players.

**What Should happen:** Spell should not be interruptable.

**Comment by jeyrella** [comment] 2020-03-18 16:29
wrt ICC specifically, https://www.wowhead.com/npc=37534/spinestalker, but should be fixed on all NPCs that can cast it
https://www.wowhead.com/spell=36922/bellowing-roar

**Comment by tvshadowz** [comment] 2020-03-19 01:55
Confirmed, but unsure if this is working as intended or a bug.

**Comment by bLeyaa** [comment] 2020-03-19 13:55
https://youtu.be/z9CQ3d5kel8?t=124
https://youtu.be/UL19fYfwHW8?t=98 (at 1:41 you can see priest fear ward tank to keep aggro just in case)
There's a lot more other videos that show the same, each group had enough players to interrupt it but they all get feared. First video is a guild that farmed it quite a bit, someone experienced like that would have had it interrupted, especially with the setup they have.

**Comment by Rushor** [comment] 2020-03-22 12:59
creature should be immune to interrupt effects now: (23282, 23061, 23281, 37534, 38219, 17225);

**Closed** 2020-03-24 10:35 UTC
Labels: Confirmed - Improvement, Fix - Confirmed, Fix - In Dev/PTR
