### ISSUE TITLE
Valkyrs (trash mobs in ICC) missing ability

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4814] opened 2020-08-02 00:24 UTC
**Links:** [Val'kyr Herald](http://www.wow-mania.com/armory?npc=37098) / [Severed Essence](https://www.wow-mania.com/armory/?spell=71906)

**What is Happening:** The ability does not exist at all at the moment, they're not doing anything.

**What Should happen:** Copies of players should appear and attack the raid casting their class spells and everything.

**Comment by bLeyaa** [comment] 2020-08-02 00:24
https://www.youtube.com/watch?v=AXkAFHXOlJs

https://www.youtube.com/watch?v=vQeopu8evl0

**Comment by Oganku** [comment] 2020-08-02 01:32
See #4449 about the exact same topic. It was tagged as confirmed - won't fix since the core didn't support it I believe

**Comment by bLeyaa** [comment] 2020-08-02 01:45
Well, comment said it couldnt be fixed "atm"... perhaps now... x)

**Closed** 2020-08-02 06:52 UTC
Labels: Confirmed / Can't Fix, Invalid - Duplicate

**Comment by bLeyaa** [comment] 2020-08-02 09:24
@jeyrella why close is keader assigned it to rushor?

**Comment by jeyrella** [comment] 2020-08-02 23:53
Because rushor already assigned to keader.  both have said unfixable, no point in ping pong.
