### ISSUE TITLE
[Dungeon] Halls of Reflection Heroic despawns & resets during waves

### ISSUE THREAD

**Issue by Omnicloud0** [WoWManiaUK/Redemption#4192] opened 2020-03-05 05:36 UTC
**Links:**

**What is Happening:**
After the 1st boss goes down and its time for the next wave all mobs despawn and the doors close. Haven't figured out a way to reset the event. I,ve ran it twice on heroic and its bugged twice on heroic.

I have ran it successfully on normal. Not sure if it's totally random or a heroic issue.

**What Should happen:**
The event should continue to next series of waves leading up to second boss.

**Comment by Keader** [comment] 2020-03-07 18:59
![image](https://user-images.githubusercontent.com/7120913/76150753-9e8dc300-608c-11ea-8bc6-6a174ffe62de.png)

Tested and i cant reproduce.

**Comment by GMMetaxa** [comment] 2020-03-10 19:14
![HoR](https://user-images.githubusercontent.com/34750502/76350112-72cc4080-630b-11ea-9f57-1f677c7844a6.png)

Apparently there's something that causes to despawn the npc's and stops the waves.
Please test on different classes, maybe it's class related.

**Comment by Oganku** [comment] 2020-03-10 20:39
When hallucinations spawn behind walls or mercenaries shadowstep through them it usually does that, but it's quite easy to avoid by not hugging the walls too much. Never had anything else cause this issue personally

**Comment by svijetlo** [comment] 2020-03-10 21:08
i will test it tomorrow but as i figured so far in runs is if you go behind walls and hide enemies can not have you in line of sight and they disappear. how i do it is stand in middle hallway opposite side form one you enter and never had any problem

**Comment by svijetlo** [comment] 2020-03-11 04:32
ok i have good and bad news 
i can confirm problem can happen but only in some special cases 
i tested in on rogue, hunter , paladin, druid, shadow priest and DK 
how the problem happen if you are rogue or night elf if you use vanish or shadow-meld during boss incoming timer everything in room will disappear  and wave counter will be set to 0/10
but if you run back to entrance of the dung and run back to middle where Frostmorne  waves will start from 1/10.
i would appreciate more info about what races , specks were involved in dungeon run to help us narrow down possibility of it happening and fix it

**Comment by Oganku** [comment] 2020-03-11 12:24
I know bloodworms can mess it up. Don't know if there's more for DK.

**Comment by Rushor** [comment] 2020-03-11 15:00
suggestion: disable mmaps or mpathfinding for all those creatues in the first encounter

**Comment by jarvik76** [comment] 2020-03-11 15:49
@Rushor from what i'm understanding, it is not the NPC causing the problem (that was fixed on previous ticket) but a **player** rogue using the skill

**Comment by jarvik76** [comment] 2020-03-11 15:51
> When hallucinations spawn behind walls or mercenaries shadowstep through them it usually does that, but it's quite easy to avoid by not hugging the walls too much. Never had anything else cause this issue personally

oganku this was fixed in https://github.com/WoWManiaUK/Redemption/issues/4086.  if the NPCs are still a problem, we should re-open that ticket, but I have heard of no problems since.  
This ticket specifically seems to be player-triggered despawn

**Comment by svijetlo** [comment] 2020-03-11 16:03
did not happen, seen enemy rogue half in wall and still works fine , also seen few rly bed resolution old vids of place and what i figured out at all time some one need to be in line of sight of mobs, so if you do side tactic everyone hides while tank is always out in line of sight , or do stay in middle of hallway opposite to entrance of dung, but still have not found any old info about mobs resenting . So can not confirm is that as blizz or smt we need to change here , also i forgotten to write before if you are rogue or night elf if you start fight in stealth or in shadow meld form mobs will appear , wont reset but they wont run to you till you get out to open so they can see you , imo just make that mobs there can see/agro trou those small bits of walls on side and so they can seen players in hide

**Comment by jarvik76** [comment] 2020-03-13 19:03
@Omnicloud0 although there's been lots of comments here, the bottom line is we suspect it was triggered by some player skill.  However without knowing what skill that was, it's tough to test fully. 
What we really need is a list of the classes/specs you had in the group.

@Keader this is the pertinent comment from @svijetlo for you to look at:
> if you are rogue or night elf if you use vanish or shadow-meld during boss incoming timer everything in room will disappear and wave counter will be set to 0/10

**Comment by Omnicloud0** [comment] 2020-03-13 21:57
thank you for the feed back. next time it happens Ill take note.
    On Friday, March 13, 2020, 02:03:56 PM CDT, jarvik76 <notifications@github.com> wrote:  
 
 


@Omnicloud0 although there's been lots of comments here, the bottom line is we suspect it was triggered by some player skill. However without knowing what skill that was, it's tough to test fully.
What we really need is a list of the classes/specs you had in the group.

@Keader this is the pertinent comment from @svijetlo for you to look at:


if you are rogue or night elf if you use vanish or shadow-meld during boss incoming timer everything in room will disappear and wave counter will be set to 0/10

**Comment by Keader** [comment] 2020-03-14 12:52
@svijetlo ok, now will not reset for shadowmeld/invisibility anymore

**Comment by svijetlo** [comment] 2020-03-15 12:01
still same use of vanish / shadowmeld before last boss (Marwyn) comes out it reset waves to 0/10
running to entrance and back to middle set waves to 1/10 but this time around you have no 1st boss in wave 5/10

**Comment by Keader** [comment] 2020-03-15 13:25
hmm
Applied a new patch.
Check again in 5 minutes.

**Comment by svijetlo** [comment] 2020-03-15 13:57
works like a charm , did vanish/ shadow meld  before last boss went to hide stood in corner he just came to

**Closed** 2020-03-17 10:42 UTC
Labels: Confirmed - Not Working, Fix - Confirmed, Fix - In Dev/PTR

**Comment by Probzta5311** [comment] 2020-03-28 22:33
This is still happening its the Rogue Mob that bugs it … possibly remove rogue to fix?
