### ISSUE TITLE
[Spell] Pursuit of Justice

### ISSUE THREAD

**Issue by Tery-Redemption** [WoWManiaUK/Redemption#3210] opened 2019-04-25 22:04 UTC
Retribution paladins talents pursuit of justice which should increase speed by 15% mounted or not is not working in most regions.  I did not make a list of all regions where it doesn't work but I can confirm Dalaran and Wintergrasp among others.  In fact,  I've met fewer places where it does work then the opposite around Northrend.  I know the issue has been reported in the past and seemed linked to speed hack control.  I don't know if it was supposed to be fixed or not but any paladins with the talent will confirm that there is a still a problem.  Thank you.

**Comment by Kitzunu** [comment] 2019-04-26 06:02
Please follow the Template made to log issues.
You can also read CONTRIBUTION.MD for extra help.

Thank you for taking the time to log the issue, it will be looked into

**Comment by Keader** [comment] 2019-04-29 12:58
Cant reproduce.
Any specific region or specific mount?
Anyway closing, if you know a way to reproduce i can reopen this.

**Closed by Keader** 2019-04-29 12:58 UTC

**Comment by Tery-Redemption** [comment] 2019-05-02 23:36
Ok, it seems to be related with the usage of siege vehicules in Wintergrasp.  If I enter one then pursuit of justice stops working when I exit.  Relogging makes it work again otherwise it won't work for as along as I play wherever I go.
